import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const researchedBatchCases = [
  ["Acteck Kioto GC220 AC-933063 gabinete micro ATX slim", "ACTECK", "computo/componentes/gabinetes"],
  ["OvalTech OTAC-E65 adaptador corriente laptop ASUS 19V 1.75A USB", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["PCM B7670 rollo papel bond 76 x 70 punto venta", "PCM", "punto-de-venta/consumibles/rollos-bond"],
  ["PCM EBA5760 rollo autocopia blanco amarillo 57 x 60", "PCM", "punto-de-venta/consumibles/rollos-autocopia"],
  ["PCM BRA7670 rollo autocopiante 76 x 70 R/B/A", "PCM", "punto-de-venta/consumibles/rollos-autocopia"],
  ["PCM B38X70 rollo bond blanco", "PCM", "punto-de-venta/consumibles/rollos-bond"],
  ["PCM B5760 rollo bond satinado 57 x 60", "PCM", "punto-de-venta/consumibles/rollos-bond"],
  ["PCM T5760 rollo termico 57 x 60 c100", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T5745 rollo termico 57 x 45 c175", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T8070C50 rollo termico 80 x 70 c50", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T8080 rollo termico 80 x 80", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T5736MMS12K rollo termico 57 x 36", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["Provision ISR PR-C08 adaptador alimentacion DC macho CCTV", "PROVISION-ISR", "seguridad/cctv/accesorios-cableado"],
  ["Provision ISR PR-C13 conector BNC macho RG59", "PROVISION-ISR", "seguridad/cctv/accesorios-cableado"],
  ["Provision ISR PR-10A9CH+ fuente poder CCTV 12V 10A 9 canales", "PROVISION-ISR", "seguridad/cctv/fuentes-poder"],
  ["Provision ISR PR-12A16CH+ fuente poder CCTV 12V 12A 16 canales", "PROVISION-ISR", "seguridad/cctv/fuentes-poder"],
  ["Provision ISR PR-12V1A-A fuente poder individual 12V 1A", "PROVISION ISR", "seguridad/cctv/fuentes-poder"],
  ["Provision ISR PR-C14 divisor fuente poder 1 entrada 4 salidas", "PROVISION ISR", "seguridad/cctv/accesorios-cableado"],
  ["Provision ISR PR-C09 adaptador alimentacion CCTV", "PROVISION-ISR", "seguridad/cctv/accesorios-cableado"],
  ["TechZone TZEST01N maletin laptop 15.6 nylon negro", "TECHZONE", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["TechZone TZBTS10BLK mochila laptop 15.6 negro", "TECHZONE", "computo/accesorios/mochilas-fundas/mochilas-laptop"],
  ["UNV IPC3624LE-ADF28K-WP-L camara IP turret PoE ColorHunter", "UNV", "seguridad/cctv/camaras-ip-poe"],
  ["Brobotix 406351 cable HDMI 2.0 espiral 8K 60Hz", "BROBOTIX", "accesorios/cables-adaptadores/video-hdmi"],
  ["TP-Link Omada EAP773 BE11000 Wi-Fi 7 access point", "TP-LINK", "redes/access-points/wifi-7"],
  ["Brobotix 6006528 maletin portafolio neopreno laptop", "BROBOTIX", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["Brobotix 263786 plug RJ45 Cat5e bote 100 piezas", "BROBOTIX", "redes/cableado-estructurado/conectores-rj45"],
  ["Perfect Choice PC-084716 Branston portafolio laptop", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["Silimex Laptop Cleaner kit limpieza laptop", "SILIMEX", "computo/accesorios/limpieza/kits-limpieza"],
  ["Game Factor MAG500 brazo para microfono ajustable", "GAME FACTOR", "audio/microfonos/soportes-brazos"],
  ["Gigabyte B850 Eagle WiFi6E tarjeta madre socket AM5", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am5"],
  ["Lenovo ThinkPad T14 Gen 6 21QK000WLM laptop empresarial", "LENOVO", "computo/laptops/empresariales"],
  ["Xzeal X-Tron XZGAXT1B gabinete gamer Mid Tower ATX 4 ARGB", "XZEAL", "computo/componentes/gabinetes/gaming"],
  ["Uniarch Uho-S3S-M33D camara IP doble lente WiFi interior", "UNIARCH", "seguridad/cctv/camaras-ip-wifi/interior"],
  ["UNV IPC3K28SE-ADF28KMC-DL-I0 turret ColorHunter Omniview", "UNV", "seguridad/cctv/camaras-ip-poe/panoramicas"],
  ["Provision ISR Z4-25IPEN-2 IR camara PTZ IP x25", "PROVISION-ISR", "seguridad/cctv/camaras-ip-poe/ptz"],
  ["BRobotix 6006627 cargador de pared USB tipo C 20W", "BROBOTIX", "energia/cargadores-usb/pared-usb-c"],
  ["Dahua S042-1A120300HU adaptador 12VDC 3A CCTV", "DAHUA", "seguridad/cctv/fuentes-poder"],
  ["Epson T504320-AL botella tinta magenta EcoTank", "EPSON", "impresion/consumibles/botellas-tinta-ecotank"],
  ["Grandstream UCM6304A conmutador IP PBX 4 FXO 4 FXS", "GRANDSTREAM", "telefonia/pbx-ip"],
  ["Logitech PRO X SUPERLIGHT 2 910-006637 mouse inalambrico", "LOGITECH", "computo/perifericos/mouse/inalambricos/gaming"],
  ["Manhattan 179843 audifonos USB con microfono flexible", "MANHATTAN", "audio/audifonos/usb"],
  ["TP-Link Omada EAP660 HD access point AX3600 Wi-Fi 6", "TP-LINK", "redes/access-points/wifi-6"],
  ["Naceb Boreal NA-0656B enfriamiento liquido 360 mm blanco", "NACEB", "computo/componentes/enfriamiento/liquido-cpu"],
  ["Brother WT229CL waste toner box contenedor de desperdicio", "BROTHER", "impresion/consumibles/contenedores-desperdicio"],
  ["MSI A520M-A PRO tarjeta madre AMD AM4 micro ATX", "MSI", "computo/componentes/tarjetas-madre/amd-am4"],
  ["Logitech Ultimate Ears BOOM 3 984-001358 bocina bluetooth roja", "LOGITECH", "audio/bocinas/bluetooth"],
  ["Manhattan 353243 cable HDMI activo fibra optica 20 m", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/fibra-optica"],
  ["Brother DR433CL drum unit unidad de tambor color", "BROTHER", "impresion/consumibles/tambores"],
  ["Gigabyte H610M K V2 tarjeta madre Intel LGA1700 DDR5", "GIGABYTE", "computo/componentes/tarjetas-madre/intel-lga1700"],
  ["Meriva MDL-5202A camara HD bullet 4 en 1 AHD TVI CVI", "MERIVA", "seguridad/cctv/camaras-turbohd/bullet"],
  ["ASUS ExpertBook P1 P1403CVA-i58G512-P1 laptop empresarial", "ASUS", "computo/laptops/empresariales"],
  ["TP-Link Archer TXE70UH adaptador USB Wi-Fi 6E tribanda", "TP-LINK", "redes/adaptadores-wifi/usb"],
  ["Brother TN815Y toner amarillo alto rendimiento 12000 paginas", "BROTHER", "impresion/consumibles/toner-laser"],
  ["Seagate ST2000LM015 BarraCuda disco duro 2TB 2.5 SATA 5400RPM", "SEAGATE", "computo/almacenamiento/discos-duros/2-5-sata"],
  ["WD Green SN350 WDS500G2G0C SSD 500GB M.2 2280 NVMe PCIe Gen3", "SANDISK", "computo/almacenamiento/ssd/m2-nvme"],
  ["Hikvision DS-2CD3T86G2H-LISU camara bala IP 8MP", "HIKVISION", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Forza FSI-3011RUL UPS 3000VA 2700W bastidor torre", "FORZA", "energia/no-breaks-ups/rack-torre"],
  ["Manhattan 190329 mouse optico inalambrico USB", "MANHATTAN", "computo/perifericos/mouse/inalambricos"],
  ["HPE ProLiant ML350 Gen11 servidor torre P75341-DM5", "HPE", "computo/servidores/torre"],
  ["Panasonic KX-TGB310MEB telefono inalambrico LCD ambar", "PANASONIC", "telefonia/telefonos/inalambricos"],
  ["CyberPower AVRG750LCD no break 760VA 450W interactivo LCD", "CYBERPOWER", "energia/no-breaks-ups/line-interactive"],
  ["Acteck ONEX GS450 AC-943086 gabinete mini torre slim", "ACTECK", "computo/componentes/gabinetes/mini-tower"],
  ["Manhattan 333405 cable USB 2.0 A-B 1.8m", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-b"],
  ["Perfect Choice PC-113102 Goliat bocina Bluetooth 50W", "PERFECT CHOICE", "audio/bocinas/bluetooth"],
  ["Creative Labs ZEN Hybrid 2 CR audifonos Bluetooth ANC", "CREATIVE", "audio/audifonos/bluetooth"],
  ["Brother TN433Y toner amarillo 4000 paginas", "BROTHER", "impresion/consumibles/toner-laser"],
  ["Xerox 113R00670 tambor Phaser 5500", "XEROX", "impresion/consumibles/tambores"],
  ["BRobotix 000140 cable corriente CPU NEMA 5-15 C13", "BROBOTIX", "accesorios/cables-adaptadores/energia/corriente-cpu"],
  ["TP-Link Deco S7 2 Pack router WiFi Mesh AC1900", "TP-LINK", "redes/routers/mesh-wifi"],
  ["Acteck MI790 mouse trackball ergonomico inalambrico", "ACTECK", "computo/perifericos/mouse/inalambricos/trackball"],
  ["Grandstream GXP1630 telefono IP 3 cuentas SIP PoE", "GRANDSTREAM", "telefonia/telefonos-ip"],
  ["ADATA AD5S480016G-S memoria SO-DIMM DDR5 16GB 4800MHz CL40", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr5"],
  ["Intellinet 517874 caja para pared single gang 4.8cm", "INTELLINET", "redes/cableado-estructurado/cajas-pared"],
  ["Creative Stage SE mini MF8460 soundbar Bluetooth USB-C", "CREATIVE LABS", "audio/barras-sonido/pc"],
  ["Game Factor MDTD400 cable Mini DisplayPort a DisplayPort 2m 4K", "GAME FACTOR", "accesorios/cables-adaptadores/video-displayport"],
  ["Dahua DH-HAC-T1A51N-U-IL-A camara HDCVI 5MP Smart Dual Light", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi"],
  ["Corsair USB100 CU-9000003-NA hub USB-C USB-A 7 puertos", "CORSAIR", "computo/accesorios/hubs-usb/usb-c"],
  ["Vortred Helmet V-930174 audifonos TWS gamer Bluetooth", "VORTRED", "audio/audifonos/bluetooth/tws"],
  ["Huawei MatePad SE 11 53014GYW tableta 8GB 128GB", "HUAWEI", "computo/tabletas"],
  ["Urban Balance UBSC11 dock USB-C 11 en 1 100W", "URBAN BALANCE", "computo/accesorios/docks-hubs/usb-c"],
  ["Zebra 800033-840 cinta YMCKO ZXP Series 3 200 impresiones", "ZEBRA", "impresion/consumibles/cintas-tarjetas"],
  ["UNV IPC2B18SE-ADF28K-WP-I1 OwlView Plus camara IP bullet 8MP PoE", "UNIVIEW", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Naceb Raptor KITNCB100 kit teclado y mouse gamer", "NACEB TECHNOLOGY", "computo/perifericos/combos-teclado-mouse/gaming"],
  ["Microsoft 365 Business Standard KLQ-00698 licencia FPP 1 usuario", "MICROSOFT", "software/productividad-oficina/microsoft-365"],
  ["Epson EcoTank L3210 C11CJ68301 multifuncional tinta continua", "EPSON", "impresion/impresoras/multifuncionales-ecotank"],
  ["TP-Link SG2016P Omada switch 16 puertos 8 puertos PoE", "TP-LINK", "redes/switches/poe-administrables"],
  ["Balam Rush MRX8000 escritorio gamer Olympus Spot Glow RGB", "BALAM RUSH", "gaming/mobiliario/escritorios"],
  ["Mercusys MW325R router inalambrico 300Mbps 4 antenas", "TP-LINK", "redes/routers/wifi-n"],
  ["Acteck Captive Vivid SP245 monitor 24.5 FHD 75Hz", "ACTECK", "computo/monitores/oficina/24-25-fhd"],
  ["Provision-ISR NVR16-641600RFAN(2U) NVR 64CH 16MP", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/nvr-ip"],
  ["Logitech Brio 300 960-001440 webcam FHD 1080p USB-C", "LOGITECH", "computo/perifericos/webcams/usb-fhd"],
  ["Lenovo ThinkSystem ST45 V3 7DH4A00GLA servidor torre AMD EPYC", "LENOVO", "computo/servidores/torre"],
  ["BRobotix 938276 tapa faceplate 1 panel para jack", "BROBOTIX", "redes/cableado-estructurado/placas-keystone"],
  ["Manhattan 460941 soporte TV pared 32 a 55 35kg ajuste vertical", "MANHATTAN", "video/soportes-tv/pared"],
  ["EZVIZ CSH5/3MP/POE camara H5 PoE 3MP", "EZVIZ", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Dell 460-BCYY GM1720PM Gaming Backpack 17 pulgadas", "DELL", "computo/accesorios/mochilas-fundas/mochilas-gaming"],
  ["Grandstream GWN7615 access point WiFi 5 MU-MIMO 3x3", "GRANDSTREAM", "redes/access-points/wifi-5"],
  ["Silimex 7503018454344 alcohol isopropilico 500 ml mini trigger", "SILIMEX", "computo/accesorios/limpieza/alcohol-isopropilico"],
  ["Uniarch NVR-108S3-P8-ECO NVR 8 canales PoE 6MP", "UNIARCH", "seguridad/cctv/dvr-nvr/nvr-ip"],
  ["Dahua DH-XVR1B08-I/T XVR HDCVI 8 canales WizSense", "DAHUA", "seguridad/cctv/dvr-nvr/xvr-hdcvi"],
  ["Naceb Gaming NA-0925 kit gamer teclado mouse USB 2400 DPI headset mousepad", "NACEB", "computo/perifericos/kits-gamer/4-en-1"],
  ["MSI GeForce RTX 3050 LP 6G OC GDDR6 96-bit", "MSI", "computo/componentes/tarjetas-video/nvidia-geforce"],
  ["Xerox 108R01420 tambor negro WorkCentre 6515 48000 paginas", "XEROX", "impresion/consumibles/tambores/xerox"],
  ["Ajax TurretCam5MP CI121AJX01 camara IP turret 5MP NVR Ajax", "AJAX", "seguridad/cctv/camaras-ip-poe/turret"],
  ["Brother DCPB7640DW multifuncional laser 36 ppm duplex WiFi", "BROTHER", "impresion/impresoras/multifuncionales-laser"],
  ["Perfect Choice PC-241041 Voltus cargador magnetico MagSafe", "PERFECT CHOICE", "energia/cargadores-inalambricos/magneticos-magsafe"],
  ["UNV IPC2314LE-ADF28K-WP-L OwlView 4MP bullet PoE", "UNV", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["BRobotix 497127 patch cord Cat5e 0.5m RJ45 gris", "BROBOTIX", "redes/cableado-estructurado/patch-cords/cat5e"],
  ["Acteck AS450 Elant Brick bocinas 2.0 6W USB 3.5 mm", "ACTECK", "computo/perifericos/bocinas-audio/2-0"],
  ["Kyocera TK-5442K 1T0C0A0US0 toner negro 2800 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera"],
  ["Epson T574520-AL botella T574 light cyan L8050", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t574"],
  ["Multimedia Screens MST-246 pantalla proyeccion tripie 137 246 cm x 246 cm", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion/pantallas-tripie"],
  ["TP-Link Omada EAP783 access point Wi-Fi 7 BE22000 2 puertos 10G", "TP-LINK", "redes/access-points/wifi-7"],
  ["HPE Instant On SG1004 secure gateway firewall VPN IDS IPS", "ARUBA", "redes/seguridad/firewalls"],
  ["Naceb NA-0103R cable USB a Micro USB 1m rojo", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/usb/micro-usb"],
  ["Dahua KTP02 KITKTP02-V2 videoportero IP monitor 7 1024 x 600", "DAHUA TECHNOLOGY", "seguridad/control-acceso/videoporteros-ip/kits"],
  ["ADATA AD4S26664G19-SGN memoria SO-DIMM DDR4 4GB 2666MHz", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr4"],
  ["Brother TN227C toner cyan alto rendimiento 2300 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother"],
  ["Roku Premiere 3920RW reproductor streaming 4K UHD HDR", "ROKU", "video/streaming/reproductores"],
  ["Intellinet 704823 bobina Cat5e CCA UTP 305m gris", "INTELLINET", "redes/cableado-estructurado/bobinas-utp/cat5e"],
  ["Hikvision AE-VC222T-ITS camara movil Turbo HD 1080p conector aviacion", "HIKVISION", "seguridad/cctv/camaras-moviles/turbo-hd"],
  ["Manhattan 461344 soporte TV pared movimiento completo 32-55 40kg", "MANHATTAN", "video/soportes-tv/pared"],
  ["Brother TN229BK toner negro rendimiento estandar 1500 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother"],
  ["Perfect Choice PC-113294 Sugary bocina Bluetooth IPX6 35 h", "PERFECT CHOICE", "audio/bocinas/bluetooth"],
  ["ESET HOME Security Essential TMESET-506 antivirus 10 licencias 1 ano", "ESET", "software/seguridad/antivirus"],
  ["BRobotix 406269 soporte para celular plegable magnetico", "BROBOTIX", "telefonia/accesorios/soportes-celular/magneticos"],
  ["Bixolon XM7-20iK impresora movil de etiquetas termica directa Bluetooth", "BIXOLON", "impresion/impresoras/etiquetas/termicas-moviles"],
  ["Urban Balance VGA A HDMI - UB adaptador HDMI a VGA 1080p", "URBAN BALANCE", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Kensington K52801WW ErgoSoft descansa munecas teclado compacto", "KENSINGTON", "computo/perifericos/teclados/descansa-munecas"],
  ["IMOU IPC-K3DN-5H0WF Bullet 2E 5MP WiFi microfono IP67", "IMOU", "seguridad/cctv/camaras-ip-wifi/bullet-exterior"],
  ["Canon GI-10 C tanque de tinta cyan 7700 paginas", "CANON", "impresion/consumibles/botellas-tinta-megatank/canon-gi10"],
  ["Balam Rush EXL95 Eolox Link ventilador 120mm 1800 RPM RGB", "BALAM RUSH", "computo/componentes/enfriamiento/ventiladores-gabinete"],
  ["Gigabyte X870 AORUS ELITE WIFI7 ICE motherboard AM5 DDR5", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am5"],
  ["BenQ EX3410R MOBIUZ monitor gaming ultrawide curvo 34 3440x1440", "BENQ", "computo/monitores/gaming/ultrawide-curvos"],
  ["TP-Link TL-WN725N adaptador USB Nano Wireless N 150Mbps", "TP LINK", "redes/adaptadores-wifi/usb"],
  ["Uniarch IPC-B122-APF28-E camara IP mini bala 2MP PoE IR 30m", "UNIARCH", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["BRobotix 6001356 combo carga rapida cargador USB V3.0 cable Lightning", "BROBOTIX", "energia/cargadores-usb/kits-carga-lightning"],
  ["Lenovo ThinkCentre Neo 50q Gen 5 13C50022LS i3-1315U mini PC", "LENOVO", "computo/desktops/mini-pc"],
  ["Getttech GPI-GVN100A-01M PC Desktop Intel N100 8GB 240GB SSD", "GETTTECH", "computo/desktops/mini-pc"],
  ["Logitech BRIO 500 960-001412 webcam FHD USB-C", "LOGITECH", "computo/perifericos/webcams/usb-fhd"],
  ["Dahua DH-PFA120 caja de conexiones PTZ junction box", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-montaje/cajas-conexion"],
  ["BRobotix 110910N convertidor HDMI macho a VGA hembra 24.5 cm", "BROBOTIX", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Dell 24 AIO EC24250 XNT23 Core i7-1355U 16GB 1TB", "DELL", "computo/desktops/all-in-one"],
  ["TP-Link Tapo P100 mini contacto inteligente Wi-Fi 1200W", "TP LINK", "domotica/enchufes-inteligentes"],
  ["BRobotix 6001431 cable adaptador PCI Express 6 pines a 8 pines", "BROBOTIX", "computo/componentes/cables-internos/alimentacion-pcie"],
  ["TP-Link Omada ER7212PC router VPN 3 en 1 PoE controlador", "TP-LINK", "redes/routers/vpn/omada"],
  ["Naceb NA-0321 audifonos in-ear USB-C con control", "NACEB TECHNOLOGY", "audio/audifonos/in-ear/usb-c"],
  ["Kingston DTXM/128GB DataTraveler Exodia M USB 3.2 rojo", "KINGSTON", "computo/almacenamiento/memorias-flash/usb"],
  ["Logitech M720 Triathlon 910-004790 mouse Unifying Bluetooth", "LOGITECH", "computo/perifericos/mouse/inalambricos/multi-dispositivo"],
  ["ADATA AX5S5600C468G-SBHT XPG Hunter DDR5 SO-DIMM 8GB 5600", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr5"],
  ["EZVIZ CS-H9C/6MP camara PT doble lente 3MP+3MP WiFi", "EZVIZ", "seguridad/cctv/camaras-ip-wifi/pt-doble-lente"],
  ["Silimex Silitek 28.33grs pasta termica grasa disipadora de calor", "SILIMEX", "computo/componentes/pasta-termica"],
  ["Kensington SD1650P estacion de acoplamiento portatil USB-C", "KENSINGTON", "computo/accesorios/docks-hubs/usb-c"],
  ["BRobotix 6006658 cargador 18W dual USB-A USB-C negro", "BROBOTIX", "energia/cargadores-usb/pared-dual-usb-a-usb-c"],
  ["Brother PTE560BTVP rotulador industrial P-touch etiquetas 24 mm", "BROTHER", "impresion/impresoras/etiquetas/rotuladores-p-touch"],
  ["TCL 50Q5K televisor QLED Google TV 50 4K UHD", "TCL", "video/televisores/qled-google-tv"],
  ["Manhattan 153218 cable DisplayPort a HDMI M-M 4K 60Hz 3m", "MANHATTAN", "accesorios/cables-adaptadores/video-displayport-hdmi"],
  ["Logitech MX Vertical 910-005449 mouse ergonomico inalambrico 4000 DPI", "LOGITECH", "computo/perifericos/mouse/inalambricos/ergonomicos"],
  ["Meriva MOB-800FS4 camara IP bullet 8MP 4K H.265+ PoE", "MERIVA", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Generico AC-LENOVO-CH cargador laptop 45W 20V 2.25A 4.0x1.7", "GENERICO", "computo/accesorios/cargadores-laptop"],
  ["Brother PTM95 rotulador P-touch termica directa etiquetas 12 mm", "BROTHER", "impresion/impresoras/etiquetas/rotuladores-p-touch"],
  ["Manhattan 506847 adaptador USB 3.0 a Ethernet Gigabit", "MANHATTAN", "redes/adaptadores-ethernet/usb-gigabit"],
  ["Acteck RV1200 regulador de voltaje AVR 1200VA 600W", "ACTECK", "energia/supresores-reguladores/reguladores-voltaje/avr"],
  ["Dahua DH-IPC-HDW1431SN-S4 camara IP turret 4MP PoE IR 30m", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/turret"],
  ["Dahua DH-IPC-HDW1239T1P-A-LED camara IP Full Color 2MP PoE", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/turret/full-color"],
  ["Dahua DH-HAC-B1A51N-U-0280B camara bullet HDCVI 5MP", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet"],
  ["CyberPower CP1000PFCLCDa UPS PFC Sinewave 1000VA 600W LCD", "CYBERPOWER", "energia/no-breaks-ups/line-interactive/senoidal-pura"],
  ["Meriva MVD-EB200ZA camara IP domo varifocal motorizado 2.8-12mm PoE", "MERIVA", "seguridad/cctv/camaras-ip-poe/domo-varifocal"],
  ["XPG RIFT R24F2-BKCMX monitor gamer 23.8 FHD 120Hz 1ms", "XPG", "computo/monitores/gaming/24-fhd"],
  ["DataShield MI-4217 bateria sellada UPS 12V 4.5Ah", "DATASHIELD", "energia/baterias-ups/selladas-12v"],
  ["Xzeal XZCO413B enfriamiento liquido AIO 240mm ARGB", "XZEAL", "computo/componentes/enfriamiento/liquido-cpu/240mm"],
  ["Kingston KCP432SD8/16 memoria SO-DIMM DDR4 16GB 3200 CL22", "KINGSTON TECHNOLOGY", "computo/componentes/memoria-ram/sodimm-ddr4"],
  ["BRobotix 350323 bateria CMOS CR2032 litio 3V pack 5 piezas", "BROBOTIX", "energia/pilas-baterias/boton-cmos"],
  ["Epson T504220-AL botella tinta cyan T504 EcoTank L4150", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t504"],
  ["Xerox 106R04054 toner cyan alta capacidad VersaLink C8000", "XEROX", "impresion/consumibles/toner-laser/xerox"],
  ["Kingston DataTraveler Exodia DTX/64GB memoria USB 3.2", "KINGSTON TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb"],
  ["Xzeal X-Zynergy XZGAZNY1B gabinete Micro-ATX ITX RGB", "XZEAL", "computo/componentes/gabinetes/gaming"],
  ["Naceb NA-0963G teclado mecanico 60 con teclas intercambiables", "NACEB TECHNOLOGY", "computo/perifericos/teclados/mecanicos-compactos"],
  ["BRobotix 6000762 mouse inalambrico optico negro 1000 DPI", "BROBOTIX", "computo/perifericos/mouse/inalambricos"],
  ["Uniarch CAB-6-CCA cable UTP Cat6 100m CCA interior", "UNIARCH", "redes/cableado-estructurado/bobinas-utp/cat6"],
  ["Hikvision DS-3WR3N router WISP 2.4GHz 300Mbps 4 puertos", "HIKVISION", "redes/routers/wisp"],
  ["Hikvision DS-KIS313-P kit videoportero hibrido TurboHD pantalla touch 7 pulgadas", "HIKVISION", "seguridad/control-acceso/videoporteros-hibridos/kits"],
  ["Logitech Lift Vertical mouse ergonomico grafito Bluetooth Logi Bolt", "LOGITECH", "computo/perifericos/mouse/inalambricos/ergonomicos"],
  ["ADATA SU630 ASU630SS-240GQ-R SSD 240GB 2.5 SATA 3D QLC", "ADATA", "computo/almacenamiento/ssd/2-5-sata"],
  ["EC Line EC-LS-9620-USB lector codigo barras laser 1D USB", "EC LINE", "punto-de-venta/lectores-codigo-barras"],
  ["BRobotix 6000298 candado Nano combinacion laptop 1.80 m", "BROBOTIX", "accesorios/seguridad-fisica/candados-laptop"],
  ["BRobotix 764786 adaptador CCTV BNC macho a bornera", "BROBOTIX", "seguridad/cctv/accesorios-cableado/conectores-bnc"],
  ["Easy Line Storm audifonos in-ear 3.5mm microfono desmontable", "EASY LINE", "audio/audifonos/alambricos-3-5mm"],
  ["MSI GeForce RTX 5050 8G Ventus 2X OC GDDR6 Blackwell", "MSI OEM", "computo/componentes/tarjetas-video/nvidia-geforce/rtx-50/rtx-5050"],
  ["Dahua S5PRO dashcam doble canal 4K 1080p Wi-Fi GPS", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-moviles/dashcam"],
  ["VICA ALPHA 2K UPS online doble conversion rack torre 2000VA 2000W", "VICA", "energia/no-breaks-ups/doble-conversion/rack-torre"],
  ["Uniarch UHO-P2A-M3F4D camara IP WiFi PT exterior 3MP auto tracking", "UNIARCH", "seguridad/cctv/camaras-ip-wifi/pt-exterior"],
  ["Provision ISR PoES-0460C+2I-V2 switch PoE 4 puertos 60W modo CCTV", "PROVISION-ISR", "redes/switches/poe-no-administrables/cctv"],
  ["Manhattan 323222 cable HDMI alta velocidad con Ethernet 3m 10.2Gbps", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad"],
  ["BRobotix 053161 adaptador OTG USB-C a USB-A 3.2 20cm", "BROBOTIX", "accesorios/cables-adaptadores/usb/otg-usb-c"],
  ["Nexxt Solutions Home NHB-W310 foco inteligente Wi-Fi GU10 4W blanco ajustable", "NEXXT SOLUTIONS HOME", "domotica/iluminacion-inteligente/focos-wifi"],
  ["MSI SPATIUM S270 SATA 2.5 480GB SSD 3D NAND", "MSI OEM", "computo/almacenamiento/ssd/2-5-sata"],
  ["Grandstream GWN7801P switch administrable L2+ PoE Gigabit 8 puertos 2 SFP", "GRANDSTREAM", "redes/switches/poe-administrables/gigabit"],
  ["Naceb NA-589R audifonos diadema alambricos 3.5mm rojo con microfono", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono"],
  ["Manhattan 340458 cable USB 2.0 A-B 3m plata 480Mbps", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-b/3m"],
  ["TP-Link TL-SF1008D switch no administrable Fast Ethernet 8 puertos", "TP LINK", "redes/switches/no-administrables/fast-ethernet"],
  ["TP-Link EAP211-Bridge Kit Omada puente inalambrico exterior 5GHz 867Mbps 1km", "TP LINK", "redes/radioenlaces-antenas/puentes-wifi-exterior"],
  ["Huawei MateBook D16 53014MUD laptop 16 pulgadas i5-13420H 16GB 512GB", "HUAWEI", "computo/laptops/16-pulgadas"],
  ["Thermaltake Core P6 TG Snow CA-1V2-00M6WN-00 gabinete ATX mid tower open frame", "THERMALTAKE", "computo/componentes/gabinetes/atx-mid-tower"],
  ["Balam Rush GK9791 Dominate Expert teclado gamer mecanico inalambrico RGB", "BALAM RUSH", "computo/perifericos/teclados/inalambricos/mecanicos-gaming"],
  ["Koblenz 10017 USB/R no break linea pro 1000VA 500W 8 contactos", "KOBLENZ", "energia/no-breaks-ups/line-interactive/1000va"],
  ["Tech Zone TZACMOA01 mouse alambrico negro 1200 DPI 1.5m", "TECH ZONE ACCESORIOS", "computo/perifericos/mouse/alambricos/basicos"],
  ["Uniarch UAC-B112-F28-W camara bala analog HD ColourHunter 2MP", "UNIARCH", "seguridad/cctv/camaras-analogicas/bullet-hd"],
  ["Nextep NE-650BG silla basica gris altura ajustable sin brazos soporta 120 kg", "NEXTEP", "oficina/mobiliario-accesorios/sillas-oficina/operativas-sin-brazos"],
  ["Vorago KSP-530 bafle karaoke 40W RMS 5400mAh flame light TWS Bluetooth", "VORAGO", "audio/bocinas/portatiles/karaoke-party"],
  ["Manhattan 421010 mini kit limpiador LCD 60cc pantalla", "MANHATTAN", "computo/accesorios/limpieza/limpiadores-pantalla"],
  ["Saxxon SUA-HAC-B20M-0280B camara bala analog HD 2MP 1080P IR 30m IP67", "SAXXON", "seguridad/cctv/camaras-analogicas/bullet-hd"],
  ["CDP R-UPR1008 no break interactivo 1000VA 500W 8 contactos", "CDP", "energia/no-breaks-ups/line-interactive/1000va"],
  ["BRobotix 206823 cable USB 2.0 Tipo A a Tipo A 0.9m negro", "BROBOTIX", "accesorios/cables-adaptadores/usb/usb-a-a"],
  ["Kaspersky Standard KL1041Z5KFS 10 dispositivos 1 ano fisica", "KASPERSKY", "software/seguridad/antivirus/multidispositivo"],
  ["TP-Link TL-WN8200ND adaptador USB Wi-Fi alta potencia 300Mbps 2 antenas", "TP LINK", "redes/adaptadores-wifi/usb/alta-potencia"],
  ["Koblenz SS-460 C supresor de picos 460 joules 6 contactos", "KOBLENZ", "energia/supresores-reguladores/supresores-picos/multicontactos"],
  ["IMOU IPC-S3EN-3M0WE Bullet 3MP Wi-Fi Full Color IMOU Sense", "IMOU", "seguridad/cctv/camaras-ip-wifi/bullet-exterior"],
  ["TP-Link RE450 extensor de rango Wi-Fi AC1750 dual band", "TP LINK", "redes/extensores-wifi/dual-band"],
  ["DataShield UT-3000 no break 3000VA 2700W 8h recarga", "DATASHIELD", "energia/no-breaks-ups/doble-conversion/rack-torre/3000va"],
  ["Qian QMF-REF19-01 Monitor Office Mate 19 pulgadas 1440x900 75Hz", "QIAN", "computo/monitores/oficina/19-wxga"],
  ["EZVIZ CS-EB3 camara IP Wi-Fi 2K bateria cero cables exterior", "EZVIZ", "seguridad/cctv/camaras-ip-wifi/bateria-exterior"],
  ["Provision ISR SH-4100A5S-2L DVR pentahibrido 4 canales 2MP H265", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/xvr-pentahibrido"],
  ["Uniarch IPC-T122-APF28-E camara IP turret 2MP PoE techo", "UNIARCH", "seguridad/cctv/camaras-ip-poe/turret/2mp"],
  ["Vorago AU-303 cargador auto micro USB 2.4A negro", "VORAGO", "energia/cargadores-usb/auto-micro-usb"],
  ["Perfect Choice PC-045274 mini mouse dual Bluetooth 2.4GHz USB-C recargable", "PERFECT CHOICE", "computo/perifericos/mouse/inalambricos/multi-dispositivo"],
  ["HPE Microsoft Windows Server 2025 Remote Desktop Services 5 User CAL", "HEWLETT PACKARD ENTERPRISE", "software/licencias/windows-server/cal-rds"],
  ["Acteck TI747 Inspire Trek teclado inalambrico multidispositivo Bluetooth 5.1", "ACTECK", "computo/perifericos/teclados/inalambricos/multidispositivo"],
  ["Brother M531 cinta etiqueta azul 12mm x 8m P-touch M", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-m"],
  ["Kyocera TK-1262 toner negro 10000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera"],
  ["Tenda N6P-8H NVR PoE 8 canales 4K UHD HDD 10TB", "TENDA", "seguridad/cctv/dvr-nvr/nvr-poe"],
  ["Fujitsu ScanSnap iX1300 escaner documental compacto duplex Wi-Fi", "FUJITSU", "impresion/escaneres/documentales-compactos"],
  ["Ubiquiti Rocket Prism RP-5AC-GEN2 airMAX AC radio base 5GHz GPS", "UBIQUITI", "redes/radioenlaces-antenas/radios-base/airmax-ac"],
  ["TP-Link TL-SG108PE switch Easy Smart 8 puertos Gigabit 4 PoE 55W", "TP LINK", "redes/switches/poe-administrables/gigabit/8-puertos"],
  ["Vorago KSP-580 bafle karaoke Bluetooth RGB dos bocinas 6.5", "VORAGO", "audio/bocinas/portatiles/karaoke-party"],
  ["Logitech Brio 100 960-001586 webcam FHD 1080p RightLight 2", "LOGITECH", "computo/perifericos/webcams/usb-fhd"],
  ["Nexxt AW250NXT18 pinza corte lateral profesional 5 pulgadas", "NEXXT SOLUTIONS", "herramientas/herramientas-mano/pinzas-corte"],
  ["SanDisk Ultra Shift Z410 SDCZ410-032G-G46BB memoria USB 32GB 3.2", "SANDISK", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Lenovo 4XB7A77446 ThinkSystem HDD 2TB 3.5 7.2K SATA Simple Swap", "LENOVO", "computo/servidores/componentes/discos-hdd"],
  ["Ovaltech OTR4551 bateria para Acer AS5742 10.8V 6 celdas", "OVALTECH", "computo/accesorios/baterias-laptop/acer"],
  ["XPG GAMMIX D35 AX4U32008G16A-SBKD35 UDIMM DDR4 8GB 3200MHz", "ADATA", "computo/componentes/memoria-ram/udimm-ddr4"],
  ["Netis ST108GD switch no administrable Gigabit 8 puertos metalico", "NETIS", "redes/switches/no-administrables/gigabit/8-puertos"],
  ["Gigabyte Radeon RX 9060 XT Gaming OC ICE 16GB GDDR6", "GIGABYTE", "computo/componentes/tarjetas-video/amd-radeon/rx-9000/rx-9060-xt"],
  ["Gigabyte B850 Gaming X WiFi6E tarjeta madre AMD AM5 DDR5", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am5"],
  ["Tech Zone TZ20COMB02-INA combo teclado y mouse inalambrico azul", "TECH ZONE ACCESORIOS", "computo/perifericos/combos-teclado-mouse/inalambricos"],
  ["Thermaltake View 51 TG ARGB gabinete full tower E-ATX negro", "THERMALTAKE", "computo/componentes/gabinetes/full-tower/e-atx"],
  ["Synology DS725+ NAS 2 bahias Ryzen R1600 2.5GbE M.2 NVMe", "SYNOLOGY", "computo/almacenamiento/nas/2-bahias"],
  ["Manhattan 180764 mini teclado USB inalambrico compacto 82 teclas", "MANHATTAN", "computo/perifericos/teclados/inalambricos/compactos"],
  ["Game Factor WG400 webcam Full HD 1080p 30fps LED microfono", "GAME FACTOR", "computo/perifericos/webcams/usb-fhd"],
  ["Logitech G535 Lightspeed headset gaming inalambrico 40mm 33 horas", "LOGITECH", "audio/audifonos/gaming-inalambricos"],
  ["Balam Rush GR Burst GR550B BR-937696 fuente ATX 550W 80 Plus Bronze", "BALAM RUSH", "computo/componentes/fuentes-poder/atx-80-plus-bronze"],
  ["Dahua DH-SF1005L switch Fast Ethernet no administrable 5 puertos", "DAHUA TECHNOLOGY", "redes/switches/no-administrables/fast-ethernet"],
  ["BRobotix 406160 funda uso rudo Galaxy A9 Plus 11 giro 360", "BROBOTIX", "computo/tabletas/accesorios/fundas-uso-rudo"],
  ["Uniarch IPC-B242-ADF28K-WP OwlView camara bullet IP PoE 2MP", "UNIARCH", "seguridad/cctv/camaras-ip-poe/bullet/2mp-owlview"],
  ["Uniarch IPC-T134-AF28-ECO camara IP turret 4MP PoE microfono", "UNIARCH", "seguridad/cctv/camaras-ip-poe/turret/4mp"],
  ["TP-Link Deco S7 3-Pack sistema WiFi Mesh AC1900 tres puertos Gigabit", "TP LINK", "redes/routers/mesh-wifi/wifi-5-ac1900"],
  ["Logitech M280 mouse inalambrico rojo 1000 DPI", "LOGITECH", "computo/perifericos/mouse/inalambricos/basicos"],
  ["Perfect Choice PC-084037 Rohe portafolio laptop 15.6 gris", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["TP-Link RE205 extensor de rango AC750 dual band 300 433 Mbps", "TP LINK", "redes/extensores-wifi/dual-band/ac750"],
  ["Naceb NA-0643 Oasis monitor gaming 32 QHD 165Hz 1ms", "NACEB GAMING", "computo/monitores/gaming/32-qhd"],
  ["Hisense 55QD6QV televisor QLED VIDAA 55 4K Quantum Dot", "HISENSE", "video/televisores/qled-vidaa-tv"],
  ["Evotec EV-3001 lector codigo de barras 1D USB", "EVOTEC", "punto-de-venta/lectores-codigo-barras/1d-usb"],
  ["ADATA AD4S32008G22-SGN memoria SO-DIMM DDR4 8GB 3200MHz", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200"],
  ["Stylos STCBHUB42G hub USB-C 4 puertos plata", "STYLOS", "computo/accesorios/hubs-usb/usb-c/4-puertos"],
  ["BRobotix 6000410 pluma stylus tablet Duopk plata", "BROBOTIX", "computo/tabletas/accesorios/stylus"],
  ["Grandstream GWN7801 switch administrable L2+ Gigabit 8 puertos 2 SFP", "GRANDSTREAM", "redes/switches/administrables/gigabit"],
  ["Intel Core i5-14400 procesador LGA1700 10 nucleos 16 hilos", "INTEL", "computo/componentes/procesadores/intel-core-i5-lga1700"],
  ["BRobotix 263793 convertidor audio a Bluetooth para auto negro", "BROBOTIX", "audio/adaptadores-bluetooth/auto"],
  ["HPE P38995-B21 fuente Flex Slot Platinum 800W hot-plug", "HEWLETT PACKARD ENTERPRISE", "computo/servidores/componentes/fuentes-poder/flex-slot"],
  ["Tenda MW5G 2-Pack router mesh Wi-Fi AC1200", "TENDA", "redes/routers/mesh-wifi/wifi-5-ac1200"],
  ["Perfect Choice PC-030331 E-Duster aire comprimido ecologico 330 ml", "PERFECT CHOICE", "computo/accesorios/limpieza/aire-comprimido"],
  ["Naceb Gaming PLAYER Crystal Case NA-0603 gabinete Full ATX negro", "NACEB GAMING", "computo/componentes/gabinetes/gaming/full-atx"],
  ["Koblenz 20015 OL USB/R UPS online 2000VA 1800W rack tower", "KOBLENZ", "energia/no-breaks-ups/doble-conversion/2000va"],
  ["Mirati MISW2 mini switch inteligente WiFi 2.4GHz 3680W", "MIRATI", "domotica/interruptores-inteligentes/wifi"],
  ["TP-Link Tapo C210 camara IP WiFi interior 3MP pan tilt", "TP LINK", "seguridad/cctv/camaras-ip-wifi/pt-interior/3mp"],
  ["BRobotix USB V2.0 a RJ45 adaptador Ethernet 10/100 blanco", "BROBOTIX", "redes/adaptadores-ethernet/usb-fast-ethernet"],
  ["ADATA Speed Plus microSDXC 256GB UHS-I U3 V30 A2", "ADATA", "computo/almacenamiento/memorias-flash/microsd/256gb-v30-a2"],
  ["BRobotix 500074A mouse pad gel azul marino", "BROBOTIX", "computo/accesorios/mousepads/gel"],
  ["Gigabyte GV-N506TEAGLE OC-8GD GeForce RTX 5060 Ti 8GB GDDR7", "GIGABYTE", "computo/componentes/tarjetas-video/nvidia-geforce/rtx-50/rtx-5060-ti"],
  ["Tripp Lite SMART1000LCD UPS 1000VA 500W LCD", "TRIPP-LITE", "energia/no-breaks-ups/line-interactive/1000va/lcd"],
  ["TP-Link RE815XE repetidor Wi-Fi 6E Mesh AXE5400 tri-band", "TP LINK", "redes/extensores-wifi/tri-band/wifi-6e-axe5400"],
  ["Meriva Streamax MC38 camara AHD para placa vehicular 2MP IP69K", "MERIVA", "seguridad/cctv/camaras-moviles/ahd-placa"],
  ["Perfect Choice Silhouette PC-084129 portafolio laptop 15.6 negro", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/maletines-laptop/15-6"],
  ["Meriva MOB-808D camara IP bullet 8MP PoE iluminacion dual", "MERIVA", "seguridad/cctv/camaras-ip-poe/bullet/8mp"],
  ["Getttech GFS-60020-01 fuente poder ATX 600W ventilador 120mm", "GETTTECH", "computo/componentes/fuentes-poder/atx-600w"],
  ["Generico AC-HP-PinCentral cargador laptop 65W 18.5V 3.5A", "GENERICO", "computo/accesorios/cargadores-laptop/hp-pin-central"],
  ["ADATA R050 PR050-11LB power bank magnetico 5000mAh azul", "ADATA", "energia/power-banks/magneticos/5000mah"],
  ["Aspel PSAEL1AN actualizacion usuario adicional SAE 10 fisico", "ASPEL", "software/licencias/aspel-sae"],
  ["Tripp Lite OMNIVS1200LCD UPS interactivo 1200VA 600W LCD", "TRIPP-LITE", "energia/no-breaks-ups/line-interactive/1200va/lcd"],
  ["Kyocera TK-5417C toner cian 13000 paginas TASKalfa", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5417"],
  ["Perfect Choice PC-113218 Owty bocina Bluetooth portatil teclas mecanicas", "PERFECT CHOICE", "audio/bocinas/bluetooth/portatiles"],
  ["Provision ISR I2-320A-28 camara AHD bala 2MP IR 20m", "PROVISION ISR", "seguridad/cctv/camaras-analogicas/bullet-hd/2mp-ahd"],
  ["Silimex Compucare locion limpiadora protectora 1 LT", "SILIMEX", "computo/accesorios/limpieza/lociones-limpiadoras"],
  ["CDP B-12/9.0 bateria UPS 12V 9Ah", "CDP", "energia/baterias-ups/selladas-12v/9ah"],
  ["HiLook IPC-D120HA-LUC domo IP 2MP PoE AcuSense Lite", "HILOOK", "seguridad/cctv/camaras-ip-poe/domo/2mp"],
  ["Naceb NA-0146 gabinete externo disco duro 2.5 USB 3.1 aluminio", "NACEB TECHNOLOGY", "computo/almacenamiento/gabinetes-externos/2-5-usb-3-1"],
  ["SanDisk SDCZ50C-016G-B35BE Cruzer Blade USB 16GB azul", "SANDISK", "computo/almacenamiento/memorias-flash/usb/16gb"],
  ["Tripp Lite N206-KJ01-IND conector keystone Cat6 Cat5e negro", "TRIPP-LITE", "redes/cableado-estructurado/conectores-keystone/rj45-cat6-industrial"],
  ["Naceb NA-0132 mouse inalambrico 10000 DPI 5 botones negro", "NACEB TECHNOLOGY", "computo/perifericos/mouse/inalambricos/alto-dpi"],
  ["TP-Link Tapo C220 camara WiFi 2K QHD IA pan tilt", "TP LINK", "seguridad/cctv/camaras-ip-wifi/pt-interior/4mp-2k"],
  ["Provision ISR BSH-340IPBN-28 camara bala IP 4MP PoE microfono", "PROVISION-ISR", "seguridad/cctv/camaras-ip-poe/bullet/4mp-mic"],
  ["Brobotix 180824 cable SATA corriente doble 0.15m", "BROBOTIX", "computo/componentes/cables-internos/alimentacion-sata"],
  ["Perfect Choice PC-201076 kit teclado y mouse alambrico USB negro", "PERFECT CHOICE", "computo/perifericos/combos-teclado-mouse/alambricos"],
  ["Urban Balance HDMI-TIPC-UB adaptador HDMI a USB-C 2.0 gris", "URBAN BALANCE", "accesorios/cables-adaptadores/video-usb-c-hdmi"],
  ["HP X4E75AL cabezal impresion negro Smart Tank", "HP", "impresion/consumibles/cabezales/hp-smart-tank"],
  ["Lenovo ThinkPad E14 Gen 6 21M8000VLM Core Ultra 7", "LENOVO", "computo/laptops/empresariales/14-pulgadas"],
  ["Tripp Lite ECO1000LCD UPS 1000VA 600W Energy Star LCD", "TRIPP-LITE", "energia/no-breaks-ups/line-interactive/1000va/lcd"],
  ["LG 24U421A-B monitor 23.8 FHD curvo 100Hz", "LG", "computo/monitores/oficina/24-fhd-100hz"],
  ["Ovaltech OVPR-580MM soporte acero proyector 380-580mm", "OVALTECH", "video/accesorios-proyeccion/soportes-proyector"],
  ["CDP UPO11-1RTAX UPS online 1000VA 1000W rack torre", "CDP", "energia/no-breaks-ups/doble-conversion/rack-torre/1000va"],
  ["SanDisk SDSQXAO-512G-GNCZN microSDXC 512GB Nintendo Switch", "SANDISK", "computo/almacenamiento/memorias-flash/microsd/512gb-nintendo-switch"],
  ["Sabo 053-100 espuma limpiadora multisurface 590 ml", "SABO", "computo/accesorios/limpieza/espumas-limpiadoras/590ml"],
  ["Balam Rush DRIFT PRO MG7 mouse gamer inalambrico 2.4GHz", "BALAM RUSH", "computo/perifericos/mouse/inalambricos/gaming/2-4ghz"],
  ["Kensington K60397WW Simply Portable Lite mochila laptop 16 verde", "KENSINGTON", "computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas"],
  ["ZKTeco VK07-C51 videoportero analogico 7 pulgadas 4 hilos", "ZKTECO", "seguridad/control-acceso/videoporteros-analogicos/kits"],
  ["Manhattan 461993 soporte TV pared fijo 60 a 100 100kg", "MANHATTAN", "video/soportes-tv/pared/fijos-60-100"],
  ["TP-Link TL-SF1016D switch 16 puertos 10/100 no administrable", "TP LINK", "redes/switches/no-administrables/fast-ethernet/16-puertos"],
  ["Necnon NBHG-DRAGON HI-FI headset gaming alambrico azul vibracion", "NECNON", "audio/audifonos/gaming-alambricos"],
  ["Grandstream GWN7701 switch gigabit no administrable 8 puertos", "GRANDSTREAM", "redes/switches/no-administrables/gigabit/8-puertos"],
  ["Patriot P300P1TBM28 SSD 1TB M.2 NVMe PCIe Gen3x4", "PATRIOT", "computo/almacenamiento/ssd/m2-nvme/1tb-gen3"],
  ["Brobotix 263045 bocina Bluetooth portatil radio FM USB azul", "BROBOTIX", "audio/bocinas/bluetooth/portatiles/fm-usb"],
  ["Ovaltech OTDGJKNX bateria laptop Dell Latitude 5480 8200mAh", "OVALTECH", "computo/accesorios/baterias-laptop/dell"],
  ["Acteck Shift Plus AV400 AC-934756 adaptador HDMI a VGA 20 cm", "ACTECK", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Smartbitt SBAVRC2000 regulador voltaje 2000VA linea blanca", "SMARTBITT", "energia/supresores-reguladores/reguladores-voltaje/avr/linea-blanca"],
  ["TP-Link Omada SG3428MP switch PoE administrable 24 puertos gigabit", "TP LINK", "redes/switches/poe-administrables/gigabit/24-puertos"],
  ["TP-Link POE10E extensor PoE Fast Ethernet", "TP LINK", "redes/poe/extensores/fast-ethernet"],
  ["Silimex Sili Jet 40 454 ml aflojatodo anticorrosivo", "SILIMEX", "mantenimiento/quimicos/aflojatodo-anticorrosivo"],
  ["TP-Link Archer GE800 router gaming Wi-Fi 7 BE19000", "TP LINK", "redes/routers/wifi-7/gaming-be19000"],
  ["Tech Zone TZLBP27-A Backpack Max III mochila laptop 16", "TECH ZONE", "computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas"],
  ["Stylos STMSDS4B memoria micro SD 64GB Clase 10", "STYLOS", "computo/almacenamiento/memorias-flash/microsd/64gb-clase-10"],
  ["Balam Rush BR-922999 Heimdall Spectrum mousepad carga inalambrica RGB", "BALAM RUSH", "computo/accesorios/mousepads/gaming-carga-inalambrica"],
  ["Nextep NE-205 lampara detectora billetes falsos", "NEXTEP", "punto-de-venta/detectores-billetes"],
  ["Ubiquiti POE-24-24W inyector PoE 24V 24W", "UBIQUITI", "redes/poe/inyectores/24v"],
  ["SanDisk SDCZ50C-016G-B35PE Cruzer Blade USB 16GB Electric Pink", "SANDISK", "computo/almacenamiento/memorias-flash/usb/16gb"],
  ["Naceb NA-0139N mouse inalambrico dual mode 2.4G BT 1600 DPI", "NACEB TECHNOLOGY", "computo/perifericos/mouse/inalambricos/multi-dispositivo"],
  ["Perfect Choice PC-101260 adaptador USB Tipo C a HDMI 4K 60Hz", "PERFECT CHOICE", "accesorios/cables-adaptadores/video-usb-c-hdmi"],
  ["ADATA Premier Pro V30 tarjeta SD 64GB Clase 10 100MBs 80MBs", "ADATA", "computo/almacenamiento/memorias-flash/sd/64gb-v30"],
  ["Manhattan 312721 cable SVGA HD15 macho macho 4.5m", "MANHATTAN", "accesorios/cables-adaptadores/video-vga/hd15-4-5m"],
  ["Balam Rush GR850G fuente ATX 850W 80 Plus Gold", "BALAM RUSH", "computo/componentes/fuentes-poder/atx-80-plus-gold/850w"],
  ["Nextep NE-515 cajon de dinero acero 8 monedas 5 billetes", "NEXTEP", "punto-de-venta/cajones-dinero/metalicos"],
  ["LG 32LR600BPSC television LED 32 pulgadas HD webOS", "LG", "video/televisores/led-webos/32-hd"],
  ["Lenovo ThinkPad E14 G7 21TA000FLM Core 5 210H 14 pulgadas", "LENOVO", "computo/laptops/empresariales/14-pulgadas"],
  ["Acteck CW480 webcam 2K USB 2592 x 1944 AC-933056", "ACTECK", "computo/perifericos/webcams/usb-2k"],
  ["Tripp Lite SMART750USB UPS interactivo 750VA 450W AVR", "TRIPP-LITE", "energia/no-breaks-ups/line-interactive/750va"],
  ["Ubiquiti RD-5G30 RocketDish antena 5GHz 30dBi", "UBIQUITI", "redes/radioenlaces-antenas/antenas-parabolicas/5ghz-30dbi"],
  ["Provision ISR NVR8-16400AN 16 canales 8MP 2 SATA 20TB", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/nvr-ip/16-canales"],
  ["Dahua NA+C1C11:G21 PDU barra 8 contactos USA", "DAHUA TECHNOLOGY", "energia/pdu-rack/multicontactos-8"],
  ["Samsung Odyssey G3 LS24DG300ELXZX monitor 24 FHD 180Hz", "SAMSUNG", "computo/monitores/gaming/24-fhd/180hz"],
  ["Intellinet 210546 jack keystone Cat5e azul de impacto", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat5e"],
  ["Logitech Pebble Keys 2 K380s teclado Bluetooth blanco", "LOGITECH", "computo/perifericos/teclados/inalambricos/multidispositivo"],
  ["TP-Link Archer BE400 router Wi-Fi 7 BE6500 doble banda", "TP LINK", "redes/routers/wifi-7/be6500"],
  ["Kyocera TK-1122 toner negro 3000 paginas TONKYC100", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-1122"],
  ["Techzone ECO HERO mochila laptop 15.6 pulgadas negra", "TECHZONE", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6"],
  ["Hikvision DS-2CE78U0T-LXTS turret 8MP ColorVu sirena estrobo", "HIKVISION", "seguridad/cctv/camaras-turbohd/turret/8mp-colorvu"],
  ["Canon GPR-52 toner cian 16500 paginas CARCNN6050", "CANON", "impresion/consumibles/toner-laser/canon/gpr-52"],
  ["Brobotix 044695R base enfriadora laptop 15 pulgadas LED", "BROBOTIX", "computo/accesorios/bases-enfriadoras/15-pulgadas"],
  ["Dahua Hero-K51H camara WiFi PT interior 5MP 2880 x 1620", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-wifi/pt-interior/5mp"],
  ["Manhattan 323215 cable HDMI 2.0m Ethernet alta velocidad", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/2m-ethernet"],
  ["Manhattan 208222 switch HDMI 3 entradas 4K60 HDR", "MANHATTAN", "video/accesorios-av/switches-hdmi/3x1-4k60"],
  ["Hikvision DS-3E1526P-EI switch PoE administrable 24 puertos", "HIKVISION", "redes/switches/poe-administrables/gigabit/24-puertos"],
  ["Dahua DH-IPC-HDW2449T-S-IL camara IP turret 4MP WizSense dual light", "DAHUA", "seguridad/cctv/camaras-ip-poe/turret/4mp-dual-light"],
  ["Lanix XBook B15 42138 Core i5-13500H 15.6 Windows 11 Pro", "LANIX", "computo/laptops/empresariales/15-6-pulgadas"],
  ["Brother TN436BK toner negro 6500 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-436bk"],
  ["ESET Small Office Security Pack 5 licencias 1 ano", "ESET", "software/seguridad/antivirus/small-office"],
  ["Ovaltech OVTV-CA3255 soporte carrito TV 32 a 55 35kg", "OVALTECH", "video/soportes-tv/piso-carrito/32-55"],
  ["Kyocera TK-3432 toner negro 21000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-3432"],
  ["Kaspersky Standard KL1041Z5EFS-22 5 dispositivos 1 ano", "KASPERSKY", "software/seguridad/antivirus/multidispositivo/5-dispositivos"],
  ["Gigabyte B850M D3HP tarjeta madre AMD AM5 DDR5 micro ATX", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am5/b850m"],
  ["TP-Link RE200 repetidor Wi-Fi AC750 433 300 Mbps", "TP LINK", "redes/extensores-wifi/dual-band/ac750"],
  ["ADATA AD4U266616G19-SGN memoria UDIMM DDR4 16GB 2666MHz", "ADATA", "computo/componentes/memoria-ram/udimm-ddr4/16gb-2666"],
  ["Manhattan 440271 candado laptop con llave 1.4m K-slot", "MANHATTAN", "accesorios/seguridad-fisica/candados-laptop/llave"],
  ["Manhattan 323239 cable HDMI alta velocidad Ethernet 5m", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/5m-ethernet"],
  ["Logitech M90 910-004053 mouse USB alambrico 1000 DPI", "LOGITECH", "computo/perifericos/mouse/alambricos/basicos"],
  ["Stylos STMSSD4B SSD 1TB SATA III 2.5 pulgadas", "STYLOS", "computo/almacenamiento/ssd/2-5-sata/1tb"],
  ["Manhattan MW6200 190343 mouse inalambrico 6 botones 1600 DPI", "MANHATTAN", "computo/perifericos/mouse/inalambricos"],
  ["Barkan E310+ soporte TV pared inclinable 50kg", "BARKAN", "video/soportes-tv/pared/inclinables"],
  ["Kingston DataTraveler SE9 G3 64GB USB 3.2 oro", "KINGSTON", "computo/almacenamiento/memorias-flash/usb/64gb"],
  ["Streamax MADKIT kit ADAS DSM R-Watch para MDVR", "STREAMAX", "seguridad/cctv/camaras-moviles/adas-dsm"],
  ["GHIA GSOM3 lector codigo barras QR 2D omnidireccional USB", "GHIA", "punto-de-venta/lectores-codigo-barras/2d-omnidireccionales"],
  ["Brother LC402XLM cartucho tinta magenta alto rendimiento", "BROTHER", "impresion/consumibles/cartuchos-tinta/brother-lc402xl"],
  ["HP 154A W1540A kit recarga toner LaserJet Tank negro", "HP", "impresion/consumibles/toner-laser/hp/laserjet-tank-154a"],
  ["Dahua DH-HAC-HFW1500TLN-0280B-S2 camara bullet HDCVI 5MP", "DAHUA", "seguridad/cctv/camaras-hdcvi/bullet"],
  ["Brobotix 651879 adaptador USB-C a RJ45 Gigabit", "BROBOTIX", "redes/adaptadores-ethernet/usb-gigabit"],
  ["Nextep NE-512 mini impresora termica portatil 58mm Bluetooth", "NEXTEP", "punto-de-venta/impresoras-recibos/portatiles-58mm"],
  ["Aspel PCOIL1AO COI 11 usuario adicional fisico", "ASPEL", "software/licencias/aspel-coi"],
  ["Synology DS925+ NAS 4 bahias Ryzen V1500B 2.5GbE", "SYNOLOGY", "computo/almacenamiento/nas/4-bahias"],
  ["Tech Zone POS TZPOIMT01 miniprinter termica 58mm USB RJ11", "TECH ZONE POS", "punto-de-venta/impresoras-recibos"],
  ["Lenovo 13FA003VLS ThinkCentre neo 55a 24 Gen 6 All in One", "LENOVO", "computo/desktops/all-in-one"],
  ["HiLook DS-7204HGHI-M1(T) DVR 4 canales TurboHD AcuSense", "HILOOK", "seguridad/cctv/dvr-nvr/dvr-4-canales"],
  ["Saxxon LKV312HDR-V2.0 splitter HDMI 1x2 4K", "SAXXON", "video/accesorios-av/splitters-hdmi/1x2-4k"],
  ["Cooler Master HAF 500 H500-WGNN-S00 gabinete ATX alto flujo", "COOLER MASTER", "computo/componentes/gabinetes/gaming/atx-alto-flujo"],
  ["SanDisk Ultra Shift SDCZ410-128G-G46BB memoria USB 128GB turquesa", "SANDISK", "computo/almacenamiento/memorias-flash/usb/128gb"],
  ["Generico AC-ASUS AGUJA cargador Asus 40W 19V 2.1A 2.5 x 0.7", "GENERICO", "computo/accesorios/cargadores-laptop/asus-aguja-40w"],
  ["Logitech H390 diadema USB con microfono noise-cancelling", "LOGITECH", "audio/audifonos/usb/diadema-microfono"],
  ["Brobotix 170144 adaptador jack plug VCD macho a terminal CCTV", "BROBOTIX", "seguridad/cctv/accesorios-cableado/conectores-corriente"],
  ["PCM 50000B0015A etiquetas TT 4 x 6 transferencia termica 4000", "PCM", "impresion/consumibles/etiquetas-papel/transferencia-termica"],
  ["Brobotix 651480 adaptador USB 3.0 tipo C macho a USB-A hembra", "BROBOTIX", "accesorios/cables-adaptadores/usb/otg-usb-c"],
  ["Brother BT5001M botella de tinta magenta 48.8 ml 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-bt5001"],
  ["Vorago Slimbay A SBA RZN 3200G-TR-3 Ryzen 3 3200G 8GB 240GB", "VORAGO", "computo/desktops/slim"],
  ["Yeyian Raiden YFB-55020-01 fuente 550W 80 Plus Bronze", "YEYIAN", "computo/componentes/fuentes-poder/atx-80-plus-bronze/550w"],
  ["Hikvision DS-7104HGHI-K1(S) DVR 4 canales H.265 Pro 1080p Lite", "HIKVISION", "seguridad/cctv/dvr-nvr/dvr-4-canales"],
  ["Brother TN229XXLY toner amarillo super alto rendimiento 4000 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-229/xxl-amarillo"],
  ["Mercusys MS105GS switch Gigabit 5 puertos RJ45 metalico", "MERCUSYS", "redes/switches/no-administrables/gigabit/5-puertos"],
  ["Stylos STPTEC6B teclado alambrico USB membrana 104 teclas", "STYLOS", "computo/perifericos/teclados/alambricos/usb"],
  ["TP-Link Tapo L530E 4-Pack focos Wi-Fi multicolor E26 RGBW", "TP-LINK", "domotica/iluminacion-inteligente/focos-wifi/rgb/e26-4-pack"],
  ["MSI Cubi 5 12M-086BUS mini PC barebone Core i3-1215U dual LAN", "MSI", "computo/desktops/mini-pc/barebone"],
  ["Anviz AN-GC100 checador biometrico huella RFID 1000 usuarios", "ANVIZ", "seguridad/control-acceso/biometricos/checadores-asistencia"],
  ["BRobotix 406498 soporte POS tablet iPad antirrobo giro 360", "BROBOTIX", "punto-de-venta/terminales-accesorios/soportes-tablet"],
  ["DataShield KS800 LCD no-break 800VA 480W 6 contactos", "DATASHIELD", "energia/no-breaks-ups/line-interactive/800va-lcd"],
  ["Perfect Choice Thumb PC-045120 mouse inalambrico silencioso 1600 DPI azul", "PERFECT CHOICE", "computo/perifericos/mouse/inalambricos/ergonomicos"],
  ["Provision ISR PoES-16250C+2Combo-V2 switch PoE 16 puertos CCTV 250W", "PROVISION-ISR", "redes/switches/poe-no-administrables/cctv/16-puertos"],
] as const;

describe("manual taxonomy researched batches", () => {
  it.each(researchedBatchCases)("%s -> %s", (name, brand, path) => {
    expect(classifyManualCategory({ name, brand, category: "laptops" }).path).toBe(path);
  });
});
