import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const batch160PlusCases = [
  ["SanDisk Portable SSD SDSSDE30-1T00-G26 1TB USB-C USB 3.2 Gen 2 800 MB/s", "SANDISK", "computo/almacenamiento/ssd/externos/usb-c/1tb/sandisk-portable", "storage"],
  ["Balam Rush Power Rush V2 silla gamer tela piel sintetica reclinable 135 120kg", "BALAM RUSH", "gaming/mobiliario/sillas-gamer/tela/reclinable-135-120kg", "gaming"],
  ["TP-Link TL-WN781ND adaptador Wi-Fi PCI Express N150 150Mbps", "TP LINK", "redes/adaptadores-wifi/pcie/n150", "networking"],
  ["Huawei BE3 53030CSM router Wi-Fi 7 BE3600 3570Mbps 2.5G negro", "HUAWEI", "redes/routers/wifi-7/be3600", "networking"],
  ["PCM EBA7670 rollo autocopiante 76 x 70 mm blanco amarillo paquete 50", "PCM", "punto-de-venta/consumibles/rollos-autocopia/76x70", "laptops"],
  ["Perfect Choice ClearBeat PC-117025 audifonos Bluetooth TWS con display USB-C negros", "PERFECT CHOICE", "audio/audifonos/bluetooth/tws/estuche-display", "headphones"],
  ["Hikvision CAMHKV2610 camara bala 5MP TurboHD exterior metal techo pared", "HIKVISION", "seguridad/cctv/camaras-turbohd/bullet/5mp", "cameras"],
  ["ADATA XPG Spectrix D35G AX4U320016G16A-SBKD35G memoria RAM DDR4 16GB 3200MHz RGB", "ADATA", "computo/componentes/memoria-ram/udimm-ddr4/16gb-3200", "components"],
  ["Hyundai Hy View HT34CGMBK01 monitor gaming curvo 34 UWQHD 180Hz negro", "HYUNDAI", "computo/monitores/gaming/ultrawide-curvos/34-uwqhd-180hz", "monitors"],
  ["Stylos ST300 STMUS316B memoria USB 16GB gris", "STYLOS", "computo/almacenamiento/memorias-flash/usb/16gb", "storage"],
  ["Manhattan 353274 cable HDMI alta velocidad con Ethernet 7.5 m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/7-5m", "accessories"],
  ["Brother TN229Y toner amarillo rendimiento estandar 1200 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-229/amarillo", "printers_scanners"],
  ["Lenovo ThinkVision T22i-30 63B0MAR6LA monitor 21.5 FHD IPS 60Hz", "LENOVO", "computo/monitores/oficina/22-fhd-60hz", "monitors"],
  ["Manhattan MW3050 190312 mouse inalambrico USB 1200 DPI negro", "MANHATTAN", "computo/perifericos/mouse/inalambricos/basicos/1200-dpi", "accessories"],
  ["Poly Studio V12 A9DD8AA#ABM barra de video USB 4K 20MP", "POLYCOM", "colaboracion/video-conferencia/barras-video/usb-4k", "accessories"],
  ["Provision ISR DMA-320IPEN-28-V4 camara domo IP PoE 2MP DDA2 microfono", "PROVISION-ISR", "seguridad/cctv/camaras-ip-poe/domo/2mp-analytics-mic", "cameras"],
  ["Stylos STMS321B memoria microSDHC 32GB clase 10 con adaptador", "STYLOS", "computo/almacenamiento/memorias-flash/microsd/32gb-clase-10", "storage"],
  ["Intellinet 715072 charola rack 19 pulgadas 1U 300mm 25kg negra", "INTELLINET", "infraestructura/racks-accesorios/charolas/1u-300mm-25kg", "networking"],
  ["Quaroni QD4S08G1 memoria RAM SO-DIMM DDR4 8GB 3200MHz CL22", "QUARONI", "computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200", "components"],
  ["Logitech G923 TRUEFORCE volante y pedales racing PS5 PS4 PC", "LOGITECH", "gaming/accesorios/volantes-simulacion/trueforce", "gaming"],
  ["Nexxt Solutions Home NHE-S100 interruptor inteligente Wi-Fi monopolar blanco", "NEXXT SOLUTIONS HOME", "hogar/casa-inteligente/interruptores-wifi/monopolares", "accessories"],
  ["Manhattan 152082 tarjeta serial PCI Express 2 puertos DB9", "MANHATTAN", "computo/componentes/tarjetas-expansion/serial-pcie/db9-2-puertos", "components"],
  ["Kensington K55256WW MagPro filtro de privacidad magnetico para laptop 16 16:10", "KENSINGTON", "computo/accesorios/filtros-privacidad/laptops/16-16-10", "accessories"],
  ["Koblenz 9022 USB no break interactivo 900VA 450W LCD", "KOBLENZ", "energia/no-breaks-ups/line-interactive/900va/lcd", "power"],
  ["Polaroid PASU100-63 rollo papel sublimacion 100gsm 63in x 100m blanco", "POLAROID", "impresion/consumibles/papel-sublimacion/rollos/63in-100m-100gsm", "printers_scanners"],
  ["PCM 50000B0160A etiquetas transferencia termica 4x2 R-700 caja 12 rollos", "PCM", "impresion/consumibles/etiquetas-transferencia-termica/4x2/r-700-12-rollos", "printers_scanners"],
  ["Brother TN890 toner negro ultra alto rendimiento 20000 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-890", "printers_scanners"],
  ["ADATA Premier Pro AUSDX128GUI3V30SA2-RA1 microSDXC 128GB UHS-I V30 A2 con adaptador", "ADATA", "computo/almacenamiento/memorias-flash/microsd/128gb-uhs-i-v30-a2", "storage"],
  ["Manhattan 371377 cable VGA SVGA HD15 macho macho 11m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-vga/hd15/11m", "accessories"],
  ["Brother TZe-641 cinta laminada P-touch 18mm x 8m negro sobre amarillo", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-tze/laminadas/18mm/negro-sobre-amarillo", "printers_scanners"],
  ["Hyundai HYtab Plus 8WB1 HT8WB1RBK02A tablet 8 pulgadas Wi-Fi negra", "HYUNDAI", "computo/tabletas/android/8-pulgadas", "tablets"],
  ["Lenovo B210 4X40T84059 mochila para laptop 15.6 pulgadas negra", "LENOVO", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6", "accessories"],
  ["Brobotix 030570 cable extension USB-A 2.0 macho a hembra 4.9 m negro", "BROBOTIX", "accesorios/cables-adaptadores/usb/extensiones/5m", "accessories"],
  ["Mirati MSL02 cerradura inteligente Wi-Fi con huella RFID teclado y llave", "MIRATI", "seguridad/control-acceso/cerraduras-inteligentes/huella-rfid-wifi", "security"],
  ["GHIA Vector Plus GVPN tablet Android 13 10.1 pulgadas 4GB 64GB negra", "GHIA", "computo/tabletas/android/10-1-pulgadas", "tablets"],
  ["Intellinet 319874 patch cord Cat5e UTP RJ45 7.5 m azul", "INTELLINET", "redes/cableado-estructurado/patch-cords/cat5e/7-5m", "networking"],
  ["Stylos STPKTM3B combo teclado y mouse inalambrico USB negro 105 teclas", "STYLOS", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Acteck Captive Brite CB195 AC-939409 monitor 19.5 pulgadas TN HD HDMI VGA negro", "ACTECK", "computo/monitores/oficina/19-5-hd", "monitors"],
  ["TP-Link LS108G switch no administrable Gigabit de 8 puertos", "TP LINK", "redes/switches/no-administrables/gigabit/8-puertos", "networking"],
  ["Getttech GAC-24404P mouse ergonomico inalambrico 2.4GHz 1600 DPI rosa", "GETTTECH", "computo/perifericos/mouse/inalambricos/ergonomicos/1600-dpi", "accessories"],
  ["Naceb NA-0145 cargador de pared GaN 100W 2 USB-C 1 USB-A negro", "NACEB TECHNOLOGY", "energia/cargadores-usb/pared-gan/100w", "accessories"],
  ["Meriva MOB-202FS4D camara IP bullet 2MP PoE iluminacion dual microfono", "MERIVA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/bullet/2mp-dual-light-mic", "cameras"],
  ["Targus ASP61LA candado de seguridad T-Lock con combinacion 1.5 m negro", "TARGUS", "accesorios/seguridad-fisica/candados-laptop/combinacion", "accessories"],
  ["Epson EcoTank L14150 multifuncional A3 Plus Wi-Fi tinta continua", "EPSON", "impresion/impresoras/multifuncionales-ecotank/a3-plus", "printers_scanners"],
  ["Getttech GUE-MSSBT-01-YW audifonos deportivos Bluetooth negros", "GETTTECH", "audio/audifonos/bluetooth/deportivos/oreja-abierta", "headphones"],
  ["Complet XPower ERV-9-001 regulador 1300VA 650W con supresor 8 contactos", "COMPLET", "energia/reguladores/supresor-picos/1300va", "power"],
  ["Thermaltake Toughpower GF1 PS-TPD-0850FNFAGU-H fuente ATX 850W 80 Plus Gold modular", "THERMALTAKE", "computo/componentes/fuentes-poder/atx-80-plus-gold/850w/modular", "components"],
  ["Vica VIC12-9A bateria sellada VRLA 12V 9Ah para UPS", "VICA", "energia/baterias-ups/selladas-12v/9ah", "power"],
  ["HiLook by Hikvision HL1080PS(C) kit TurboHD DVR 4 canales 4 camaras 2MP", "HIKVISION", "seguridad/cctv/kits-turbohd/4-canales/4-camaras-2mp", "cameras"],
  ["Kyocera TK-582C 1T02KTCUS0 toner cian original", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/cian", "printers_scanners"],
  ["Acteck Captive Vivid SP215 AC-933858 monitor 21.5 FHD 75Hz negro", "ACTECK", "computo/monitores/oficina/22-fhd-75hz", "monitors"],
  ["Complet RPLUS 2000 ERV-6-012 regulador de voltaje 2000VA 1000W", "COMPLET", "energia/supresores-reguladores/reguladores-voltaje/avr/2000va", "power"],
  ["Manhattan 307178 cable USB 2.0 A macho a Micro-B macho 1.8 m negro", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-micro-b/2-0-1-8m", "accessories"],
  ["Perfect Choice PC-331148 transmisor Bluetooth FM para auto con 2 USB", "PERFECT CHOICE", "audio/accesorios/transmisores-fm/bluetooth-12v", "audio"],
  ["Vorago Slimbay A 5 N4020-NOS-5 PC Celeron N4020 8GB 240GB SSD", "VORAGO", "computo/desktops/slim/celeron-n4020-8gb-240gb", "desktops"],
  ["TP-Link Tapo C310 camara Wi-Fi exterior 2K IP66 microSD", "TP LINK", "seguridad/cctv/camaras-ip-wifi/bullet-exterior/3mp-2k", "cameras"],
  ["Xerox 006R04644 toner negro extra alta capacidad 25000 paginas C620 C625", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04644-negro", "printers_scanners"],
  ["Smartbitt SBOL10KRTG1-2 UPS online doble conversion 10kVA 10kW rack torre", "SMARTBITT", "energia/no-breaks-ups/doble-conversion/rack-torre/10000va", "power"],
  ["Ocelot Gaming OEL360 enfriamiento liquido AIO 360mm ARGB negro", "OCELOT GAMING", "computo/componentes/enfriamiento/liquido-cpu/360mm/argb", "components"],
  ["Naceb Technology NA-0313A audifonos diadema alambricos 3.5mm azul verde", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono", "headphones"],
  ["Intellinet 340373 Cable Patch Cat6 UTP RJ45 1 m gris", "INTELLINET", "redes/cableado-estructurado/patch-cords/cat6/1m", "networking"],
  ["Samsung Essential Monitor S3 LS22D300GALXZX 22 in Full HD IPS 100Hz", "SAMSUNG", "computo/monitores/oficina/22-fhd-100hz", "monitors"],
  ["Huawei MateBook D 16 53014MSJ Core i5-13420H 16GB 1TB SSD 16 in", "HUAWEI", "computo/laptops/consumo/16-pulgadas/huawei-matebook-d16", "laptops"],
  ["ASUS TUF Gaming A520M-PLUS WiFi Motherboard Micro-ATX AM4 DDR4", "ASUS", "computo/componentes/tarjetas-madre/amd-am4/a520m", "components"],
  ["Ghia GT4000BB Kit Teclado y Mouse Inalambrico USB Negro", "GHIA", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Synology Plus Series HAT3320-8T Disco Duro NAS 8TB SATA 3.5 in", "SYNOLOGY", "computo/almacenamiento/discos-duros/3-5-sata/nas/8tb", "storage"],
  ["Xerox 006R04765 Toner Cyan Alta Capacidad para C410 C415 7000 Paginas", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04765-cian", "printers_scanners"],
  ["Intellinet 210478 Jack Modular Keystone Cat5e UTP Rojo", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat5e/rojo", "networking"],
  ["Yeyian Hussar Plus YCM-ASHUS-01 Gabinete Mid Tower ATX Negro", "YEYIAN", "computo/componentes/gabinetes/gaming/atx-mid-tower", "components"],
  ["Game Factor SMG500 Base Gamer para Monitor VESA hasta 27 in", "GAME FACTOR", "computo/accesorios/soportes-monitor/vesa/27-5kg", "accessories"],
  ["be quiet! Pure Loop 2 FX BW014 enfriamiento liquido AIO 280mm ARGB", "BE QUIET", "computo/componentes/enfriamiento/liquido-cpu/280mm/argb", "components"],
  ["Perfect Choice Bagiq PC-084273 funda de neopreno para laptop 15.6 pulgadas rosa", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas/neopreno", "accessories"],
  ["Logitech MX Mechanical teclado inalambrico iluminado mecanico grafito TECLOG1040", "LOGITECH", "computo/perifericos/teclados/inalambricos/mecanicos", "accessories"],
  ["Brother LC402XLY cartucho de tinta amarillo alto rendimiento 1500 paginas", "BROTHER", "impresion/consumibles/cartuchos-tinta/brother/lc402/amarillo-xl", "printers_scanners"],
  ["Lenovo ThinkPad Bluetooth Silent Mouse 4Y50X88823 2400 DPI negro", "LENOVO", "computo/perifericos/mouse/inalambricos/bluetooth/silenciosos", "accessories"],
  ["Nexxt Home NHE-T100 interruptor inteligente Wi-Fi de 3 circuitos blanco", "NEXXT SOLUTIONS HOME", "hogar/casa-inteligente/interruptores-wifi/3-circuitos", "accessories"],
  ["Hisense ARU122KAW minisplit inverter 12000 BTU frio calor 230V blanco", "HISENSE", "climatizacion/aires-acondicionados/minisplit/inverter/12000-btu", "accessories"],
  ["BRobotix 6005989 kit de limpieza 7 en 1 para audifonos y smartphones", "BROBOTIX", "computo/accesorios/limpieza/kits/telefonos-audifonos", "accessories"],
  ["ASUS TUF Gaming B550M-PLUS Wi-Fi motherboard micro ATX AM4", "ASUS", "computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx/wifi", "components"],
  ["CyberPower Smart App LCD OR500LCDRM1U UPS rack 1U 500VA 300W", "CYBERPOWER", "energia/no-breaks-ups/line-interactive/rack-1u/500va", "power"],
  ["Netis E3 AC1200 extensor de rango Wi-Fi dual band", "NETIS", "redes/extensores-wifi/dual-band/ac1200", "networking"],
  ["XFX Speedster SWFT 210 Radeon RX 7600 Core RX-76PSWFTFY 8GB GDDR6", "XFX", "computo/componentes/tarjetas-video/amd-radeon/rx-7000/rx-7600", "components"],
  ["BRobotix 170906 caja de mesa RJ45 Cat6 HDMI USB NEMA 5-15R negra", "BROBOTIX", "redes/cableado-estructurado/cajas-mesa/multimedia-rj45-hdmi-usb-corriente", "networking"],
  ["Tenda S105 switch no administrable Fast Ethernet 5 puertos 10/100 blanco", "TENDA", "redes/switches/no-administrables/fast-ethernet/5-puertos", "networking"],
  ["Silimex IsoPro 750300219690 alcohol isopropilico aerosol 250 ml", "SILIMEX", "computo/accesorios/limpieza/alcohol-isopropilico/250ml", "accessories"],
  ["Acteck Optimize Joy MI215 AC-933445 mouse inalambrico 1600 DPI negro", "ACTECK", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi", "accessories"],
  ["WAM WAM-RACK419 rack abierto de piso 25U 19 pulgadas acero negro", "WAM", "infraestructura/racks-enfriamiento/racks-piso/abiertos-25u", "networking"],
  ["Game Factor MPG500 mousepad gamer XL RGB 800 x 300 x 4 mm", "GAME FACTOR", "computo/accesorios/mousepads/gaming-rgb/extendidos", "accessories"],
  ["Zebra ZD220D impresora de etiquetas termica directa 4 pulgadas 203 dpi USB", "ZEBRA", "impresion/impresoras/etiquetas/termicas-directas/desktop-4-pulgadas", "printers_scanners"],
  ["Silimex 7503018454009 toallitas humedas limpiadoras Gamer 30 piezas", "SILIMEX", "computo/accesorios/limpieza/toallitas/gamer-30-piezas", "accessories"],
  ["Logitech M110 Silent 910-006757 mouse alambrico USB 1000 DPI gris", "LOGITECH", "computo/perifericos/mouse/alambricos/basicos/1000-dpi", "accessories"],
  ["Logitech Z207 bocinas Bluetooth 2.0 10W pico 5W RMS 3.5mm negras", "LOGITECH", "computo/perifericos/bocinas-audio/2-0", "headphones"],
  ["Dell Pro Max 16 Core Ultra 9 285H 32GB 1TB RTX PRO 2000 Blackwell", "DELL", "computo/laptops/workstations/16-pulgadas/dell-pro-max-16", "laptops"],
  ["Uniarch NVR-104E2-P4 NVR 4 canales PoE Ultra265 HDMI 4K", "UNIARCH", "seguridad/cctv/dvr-nvr/nvr-poe", "cameras"],
  ["Perfect Choice Meucci PC-117223 manos libres Bluetooth 20h USB-C", "PERFECT CHOICE", "audio/audifonos/bluetooth/monoaurales-uc", "headphones"],
  ["LG UltraGear 24GS60F-B monitor gaming 24 FHD IPS 180Hz 1ms", "LG", "computo/monitores/gaming/24-fhd/180hz", "monitors"],
  ["Naceb Gaming NA-0122 cable HDMI 2.1 3m 8K 48Gbps eARC", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/3m", "accessories"],
  ["BRobotix 651855 funda City poliester gris para laptop 15.6 pulgadas", "BROBOTIX", "computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas", "accessories"],
  ["Generico cargador compatible Dell 65W 19.5V 3.34A punta 4.5 x 3.0", "GENERICO", "computo/accesorios/cargadores-laptop/compatibles-dell/65w-19-5v-4-5x3-0", "laptops"],
  ["Grandstream GRP2602P telefono IP 2 lineas 4 cuentas SIP PoE", "GRANDSTREAM", "telefonia/telefonos-ip/escritorio/2-lineas/poe", "networking"],
] as const;

describe("manual taxonomy batches 160 plus", () => {
  it.each(batch160PlusCases)("%s -> %s", (name, brand, path, legacyCategory) => {
    const result = classifyManualCategory({ name, brand, category: "laptops" });
    expect(result.path).toBe(path);
    expect(result.legacyCategory).toBe(legacyCategory);
  });
});
