import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const researchedBatchCases = [
  ["Dbugg DB-PD64 cargador de pared USB-C PD GaN 67W", "DBUGG", "energia/cargadores-usb"],
  ["Fujitsu fi-70F escaner plano A6 USB", "FUJITSU", "impresion/escaneres"],
  ["Perfect Choice PC-085058 bolso cruzado Holdi negro", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Creative Sound Blaster GS5 barra de sonido compacta", "CREATIVE", "audio/barras-sonido"],
  ["Game Factor HSG500 headset gamer USB 7.1 RGB", "GAME FACTOR", "audio/audifonos"],
  ["Huawei M-Pencil CD54-S1 lapiz optico blanco", "HUAWEI", "computo/accesorios/stylus-tablets"],
  ["Perfect Choice PC-085249 mochila escolar Bookery purpura", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["HP GT52 3YP17AL botella de tinta amarilla 70 ml", "HP", "impresion/consumibles/tinta-toner"],
  ["Perfect Choice PC-084433 mochila escolar Delfin Astro", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Duosmart E21 camara inteligente WiFi 3MP PIR", "DUOSMART", "seguridad/cctv/camaras-ip-wifi"],
  ["KSA GKSA01-B goggles de proteccion anti empanante", "KSA", "seguridad/epp/proteccion-ocular"],
  ["TopVision TBDL200A camara HD bullet 2MP TVI AHD CVI", "TOPVISION", "seguridad/cctv/camaras-turbohd"],
  ["Laces LA100KSP kit de soportes de pared para rack", "LACES", "infraestructura/racks-accesorios/soportes-pared"],
  ["Logitech PRO X 60 920-011921 teclado gaming wireless", "LOGITECH", "computo/perifericos/teclados"],
  ["Dell PowerEdge R470 R470271 servidor rack 1U", "DELL", "computo/servidores/rack"],
  ["TechZone TZLBP02 mochila laptop 15.6 pulgadas", "TECHZONE", "computo/accesorios/mochilas-fundas"],
  ["Nexxt AW222NXT67 NPS-V11U3B charola para rack 1U", "NEXXT", "infraestructura/racks-accesorios/charolas"],
  ["Vorago KSP-205 mini bafle karaoke bluetooth RGB", "VORAGO", "audio/bocinas"],
  ["Syble XB-VP1106 verificador de precios POS", "SYBLE", "punto-de-venta/verificadores-precio"],
  ["Perfect Choice PC-085027 bolso cruzado Holdy avellana", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-085294 mochila escolar Kiddo Corazon", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Pacific Soft PSF030 punto de venta para farmacias", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Redragon Sacarab White A130W-SP keycaps PBT", "REDRAGON", "computo/perifericos/teclados/keycaps"],
  ["TP-Link Omada OC200 controlador cloud", "OMADA", "redes/controladores-cloud"],
  ["North System NORTH109-BKL organizador horizontal rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/organizadores-cable"],
  ["Vorago BSP-400 Pool Bluetooth IPX67 bocina", "VORAGO", "audio/bocinas"],
  ["PCM 10B13 papel bond plotter 0.61 x 50", "PCM", "impresion/consumibles/papel-plotter"],
  ["Necnon NPW-10FC power bank 10000 mAh", "NECNON", "energia/power-banks"],
  ["Huawei 55037722 M-Pen Lite AF63-R lapiz optico", "HUAWEI", "computo/accesorios/stylus-tablets"],
  ["Perfect Choice PC-084730 Sportiva bolso deportivo", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Vorago KSP-180 mini bafle karaoke bluetooth RGB", "VORAGO", "audio/bocinas"],
  ["Perfect Choice PC-270157 smartwatch Mercury negro", "PERFECT CHOICE", "wearables/smartwatches"],
  ["Perfect Choice PC-270218 smartwatch Minoro llamadas", "PERFECT CHOICE", "wearables/smartwatches"],
  ["Nexxt AW222NXT66 NPS-S11U3B charola lisa rack", "NEXXT", "infraestructura/racks-accesorios/charolas"],
  ["TopVision TDDL500A camara HD turret 5MP", "TOPVISION", "seguridad/cctv/camaras-turbohd"],
  ["Meriva MDL-3202A camara HD turret 2MP", "MERIVA", "seguridad/cctv/camaras-turbohd"],
  ["Vorago KSP-350 bocina bluetooth 30W", "VORAGO", "audio/bocinas"],
  ["Redragon Sacarab Pink A130P-SP keycaps PBT", "REDRAGON", "computo/perifericos/teclados/keycaps"],
  ["Verbatim 95310 DVD+R DL 8.5GB 20 pack", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Fujitsu ScanSnap SV600 escaner elevado A3", "FUJITSU", "impresion/escaneres"],
  ["Nexxt AW251NXT05 PTKCKKBSDKT01 kit basico herramientas red", "NEXXT", "redes/herramientas-cableado"],
  ["Pacific Soft SF020 punto de venta para autoservicios", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Pacific Soft PSF040 comandera movil restaurantes Android", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Kensington K64704WW VeriMark Pro fingerprint key", "KENSINGTON", "computo/accesorios/seguridad-biometrica"],
  ["Huawei Band 10 55020EKW Aluminum Blue smartwatch", "HUAWEI", "wearables/smartwatches"],
  ["Perfect Choice PC-085164 mochila escolar Arcade", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Pacific Soft KITPSF070 punto de venta para farmacias", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Orvibo SM11 sensor de puerta ventana Zigbee", "ORVIBO", "domotica/sensores"],
  ["Multimedia Screens MSC-265 pantalla de proyeccion 120", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Poly EncorePro 510 783Q1AA headset Quick Disconnect", "POLY", "audio/audifonos"],
  ["Anviz AN-C2Slim-BT control de acceso lector de huella", "ANVIZ", "seguridad/control-acceso/biometricos"],
  ["Anviz AN-EMICARD tarjeta RFID 125Khz PVC", "ANVIZ", "seguridad/control-acceso/tarjetas-rfid"],
  ["IMOU ARD311-SW contacto magnetico inalambrico", "IMOU", "domotica/sensores"],
  ["Multimedia Screens MSC-332 pantalla manual 150 16:9", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Multimedia Screens MSE-332 pantalla electrica 150 16:9", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Perfect Choice PC-085089 Kiddo Monstruos mochila escolar", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-114024 Emphoria barra de audio RGB 70W", "PERFECT CHOICE", "audio/barras-sonido"],
  ["Tripp Lite N206-FP02-IND bulkhead wall plate", "TRIPP-LITE", "redes/cableado-estructurado/placas-keystone"],
  ["DataShield IS-1000 inversor cargador solar", "DATASHIELD", "energia/inversores-solares"],
  ["DataShield IS-3000 inversor solar hibrido", "DATASHIELD", "energia/inversores-solares"],
  ["Logitech G335 wired gaming headset blanco azul", "LOGITECH", "audio/audifonos"],
  ["Mirati MBJ01N exprimidor de citricos 700 ml 25 W", "MIRATI", "hogar/electrodomesticos/exprimidores"],
  ["Naceb Fornax NA-0308N diadema Bluetooth", "NACEB TECHNOLOGY", "audio/audifonos"],
  ["PCM 10B11 papel bond plotter 0.91 x 100", "PCM", "impresion/consumibles/papel-plotter"],
  ["PCM 10B5 papel bond plotter 0.91 x 100", "PCM", "impresion/consumibles/papel-plotter"],
  ["Perfect Choice PC-085225 mochila escolar Loopy rojo", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-085300 mochila escolar Brooklyn Dinosaurios", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Poly Voyager 4310 ACCPTS1960 headset Bluetooth BT700", "POLY", "audio/audifonos"],
  ["Targus ASP71GLX-S DEFCON Compact Serialized Combo Cable Lock", "TARGUS", "accesorios/seguridad-fisica"],
  ["Verbatim 95179 DVD-RW 4.7GB 30 pack", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Zebra Z-Band Direct 10006995K pulsera termica", "ZEBRA", "impresion/consumibles/pulseras-termicas"],
  ["Acteck AC-937146 Energon S-Mate CI730 cargador inalambrico Qi", "ACTECK", "energia/cargadores-inalambricos"],
  ["Epson C33S021501 SJMB6000 maintenance box", "EPSON", "impresion/consumibles/mantenimiento"],
  ["Hisense AC121CF minisplit 1 tonelada solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["Kensington K60604WW Slim NanoSaver combination lock", "KENSINGTON", "accesorios/seguridad-fisica"],
  ["Lanix 14996 XAir 1 purificador de aire", "LANIX", "hogar/electrodomesticos/purificadores-aire"],
  ["Lenovo 4XH7A83845 PCIe riser SR630 V3", "LENOVO", "computo/servidores/componentes"],
  ["Logitech 920-010478 MX Keys Mini rosa", "LOGITECH", "computo/perifericos/teclados"],
  ["MSI GeForce RTX 5060 8G Shadow 2X OC", "MSI", "computo/componentes/tarjetas-video"],
  ["Mobifree base de carga inalambrica 10W Qi", "MOBIFREE", "energia/cargadores-inalambricos"],
  ["North System NORTH115-BKL organizador vertical rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/organizadores-cable"],
  ["Verbatim 95093 DVD-R 4.7GB 16X", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Manhattan 438889 London maletin laptop 15.4", "MANHATTAN", "computo/accesorios/mochilas-fundas"],
  ["Badgy VBDG204EU kit YMCKO ribbon 100 impresiones", "BADGY", "punto-de-venta/credenciales-identificacion"],
  ["Zebra 10011042 Z-Perform 1000D receipt paper 3 x 80", "ZEBRA", "punto-de-venta/consumibles/rollos-termicos"],
  ["Polaroid PASU85-63 papel de sublimacion", "POLAROID", "impresion/consumibles/papel-fotografico-sublimacion"],
  ["Perfect Choice EL-994787 auriculares diadema", "PERFECT CHOICE", "audio/audifonos"],
  ["Orvibo SN11 sensor de movimiento PIR Zigbee", "ORVIBO", "domotica/sensores/movimiento"],
  ["Kingston SNA-BR2/35 SSD bracket 2.5 to 3.5", "KINGSTON TECHNOLOGY", "computo/almacenamiento/accesorios-montaje"],
  ["Jabra Speak 510 speakerphone USB Bluetooth", "JABRA", "audio/conferencia-speakerphones"],
] as const;

describe("manual taxonomy researched batches", () => {
  it.each(researchedBatchCases)("%s -> %s", (name, brand, path) => {
    expect(classifyManualCategory({ name, brand, category: "laptops" }).path).toBe(path);
  });
});
