import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const batch160PlusCases = [
  ["SanDisk Portable SSD SDSSDE30-1T00-G26 1TB USB-C USB 3.2 Gen 2 800 MB/s", "SANDISK", "computo/almacenamiento/ssd/externos/usb-c/1tb/sandisk-portable", "storage"],
  ["Balam Rush Power Rush V2 silla gamer tela piel sintetica reclinable 135 120kg", "BALAM RUSH", "gaming/mobiliario/sillas-gamer/tela/reclinable-135-120kg", "gaming"],
  ["TP-Link TL-WN781ND adaptador Wi-Fi PCI Express N150 150Mbps", "TP LINK", "redes/adaptadores-wifi/pcie/n150", "networking"],
  ["Huawei BE3 53030CSM router Wi-Fi 7 BE3600 3570Mbps 2.5G negro", "HUAWEI", "redes/routers/wifi-7/be3600", "networking"],
  ["PCM EBA7670 rollo autocopiante 76 x 70 mm blanco amarillo paquete 50", "PCM", "punto-de-venta/consumibles/rollos-autocopia/76x70", "laptops"],
  ["Perfect Choice ClearBeat PC-117025 audifonos Bluetooth TWS con display USB-C negros", "PERFECT CHOICE", "audio/audifonos/bluetooth/tws/estuche-display", "headphones"],
  ["Hikvision CAMHKV2610 camara bala 5MP TurboHD exterior metal techo pared", "HIKVISION", "seguridad/cctv/camaras-turbohd/bullet/5mp", "cameras"],
  ["ADATA XPG Spectrix D35G AX4U320016G16A-SBKD35G memoria RAM DDR4 16GB 3200MHz RGB", "ADATA", "computo/componentes/memoria-ram/udimm-ddr4/16gb-3200", "components"],
  ["Hyundai Hy View HT34CGMBK01 monitor gaming curvo 34 UWQHD 180Hz negro", "HYUNDAI", "computo/monitores/gaming/ultrawide-curvos/34-uwqhd-180hz", "monitors"],
  ["Stylos ST300 STMUS316B memoria USB 16GB gris", "STYLOS", "computo/almacenamiento/memorias-flash/usb/16gb", "storage"],
  ["Manhattan 353274 cable HDMI alta velocidad con Ethernet 7.5 m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/7-5m", "accessories"],
  ["Brother TN229Y toner amarillo rendimiento estandar 1200 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-229/amarillo", "printers_scanners"],
  ["Lenovo ThinkVision T22i-30 63B0MAR6LA monitor 21.5 FHD IPS 60Hz", "LENOVO", "computo/monitores/oficina/22-fhd-60hz", "monitors"],
  ["Manhattan MW3050 190312 mouse inalambrico USB 1200 DPI negro", "MANHATTAN", "computo/perifericos/mouse/inalambricos/basicos/1200-dpi", "accessories"],
  ["Poly Studio V12 A9DD8AA#ABM barra de video USB 4K 20MP", "POLYCOM", "colaboracion/video-conferencia/barras-video/usb-4k", "accessories"],
  ["Provision ISR DMA-320IPEN-28-V4 camara domo IP PoE 2MP DDA2 microfono", "PROVISION-ISR", "seguridad/cctv/camaras-ip-poe/domo/2mp-analytics-mic", "cameras"],
  ["Stylos STMS321B memoria microSDHC 32GB clase 10 con adaptador", "STYLOS", "computo/almacenamiento/memorias-flash/microsd/32gb-clase-10", "storage"],
  ["Intellinet 715072 charola rack 19 pulgadas 1U 300mm 25kg negra", "INTELLINET", "infraestructura/racks-accesorios/charolas/1u-300mm-25kg", "networking"],
  ["Quaroni QD4S08G1 memoria RAM SO-DIMM DDR4 8GB 3200MHz CL22", "QUARONI", "computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200", "components"],
  ["Logitech G923 TRUEFORCE volante y pedales racing PS5 PS4 PC", "LOGITECH", "gaming/accesorios/volantes-simulacion/trueforce", "gaming"],
  ["Nexxt Solutions Home NHE-S100 interruptor inteligente Wi-Fi monopolar blanco", "NEXXT SOLUTIONS HOME", "hogar/casa-inteligente/interruptores-wifi/monopolares", "accessories"],
  ["Manhattan 152082 tarjeta serial PCI Express 2 puertos DB9", "MANHATTAN", "computo/componentes/tarjetas-expansion/serial-pcie/db9-2-puertos", "components"],
  ["Kensington K55256WW MagPro filtro de privacidad magnetico para laptop 16 16:10", "KENSINGTON", "computo/accesorios/filtros-privacidad/laptops/16-16-10", "accessories"],
  ["Koblenz 9022 USB no break interactivo 900VA 450W LCD", "KOBLENZ", "energia/no-breaks-ups/line-interactive/900va/lcd", "power"],
  ["Polaroid PASU100-63 rollo papel sublimacion 100gsm 63in x 100m blanco", "POLAROID", "impresion/consumibles/papel-sublimacion/rollos/63in-100m-100gsm", "printers_scanners"],
  ["PCM 50000B0160A etiquetas transferencia termica 4x2 R-700 caja 12 rollos", "PCM", "impresion/consumibles/etiquetas-transferencia-termica/4x2/r-700-12-rollos", "printers_scanners"],
  ["Brother TN890 toner negro ultra alto rendimiento 20000 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-890", "printers_scanners"],
  ["ADATA Premier Pro AUSDX128GUI3V30SA2-RA1 microSDXC 128GB UHS-I V30 A2 con adaptador", "ADATA", "computo/almacenamiento/memorias-flash/microsd/128gb-uhs-i-v30-a2", "storage"],
  ["Manhattan 371377 cable VGA SVGA HD15 macho macho 11m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-vga/hd15/11m", "accessories"],
  ["Brother TZe-641 cinta laminada P-touch 18mm x 8m negro sobre amarillo", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-tze/laminadas/18mm/negro-sobre-amarillo", "printers_scanners"],
  ["Hyundai HYtab Plus 8WB1 HT8WB1RBK02A tablet 8 pulgadas Wi-Fi negra", "HYUNDAI", "computo/tabletas/android/8-pulgadas", "tablets"],
  ["Lenovo B210 4X40T84059 mochila para laptop 15.6 pulgadas negra", "LENOVO", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6", "accessories"],
  ["Brobotix 030570 cable extension USB-A 2.0 macho a hembra 4.9 m negro", "BROBOTIX", "accesorios/cables-adaptadores/usb/extensiones/5m", "accessories"],
  ["Mirati MSL02 cerradura inteligente Wi-Fi con huella RFID teclado y llave", "MIRATI", "seguridad/control-acceso/cerraduras-inteligentes/huella-rfid-wifi", "security"],
  ["GHIA Vector Plus GVPN tablet Android 13 10.1 pulgadas 4GB 64GB negra", "GHIA", "computo/tabletas/android/10-1-pulgadas", "tablets"],
  ["Intellinet 319874 patch cord Cat5e UTP RJ45 7.5 m azul", "INTELLINET", "redes/cableado-estructurado/patch-cords/cat5e/7-5m", "networking"],
  ["Stylos STPKTM3B combo teclado y mouse inalambrico USB negro 105 teclas", "STYLOS", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Acteck Captive Brite CB195 AC-939409 monitor 19.5 pulgadas TN HD HDMI VGA negro", "ACTECK", "computo/monitores/oficina/19-5-hd", "monitors"],
  ["TP-Link LS108G switch no administrable Gigabit de 8 puertos", "TP LINK", "redes/switches/no-administrables/gigabit/8-puertos", "networking"],
  ["Getttech GAC-24404P mouse ergonomico inalambrico 2.4GHz 1600 DPI rosa", "GETTTECH", "computo/perifericos/mouse/inalambricos/ergonomicos/1600-dpi", "accessories"],
  ["Naceb NA-0145 cargador de pared GaN 100W 2 USB-C 1 USB-A negro", "NACEB TECHNOLOGY", "energia/cargadores-usb/pared-gan/100w", "accessories"],
  ["Meriva MOB-202FS4D camara IP bullet 2MP PoE iluminacion dual microfono", "MERIVA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/bullet/2mp-dual-light-mic", "cameras"],
  ["Targus ASP61LA candado de seguridad T-Lock con combinacion 1.5 m negro", "TARGUS", "accesorios/seguridad-fisica/candados-laptop/combinacion", "accessories"],
  ["Epson EcoTank L14150 multifuncional A3 Plus Wi-Fi tinta continua", "EPSON", "impresion/impresoras/multifuncionales-ecotank/a3-plus", "printers_scanners"],
  ["Getttech GUE-MSSBT-01-YW audifonos deportivos Bluetooth negros", "GETTTECH", "audio/audifonos/bluetooth/deportivos/oreja-abierta", "headphones"],
  ["Complet XPower ERV-9-001 regulador 1300VA 650W con supresor 8 contactos", "COMPLET", "energia/reguladores/supresor-picos/1300va", "power"],
  ["Thermaltake Toughpower GF1 PS-TPD-0850FNFAGU-H fuente ATX 850W 80 Plus Gold modular", "THERMALTAKE", "computo/componentes/fuentes-poder/atx-80-plus-gold/850w/modular", "components"],
  ["Vica VIC12-9A bateria sellada VRLA 12V 9Ah para UPS", "VICA", "energia/baterias-ups/selladas-12v/9ah", "power"],
  ["HiLook by Hikvision HL1080PS(C) kit TurboHD DVR 4 canales 4 camaras 2MP", "HIKVISION", "seguridad/cctv/kits-turbohd/4-canales/4-camaras-2mp", "cameras"],
  ["Kyocera TK-582C 1T02KTCUS0 toner cian original", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/cian", "printers_scanners"],
  ["Acteck Captive Vivid SP215 AC-933858 monitor 21.5 FHD 75Hz negro", "ACTECK", "computo/monitores/oficina/22-fhd-75hz", "monitors"],
  ["Complet RPLUS 2000 ERV-6-012 regulador de voltaje 2000VA 1000W", "COMPLET", "energia/supresores-reguladores/reguladores-voltaje/avr/2000va", "power"],
  ["Manhattan 307178 cable USB 2.0 A macho a Micro-B macho 1.8 m negro", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-micro-b/2-0-1-8m", "accessories"],
  ["Perfect Choice PC-331148 transmisor Bluetooth FM para auto con 2 USB", "PERFECT CHOICE", "audio/accesorios/transmisores-fm/bluetooth-12v", "audio"],
  ["Vorago Slimbay A 5 N4020-NOS-5 PC Celeron N4020 8GB 240GB SSD", "VORAGO", "computo/desktops/slim/celeron-n4020-8gb-240gb", "desktops"],
  ["TP-Link Tapo C310 camara Wi-Fi exterior 2K IP66 microSD", "TP LINK", "seguridad/cctv/camaras-ip-wifi/bullet-exterior/3mp-2k", "cameras"],
  ["Xerox 006R04644 toner negro extra alta capacidad 25000 paginas C620 C625", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04644-negro", "printers_scanners"],
  ["Smartbitt SBOL10KRTG1-2 UPS online doble conversion 10kVA 10kW rack torre", "SMARTBITT", "energia/no-breaks-ups/doble-conversion/rack-torre/10000va", "power"],
  ["Ocelot Gaming OEL360 enfriamiento liquido AIO 360mm ARGB negro", "OCELOT GAMING", "computo/componentes/enfriamiento/liquido-cpu/360mm/argb", "components"],
  ["Naceb Technology NA-0313A audifonos diadema alambricos 3.5mm azul verde", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono", "headphones"],
  ["Intellinet 340373 Cable Patch Cat6 UTP RJ45 1 m gris", "INTELLINET", "redes/cableado-estructurado/patch-cords/cat6/1m", "networking"],
  ["Samsung Essential Monitor S3 LS22D300GALXZX 22 in Full HD IPS 100Hz", "SAMSUNG", "computo/monitores/oficina/22-fhd-100hz", "monitors"],
  ["Huawei MateBook D 16 53014MSJ Core i5-13420H 16GB 1TB SSD 16 in", "HUAWEI", "computo/laptops/consumo/16-pulgadas/huawei-matebook-d16", "laptops"],
  ["ASUS TUF Gaming A520M-PLUS WiFi Motherboard Micro-ATX AM4 DDR4", "ASUS", "computo/componentes/tarjetas-madre/amd-am4/a520m", "components"],
  ["Ghia GT4000BB Kit Teclado y Mouse Inalambrico USB Negro", "GHIA", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Synology Plus Series HAT3320-8T Disco Duro NAS 8TB SATA 3.5 in", "SYNOLOGY", "computo/almacenamiento/discos-duros/3-5-sata/nas/8tb", "storage"],
  ["Xerox 006R04765 Toner Cyan Alta Capacidad para C410 C415 7000 Paginas", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04765-cian", "printers_scanners"],
  ["Intellinet 210478 Jack Modular Keystone Cat5e UTP Rojo", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat5e/rojo", "networking"],
  ["Yeyian Hussar Plus YCM-ASHUS-01 Gabinete Mid Tower ATX Negro", "YEYIAN", "computo/componentes/gabinetes/gaming/atx-mid-tower", "components"],
  ["Game Factor SMG500 Base Gamer para Monitor VESA hasta 27 in", "GAME FACTOR", "computo/accesorios/soportes-monitor/vesa/27-5kg", "accessories"],
  ["be quiet! Pure Loop 2 FX BW014 enfriamiento liquido AIO 280mm ARGB", "BE QUIET", "computo/componentes/enfriamiento/liquido-cpu/280mm/argb", "components"],
  ["Perfect Choice Bagiq PC-084273 funda de neopreno para laptop 15.6 pulgadas rosa", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas/neopreno", "accessories"],
  ["Logitech MX Mechanical teclado inalambrico iluminado mecanico grafito TECLOG1040", "LOGITECH", "computo/perifericos/teclados/inalambricos/mecanicos", "accessories"],
  ["Brother LC402XLY cartucho de tinta amarillo alto rendimiento 1500 paginas", "BROTHER", "impresion/consumibles/cartuchos-tinta/brother/lc402/amarillo-xl", "printers_scanners"],
  ["Lenovo ThinkPad Bluetooth Silent Mouse 4Y50X88823 2400 DPI negro", "LENOVO", "computo/perifericos/mouse/inalambricos/bluetooth/silenciosos", "accessories"],
  ["Nexxt Home NHE-T100 interruptor inteligente Wi-Fi de 3 circuitos blanco", "NEXXT SOLUTIONS HOME", "hogar/casa-inteligente/interruptores-wifi/3-circuitos", "accessories"],
  ["Hisense ARU122KAW minisplit inverter 12000 BTU frio calor 230V blanco", "HISENSE", "climatizacion/aires-acondicionados/minisplit/inverter/12000-btu", "accessories"],
  ["BRobotix 6005989 kit de limpieza 7 en 1 para audifonos y smartphones", "BROBOTIX", "computo/accesorios/limpieza/kits/telefonos-audifonos", "accessories"],
  ["ASUS TUF Gaming B550M-PLUS Wi-Fi motherboard micro ATX AM4", "ASUS", "computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx/wifi", "components"],
  ["CyberPower Smart App LCD OR500LCDRM1U UPS rack 1U 500VA 300W", "CYBERPOWER", "energia/no-breaks-ups/line-interactive/rack-1u/500va", "power"],
  ["Netis E3 AC1200 extensor de rango Wi-Fi dual band", "NETIS", "redes/extensores-wifi/dual-band/ac1200", "networking"],
  ["XFX Speedster SWFT 210 Radeon RX 7600 Core RX-76PSWFTFY 8GB GDDR6", "XFX", "computo/componentes/tarjetas-video/amd-radeon/rx-7000/rx-7600", "components"],
  ["BRobotix 170906 caja de mesa RJ45 Cat6 HDMI USB NEMA 5-15R negra", "BROBOTIX", "redes/cableado-estructurado/cajas-mesa/multimedia-rj45-hdmi-usb-corriente", "networking"],
  ["Tenda S105 switch no administrable Fast Ethernet 5 puertos 10/100 blanco", "TENDA", "redes/switches/no-administrables/fast-ethernet/5-puertos", "networking"],
  ["Silimex IsoPro 750300219690 alcohol isopropilico aerosol 250 ml", "SILIMEX", "computo/accesorios/limpieza/alcohol-isopropilico/250ml", "accessories"],
  ["Acteck Optimize Joy MI215 AC-933445 mouse inalambrico 1600 DPI negro", "ACTECK", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi", "accessories"],
  ["WAM WAM-RACK419 rack abierto de piso 25U 19 pulgadas acero negro", "WAM", "infraestructura/racks-enfriamiento/racks-piso/abiertos-25u", "networking"],
  ["Game Factor MPG500 mousepad gamer XL RGB 800 x 300 x 4 mm", "GAME FACTOR", "computo/accesorios/mousepads/gaming-rgb/extendidos", "accessories"],
  ["Zebra ZD220D impresora de etiquetas termica directa 4 pulgadas 203 dpi USB", "ZEBRA", "impresion/impresoras/etiquetas/termicas-directas/desktop-4-pulgadas", "printers_scanners"],
  ["Silimex 7503018454009 toallitas humedas limpiadoras Gamer 30 piezas", "SILIMEX", "computo/accesorios/limpieza/toallitas/gamer-30-piezas", "accessories"],
  ["Logitech M110 Silent 910-006757 mouse alambrico USB 1000 DPI gris", "LOGITECH", "computo/perifericos/mouse/alambricos/basicos/1000-dpi", "accessories"],
  ["Logitech Z207 bocinas Bluetooth 2.0 10W pico 5W RMS 3.5mm negras", "LOGITECH", "computo/perifericos/bocinas-audio/2-0", "headphones"],
  ["Dell Pro Max 16 Core Ultra 9 285H 32GB 1TB RTX PRO 2000 Blackwell", "DELL", "computo/laptops/workstations/16-pulgadas/dell-pro-max-16", "laptops"],
  ["Uniarch NVR-104E2-P4 NVR 4 canales PoE Ultra265 HDMI 4K", "UNIARCH", "seguridad/cctv/dvr-nvr/nvr-poe", "cameras"],
  ["Perfect Choice Meucci PC-117223 manos libres Bluetooth 20h USB-C", "PERFECT CHOICE", "audio/audifonos/bluetooth/monoaurales-uc", "headphones"],
  ["LG UltraGear 24GS60F-B monitor gaming 24 FHD IPS 180Hz 1ms", "LG", "computo/monitores/gaming/24-fhd/180hz", "monitors"],
  ["Naceb Gaming NA-0122 cable HDMI 2.1 3m 8K 48Gbps eARC", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/3m", "accessories"],
  ["BRobotix 651855 funda City poliester gris para laptop 15.6 pulgadas", "BROBOTIX", "computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas", "accessories"],
  ["Generico cargador compatible Dell 65W 19.5V 3.34A punta 4.5 x 3.0", "GENERICO", "computo/accesorios/cargadores-laptop/compatibles-dell/65w-19-5v-4-5x3-0", "laptops"],
  ["Grandstream GRP2602P telefono IP 2 lineas 4 cuentas SIP PoE", "GRANDSTREAM", "telefonia/telefonos-ip/escritorio/2-lineas/poe", "networking"],
  ["DBUGG DB-USB-SE12 memoria USB 128GB USB-A plata", "DBUGG", "computo/almacenamiento/memorias-flash/usb/128gb", "storage"],
  ["Logitech Signature M650 L mouse inalambrico Bluetooth Logi Bolt grafito", "LOGITECH", "computo/perifericos/mouse/inalambricos/productividad", "accessories"],
  ["Acteck Flux Core EC303HR silla ergonomica de oficina malla gris", "ACTECK", "oficina/mobiliario-accesorios/sillas-oficina/ergonomicas-malla", "accessories"],
  ["Epson EcoTank L8180 C11CJ21301 multifuncional fotografica A3 Plus 6 tintas", "EPSON", "impresion/impresoras/multifuncionales-ecotank/fotografica-a3-plus", "printers_scanners"],
  ["Necnon NSG-RGB-1 silla gamer RGB reclinable 145 grados negra", "NECNON", "gaming/mobiliario/sillas-gamer/rgb", "gaming"],
  ["Orvibo VS10ZW-1UO miniHub Zigbee Wi-Fi 2.4GHz blanco", "ORVIBO", "domotica/hubs/zigbee", "accessories"],
  ["BRobotix 6005835 audifonos Bluetooth TWS in-ear 5.3 blancos", "BROBOTIX", "audio/audifonos/bluetooth/tws/in-ear", "headphones"],
  ["Swann SWDVK-846806MQB-US kit DVR 8 canales 6 camaras 1080p 1TB", "SWANN", "seguridad/cctv/kits-dvr/8-canales/6-camaras-1080p", "cameras"],
  ["be quiet! Light Base 600 LX White gabinete ATX panoramico ARGB", "BE QUIET", "computo/componentes/gabinetes/gaming/atx-mid-tower/panoramicos-argb", "components"],
  ["Generico AP2-60W cargador Apple MagSafe 2 60W 16.5V 3.65A blanco", "GENERICO", "computo/accesorios/cargadores-laptop/apple-magsafe-2/60w", "laptops"],
  ["LG VO182H1 Smart Inverter Minisplit 1.5 toneladas frio calor 18000 BTU 230V", "LG", "climatizacion/aires-acondicionados/minisplit/inverter/18000-btu", "accessories"],
  ["UNV IPC3616SB-ADF28KMC-I1 camara IP turret ColorHunter Wise-ISP 6MP 2.8mm PoE", "UNV", "seguridad/cctv/camaras-ip-poe/turret/6mp-dual-light", "cameras"],
  ["Perfect Choice PC-171652 hub USB-C 4 puertos negro", "PERFECT CHOICE", "computo/accesorios/docks-hubs/usb-c", "accessories"],
  ["Vorago AU-600 cargador de pared USB-C PD 100W 5 puertos", "VORAGO", "energia/cargadores-usb/pared-usb-c/100w-multipuerto", "accessories"],
  ["Bixolon SPP-R310 impresora movil termica 3 pulgadas para recibos y etiquetas", "BIXOLON", "impresion/impresoras/etiquetas/termicas-moviles", "printers_scanners"],
  ["Balam Rush Eolox Blaze EX50KW kit 3 ventiladores ARGB 120mm blancos", "BALAM RUSH", "computo/componentes/enfriamiento/ventiladores-gabinete/120mm-argb", "components"],
  ["Complet Tulum 1500 no-break UPS 1500VA 750W 10 contactos", "COMPLET", "energia/no-breaks-ups/line-interactive/1500va", "power"],
  ["Logitech G309 LIGHTSPEED mouse gaming inalambrico Bluetooth blanco", "LOGITECH", "computo/perifericos/mouse/inalambricos/gaming", "accessories"],
  ["Dahua DH-HAC-HFW1239TLMN-A-LED-0360B camara bullet HDCVI Full Color 2MP 3.6mm con microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-full-color", "cameras"],
  ["Kyocera TK-5282K toner negro original rendimiento 13000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5282k", "printers_scanners"],
  ["Manhattan 461481 soporte de pared inclinable TV 37 a 80 pulgadas 80 kg", "MANHATTAN", "video/soportes-tv/pared/inclinables-37-80-80kg", "tvs"],
  ["Ghia GCD581 cajon de dinero metalico RJ11 5 billetes 8 monedas negro", "GHIA", "punto-de-venta/cajones-dinero/metalicos/rj11/5-billetes-8-monedas", "accessories"],
  ["Ovaltech OTHHT03XL bateria para laptop HP 11.55V 41Wh 3 celdas", "OVALTECH", "computo/accesorios/baterias-laptop/hp/ht03xl", "laptops"],
  ["CyberPower CPS1215RM PDU rack 1U 15A 10 contactos NEMA 5-15R", "CYBERPOWER", "energia/pdu-rack/1u-15a-10-contactos", "power"],
  ["Ultimate Ears WONDERBOOM 4 bocina Bluetooth portatil IP67 14h azul", "ULTIMATE EARS", "audio/bocinas/bluetooth/portatiles/ip67", "audio"],
  ["Naceb NA-632 mouse gaming alambrico USB con mousepad 1200 DPI negro", "NACEB TECHNOLOGY", "gaming/accesorios/mouse-y-mousepad", "gaming"],
  ["Ovaltech OVMDP-VGA adaptador Mini DisplayPort a VGA blanco", "OVALTECH", "accesorios/cables-adaptadores/video-displayport-vga/mini-displayport", "accessories"],
  ["Uniarch IPC-B233-APF40W camara IP bullet Dual-light 3MP 4mm PoE", "UNIARCH", "seguridad/cctv/camaras-ip-poe/bullet/3mp-dual-light", "cameras"],
  ["Omada ER7206 gateway VPN Gigabit multi-WAN SFP USB", "OMADA", "redes/routers/vpn/omada/er7206", "networking"],
  ["Necnon NB-08Y bafle Bluetooth inalambrico 8 pulgadas LED con microfono", "NECNON", "audio/bocinas/bafles-portatiles/8-pulgadas", "audio"],
  ["Dahua HAC-HFW1200T camara bullet HDCVI 2MP 3.6mm IR IP67", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-ir-ip67", "cameras"],
  ["Balam Rush Tank Mini GI930 gabinete gamer Micro-ATX mini tower ARGB negro", "BALAM RUSH", "computo/componentes/gabinetes/gaming/micro-atx/mini-tower-argb", "components"],
  ["Provision ISR DB-320WIPN videoportero IP WiFi PoE 2MP ONVIF", "PROVISION-ISR", "seguridad/videoporteros/ip/wifi-poe", "security"],
  ["BRobotix 6000380 duo pack lapiz stylus universal azul", "BROBOTIX", "computo/tabletas/accesorios/stylus/universales-duopack", "accessories"],
  ["Ghia Whale G43W25 Smart TV 43 pulgadas Full HD WiFi Bluetooth", "GHIA", "video/televisores/smart-tv/43-fhd", "tvs"],
  ["Naceb Silver Fang NA-0969 teclado gaming mecanico 75 por ciento RGB", "NACEB TECHNOLOGY", "computo/perifericos/teclados/gaming/mecanicos/75-rgb", "gaming"],
  ["Tenda IC7-PRS-4 camara IP concha PoE 4MP IR microfono", "TENDA", "seguridad/cctv/camaras-ip-poe/domo/4mp-ir-poe", "cameras"],
  ["Vorago CAB-M01W cable USB-A a Micro-USB 2.0 1m blanco", "VORAGO", "accesorios/cables-adaptadores/usb/usb-a-micro-b/2-0-1m", "accessories"],
  ["Smartbitt SBOL30KTII-3K UPS online trifasico 30kVA 30kW", "SMARTBITT", "energia/no-breaks-ups/doble-conversion/trifasicos/30000va", "power"],
  ["Naceb Boreal NA-0656N enfriamiento liquido AIO 360mm ARGB con pantalla", "NACEB GAMING", "computo/componentes/enfriamiento/liquido-cpu/360mm/argb-pantalla", "components"],
  ["Dahua DH-IPC-HFW1239S1-LED-S4 camara IP bullet Full-Color 2MP PoE 3.6mm", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/bullet/2mp-full-color", "cameras"],
  ["BRobotix 188533-2 kit teclado y mouse gaming USB alambrico RGB espanol", "BROBOTIX", "computo/perifericos/combos-teclado-mouse/gaming/alambricos-rgb", "gaming"],
  ["TP-Link TL-SL1226P switch PoE+ no administrable 24 puertos Fast Ethernet 250W", "TP LINK", "redes/switches/poe-no-administrables/fast-ethernet/24-puertos-250w", "networking"],
  ["Dahua HAC-HFW1200D-0360B camara bullet HDCVI IR 2MP 3.6mm 80m IP67", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-ir", "cameras"],
  ["Kingston KCP432SD8/16 memoria RAM SO-DIMM DDR4 16GB 3200MT/s CL22", "KINGSTON", "computo/componentes/memoria-ram/sodimm-ddr4", "components"],
  ["Dahua DH-IPC-T1E20 camara IP domo eyeball 2MP IR 30m PoE", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/domo/2mp-ir", "cameras"],
  ["UNV IPC2B24SA-AHDZK-PI-I1 camara IP bullet LightHunter 4MP varifocal PoE", "UNV", "seguridad/cctv/camaras-ip-poe/bullet/4mp-lighthunter-varifocal", "cameras"],
  ["Grandstream UCM6304 PBX IP 2000 usuarios 4 FXS 4 FXO", "GRANDSTREAM", "telefonia/pbx-ip/grandstream-ucm6300/4fxs-4fxo", "networking"],
  ["PCM 50000B0161A etiquetas termicas directas 4x6 pulgadas caja 12 rollos", "PCM", "impresion/consumibles/etiquetas-papel/termicas-directas/102x152mm", "printers_scanners"],
  ["BRobotix 810533 rack abierto 19 pulgadas 24U 1.20m con tornilleria M6", "BROBOTIX", "infraestructura/racks-enfriamiento/racks-piso/abiertos-24u", "networking"],
  ["Dahua DH-PFA134 caja de conexion para camaras CCTV blanca", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-montaje/cajas-conexion/dahua-pfa134", "cameras"],
  ["Vorago AU-402-WH cargador pared GaN 45W 2 USB-C blanco", "VORAGO", "energia/cargadores-usb/pared-gan/45w-dual-usb-c", "accessories"],
  ["UNV OEU-301S-HMKA kit videoportero IP departamental con monitor OEI-371S-H-W 7 pulgadas", "UNV", "seguridad/videoporteros/ip/kits-departamentales/7-pulgadas", "security"],
  ["Dahua DH-HAC-HFW1509TN-A-LED-0360B camara HDCVI bullet 5MP Full-Color microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/5mp-full-color-mic", "cameras"],
  ["Acteck BE220 Frezze Book Prime base enfriadora para laptop 15.5 pulgadas", "ACTECK", "computo/accesorios/soportes-laptop/bases-enfriadoras", "laptops"],
  ["Necnon NBAB042600 NBH-04 Pro audifonos Bluetooth over-ear radio FM MicroSD verdes", "NECNON", "audio/audifonos/bluetooth/diadema-over-ear/radio-fm-microsd", "headphones"],
  ["Kyocera TK-5292K toner negro original rendimiento 17000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5292k", "printers_scanners"],
  ["Tripp Lite N001-005-WH cable patch Cat5e UTP RJ45 5ft blanco", "TRIPP-LITE", "redes/cableado-estructurado/patch-cords/cat5e/1-5m-blanco", "networking"],
  ["Dell Premier KM7321W combo teclado y mouse inalambrico multi-dispositivo", "DELL", "computo/perifericos/combos-teclado-mouse/inalambricos/productividad", "accessories"],
  ["Redragon Hylas Lunar White H260-W headset gaming alambrico RGB 50mm", "REDRAGON", "gaming/audio/headsets/alambricos/rgb", "gaming"],
  ["Kensington K58352WW MagPro filtro de privacidad magnetico laptop 14 16:9", "KENSINGTON", "computo/accesorios/filtros-privacidad/laptops/14-16-9", "accessories"],
  ["Netis ST3126GS switch Gigabit no administrable 26 puertos 24 RJ45 2 SFP", "NETIS", "redes/switches/no-administrables/gigabit/26-puertos-sfp", "networking"],
  ["Stylos STMUS564B ST500 memoria USB 64GB USB-A 2.0 plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/64gb/usb-2-metalicas", "storage"],
  ["Necnon NBHK-PUG audifonos infantiles alambricos 3.5mm volumen seguro 95dB", "NECNON", "audio/audifonos/alambricos-3-5mm/infantiles", "headphones"],
  ["HPE Q2079A cinta LTO-9 Ultrium 45TB RW", "HEWLETT PACKARD ENTERPRISE", "computo/almacenamiento/cintas-lto/lto-9", "storage"],
  ["Perfect Choice PC-084761 mochila laptop Essential 17 pulgadas morada", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/mochilas-laptop/17-pulgadas", "accessories"],
  ["Kingston KCP432SS8/8 memoria RAM SO-DIMM DDR4 8GB 3200MT/s CL22", "KINGSTON", "computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200", "components"],
  ["Naceb Gaming NA-0972G teclado mecanico Red Phyton RGB switch Brown", "NACEB GAMING", "computo/perifericos/teclados/gaming/mecanicos/full-size-rgb", "gaming"],
  ["Dahua DH-HAC-HFW1801TN-A-0280B camara HDCVI bullet 8MP IR con microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/8mp-ir-mic", "cameras"],
  ["Forza HT-650LCD UPS line-interactive 650VA 390W con LCD", "FORZA", "energia/no-breaks-ups/line-interactive/650va/lcd", "power"],
  ["BRobotix 963579 convertidor USB-A a serial RS-232 DB9 macho 1.8m", "BROBOTIX", "accesorios/cables-adaptadores/usb-serial/db9-rs232", "accessories"],
  ["Smartbitt SBBA12-5 bateria sellada VRLA para UPS 12V 5Ah", "SMARTBITT", "energia/baterias-ups/selladas-12v/5ah", "power"],
  ["Ubiquiti UniFi U6 Pro access point Wi-Fi 6 AX5400 PoE techo", "UBIQUITI", "redes/access-points/wifi-6/techo/ax5400", "networking"],
  ["DataShield MI-4235 bateria AGM ciclo profundo solar 12V 100Ah", "DATASHIELD", "energia/baterias-solares/agm-ciclo-profundo/12v-100ah", "power"],
  ["Hyundai HYLine Pro HY65PA1402NABL smartphone Android 6GB 128GB azul", "HYUNDAI", "telefonia/smartphones/android/hyundai-hyline-pro/6gb-128gb", "smartphones"],
  ["Cooler Master Hyper 212 Spectrum V3 RR-S4NA-17PA-R1 disipador CPU ARGB", "COOLER MASTER", "computo/componentes/enfriamiento/disipadores-cpu/torre-120mm-argb", "components"],
  ["VICA Optima 1250 no-break line-interactive 1250VA 600W 6 contactos", "VICA", "energia/no-breaks-ups/line-interactive/1250va", "power"],
  ["Kaspersky Small Office Security KL4541Z5EFS 5 licencias 1 ano", "KASPERSKY", "software/seguridad/antivirus/kaspersky-small-office/5-licencias-1-ano", "software"],
  ["Kaspersky Next EDR Foundations KL4065ZAQFS 50-99 licencias 1 ano", "KASPERSKY", "software/seguridad/edr/kaspersky-next-edr-foundations/50-99-licencias-1-ano", "software"],
  ["Kingston A400 SA400S37/240G SSD SATA III 2.5 pulgadas 240GB", "KINGSTON", "computo/almacenamiento/ssd/2-5-sata/240gb", "storage"],
  ["Naceb NA-595AZ baston selfie para smartphone 18-74 cm azul plug 3.5 mm", "NACEB TECHNOLOGY", "foto-video/accesorios/selfie-sticks", "accessories"],
  ["Complet SIGNAL 3KT120M UPS online doble conversion 3000VA 3000W rack torre 120V", "COMPLET", "energia/no-breaks-ups/doble-conversion/rack-torre/3000va/120v", "power"],
  ["Naceb NA-0123 kit teclado y mouse inalambrico 2.4GHz espanol negro", "NACEB TECHNOLOGY", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Vorago PSU-101 fuente de poder ATX 500W no modular gris", "VORAGO", "computo/componentes/fuentes-poder/atx-500w", "components"],
  ["Ovaltech OTD6420 bateria Dell Latitude E5420 E6420 11.1V 6 celdas negra", "OVALTECH", "computo/accesorios/baterias-laptop/dell/latitude-e5420-e6420", "laptops"],
  ["Logitech G PRO X SUPERLIGHT 2 910-006629 mouse gamer inalambrico LIGHTSPEED negro 60g", "LOGITECH G", "computo/perifericos/mouse/inalambricos/gaming/esports-60g", "gaming"],
  ["Kyocera TK-5417Y toner amarillo original rendimiento 13000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5417/amarillo", "printers_scanners"],
  ["Patriot Signature Premium PSP48G3200H1 memoria RAM DDR4 8GB 3200MHz CL22 UDIMM", "PATRIOT", "computo/componentes/memoria-ram/udimm-ddr4/8gb-3200", "components"],
  ["Redragon Storm Elite White M988W mouse gamer alambrico RGB Pixart P3389 32000 DPI", "REDRAGON", "computo/perifericos/mouse/alambricos/gaming/alto-dpi/32000-dpi", "gaming"],
  ["TP-Link Omada TL-SG3428X switch administrable L2+ JetStream 24 puertos Gigabit 4 SFP+ 10G", "TP LINK", "redes/switches/administrables/gigabit/24-puertos-4-sfp-plus", "networking"],
  ["Smartbitt SBEC-HD08M extension electrica uso rudo 8m 3 tomas naranja", "SMARTBITT", "energia/extensiones-electricas/uso-rudo", "power"],
  ["Perfect Choice Lusso PC-084464 mochila ejecutiva slim para laptop 15.6 pulgadas negra", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6/ejecutivas-slim", "accessories"],
  ["Brother PT-E110 rotuladora industrial portatil P-touch para cintas TZe hasta 12mm", "BROTHER", "impresion/rotuladoras/portatiles-industriales", "printers_scanners"],
  ["Brother TZe-221 cinta laminada P-touch 9mm x 8m negro sobre blanco", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-tze/laminadas/9mm/negro-sobre-blanco", "printers_scanners"],
  ["Manhattan 353595 cable DisplayPort 1.4 8K 60Hz macho-macho 1m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-displayport/1m/8k", "accessories"],
  ["TechZone TZBE5B8M100 cajon electronico de dinero POS RJ11 5 billetes 8 monedas", "TECH ZONE POS", "punto-de-venta/cajones-dinero/metalicos/rj11/5-billetes-8-monedas", "accessories"],
  ["Honeywell Voyager 1400g lector codigo de barras 1D 2D area-imaging cableado USB", "HONEYWELL", "punto-de-venta/lectores-codigo-barras/2d-usb/area-imager", "accessories"],
  ["be quiet! Light Base 600 DX White gabinete panoramico ATX ARGB blanco BGW66", "BE QUIET", "computo/componentes/gabinetes/gaming/atx-mid-tower/panoramicos-argb/sin-ventiladores", "components"],
  ["Cisco CAB-AC-C5 cable alimentacion AC NEMA 5-15P a IEC C5", "CISCO", "redes/accesorios/cables-de-alimentacion/cisco-c5", "networking"],
  ["XPG GAMMIX S60 AGAMMIXS60-512G-CS SSD M.2 2280 PCIe Gen4 x4 NVMe 512GB", "ADATA", "computo/almacenamiento/ssd/m2-nvme/512gb-gen4", "storage"],
  ["Xerox 006R04824 toner cian estandar 1800 paginas para C320 C325", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04824-cian", "printers_scanners"],
  ["Naceb NA-0110 adaptador USB-C macho a VGA hembra plata", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/video-usb-c-vga/usb-c-macho-vga-hembra", "accessories"],
  ["Eaton Tripp Lite ECO1300LCD no-break UPS line-interactive 1300VA 720W LCD 120V", "TRIPP LITE", "energia/no-breaks-ups/line-interactive/1300va/lcd", "power"],
  ["Cooler Master Mobius 120P ARGB MFZ-M2DN-24NP2-R1 ventilador 120mm PWM ARGB negro", "COOLER MASTER", "computo/componentes/enfriamiento/ventiladores-gabinete/120mm-pwm-argb", "components"],
  ["Manhattan 355247 cable USB-C a USB-C 2m USB 2.0 480Mbps 100W negro", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-c-c/2m", "accessories"],
  ["Bixolon XD5-40tK impresora de etiquetas 4 pulgadas transferencia termica 203 dpi USB negra", "BIXOLON", "impresion/impresoras/etiquetas/transferencia-termica/desktop-4-pulgadas", "printers_scanners"],
  ["Lenovo ThinkCentre neo 30s Gen 5 13DG001NLS PC de escritorio SFF Core i5-13420H 16GB DDR5 512GB SSD Wi-Fi Windows 11 Pro", "LENOVO", "computo/desktops/slim/lenovo-thinkcentre-neo-30s-gen-5", "desktops"],
  ["Provision-ISR NVR5-4100PXN(MM) NVR PoE 4 canales 5MP NDAA", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/nvr-poe/4-canales-5mp", "cameras"],
  ["Intellinet 520959 panel de parcheo Cat6 UTP 24 puertos 1U rack 19 pulgadas negro", "INTELLINET", "redes/cableado-estructurado/paneles-parcheo/cat6/24-puertos-1u", "networking"],
  ["BRobotix 406306 soporte antirrobo ajustable para laptop hasta 17.3 pulgadas con candado y llave plata", "BROBOTIX", "computo/accesorios/soportes-laptop/antirrobo-ajustables", "accessories"],
  ["Aspel Sellado CFDI FACTE/400 paquete 400 timbres para facturacion electronica", "ASPEL", "software/licencias/aspel-sellado-cfdi/timbres-400", "software"],
  ["Epson ERC-38BR cinta para impresora matriz punto negro rojo", "EPSON", "impresion/consumibles/cintas-matriz-punto/epson-erc-38", "printers_scanners"],
  ["Dahua DH-HAC-B2A21N-U-IL-A camara HDCVI bullet 2MP dual-light con microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-dual-light-mic", "cameras"],
  ["Naceb NA-0646 escritorio gamer fibra carbono con plataforma para monitor", "NACEB TECHNOLOGY", "gaming/mobiliario/escritorios/fibra-carbono/plataforma-monitor", "gaming"],
  ["CyberPower CL1500VR regulador AVR 1500VA 750W 8 contactos", "CYBERPOWER", "energia/supresores-reguladores/reguladores-voltaje/avr/1500va", "power"],
  ["Dahua DH-XVR1B08-I/T XVR pentahibrido WizSense 8 canales", "DAHUA TECHNOLOGY", "seguridad/cctv/dvr-nvr/xvr-pentahibrido/8-canales-wizsense", "cameras"],
  ["Cooler Master Storm Controller CMI-GSCX-BK1 gamepad Bluetooth USB-C negro", "COOLER MASTER", "gaming/accesorios/controles-gamepad/bluetooth-usb-c", "gaming"],
  ["Manhattan MWK7400 180788 combo teclado y mouse inalambrico 2.4GHz", "MANHATTAN", "computo/perifericos/combos-teclado-mouse/inalambricos/productividad/2-4ghz", "accessories"],
  ["Vorago PSU-101 fuente de poder ATX 500W gris", "VORAGO", "computo/componentes/fuentes-poder/atx-500w", "components"],
  ["Gigabyte Radeon RX 9060 XT Gaming OC 16G tarjeta de video PCIe", "GIGABYTE", "computo/componentes/tarjetas-video/amd-radeon/rx-9000/rx-9060-xt", "gaming"],
  ["Kaspersky Plus KL1042Z5KFS-22 licencia 10 dispositivos 1 ano Windows Mac Android iOS", "KASPERSKY", "software/seguridad/antivirus/kaspersky-plus/10-dispositivos-1-ano", "software"],
  ["TP-Link TL-WR845N router Wi-Fi 4 N300 2.4GHz con 3 antenas", "TP LINK", "redes/routers/wifi-n/n300", "networking"],
  ["StarTech PXT101 cable de alimentacion NEMA 5-15P a IEC C13 1.8m 10A 125V", "STARTECH.COM", "accesorios/cables-adaptadores/alimentacion/nema-5-15p-c13/1-8m", "accessories"],
  ["MSI PRO B760M-P DDR4 tarjeta madre micro ATX Intel B760 LGA1700 DDR4", "MSI", "computo/componentes/tarjetas-madre/intel-lga1700/b760/micro-atx/ddr4", "components"],
  ["Dahua DH-PFM320D-015 fuente de poder CCTV 12V 1.5A con indicador", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-alimentacion/fuentes-12v/1-5a", "cameras"],
  ["Hisense ARU362HBW minisplit inverter 3 toneladas 36000 BTU 230V blanco", "HISENSE", "climatizacion/aires-acondicionados/minisplit/inverter/36000-btu/230v", "accessories"],
  ["Nextep NE-410E mouse inalambrico ergonomico USB 1600 DPI negro", "NEXTEP", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi", "accessories"],
  ["Zebra ZD421t impresora de etiquetas transferencia termica 4 pulgadas 203 dpi USB", "ZEBRA", "impresion/impresoras/etiquetas/transferencia-termica/desktop-4-pulgadas", "printers_scanners"],
  ["Vorago AU-302-BK cargador de pared USB-A Fast Charge 5V negro", "VORAGO", "energia/cargadores-usb/pared-usb-a/fast-charge", "accessories"],
  ["Vorago CAB-AB018 cable USB 2.0 A macho a USB-B macho para impresora 1.8m negro", "VORAGO", "accesorios/cables-adaptadores/usb/usb-a-b/2-0-1-8m", "accessories"],
  ["Ruijie Reyee RG-EW1800GX PRO router Wi-Fi 6 AX1800 dual-band gigabit", "RUIJIE", "redes/routers/wifi-6/ax1800", "networking"],
  ["ASRock B550M-HDV tarjeta madre micro ATX AMD AM4 B550 DDR4", "ASROCK", "computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx", "components"],
  ["StarTech SDOCK2U313R duplicador dock SATA USB-C dual bay HDD SSD", "STARTECH.COM", "computo/almacenamiento/docks-duplicadores/sata/usb-c-dual-bay", "storage"],
  ["Azor Uni-ball Deluxe UB155NE1 boligrafo roller negro 0.5mm blister", "AZOR", "oficina/papeleria/boligrafos/roller/uni-ball-deluxe", "accessories"],
  ["Imou Cruiser SE+ IPC-S41FEN camara IP WiFi PT exterior 4MP 2K", "IMOU", "seguridad/cctv/camaras-ip-wifi/pt-exterior/4mp-2k", "cameras"],
  ["PNY GeForce RTX 4080 SUPER XLR8 VERTO EPIC-X RGB OC 16GB VCG4080S16TFXXPB1-O", "PNY", "computo/componentes/tarjetas-video/nvidia-geforce/rtx-40/rtx-4080-super", "gaming"],
  ["HPE HK1Y0E Foundation Care 3Y NBD Exchange Instant On Access Point service", "HEWLETT PACKARD ENTERPRISE", "servicios-ti/soporte-garantias/hpe-foundation-care/exchange", "software"],
  ["HP T1A62AA Keyed Cable Lock 10 mm candado para laptop 1.83m", "HP", "accesorios/seguridad-fisica/candados-laptop/llave", "accessories"],
  ["Badgy Evolis CBGR0500K ribbon monocromo negro 500 impresiones", "BADGY", "punto-de-venta/credenciales-identificacion/consumibles/ribbons-monocromo-negro", "accessories"],
  ["Epson FX-2190II C11CF38201 impresora matriz de punto 9 pines formato ancho", "EPSON", "impresion/impresoras/matriz-punto/formato-ancho/9-pines", "printers_scanners"],
  ["Vorago BP-150-BL mochila rPET ecologica para laptop 15.6 pulgadas azul negro", "VORAGO", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6/rpet-ecologicas", "accessories"],
  ["Canon PG-210 2974B017AA cartucho tinta negra FINE 9ml 250 paginas", "CANON", "impresion/consumibles/cartuchos-tinta/canon/pg-210/negro", "printers_scanners"],
  ["Perfect Choice PC-030362 kit limpieza pantallas 30ml con microfibra", "PERFECT CHOICE", "computo/accesorios/limpieza/limpiadores-pantalla/kits/30ml-microfibra", "accessories"],
  ["Naceb Iron Knight NA-0318 headset gamer 3.5mm microfono desmontable PS4 Xbox", "NACEB GAMING", "gaming/audio/headsets/alambricos/3-5mm-microfono-desmontable", "gaming"],
  ["Acteck Onex GS455 AC-943079 gabinete mini torre slim Micro-ATX fuente SFX 500W", "ACTECK", "computo/componentes/gabinetes/mini-tower/micro-atx-itx-fuente-500w/slim-sfx", "components"],
  ["TP-Link CPE710 CPE exterior 5GHz AC 867Mbps 23dBi Pharos", "TP LINK", "redes/radioenlaces-antenas/cpe-exterior/5ghz-ac-867mbps-23dbi", "networking"],
  ["XPG PROBE700B-BKCUS fuente poder ATX 700W 80 Plus Bronze", "ADATA", "computo/componentes/fuentes-poder/atx-80-plus-bronze/700w", "components"],
  ["Dell AC027075 memoria RAM 16GB DDR5 4800MHz ECC UDIMM", "DELL", "computo/componentes/memoria-ram/udimm-ddr5/ecc-16gb-4800", "components"],
  ["Manhattan 153966 USB-C PD docking station 7 en 1 HDMI Ethernet", "MANHATTAN", "computo/accesorios/docks-hubs/usb-c/7-en-1-hdmi-ethernet-pd", "accessories"],
  ["BRobotix 372782 cable USB 2.0 extension activa 15m macho hembra", "BROBOTIX", "accesorios/cables-adaptadores/usb/extensiones/activas/15m", "accessories"],
  ["EZVIZ CS-C3TN 3MP 2.8mm OutPro camara IP WiFi exterior color night", "EZVIZ", "seguridad/cctv/camaras-ip-wifi/bullet-exterior/3mp-2k", "cameras"],
  ["BIC 923995 939529 Dura Plus boligrafo negro punto mediano", "BIC", "oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-dura-plus", "accessories"],
  ["NASSA PQ500 sobre correspondencia carta sin fondo 60kg 9.2 x 16.4 paquete 500", "NASSA", "oficina/papeleria/sobres/correspondencia/carta/paquete-500", "accessories"],
  ["BACO PL005 plastilina rosa marqueta escolar 180 gramos", "BACO", "oficina/papeleria/material-escolar/plastilina/marqueta-180g", "accessories"],
  ["Peerless AV AEC1012 columna extension ajustable 10 a 12 pies 227kg", "PEERLESS-AV", "accesorios/montaje-soportes/audio-video/columnas-extension/ajustables-10-12ft", "accessories"],
  ["PCM 10B19 papel bond BriteWhite plotter 0.61 x 50 m rollo", "PCM", "impresion/consumibles/papel-plotter/bond/rollos-61cm-50m", "printers_scanners"],
  ["Soft Restaurant Analytics SR-ANALYTICS-R renta mensual software POS restaurante", "SOFT RESTAURANT", "punto-de-venta/software-pos/restaurantes/analytics/renta-mensual", "software"],
  ["Kensington K65049WW llave maestra 5mm para MicroSaver 2.0", "KENSINGTON", "accesorios/seguridad-fisica/candados-laptop/llave/llave-maestra-microsaver-2-0", "accessories"],
  ["Newland STD30i STD100 base cuello flexible para lector codigo de barras", "NEWLAND", "punto-de-venta/lectores-codigo-barras/accesorios/bases-gooseneck", "accessories"],
  ["CDP POL-11491 poliza de servicio en sitio 10KVA garantia 3 anos", "CDP", "servicios-ti/soporte-garantias/cdp/polizas-sitio/ups-10kva", "software"],
  ["PICO Neo 3 Pro PHS-N3-P1018556 visor VR empresarial 256GB Qualcomm XR2", "PICO", "gaming/realidad-virtual/visores/pico-neo-3-pro", "gaming"],
  ["QNAP QXG-100G2SF-E810 tarjeta PCIe 4.0 dual 100GbE QSFP28 Intel E810", "QNAP", "redes/tarjetas-red/pcie/100gbe/dual-qsfp28", "networking"],
  ["DataShield PC-3705 tarjeta SNMP para inversor cargador solar hibrido", "DATASHIELD", "energia/solar/accesorios/tarjetas-monitoreo-snmp/inversores-hibridos", "power"],
  ["Hisense AH242CF minisplit estandar 2 toneladas 24000 BTU frio calor 220V", "HISENSE", "climatizacion/aires-acondicionados/minisplit/estandar/24000-btu/frio-calor-220v", "accessories"],
  ["Ivanti Endpoint Manager 4ZN1N60391 licencia software gestion endpoint", "IVANTI", "software/gestion-ti/endpoint-management/ivanti-endpoint-manager", "software"],
  ["EPCOM KITEPI2K320 sistema fotovoltaico 2000W", "EPCOM", "energia/solar/kits-fotovoltaicos/2000w", "power"],
  ["Transtector I2R-SPV600-3-40 supresor sobretension 600 VDC tipo 2 DIN rail", "TRANSTECTOR", "energia/solar/proteccion-electrica/supresores-sobretension/600vdc", "power"],
  ["Mirati MFA13 freidora de aire 9L doble canasta 1700W negra", "MIRATI", "hogar/electrodomesticos/cocina/freidoras-aire/doble-canasta/9l", "accessories"],
  ["Acteck Energon Prime CP415 AC-937122 cargador GaN USB-C PD 20W negro", "ACTECK", "energia/cargadores-usb/pared-usb-c/20w-gan", "accessories"],
  ["Datalogic PowerScan PBT9600-HPRBK10US lector 2D industrial Bluetooth USB kit", "DATALOGIC", "punto-de-venta/lectores-codigo-barras/2d-inalambricos/industriales-powerscan-9600", "accessories"],
  ["Kodak Alaris A3 Flatbed Accessory escaner cama plana A3 SCAKDK110", "KODAK", "impresion/escaneres/accesorios/cama-plana-a3", "printers_scanners"],
  ["Dell N_TOM1_N1_P3 garantia desktops 1Y Basic NBD a 3Y ProSupport", "DELL", "servicios-ti/soporte-garantias/dell/prosupport/desktops/1y-nbd-a-3y-prosupport", "software"],
  ["Autodesk AutoCAD C1RK1-WW1762-L158 specialized toolsets annual subscription", "AUTODESK", "software/cad-diseno/autodesk-autocad/toolsets-1y-1usuario", "software"],
  ["Zebra 21-118517-01R kit montaje pared CC600 MK500 negro", "ZEBRA", "punto-de-venta/kioscos/accesorios/montaje-pared/zebra-cc600-mk500", "accessories"],
  ["Baco Bacoflash 99341 resaltador amarillo caja 12 piezas", "BACO", "oficina/papeleria/marcadores/resaltadores/amarillos/12-piezas", "accessories"],
  ["Impress 6951476310602 papel bond carta 70 g 95 blancura caja 5000 hojas", "IMPRESS", "oficina/papel-consumibles/papel-bond/carta/5000-hojas/impress-70g-95-blancura", "accessories"],
  ["Cubrebocas KN95 blanco CN-4102 caja 50 piezas 5 paquetes de 10", "GENERICO", "salud/higiene/cubrebocas/kn95/50-piezas-blanco", "accessories"],
  ["Tripp Lite SRVRTBAR barras verticales organizadoras de cable 42U para rack", "TRIPP-LITE", "infraestructura/racks-accesorios/organizadores-cable/verticales/tripp-lite-srvrtbar-42u", "networking"],
  ["Creative MUVO Go MF8405 BU bocina Bluetooth 5.3 IPX7 20W azul", "CREATIVE", "audio/bocinas/bluetooth/portatiles/ipx7-20w/creative-muvo-go", "audio"],
  ["Dell N_OPTL1_N1_P3 garantia OptiPlex 3000 1Y Basic NBD a 3Y ProSupport", "DELL", "servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/1y-nbd-a-3y-prosupport", "software"],
  ["PCM 50000I0012A etiquetas transferencia termica blancas", "PCM", "impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0012a", "printers_scanners"],
  ["Qian Linyi PA-96R SS5009 sensor movimiento PIR inalambrico", "QIAN", "seguridad/alarmas/sensores/movimiento-pir/inalambricos/qian-pa-96r", "security"],
  ["LG GM25BPT refrigerador French Door 25 pies negro mate", "LG", "hogar/electrodomesticos/refrigeradores/french-door/25-pies/lg-gm25bpt", "accessories"],
  ["Soft Restaurant CFDI-10000 paquete 10000 timbres CFDI", "NATIONAL SOFT", "punto-de-venta/software-pos/restaurantes/timbres-cfdi/10000", "software"],
  ["ALTER EV-OB251 cargador EV wallbox Tipo 2 7kW 32A IP54", "ALTER", "energia/movilidad-electrica/cargadores-ev/wallbox/tipo-2/7kw-32a", "power"],
  ["Targus Newport TXZ026GL bolso crossbody negro para tablet", "TARGUS", "computo/accesorios/mochilas-fundas/bolsos-crossbody/tablet/targus-newport", "accessories"],
  ["Vorago KSP-502 bafle karaoke Bluetooth 15 pulgadas 80W negro", "VORAGO", "audio/bocinas/karaoke/bafles-bluetooth/15-pulgadas/80w", "audio"],
  ["Azor Signal Metalink 30010 marcador permanente plata caja 12 piezas", "AZOR", "oficina/papeleria/marcadores/permanentes/metalicos/plata/12-piezas", "accessories"],
  ["Dell EXTGAR extension de garantia generica validar service tag", "DELL", "servicios-ti/soporte-garantias/dell/extension-generica", "software"],
  ["Anviz W1 Pro terminal control asistencia huella RFID WiFi", "ANVIZ", "seguridad/control-acceso/asistencia/biometricos/huella-rfid/anviz-w1-pro", "security"],
  ["EC Line EC-WT-CRADLE base acoplamiento para terminal EC-WT-10", "EC LINE", "punto-de-venta/terminales-pos/accesorios/docking/ec-line-ec-wt-cradle", "accessories"],
  ["Zebra TRG-TC2L-SNP1-01 gatillo snap-on para TC22 TC27", "ZEBRA", "punto-de-venta/terminales-moviles/accesorios/gatillos/zebra-tc22-tc27", "accessories"],
  ["Baco 5050 juego de geometria mediano con compas", "BACO", "oficina/papeleria/material-escolar/juegos-geometria/medianos/baco-5050", "accessories"],
  ["Corsair XTM70 CT-9010010-WW pasta termica 3 g kit aplicacion", "CORSAIR", "computo/componentes/enfriamiento/pasta-termica/corsair-xtm70-3g", "components"],
  ["Lenovo ThinkSmart Core Gen 2 12WN000JLS kit sala Microsoft Teams Rooms", "LENOVO", "computo/colaboracion/salas-reunion/microsoft-teams-rooms/lenovo-thinksmart-core-gen-2-full-room", "desktops"],
  ["Epson S041586 Bright White Pro Paper carta 500 hojas 90 g", "EPSON", "impresion/consumibles/papel/bright-white-pro/carta-500-hojas", "printers_scanners"],
  ["TechZone TZ15PCAUD diadema alambrica 3.5 mm con microfono", "TECHZONE", "audio/audifonos/diadema/alambricos/3-5mm-microfono/techzone-tz15pcaud", "audio"],
  ["Kensington MicroSaver 2.0 K64434WW candado laptop con llave 6 ft", "KENSINGTON", "accesorios/seguridad-fisica/candados-laptop/llave/microsaver-2-0-master-k64434ww", "accessories"],
  ["Panasonic SE-NSP360FULL activacion KX-NS500 maxima capacidad IP", "PANASONIC", "telefonia/conmutadores-ip/panasonic-kx-ns500/licencias/activacion-full", "software"],
  ["Tripp Lite SRCTMTSDD kit puertas dobles deslizantes contencion pasillo", "TRIPP-LITE", "infraestructura/racks-accesorios/contencion-pasillos/puertas-deslizantes/tripp-lite-srctmtsdd", "networking"],
  ["NECNON NPW-05FB NBPB0512FB power bank 5000 mAh blanca", "NECNON", "energia/baterias-portatiles/power-banks/5000mah/necnon-npw-05fb", "power"],
  ["CT Cloud NCSVXPLUSCQ servicio nube XPLUS CQ", "CT CLOUD", "software/servicios-nube/ct-cloud/gestion-nube/xplus-cq", "software"],
  ["ADATA CHARGERU-0352-QCPDWH cargador GaN 35W USB-C USB-A blanco", "ADATA", "energia/cargadores-usb/pared-usb-c-usb-a/35w-gan/adata-qcpdwh", "power"],
  ["Epson ELPLP88 V13H010L88 lampara repuesto para proyector", "EPSON", "audio-video/proyectores/accesorios/lamparas/epson-elplp88", "accessories"],
  ["CT Cloud IFTPSFTP instalacion configuracion rol FTP SFTP", "CT CLOUD", "software/servicios-nube/ct-cloud/configuracion-servidores/ftp-sftp", "software"],
  ["Anviz AN-EMIDCARD-10PAQ tarjetas RFID EM 125kHz PVC 10 piezas", "ANVIZ", "seguridad/control-acceso/credenciales-rfid/tarjetas-pvc/em-125khz/anviz-10-pack", "security"],
  ["UNV TR-JB03-H-IN-V2 caja conexiones para camara turret metalica", "UNV", "seguridad/cctv/accesorios-camaras/cajas-conexion/turret-metalicas/unv-tr-jb03-h-in-v2", "security"],
  ["EC-Line EC-MSR-VP1100 lector banda magnetica USB para VP1100", "EC-LINE", "punto-de-venta/accesorios-pos/lectores-banda-magnetica/ec-line-ec-msr-vp1100", "accessories"],
  ["Datamax PHD20-2278-01 cabezal termico I-4212e 203 dpi", "DATAMAX", "impresion/refacciones/cabezales/termicos/datamax-i-4212e-203dpi", "printers_scanners"],
  ["Zebra G32432-1M cabezal impresion 105SL 203 dpi", "ZEBRA", "impresion/refacciones/cabezales/termicos/zebra-105sl-203dpi", "printers_scanners"],
  ["Pantum PB-210RB kit recarga toner negro 1600 paginas", "PANTUM", "impresion/consumibles/toner-laser/pantum/pb-210rb-recarga", "printers_scanners"],
  ["Microsoft Visio LTSC Standard 2024 Education CSP licencia perpetua", "MICROSOFT", "software/licencias/microsoft/visio/ltsc-standard-2024-education", "software"],
  ["LG LT57BT refrigerador top freezer 20 pies negro mate", "LG", "hogar/electrodomesticos/refrigeradores/top-freezer/20-pies/lg-lt57bt", "accessories"],
  ["PCM 50000I0017A etiquetas transferencia termica blancas", "PCM", "impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0017a", "printers_scanners"],
  ["Apple Pencil 2a generacion blanco", "APPLE", "computo/accesorios/stylus-tablets/apple-pencil/2-generacion", "accessories"],
  ["Tenda A18 extensor WiFi AC1200 doble banda blanco", "TENDA", "redes/extensores-wifi/dual-band/ac1200/tenda-a18", "networking"],
  ["Datalogic 94ACC0325 mango tipo pistola para Skorpio X5", "DATALOGIC", "punto-de-venta/terminales-moviles/accesorios/mangos/datalogic-skorpio-x5", "accessories"],
  ["Azor Vision Plus 2600RS resaltador rosa fluorescente caja 12 piezas", "AZOR", "oficina/papeleria/marcadores/resaltadores/rosa/12-piezas/azor-2600rs", "accessories"],
  ["Baco G-30 goma blanca mediana para escuela y oficina", "BACO", "oficina/papeleria/material-escolar/borradores/blancos/baco-g30", "accessories"],
  ["Hune AT-ACC-WI-001BOS cargador inalambrico Hoja 10W verde", "HUNE", "energia/cargadores-inalambricos/10w/hune-hoja", "power"],
  ["Dell N_ANWNBM3_C1_R3 garantia Alienware X14 1Y Carry-In a 3Y Premium Support", "DELL", "servicios-ti/soporte-garantias/dell/premium-support/alienware-x14/1y-carry-in-a-3y-premium", "software"],
  ["CDP UPOMODBUS tarjeta interna Modbus RS485 para UPS UPO", "CDP", "energia/no-breaks-ups/accesorios/tarjetas-comunicacion/modbus/cdp-upomodbus", "power"],
  ["Anviz M5 Plus control de acceso exterior huella RFID WiFi Bluetooth", "ANVIZ", "seguridad/control-acceso/lectores-biometricos/huella-rfid/anviz-m5-plus", "security"],
  ["BACO PL006 plastilina marqueta 180 g rojo No. 54", "BACO", "oficina/papeleria/material-escolar/plastilina/marqueta-180g", "accessories"],
  ["Hisense AC242CF minisplit estandar solo frio 2 toneladas 230V blanco", "HISENSE", "climatizacion/aires-acondicionados/minisplit/estandar/24000-btu/solo-frio-230v", "accessories"],
  ["Provision-ISR PR-JB12IP66-G caja de conexiones IP66 para camaras negra", "PROVISION-ISR", "seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip66/provision-pr-jb12ip66-g", "security"],
  ["Acteck Glee Mini AP420 bocina Bluetooth TWS IPX5 5W negra", "ACTECK", "audio/bocinas/bluetooth/portatiles/ipx5-5w/acteck-ap420", "audio"],
  ["Enson ENS-SRJ45-CAT5E plug RJ45 blindado Cat5e para cable UTP", "ENSON", "redes/cableado-estructurado/conectores-rj45/cat5e/blindados/enson-ens-srj45-cat5e", "networking"],
  ["Alter EV-OMB141 cargador portatil EV Tipo 2 1.92kW 16A NEMA 5-15P", "ALTER", "energia/movilidad-electrica/cargadores-ev/portatiles/tipo-2/16a/alter-ev-omb141", "power"],
  ["Dell N_INSPNBL5_C1_C3 garantia Inspiron 2 en 1 1Y Carry-In a 3Y Carry-In", "DELL", "servicios-ti/soporte-garantias/dell/carry-in/inspiron-2-en-1/1y-a-3y", "software"],
  ["Kodak Alaris i3500 escaner documental ADF A3 110 ppm", "KODAK", "impresion/escaneres/documentales/adf/alto-volumen/kodak-i3500", "printers_scanners"],
  ["Azor Aquarelo Grip 20012 marcadores lavables base agua 12 colores", "AZOR", "oficina/papeleria/marcadores/base-agua-lavables/12-colores/azor-aquarelo-grip-20012", "accessories"],
  ["JC Vision JC-XT320PCAP mesa interactiva tactil 32 pulgadas Full HD blanca", "JC Vision", "electronica/pantallas-y-monitores/pizarrones-interactivos/mesas-interactivas/32-pulgadas", "accessories"],
  ["BACO Le Plume 53404 boligrafo 1.0 mm tinta negra caja 12 piezas", "BACO", "oficina/papeleria/boligrafos/boligrafo-punto-mediano/baco-le-plume-negro-12-piezas", "accessories"],
  ["Kodak Alaris E1035 escaner documental duplex ADF 80 hojas 35 ppm", "KODAK", "impresion/escaneres/documentales/adf/duplex/kodak-e1035", "printers_scanners"],
  ["Dell N_OPTL1_N1_N5 garantia OptiPlex 3000 1Y Basic NBD a 5Y Basic NBD", "DELL", "servicios-ti/soporte-garantias/dell/basic-nbd/optiplex-3000/1y-a-5y", "software"],
  ["GHIA PCGHIA-3286A extension de garantia 24 meses adicionales", "GHIA", "servicios-ti/soporte-garantias/ghia/pcghia-3286/24-meses-adicionales", "software"],
  ["Soft Restaurant Movil comandero con Lenovo Tab One TB305FU 8.7 pulgadas", "SOFT RESTAURANT", "punto-de-venta/software-pos/restaurantes/comandero-movil/tablet-android/lenovo-tab-one-8-7", "software"],
  ["Lenovo ThinkStation P3 Ultra SFF Gen 2 PA0012 Core Ultra 9 RTX 2000 Ada 5Y Onsite", "LENOVO", "computo/desktops/workstations/lenovo-thinkstation-p3-ultra-sff-gen-2/pa0012-5y-onsite", "desktops"],
  ["Meriva Streamax M4PIN 7M cable Tipo-B para camara MCA20D ADAS", "MERIVA TECHNOLOGY", "seguridad/cctv/accesorios-cableado/cables-camaras-moviles/streamax-m4pin", "cameras"],
  ["Pacific Soft PSF010 software punto de venta para restaurantes", "PACIFIC SOFT", "punto-de-venta/software-pos/restaurantes/pacific-soft-psf010", "software"],
  ["Sola Basic ISB 15-81-120-8000 corrector de voltaje 8000VA 120V", "SOLA BASIC ISB", "energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/8000va/sola-basic-15-81-120-8000", "power"],
  ["BACO PL008 plastilina azul oscuro marqueta 180 g No. 56", "BACO", "oficina/papeleria/material-escolar/plastilina/marqueta-180g", "accessories"],
  ["Dell N_VOSDTM2_N1_P3 garantia Vostro 3000 1Y Basic Onsite a 3Y ProSupport", "DELL", "servicios-ti/soporte-garantias/dell/prosupport/vostro-3000/1y-basic-onsite-a-3y-prosupport", "software"],
  ["Acteck Energon S-Mate CI740 AC-937139 cargador inalambrico 3 en 1 Qi 15W", "ACTECK", "energia/cargadores-inalambricos/3-en-1", "accessories"],
  ["Azor Signal 30006 marcador permanente naranja punto fino caja 12 piezas", "AZOR", "oficina/papeleria/marcadores/permanentes/signal-fino/naranja/12-piezas", "accessories"],
  ["Provision-ISR PR-JB14IP64 caja de conexiones IP64 para camaras CCTV", "PROVISION-ISR", "seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip64/provision-pr-jb14ip64", "security"],
  ["uni-ball Uni Paint PX-20 marcador permanente blanco base aceite", "UNI PAINT", "oficina/papeleria/marcadores/permanentes/industriales/base-aceite/uni-paint-px20-blanco", "accessories"],
  ["Peerless-AV PLP-UNL placa adaptadora universal para pantallas 32 a 90 pulgadas", "PEERLESS-AV", "accesorios/montaje-soportes/audio-video/adaptadores-pantalla/peerless-plp-unl", "accessories"],
  ["HP DesignJet T830 F9A28D multifuncional gran formato 24 pulgadas", "HP", "impresion/impresoras/gran-formato/multifuncionales/24-pulgadas/hp-designjet-t830", "printers_scanners"],
  ["Datalogic PowerScan PD9630-SRK2 lector industrial 2D RS-232 kit", "DATALOGIC", "punto-de-venta/lectores-codigo-barras/2d-cableados/industriales-powerscan-9600/rs232-pd9630-srk2", "accessories"],
  ["Mimosa Networks C5c radio cliente conectorizado PTP/PTMP 4.9-6.4GHz", "MIMOSA NETWORKS", "redes/radioenlaces-antenas/radios-cpe/ptp-ptmp/mimosa-c5c", "networking"],
  ["Logitech G560 LIGHTSYNC bocinas gaming 2.1 RGB 120W RMS", "LOGITECH", "audio/bocinas/pc/gaming/2-1-rgb/logitech-g560", "audio"],
  ["Zebra P1037974-001 ZebraNet 10/100 print server interno ZT200", "ZEBRA", "impresion/impresoras/etiquetas/accesorios/servidores-impresion/zebra-zt200-p1037974-001", "printers_scanners"],
  ["Perfect Choice Noctune PC-117278 diadema inalambrica Bluetooth 2.4GHz ENC", "PERFECT CHOICE", "audio/audifonos/bluetooth/diadema-over-ear/dual-2-4ghz-enc/perfect-choice-noctune", "headphones"],
  ["Acteck Dynamic Bass BW676 AC-939829 subwoofer activo Bluetooth 50W", "ACTECK", "audio/bocinas/subwoofers/bluetooth/50w/acteck-bw676", "audio"],
  ["Vorago Start The Game MPG-301 mousepad gamer XL speed-control negro", "START THE GAME", "computo/accesorios/mousepads/gaming-xl/speed-control/vorago-mpg-301", "accessories"],
  ["Grandstream GS-CAPACITACION capacitacion remota telefonia IP y redes", "GRANDSTREAM", "servicios-ti/capacitacion/telefonia-ip-redes/grandstream-remota", "software"],
  ["Vorago TP-100 pasta termica gris 3 g 1.93 W/mK", "VORAGO", "computo/componentes/enfriamiento/pasta-termica/vorago-tp-100-3g", "components"],
  ["APC SBP40KFC1M1 panel bypass mantenimiento 40kW 208V 3PH", "APC", "energia/no-breaks-ups/accesorios/paneles-bypass/40kw-208v/apc-sbp40kfc1m1", "power"],
  ["CyberPower BP48V75ART2U banco externo baterias UPS 48V 2U rack torre", "CYBERPOWER", "energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/48v/cyberpower-bp48v75art2u", "power"],
  ["HP 744 F9J86A cabezal DesignJet Photo Black Cyan", "HP", "impresion/refacciones/cabezales/inkjet/hp-designjet-744/f9j86a-photo-black-cyan", "printers_scanners"],
  ["PCM DS00232000B Data Stock papel continuo 9.5 x 5.5 3 tantos 2000 hojas", "PCM", "impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/3-tantos/pcm-ds00232000b", "printers_scanners"],
  ["Norton AntiTrack 21430244 licencia digital 1 dispositivo 2 anos", "NORTON", "software/seguridad/privacidad-antirrastreo/norton-antitrack/1-dispositivo-2-anos", "software"],
  ["Clar Systems CSY060 dispensador jabon Innova ABS rellenable 1.1L humo", "CLAR SYSTEMS", "hogar/higiene/dispensadores-jabon/manuales/rellenables-1-1l/clar-innova-csy060", "accessories"],
  ["BACO Bacoflash 99365 resaltador rosa caja 12 piezas", "BACO", "oficina/papeleria/marcadores/resaltadores/rosa/12-piezas/baco-bacoflash-99365", "accessories"],
  ["HP ScanJet Enterprise Flow 7000 s3 L2757A escaner documental ADF 75 ppm", "HP", "impresion/escaneres/documentales/adf/alto-volumen/hp-scanjet-7000-s3", "printers_scanners"],
  ["LACES LA200KEA2 kit de extractores negro para rack", "LACES", "infraestructura/racks-accesorios/ventilacion/extractores/laces-la200kea2", "networking"],
  ["Dell N_PAM3_N3_M3 garantia ProSupport Plus Pro 24 AIO 3 anos", "DELL", "servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-24-aio/3y-basic-a-3y-prosupport-plus", "software"],
  ["Lenovo 4ZN1Q45636 Ivanti Endpoint Manager PMA formerly Management Suite", "LENOVO", "software/gestion-ti/endpoint-management/ivanti-endpoint-manager/pma-4zn1q45636", "software"],
  ["Poly PBLKWIRE312 Blackwire Plus Service 3 anos advance replacement", "POLY", "servicios-ti/soporte-garantias/poly/blackwire/plus-service-3y", "software"],
  ["Enson ENS-FP62 placa faceplate universal 2 puertos sin jack blanca", "ENSON", "redes/cableado-estructurado/placas-keystone/2-puertos/enson-ens-fp62", "networking"],
  ["Corsair XTM60 CT-9010015-WW pasta termica alto rendimiento 3 g", "CORSAIR", "computo/componentes/enfriamiento/pasta-termica/corsair-xtm60-3g", "components"],
  ["Soft Restaurant SR-11LITE-RE 11 Lite renta mensual 2 nodos", "SOFT RESTAURANT", "punto-de-venta/software-pos/restaurantes/licencias-renta-mensual/lite-2-nodos", "software"],
  ["Amazfit GTS 4 smartwatch Infinite Black Bluetooth GPS AMOLED", "AMAZFIT", "electronica/wearables/smartwatches/amazfit-gts-4", "accessories"],
  ["Microsoft Visio Professional 2024 EP2-07111 licencia ESD descarga", "MICROSOFT", "software/licencias/microsoft/visio/professional-2024-esd", "software"],
  ["KSA KN95 cubrebocas blanco caja con 20 piezas", "KSA", "salud/higiene/cubrebocas/kn95/20-piezas/ksa", "accessories"],
  ["Dell N_OPTL3_N3_M5 garantia OptiPlex 7010 3Y Basic NBD a 5Y ProSupport Plus", "DELL", "servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-7010/3y-basic-a-5y-prosupport-plus", "software"],
  ["Azor Signal Xtra 40001 marcador permanente negro punta cincel 6mm caja 12 piezas", "AZOR", "oficina/papeleria/marcadores/permanentes/signal-xtra/negro/12-piezas", "accessories"],
  ["Tripp Lite SRCOOL7KDUCT ducto descarga SmartRack para SRCOOL7KRM", "TRIPP-LITE", "infraestructura/racks-accesorios/ventilacion/ductos-descarga/tripp-lite-srcool7kduct", "networking"],
  ["CT Cloud NCBU250 solucion de backup con licenciamiento 250GB", "CT CLOUD", "software/servicios-nube/ct-cloud/respaldo-nube/250gb", "software"],
  ["Mimosa Networks B11 radio backhaul PTP 10.0 11.7 GHz", "MIMOSA NETWORKS", "redes/radioenlaces-antenas/radios-backhaul/ptp-licenciados/mimosa-b11", "networking"],
  ["Adesso CyberTablet K10 tableta grafica 10 x 6 pulgadas", "ADESSO", "computo/perifericos/tabletas-digitalizadoras/adesso-cybertablet-k10", "accessories"],
  ["Lenovo 5WS0K76347 3Y Depot CCI upgrade from 1Y Depot CCI", "LENOVO", "servicios-ti/soporte-garantias/lenovo/depot-cci/3y-upgrade/5ws0k76347", "software"],
  ["MAE PH100B protector de hojas carta bolsa 100 piezas", "MAE", "oficina/papeleria/archivo/protectores-hojas/carta/100-piezas/mae-ph100b", "accessories"],
  ["TechZone TZKL703KD candado de seguridad Nano Lock para laptop", "TECHZONE", "accesorios/seguridad-fisica/candados-laptop/nano-lock/techzone-tzkl703kd", "accessories"],
  ["Azor 8350NE marcador Magistral Didactico negro para pizarron caja 12 piezas", "AZOR", "oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico/negro/12-piezas", "accessories"],
  ["Hillstone BDL1-A200-IN24 bundle de suscripciones A200 24 meses", "HILLSTONE", "software/licencias/seguridad-red/hillstone/a200/bdl1-24m", "software"],
  ["Dell N_OPTL1_N3_M3 OptiPlex 3000 3Y Basic Onsite a 3Y ProSupport Plus", "DELL", "servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-3000/3y-basic-a-3y-prosupport-plus", "software"],
  ["Cisco LIC-MX64-SEC-1YR Meraki MX64 Advanced Security License and Support 1 year", "CISCO", "software/licencias/seguridad-red/cisco-meraki/mx64/advanced-security-1y", "software"],
  ["CDP ES-AVR-612 SOL inversor UPS solar 400W MPPT 12V", "CDP", "energia/solar/inversores-ups/line-interactive/mppt-12v/cdp-es-avr-612-sol", "power"],
  ["Baseus P10111606213-00 Palm 1C cargador USB-C 30W blanco", "BASEUS", "energia/cargadores-usb/pared-usb-c/30w/baseus-palm-1c", "accessories"],
  ["StarTech GC9SM cambiador genero DB9 serial slimline macho macho", "STARTECH.COM", "accesorios/cables-adaptadores/serial-db9/cambiadores-genero/startech-gc9sm", "accessories"],
  ["Corsair HS35 Surround v2 CA-9011386-NA auriculares gamer alambricos", "CORSAIR", "audio/audifonos/diadema/gaming/alambricos/3-5mm-usb/corsair-hs35-surround-v2", "headphones"],
  ["ADATA CHARGERU-0653-QCPDWH cargador GaN 65W USB-C USB-A blanco", "ADATA", "energia/cargadores-usb/pared-usb-c-usb-a/65w-gan/adata-chargeru-0653-qcpdwh", "power"],
  ["Dell N_INSPNBL1_C1_U3 Inspiron 3000 1Y Carry-In a 3Y Premium Support Plus", "DELL", "servicios-ti/soporte-garantias/dell/premium-support-plus/inspiron-3000/1y-carry-in-a-3y-premium-support-plus", "software"],
  ["Topaz P-TS01-B pluma reemplazo SigLite con cable rizado", "TOPAZ", "punto-de-venta/digitalizadores-firma/accesorios/plumas/topaz-p-ts01-b", "accessories"],
  ["Meriva Streamax M6PIN DJ-TRANSFER cable 6 pines para MDVR MA16MAX", "MERIVA", "seguridad/cctv/accesorios-cableado/cables-camaras-moviles/streamax-m6pin-dj-transfer", "cameras"],
  ["GEO 004 caja para archivo carton carta 50x31x25 paquete 20 piezas", "GEO", "oficina/papeleria/archivo/cajas-archivo/carta/20-piezas/geo-004", "accessories"],
  ["Microsoft DG7GMGF0PN43:0002 Commercial Visio LTSC Professional 2024 CSP", "MICROSOFT", "software/licencias/microsoft/visio/ltsc-professional-2024-commercial", "software"],
  ["BACO G-1000 Superflex grapas estandar caja 1000 piezas", "BACO", "oficina/papeleria/engrapadoras-grapas/grapas-estandar/baco-g1000-1000p", "accessories"],
  ["Perfect Choice Evoir PC-117292 lentes inteligentes open ear polarizados", "PERFECT CHOICE", "audio/audifonos/wearables/lentes-inteligentes/perfect-choice-evoir", "headphones"],
  ["Logitech 939-001647 Rally Mic Pod Hub para microfonos videoconferencia", "LOGITECH", "computo/colaboracion/videoconferencia/accesorios/hubs-microfono/logitech-rally-mic-pod-hub", "audio"],
  ["Epson ELPLP75 V13H010L75 lampara para proyectores PowerLite", "EPSON", "audio-video/proyectores/accesorios/lamparas/epson-elplp75", "accessories"],
  ["Epson ELPLP71 V13H010L71 lampara de reemplazo PowerLite 475Wi", "EPSON", "audio-video/proyectores/accesorios/lamparas/epson-elplp71", "accessories"],
  ["Epson ELPLP76 V13H010L76 lampara de reemplazo PowerLite Pro", "EPSON", "audio-video/proyectores/accesorios/lamparas/epson-elplp76", "accessories"],
  ["BACO G-5000 Superflex 11039 grapas estandar caja 5040 piezas", "BACO", "oficina/papeleria/engrapadoras-grapas/grapas-estandar/baco-g5000-5040p", "accessories"],
  ["APC AP9335T NetBotz sensor de temperatura RJ-45 13 ft", "APC", "infraestructura/monitoreo-ambiental/sensores-temperatura/apc-ap9335t", "power"],
  ["Stylos STASWM3P smartwatch SW2 Bluetooth 4.0 rosa", "Stylos", "electronica/wearables/smartwatches/stylos-staswm3p", "accessories"],
  ["Dell N_ANWNBL1_C1_EC3 Alienware notebook 1Y Basic Carry-In a 3Y Elite Care", "DELL", "servicios-ti/soporte-garantias/dell/alienware-elite-care/notebooks/1y-basic-carry-in-a-3y", "software"],
  ["CyberPower BP72V60ART2U banco externo baterias 72V para OL2200RTXL2U", "CYBERPOWER", "energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/72v/cyberpower-bp72v60art2u", "power"],
  ["Kores 124029 lapiz adhesivo 40 g paquete con 6 piezas", "Kores", "oficina/papeleria/adhesivos/lapices-adhesivos/kores-124029-40g-6p", "accessories"],
  ["TechZone TZLBP27-A Backpack Max III mochila laptop 16 pulgadas", "TECHZONE", "computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas/techzone-max-iii", "accessories"],
  ["Azor Vision Plus 2625P resaltador pastel estuche 5 piezas", "AZOR", "oficina/papeleria/marcadores/resaltadores/surtidos/5-piezas/azor-vision-plus-2625p", "accessories"],
  ["Dell N_VOSDTM2_N1_N3 Vostro Desktop 3000 Basic NBD 1Y a 3Y", "DELL", "servicios-ti/soporte-garantias/dell/basic-nbd/vostro-3000/1y-a-3y", "software"],
  ["BIC 923997 Cristal Dura Plus boligrafo rojo mediano 1.0 caja 12", "BIC", "oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus-rojo-12-piezas", "accessories"],
  ["BACO 65483 crayones jumbo surtidos 12 piezas", "BACO", "oficina/papeleria/material-escolar/dibujo-arte/crayones/baco-jumbo-65483-12p", "accessories"],
  ["Tripp Lite SRCTMTFRM juego terminacion bastidor contencion pasillo", "TRIPP-LITE", "infraestructura/racks-accesorios/contencion-pasillos/kits-terminacion/tripp-lite-srctmtfrm", "networking"],
  ["PCM 10B24 papel bond plotter rollo 0.91 x 150 ACCPCM815", "PCM", "impresion/consumibles/papel-plotter/bond/rollos-91cm-150m/pcm-10b24", "printers_scanners"],
  ["Kensington K55805WW cojin de asiento espuma viscoelastica negro", "KENSINGTON", "oficina/ergonomia/cojines-asiento/espuma-viscoelastica/kensington-k55805ww", "accessories"],
] as const;

describe("manual taxonomy batches 160 plus", () => {
  it.each(batch160PlusCases)("%s -> %s", (name, brand, path, legacyCategory) => {
    const result = classifyManualCategory({ name, brand, category: "laptops" });
    expect(result.path).toBe(path);
    expect(result.legacyCategory).toBe(legacyCategory);
  });
});
