import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const researchedBatchCases = [
  ["Naceb Technology NA-0310R audifonos tipo diadema con microfono 3.5 mm rojo negro", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono"],
  ["Streamax ADPLUS 2.0-V1.1 MDVR dashcam vehicular 4G GPS Wi-Fi MOD4AMER33", "STREAMAX", "seguridad/cctv/camaras-moviles/mdvr/4g-gps"],
  ["Acteck TE-200 teclado estandar alambrico USB negro AC-928946", "ACTECK", "computo/perifericos/teclados/alambricos/usb"],
  ["Dell Pro 14 Plus laptop 14 pulgadas Core Ultra 7 266V 16GB Windows 11 Pro", "DELL", "computo/laptops/empresariales/14-pulgadas/dell-pro-14-plus"],
  ["Ocelot Gaming OMPXL01 mouse pad de tela extendido RGB con software", "OCELOT GAMING", "computo/accesorios/mousepads/gaming-rgb/extendidos"],
  ["Hisense ART121KAW minisplit inverter 1 tonelada 11500 BTU solo frio Wi-Fi", "HISENSE", "hogar/electrodomesticos/aires-acondicionados/minisplit/1-tonelada"],
  ["Hisense 40A45NV Smart TV LED 40 pulgadas Full HD VIDAA Wi-Fi", "HISENSE", "video/televisores/led-vidaa-tv/40-fhd"],
  ["Perfect Choice PC-085010 bolso crossbody para tablet 10.8 pulgadas azul", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/maletines-tablet/10-8-pulgadas"],
  ["TP-Link Omada ER605 router VPN Gigabit Multi-WAN SDN", "TP-LINK", "redes/routers/vpn/omada/er605"],
  ["Balam Rush GR Burst GR750G fuente ATX 750W 80 Plus Gold full modular", "BALAM RUSH", "computo/componentes/fuentes-poder/atx-80-plus-gold/750w"],
  ["Dahua DHI-USB-U106-20-16GB USB 2.0 Flash Drive 16GB MEMNCB020", "DAHUA TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/16gb/metalicas"],
  ["Dahua DH-PFM800-E balun pasivo HDCVI 1080p ACCDAH650", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-cableado/baluns-video/hdcvi-1080p"],
  ["Dahua DHI-USB-U106-20-8GB USB 2.0 Flash Drive 8GB MEMNCB010", "DAHUA TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/8gb/metalicas"],
  ["TP-Link TL-WR840N router Wi-Fi N300 2.4GHz ROUTPL560", "TP-LINK", "redes/routers/wifi-n/n300"],
  ["Dahua DH-PFM979-1S4P divisor alimentacion DC 1 a 4 CCTV", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-cableado/conectores-corriente/divisores-energia-dc"],
  ["Brother BT5001Y botella tinta amarilla 48.8 ml 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-bt5001/amarillo"],
  ["Logitech M90 910-004053 mouse USB alambrico 1000 DPI negro", "LOGITECH", "computo/perifericos/mouse/alambricos/basicos/1000-dpi"],
  ["Stylos ST100 STMUSB2B memoria USB 16GB USB 2.0 plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/16gb/metalicas"],
  ["Epson T504420-AL botella tinta amarilla 504 EcoTank 70 ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t504/amarillo"],
  ["TP-Link TL-WA850RE extensor Wi-Fi N300 2.4GHz", "TP-LINK", "redes/extensores-wifi/n300"],
  ["ADATA C008 AC008-16G-RKD memoria USB 2.0 retractil 16GB negro", "ADATA", "computo/almacenamiento/memorias-flash/usb/16gb/retractiles"],
  ["Epson T504120-AL botella tinta negra 504 EcoTank 127 ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t504/negro"],
  ["Xerox Marathon 003M02051 papel bond carta 5000 hojas 70 g", "XEROX", "oficina/papel-consumibles/papel-bond/carta/5000-hojas"],
  ["Perfect Choice PC-030331 E-Duster aire comprimido 230 g", "PERFECT CHOICE", "computo/accesorios/limpieza/aire-comprimido/e-duster"],
  ["Brother DCP-T530DW multifuncional tinta continua duplex Wi-Fi", "BROTHER", "impresion/impresoras/multifuncionales-tinta-continua/brother-dcp"],
  ["Koblenz RS-1410 regulador voltaje AVR 1410VA 700W 8 contactos", "KOBLENZ", "energia/supresores-reguladores/reguladores-voltaje/avr/1410va"],
  ["Brother DCP-T730DW multifuncional tinta continua duplex Wi-Fi 23 ppm", "BROTHER", "impresion/impresoras/multifuncionales-tinta-continua/brother-dcp"],
  ["Epson T544120-AL botella tinta negra Dye EcoTank L3110 65 ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t544/negro"],
  ["LG 24U411A-B.AWMQ monitor 23.8 FHD IPS 120Hz HDR10", "LG", "computo/monitores/oficina/24-fhd-120hz"],
  ["PCM T8070S rollo termico 80 x 70 mm paquete 50", "PCM", "punto-de-venta/consumibles/rollos-termicos/80x70"],
  ["Dell KM3322W 580-AKCU combo teclado y mouse inalambrico espanol", "DELL", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos"],
  ["Kingston DataTraveler Exodia M DTXM/64GB USB 3.2 retractil azul", "KINGSTON TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/64gb/retractiles"],
  ["Mercusys MW150US adaptador nano USB Wi-Fi N150 150Mbps", "MERCUSYS", "redes/adaptadores-wifi/usb/n150-nano"],
  ["Nextep NE-528 rollo termico 57 x 40 mm paquete 10", "NEXTEP", "punto-de-venta/consumibles/rollos-termicos/57x40"],
  ["Dell KM300C 580-AKKW combo teclado y mouse USB espanol", "DELL", "computo/perifericos/combos-teclado-mouse/alambricos/basicos"],
  ["Intellinet 210591 jack keystone RJ45 Cat6 blanco de impacto", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat6"],
  ["Xerox Ecologico papel bond carta 5000 hojas 75 g 93 blancura", "XEROX", "oficina/papel-consumibles/papel-bond/carta/5000-hojas/ecologico"],
  ["Brother BTD100M botella de tinta magenta 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/magenta"],
  ["ADATA UV250 AUV250-16G-RBK memoria USB 2.0 16GB plata", "ADATA", "computo/almacenamiento/memorias-flash/usb/16gb/metalicas"],
  ["Brother BTD100Y botella de tinta amarilla 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/amarillo"],
  ["Stylos STMUSB3B memoria USB 2.0 32GB plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/32gb/metalicas"],
  ["Dell KB216 teclado alambrico USB ingles negro", "DELL", "computo/perifericos/teclados/alambricos/usb/ingles"],
  ["Samsung Galaxy Tab A11 Enterprise Edition 8.7 pulgadas 4GB 64GB Wi-Fi", "SAMSUNG", "computo/tabletas/android/8-pulgadas/enterprise"],
  ["Brother BTD100C botella de tinta cian 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/cian"],
  ["TP-Link LS1005G LiteWave switch gigabit no administrable 5 puertos", "TP-LINK", "redes/switches/no-administrables/gigabit/5-puertos"],
  ["Brother BT5001C botella de tinta cian 48.8 ml 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-bt5001/cian"],
  ["Brother BTD100BK botella de tinta negra 7500 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/negro"],
  ["Nextep NE-529 rollo termico 80 x 70 mm paquete 5", "NEXTEP", "punto-de-venta/consumibles/rollos-termicos/80x70"],
  ["TP-Link Tapo C500 camara Wi-Fi exterior 360 1080p IP65", "TP-LINK", "seguridad/cctv/camaras-ip-wifi/pt-exterior/2mp"],
  ["Dell MS116 mouse USB optico alambrico 1000 DPI negro", "DELL", "computo/perifericos/mouse/alambricos/basicos/1000-dpi"],
  ["Epson ERC-38B cinta negra para miniprinter TM-U200", "EPSON", "impresion/consumibles/cintas-matriz-punto/epson-erc-38"],
  ["Lexar JumpDrive V40 LJDV40-32GAB memoria USB 2.0 32GB negra", "LEXAR", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Brobotix 497202 mouse basico USB optico negro 3 botones", "BROBOTIX", "computo/perifericos/mouse/alambricos/basicos"],
  ["Perfect Choice PC-034087 alcohol isopropilico antiestatico 250 ml", "PERFECT CHOICE", "computo/accesorios/limpieza/alcohol-isopropilico"],
  ["TP-Link UB500 adaptador nano USB Bluetooth 5.0", "TP-LINK", "redes/adaptadores-bluetooth/usb"],
  ["Logitech M170 mouse inalambrico gris 1000 DPI", "LOGITECH", "computo/perifericos/mouse/inalambricos/basicos/1000-dpi"],
  ["Provision ISR PTR-102VP-HD+ video balun energia 4 en 1", "PROVISION ISR", "seguridad/cctv/accesorios-cableado/baluns-video/video-poder"],
  ["Stylos STMUSB4B memoria USB 2.0 64GB plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/64gb/metalicas"],
  ["HP GT53 1VV22AL botella de tinta negra", "HP", "impresion/consumibles/botellas-tinta/hp-gt53/negro"],
  ["Intellinet 163286 faceplate tapa keystone 1 perforacion blanco", "INTELLINET", "redes/cableado-estructurado/placas-keystone/1-puerto"],
  ["BRobotix 497264 mouse pad ultra delgado negro con bolsa", "BROBOTIX", "computo/accesorios/mousepads/basicos-ultradelgados"],
  ["Mercusys MW300UM adaptador mini USB Wi-Fi N300 300Mbps", "MERCUSYS", "redes/adaptadores-wifi/usb/n300-mini"],
  ["Perfect Choice PC-201038 teclado USB resistente a salpicaduras negro", "PERFECT CHOICE", "computo/perifericos/teclados/alambricos/usb/resistentes-salpicaduras"],
  ["TP-Link TL-WA855RE extensor Wi-Fi N300 2 antenas externas", "TP-LINK", "redes/extensores-wifi/n300"],
  ["TP-Link Archer T2U Nano adaptador USB Wi-Fi AC600 dual band", "TP-LINK", "redes/adaptadores-wifi/usb/ac600-nano"],
  ["HP Poly Blackwire 3220 8X228A6 diadema USB-C con adaptador USB-A", "PLANTRONICS", "audio/audifonos/usb/diadema-microfono"],
  ["BRobotix 500074N mouse pad ergonomico con gel negro", "BROBOTIX", "computo/accesorios/mousepads/ergonomicos-con-gel"],
  ["ADATA SU630 ASU630SS-480GQ-R SSD 480GB 2.5 SATA", "ADATA", "computo/almacenamiento/ssd/2-5-sata/480gb"],
  ["Intellinet 210737 jack keystone Cat6 azul de impacto", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat6"],
  ["Acteck Captive Lite CL185 monitor 18.5 HD 1366x768", "ACTECK", "computo/monitores/oficina/18-5-hd"],
  ["Manhattan 151467 convertidor HDMI a VGA bolsa", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Dell DW316 unidad DVD externa USB 884116288473", "DELL", "computo/almacenamiento/unidades-opticas/dvd-externas"],
  ["SanDisk Cruzer Blade 16GB memoria USB SDCZ50", "SANDISK", "computo/almacenamiento/memorias-flash/usb/16gb"],
  ["Provision ISR PR-12V3A fuente de poder CCTV 12V 3A", "PROVISION ISR", "seguridad/cctv/fuentes-poder/12v-3a"],
  ["IMOU IPC-PS8D-3V0 camara domo IP PoE 3MP", "IMOU", "seguridad/cctv/camaras-ip-poe/domo/3mp"],
  ["IMOU IPC-PS3D-3M0 camara bala IP PoE 3MP", "IMOU", "seguridad/cctv/camaras-ip-poe/bullet/3mp"],
  ["TP-Link Archer C50 router Wi-Fi AC1200 dual band", "TP-LINK", "redes/routers/wifi-5/ac1200"],
  ["Dell KM5221W kit teclado y mouse inalambrico espanol", "DELL", "computo/perifericos/combos-teclado-mouse/inalambricos/productividad"],
  ["Provision ISR PR-12V5A fuente de poder CCTV 12V 5A", "PROVISION ISR", "seguridad/cctv/fuentes-poder/12v-5a"],
  ["Naceb Technology NA-620 aire comprimido 440ml", "NACEB TECHNOLOGY", "computo/accesorios/limpieza/aire-comprimido/440ml"],
  ["Logitech K120 teclado USB alambrico negro", "LOGITECH", "computo/perifericos/teclados/alambricos/usb/basicos"],
  ["Logitech Media Combo MK120 kit teclado y mouse USB", "LOGITECH", "computo/perifericos/combos-teclado-mouse/alambricos/basicos"],
  ["TP-Link LS1008G switch gigabit 8 puertos no administrable", "TP-LINK", "redes/switches/no-administrables/gigabit/8-puertos"],
  ["ADATA UHS-I U1 microSD 64GB clase 10", "ADATA", "computo/almacenamiento/memorias-flash/microsd/64gb-clase-10"],
  ["TP-Link TL-WR850N router WISP N300 4 LAN", "TP-LINK", "redes/routers/wifi-n/n300"],
  ["SanDisk Cruzer Blade 32GB memoria USB 2.0 roja", "SANDISK", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Acteck Blazar Prime FT500P fuente ATX 500W AC-938143", "ACTECK", "computo/componentes/fuentes-poder/atx-500w"],
  ["Silimex 750300219663 removedor de polvo", "SILIMEX", "computo/accesorios/limpieza/removedores-polvo"],
  ["Epson T664320-AL tinta magenta para EcoTank", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t664/magenta"],
  ["Stylos STPMOT3B monitor 19 pulgadas 1440 x 900", "STYLOS", "computo/monitores/oficina/19-wxga"],
  ["Epson T664220-AL tinta cian para EcoTank", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t664/cian"],
  ["Epson T664420-AL tinta amarillo para EcoTank", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t664/amarillo"],
  ["Silimex Kit LCD Cleaner SLXLMP270 limpiador pantalla", "SILIMEX", "computo/accesorios/limpieza/limpiadores-pantalla/kits"],
  ["Brother MFC-T930DW multifuncional tinta continua duplex Wi-Fi", "BROTHER", "impresion/impresoras/multifuncionales-tinta-continua/brother-mfc"],
  ["Dell 580-ADRC teclado USB alambrico espanol", "DELL", "computo/perifericos/teclados/alambricos/usb/basicos"],
  ["Mercusys MW302R router Wi-Fi N300 multimodo", "MERCUSYS", "redes/routers/wifi-n/n300"],
  ["TP-Link Tapo C200 camara Wi-Fi PT 2MP 1080p", "TP LINK", "seguridad/cctv/camaras-ip-wifi/pt-interior/2mp"],
  ["Intellinet 163293 faceplate 2 perforaciones blanco", "INTELLINET", "redes/cableado-estructurado/placas-keystone/2-puertos"],
  ["Poly Blackwire 3315 76J12AA diadema USB-A monoaural", "PLANTRONICS", "audio/audifonos/usb/diadema-microfono/monoaurales"],
  ["Intellinet 210355 jack Cat5e keystone impacto blanco", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat5e"],
  ["Dahua HAC-B1A21N-U-IL-A camara bullet HDCVI 2MP dual light", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-dual-light"],
  ["Gigabyte H610M K DDR4 tarjeta madre Intel LGA1700", "GIGABYTE", "computo/componentes/tarjetas-madre/intel-lga1700"],
  ["ADATA AUV220-32G-RGNPK memoria USB 32GB USB 2.0", "ADATA", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Intellinet 790055 plug RJ45 Cat5e UTP multifilar 100 piezas", "INTELLINET", "redes/cableado-estructurado/conectores-rj45/cat5e"],
  ["Intellinet 502344 plug RJ45 Cat6 UTP multifilar 100 piezas", "INTELLINET", "redes/cableado-estructurado/conectores-rj45/cat6"],
  ["Forza NT-751 UPS 750VA 375W line interactive", "FORZA", "energia/no-breaks-ups/line-interactive/750va"],
  ["TP-Link TL-WN823N mini adaptador USB Wi-Fi N300", "TP LINK", "redes/adaptadores-wifi/usb/n300-mini"],
  ["HP GT52 M0H54AL botella de tinta cian", "HP", "impresion/consumibles/botellas-tinta/hp-gt52/cian"],
  ["TechZone TZMOU01 mouse alambrico USB 1000 DPI negro", "TECHZONE", "computo/perifericos/mouse/alambricos/basicos/1000-dpi"],
  ["ADATA AD4S320016G22-SGN SODIMM DDR4 16GB 3200MHz", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr4/16gb-3200"],
  ["TP-Link TL-SG108 switch gigabit no administrable 8 puertos", "TP-LINK", "redes/switches/no-administrables/gigabit/8-puertos"],
  ["Acteck Optimize MI240 mouse inalambrico 2.4GHz 1200 DPI negro", "ACTECK", "computo/perifericos/mouse/inalambricos/basicos/1200-dpi"],
  ["Xerox Digital Paper 003M02000 papel bond carta 75 g 5000 hojas", "XEROX", "oficina/papel-consumibles/papel-bond/carta/5000-hojas/digital-75g"],
  ["BROBOTIX 170120 adaptador DC hembra 5.5 x 2.1 mm CCTV", "BROBOTIX", "seguridad/cctv/accesorios-cableado/conectores-corriente/dc-hembra"],
  ["CDP RAVR1408 regulador automatico AVR 1410VA 700W 8 salidas", "CDP", "energia/supresores-reguladores/reguladores-voltaje/avr/1410va"],
  ["HP Series 3 Pro 324pv monitor 23.8 FHD 100Hz HDMI VGA", "HP", "computo/monitores/oficina/24-fhd-100hz"],
  ["HP Everyday 16 inch Laptop Backpack A08KLUT Odyssey Gray", "HP", "computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas"],
  ["Dahua DH-PFM979-DCS conector DC hembra 5.5 x 2.1 mm", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-cableado/conectores-corriente/dc-hembra"],
  ["Nextep NE-511 miniprinter termica POS 80mm USB RJ11 LAN", "NEXTEP", "punto-de-venta/impresoras-recibos/80mm-lan"],
  ["Smartbitt SBAVR1200S regulador AVR 1200VA 600W 4 contactos", "SMARTBITT", "energia/supresores-reguladores/reguladores-voltaje/avr/1200va"],
  ["Nextep NE-514 cajon de dinero RJ11 4 billetes 8 monedas", "NEXTEP", "punto-de-venta/cajones-dinero/metalicos/rj11/4-billetes-8-monedas"],
  ["ADATA C906 AC906-32G-RBK memoria USB 32GB USB 2.0 negra", "ADATA", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["SanDisk SSD Plus SDSSDA3N-1T00-G26 M.2 NVMe 1TB Gen3", "SANDISK", "computo/almacenamiento/ssd/m2-nvme/1tb-gen3"],
  ["Huawei WiFi AX3S PSDN-AX30-30 router Wi-Fi 6 AX3000", "HUAWEI", "redes/routers/wifi-6/ax3000"],
  ["Acteck Captive Vivid SP215 monitor 21.5 FHD 75Hz", "ACTECK", "computo/monitores/oficina/22-fhd-75hz"],
  ["PCM RDC110074EN35AJ27 ribbon cera basica 110mm x 74m azul", "PCM", "impresion/consumibles/cintas-etiquetas/transferencia-termica/ribbon-cera/basica/110mm-74m"],
  ["PCM RDC110450EN08AA63 ribbon cera premium 110mm x 450m azul", "PCM", "impresion/consumibles/cintas-etiquetas/transferencia-termica/ribbon-cera/premium/110mm-450m"],
  ["PCM RDC110450EN35AA63 ribbon cera basica 110mm x 450m azul", "PCM", "impresion/consumibles/cintas-etiquetas/transferencia-termica/ribbon-cera/basica/110mm-450m"],
  ["Perfect Choice PC-045137 Root Pro mouse inalambrico 1600 DPI", "PERFECT CHOICE", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi"],
  ["PCM RDC110074EN08AJ27 ribbon cera premium 110mm x 74m azul", "PCM", "impresion/consumibles/cintas-etiquetas/transferencia-termica/ribbon-cera/premium/110mm-74m"],
  ["ADATA UV220 AUV220-32G-RBKBL memoria USB 32GB negro azul", "ADATA", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Intel Core i5-14400 CM8071504821112 tray LGA1700", "INTEL", "computo/componentes/procesadores/intel-core-i5-lga1700"],
  ["Epson T664120-AL botella tinta negra 664 EcoTank 70ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t664/negro"],
  ["EZVIZ H8c 2K camara PTZ IP exterior Wi-Fi 3MP", "EZVIZ", "seguridad/cctv/camaras-ip-wifi/pt-exterior/3mp-2k"],
  ["Intel Laminar RM1 BXTSRM1 disipador CPU LGA1700 65W", "INTEL", "computo/componentes/enfriamiento/disipadores-cpu/intel-lga1700-65w"],
  ["Lenovo V14 G4 ABP 82YX0042LM Ryzen 5 7430U 14 FHD", "LENOVO", "computo/laptops/empresariales/14-pulgadas"],
  ["Perfect Choice Essential PC-044758 mouse inalambrico 1600 DPI", "PERFECT CHOICE", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi"],
  ["Acteck Blazar Evo FS500E ES-05002E fuente SFX 500W", "ACTECK", "computo/componentes/fuentes-poder/sfx-500w"],
  ["TP-Link Archer T3U adaptador USB Wi-Fi AC1300 MU-MIMO", "TP LINK", "redes/adaptadores-wifi/usb/ac1300-mini"],
  ["TP-Link Tapo C320WS camara Wi-Fi exterior 2K 4MP IP66", "TP LINK", "seguridad/cctv/camaras-ip-wifi/bullet-exterior/4mp-2k"],
  ["Manhattan 151993 adaptador DisplayPort macho a HDMI hembra pasivo", "MANHATTAN", "accesorios/cables-adaptadores/video-displayport-hdmi/adaptadores-pasivos"],
  ["TP-Link LiteWave LS1008 switch 8 puertos RJ45 10/100 no administrable", "TP LINK", "redes/switches/no-administrables/fast-ethernet/8-puertos"],
  ["TP-Link Archer C24 router Wi-Fi AC750 dual band WISP", "TP LINK", "redes/routers/wifi-5/ac750"],
  ["IMOU IPC-PS70FN-10M0 PS70F camara PT doble lente 10MP PoE", "IMOU", "seguridad/cctv/camaras-ip-poe/pt-doble-lente/10mp"],
  ["Samsung LS32H5000FFXZX Smart TV Monitor H5000 32 HD Tizen", "SAMSUNG", "video/televisores/led-tizen/32-hd"],
  ["Lenovo V15 G4 ABP 82YY0037LM Ryzen 5 7430U 16GB 512GB 15.6 FHD", "LENOVO", "computo/laptops/empresariales/15-6-pulgadas"],
  ["Nexxt AB361NXT12 patch cord Cat6 UTP RJ45 7ft gris", "NEXXT", "redes/cableado-estructurado/patch-cords/cat6/2-1m"],
  ["Canon GI-190 BK botella tinta negra 135ml MegaTank", "CANON", "impresion/consumibles/botellas-tinta-megatank/canon-gi190/negro"],
  ["TP-Link Archer T2U adaptador USB Wi-Fi AC600 dual band", "TP LINK", "redes/adaptadores-wifi/usb/ac600-mini"],
  ["Silimex Silimpo espuma limpiadora 454 ml", "SILIMEX", "computo/accesorios/limpieza/espumas-limpiadoras/454ml"],
  ["BRobotix 263564 soporte plegable de aluminio para laptop tablet 7 angulos", "BROBOTIX", "computo/accesorios/soportes-laptop/plegables"],
  ["ADATA UV240 AUV240-32G-RRD memoria USB 32GB roja", "ADATA", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Mercusys MW306R router inalambrico N300 2.4GHz multimodo", "MERCUSYS", "redes/routers/wifi-n/n300"],
  ["Dell SE2426H 210-BTTL monitor 23.8 FHD IPS 144Hz", "DELL", "computo/monitores/oficina/24-fhd-144hz"],
  ["Kingston DataTraveler Exodia S DTXS/256GB memoria USB 3.2 naranja", "KINGSTON TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/256gb"],
  ["ASUS ExpertBook BM1403CDA-R58G512-P2 laptop 14 Ryzen 5 7535HS Windows 11 Pro", "ASUS BUSINESS", "computo/laptops/empresariales/14-pulgadas/asus-expertbook"],
  ["Provision ISR PR-CA20 cable siames coaxial CCTV BNC DC 20 metros", "PROVISION ISR", "seguridad/cctv/cable-coaxial-siames/20m"],
  ["Manhattan 162272 mini hub USB-A 4 puertos negro", "MANHATTAN", "computo/accesorios/hubs-usb/usb-a/4-puertos"],
  ["Perfect Choice PC-034094 alcohol isopropilico antiestatico 1 litro", "PERFECT CHOICE", "computo/accesorios/limpieza/alcohol-isopropilico/1l"],
  ["Dahua DH-PFM350-360-A UPS line-interactive 600VA 360W 4 salidas", "DAHUA TECHNOLOGY", "energia/no-breaks-ups/line-interactive/600va"],
  ["Dahua Picoo A59U-DA camara PT WiFi exterior 5MP dual light", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-wifi/pt-exterior/5mp-dual-light"],
  ["IMOU IPC-PS8D-5V0 camara domo PoE 5MP smart color vision", "IMOU", "seguridad/cctv/camaras-ip-poe/domo/5mp-dual-light"],
  ["Gigabyte A520M K motherboard AMD AM4 micro ATX DDR4", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am4/a520m"],
  ["Nextep NE-510 mini impresora termica POS 58mm USB", "NEXTEP", "punto-de-venta/impresoras-recibos/58mm-usb"],
  ["ADATA XPG SX8200 Pro ASX8200PNP-512GT-C SSD M.2 NVMe 512GB Gen3", "ADATA", "computo/almacenamiento/ssd/m2-nvme/512gb-gen3"],
  ["CDP R2C-AVR1008 regulador de voltaje AVR 1000VA 500W 8 contactos", "CDP", "energia/supresores-reguladores/reguladores-voltaje/avr/1000va"],
  ["TP-Link TL-WN881ND adaptador WiFi PCI Express N300", "TP LINK", "redes/adaptadores-wifi/pcie/n300"],
  ["Kingston A400 KC-S44480-7S SA400S37 480GB SSD 2.5 SATA", "KINGSTON TECHNOLOGY", "computo/almacenamiento/ssd/2-5-sata/480gb"],
  ["TP-Link Tapo C310 camara WiFi exterior 3MP 2K IP66", "TP-LINK", "seguridad/cctv/camaras-ip-wifi/bullet-exterior/3mp-2k"],
  ["Dell WM126 mouse inalambrico optico USB 2.4GHz 1000 DPI", "DELL", "computo/perifericos/mouse/inalambricos/basicos/1000-dpi"],
  ["TP-Link UE300 adaptador USB 3.0 a Ethernet Gigabit RJ45", "TP LINK", "redes/adaptadores-ethernet/usb-gigabit"],
  ["IMOU IPC-PS3D-5M0 camara IP bala PoE exterior 5MP Smart Color", "IMOU", "seguridad/cctv/camaras-ip-poe/bullet/5mp-dual-light"],
  ["Dahua HFW1209CN-A-LED-S3 camara bala HDCVI 2MP full color", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-full-color"],
  ["Tenda N301 router Wi-Fi N300 2.4GHz 2 antenas", "TENDA", "redes/routers/wifi-n/n300"],
  ["Acteck Entry Optimize MA210 mouse alambrico 1200 DPI USB", "ACTECK", "computo/perifericos/mouse/alambricos/basicos/1200-dpi"],
  ["TP-Link TG-3468 tarjeta de red PCI Express Gigabit RJ45", "TP LINK", "redes/tarjetas-red/pcie/gigabit"],
  ["CyberPower CP1000AVRLCDa UPS line-interactive LCD 1000VA 600W", "CYBERPOWER", "energia/no-breaks-ups/line-interactive/1000va/lcd"],
  ["Nextep 8-040-1 folder Printeck carta crema paquete 100", "NEXTEP", "oficina/papel-consumibles/folders/carta/crema-100"],
  ["TP-Link Tapo C520WS camara Wi-Fi PT exterior 4MP 2K QHD", "TP LINK", "seguridad/cctv/camaras-ip-wifi/pt-exterior/4mp-2k"],
  ["Dell Pro 14 PC14250 laptop Core Ultra 7 255U 16GB 512GB", "DELL", "computo/laptops/empresariales/14-pulgadas/dell-pro"],
] as const;

describe("manual taxonomy researched post-100 batches", () => {
  it.each(researchedBatchCases)("%s -> %s", (name, brand, path) => {
    expect(classifyManualCategory({ name, brand, category: "laptops" }).path).toBe(path);
  });
});
