import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const batch160PlusCases = [
  ["SanDisk Portable SSD SDSSDE30-1T00-G26 1TB USB-C USB 3.2 Gen 2 800 MB/s", "SANDISK", "computo/almacenamiento/ssd/externos/usb-c/1tb/sandisk-portable", "storage"],
  ["Balam Rush Power Rush V2 silla gamer tela piel sintetica reclinable 135 120kg", "BALAM RUSH", "gaming/mobiliario/sillas-gamer/tela/reclinable-135-120kg", "gaming"],
  ["TP-Link TL-WN781ND adaptador Wi-Fi PCI Express N150 150Mbps", "TP LINK", "redes/adaptadores-wifi/pcie/n150", "networking"],
  ["Huawei BE3 53030CSM router Wi-Fi 7 BE3600 3570Mbps 2.5G negro", "HUAWEI", "redes/routers/wifi-7/be3600", "networking"],
  ["PCM EBA7670 rollo autocopiante 76 x 70 mm blanco amarillo paquete 50", "PCM", "punto-de-venta/consumibles/rollos-autocopia/76x70", "laptops"],
  ["Perfect Choice ClearBeat PC-117025 audifonos Bluetooth TWS con display USB-C negros", "PERFECT CHOICE", "audio/audifonos/bluetooth/tws/estuche-display", "headphones"],
  ["Hikvision CAMHKV2610 camara bala 5MP TurboHD exterior metal techo pared", "HIKVISION", "seguridad/cctv/camaras-turbohd/bullet/5mp", "cameras"],
  ["ADATA XPG Spectrix D35G AX4U320016G16A-SBKD35G memoria RAM DDR4 16GB 3200MHz RGB", "ADATA", "computo/componentes/memoria-ram/udimm-ddr4/16gb-3200", "components"],
  ["Hyundai Hy View HT34CGMBK01 monitor gaming curvo 34 UWQHD 180Hz negro", "HYUNDAI", "computo/monitores/gaming/ultrawide-curvos/34-uwqhd-180hz", "monitors"],
  ["Stylos ST300 STMUS316B memoria USB 16GB gris", "STYLOS", "computo/almacenamiento/memorias-flash/usb/16gb", "storage"],
  ["Manhattan 353274 cable HDMI alta velocidad con Ethernet 7.5 m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/7-5m", "accessories"],
  ["Brother TN229Y toner amarillo rendimiento estandar 1200 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-229/amarillo", "printers_scanners"],
  ["Lenovo ThinkVision T22i-30 63B0MAR6LA monitor 21.5 FHD IPS 60Hz", "LENOVO", "computo/monitores/oficina/22-fhd-60hz", "monitors"],
  ["Manhattan MW3050 190312 mouse inalambrico USB 1200 DPI negro", "MANHATTAN", "computo/perifericos/mouse/inalambricos/basicos/1200-dpi", "accessories"],
  ["Poly Studio V12 A9DD8AA#ABM barra de video USB 4K 20MP", "POLYCOM", "colaboracion/video-conferencia/barras-video/usb-4k", "accessories"],
  ["Provision ISR DMA-320IPEN-28-V4 camara domo IP PoE 2MP DDA2 microfono", "PROVISION-ISR", "seguridad/cctv/camaras-ip-poe/domo/2mp-analytics-mic", "cameras"],
  ["Stylos STMS321B memoria microSDHC 32GB clase 10 con adaptador", "STYLOS", "computo/almacenamiento/memorias-flash/microsd/32gb-clase-10", "storage"],
  ["Intellinet 715072 charola rack 19 pulgadas 1U 300mm 25kg negra", "INTELLINET", "infraestructura/racks-accesorios/charolas/1u-300mm-25kg", "networking"],
  ["Quaroni QD4S08G1 memoria RAM SO-DIMM DDR4 8GB 3200MHz CL22", "QUARONI", "computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200", "components"],
  ["Logitech G923 TRUEFORCE volante y pedales racing PS5 PS4 PC", "LOGITECH", "gaming/accesorios/volantes-simulacion/trueforce", "gaming"],
  ["Nexxt Solutions Home NHE-S100 interruptor inteligente Wi-Fi monopolar blanco", "NEXXT SOLUTIONS HOME", "hogar/casa-inteligente/interruptores-wifi/monopolares", "accessories"],
  ["Manhattan 152082 tarjeta serial PCI Express 2 puertos DB9", "MANHATTAN", "computo/componentes/tarjetas-expansion/serial-pcie/db9-2-puertos", "components"],
  ["Kensington K55256WW MagPro filtro de privacidad magnetico para laptop 16 16:10", "KENSINGTON", "computo/accesorios/filtros-privacidad/laptops/16-16-10", "accessories"],
  ["Koblenz 9022 USB no break interactivo 900VA 450W LCD", "KOBLENZ", "energia/no-breaks-ups/line-interactive/900va/lcd", "power"],
  ["Polaroid PASU100-63 rollo papel sublimacion 100gsm 63in x 100m blanco", "POLAROID", "impresion/consumibles/papel-sublimacion/rollos/63in-100m-100gsm", "printers_scanners"],
  ["PCM 50000B0160A etiquetas transferencia termica 4x2 R-700 caja 12 rollos", "PCM", "impresion/consumibles/etiquetas-transferencia-termica/4x2/r-700-12-rollos", "printers_scanners"],
  ["Brother TN890 toner negro ultra alto rendimiento 20000 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother/tn-890", "printers_scanners"],
  ["ADATA Premier Pro AUSDX128GUI3V30SA2-RA1 microSDXC 128GB UHS-I V30 A2 con adaptador", "ADATA", "computo/almacenamiento/memorias-flash/microsd/128gb-uhs-i-v30-a2", "storage"],
  ["Manhattan 371377 cable VGA SVGA HD15 macho macho 11m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-vga/hd15/11m", "accessories"],
  ["Brother TZe-641 cinta laminada P-touch 18mm x 8m negro sobre amarillo", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-tze/laminadas/18mm/negro-sobre-amarillo", "printers_scanners"],
  ["Hyundai HYtab Plus 8WB1 HT8WB1RBK02A tablet 8 pulgadas Wi-Fi negra", "HYUNDAI", "computo/tabletas/android/8-pulgadas", "tablets"],
  ["Lenovo B210 4X40T84059 mochila para laptop 15.6 pulgadas negra", "LENOVO", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6", "accessories"],
  ["Brobotix 030570 cable extension USB-A 2.0 macho a hembra 4.9 m negro", "BROBOTIX", "accesorios/cables-adaptadores/usb/extensiones/5m", "accessories"],
  ["Mirati MSL02 cerradura inteligente Wi-Fi con huella RFID teclado y llave", "MIRATI", "seguridad/control-acceso/cerraduras-inteligentes/huella-rfid-wifi", "security"],
  ["GHIA Vector Plus GVPN tablet Android 13 10.1 pulgadas 4GB 64GB negra", "GHIA", "computo/tabletas/android/10-1-pulgadas", "tablets"],
  ["Intellinet 319874 patch cord Cat5e UTP RJ45 7.5 m azul", "INTELLINET", "redes/cableado-estructurado/patch-cords/cat5e/7-5m", "networking"],
  ["Stylos STPKTM3B combo teclado y mouse inalambrico USB negro 105 teclas", "STYLOS", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Acteck Captive Brite CB195 AC-939409 monitor 19.5 pulgadas TN HD HDMI VGA negro", "ACTECK", "computo/monitores/oficina/19-5-hd", "monitors"],
  ["TP-Link LS108G switch no administrable Gigabit de 8 puertos", "TP LINK", "redes/switches/no-administrables/gigabit/8-puertos", "networking"],
  ["Getttech GAC-24404P mouse ergonomico inalambrico 2.4GHz 1600 DPI rosa", "GETTTECH", "computo/perifericos/mouse/inalambricos/ergonomicos/1600-dpi", "accessories"],
  ["Naceb NA-0145 cargador de pared GaN 100W 2 USB-C 1 USB-A negro", "NACEB TECHNOLOGY", "energia/cargadores-usb/pared-gan/100w", "accessories"],
  ["Meriva MOB-202FS4D camara IP bullet 2MP PoE iluminacion dual microfono", "MERIVA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/bullet/2mp-dual-light-mic", "cameras"],
  ["Targus ASP61LA candado de seguridad T-Lock con combinacion 1.5 m negro", "TARGUS", "accesorios/seguridad-fisica/candados-laptop/combinacion", "accessories"],
  ["Epson EcoTank L14150 multifuncional A3 Plus Wi-Fi tinta continua", "EPSON", "impresion/impresoras/multifuncionales-ecotank/a3-plus", "printers_scanners"],
  ["Getttech GUE-MSSBT-01-YW audifonos deportivos Bluetooth negros", "GETTTECH", "audio/audifonos/bluetooth/deportivos/oreja-abierta", "headphones"],
  ["Complet XPower ERV-9-001 regulador 1300VA 650W con supresor 8 contactos", "COMPLET", "energia/reguladores/supresor-picos/1300va", "power"],
  ["Thermaltake Toughpower GF1 PS-TPD-0850FNFAGU-H fuente ATX 850W 80 Plus Gold modular", "THERMALTAKE", "computo/componentes/fuentes-poder/atx-80-plus-gold/850w/modular", "components"],
  ["Vica VIC12-9A bateria sellada VRLA 12V 9Ah para UPS", "VICA", "energia/baterias-ups/selladas-12v/9ah", "power"],
  ["HiLook by Hikvision HL1080PS(C) kit TurboHD DVR 4 canales 4 camaras 2MP", "HIKVISION", "seguridad/cctv/kits-turbohd/4-canales/4-camaras-2mp", "cameras"],
  ["Kyocera TK-582C 1T02KTCUS0 toner cian original", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/cian", "printers_scanners"],
  ["Acteck Captive Vivid SP215 AC-933858 monitor 21.5 FHD 75Hz negro", "ACTECK", "computo/monitores/oficina/22-fhd-75hz", "monitors"],
  ["Complet RPLUS 2000 ERV-6-012 regulador de voltaje 2000VA 1000W", "COMPLET", "energia/supresores-reguladores/reguladores-voltaje/avr/2000va", "power"],
  ["Manhattan 307178 cable USB 2.0 A macho a Micro-B macho 1.8 m negro", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-micro-b/2-0-1-8m", "accessories"],
  ["Perfect Choice PC-331148 transmisor Bluetooth FM para auto con 2 USB", "PERFECT CHOICE", "audio/accesorios/transmisores-fm/bluetooth-12v", "audio"],
  ["Vorago Slimbay A 5 N4020-NOS-5 PC Celeron N4020 8GB 240GB SSD", "VORAGO", "computo/desktops/slim/celeron-n4020-8gb-240gb", "desktops"],
  ["TP-Link Tapo C310 camara Wi-Fi exterior 2K IP66 microSD", "TP LINK", "seguridad/cctv/camaras-ip-wifi/bullet-exterior/3mp-2k", "cameras"],
  ["Xerox 006R04644 toner negro extra alta capacidad 25000 paginas C620 C625", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04644-negro", "printers_scanners"],
  ["Smartbitt SBOL10KRTG1-2 UPS online doble conversion 10kVA 10kW rack torre", "SMARTBITT", "energia/no-breaks-ups/doble-conversion/rack-torre/10000va", "power"],
  ["Ocelot Gaming OEL360 enfriamiento liquido AIO 360mm ARGB negro", "OCELOT GAMING", "computo/componentes/enfriamiento/liquido-cpu/360mm/argb", "components"],
  ["Naceb Technology NA-0313A audifonos diadema alambricos 3.5mm azul verde", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono", "headphones"],
  ["Intellinet 340373 Cable Patch Cat6 UTP RJ45 1 m gris", "INTELLINET", "redes/cableado-estructurado/patch-cords/cat6/1m", "networking"],
  ["Samsung Essential Monitor S3 LS22D300GALXZX 22 in Full HD IPS 100Hz", "SAMSUNG", "computo/monitores/oficina/22-fhd-100hz", "monitors"],
  ["Huawei MateBook D 16 53014MSJ Core i5-13420H 16GB 1TB SSD 16 in", "HUAWEI", "computo/laptops/consumo/16-pulgadas/huawei-matebook-d16", "laptops"],
  ["ASUS TUF Gaming A520M-PLUS WiFi Motherboard Micro-ATX AM4 DDR4", "ASUS", "computo/componentes/tarjetas-madre/amd-am4/a520m", "components"],
  ["Ghia GT4000BB Kit Teclado y Mouse Inalambrico USB Negro", "GHIA", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Synology Plus Series HAT3320-8T Disco Duro NAS 8TB SATA 3.5 in", "SYNOLOGY", "computo/almacenamiento/discos-duros/3-5-sata/nas/8tb", "storage"],
  ["Xerox 006R04765 Toner Cyan Alta Capacidad para C410 C415 7000 Paginas", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04765-cian", "printers_scanners"],
  ["Intellinet 210478 Jack Modular Keystone Cat5e UTP Rojo", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat5e/rojo", "networking"],
  ["Yeyian Hussar Plus YCM-ASHUS-01 Gabinete Mid Tower ATX Negro", "YEYIAN", "computo/componentes/gabinetes/gaming/atx-mid-tower", "components"],
  ["Game Factor SMG500 Base Gamer para Monitor VESA hasta 27 in", "GAME FACTOR", "computo/accesorios/soportes-monitor/vesa/27-5kg", "accessories"],
  ["be quiet! Pure Loop 2 FX BW014 enfriamiento liquido AIO 280mm ARGB", "BE QUIET", "computo/componentes/enfriamiento/liquido-cpu/280mm/argb", "components"],
  ["Perfect Choice Bagiq PC-084273 funda de neopreno para laptop 15.6 pulgadas rosa", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas/neopreno", "accessories"],
  ["Logitech MX Mechanical teclado inalambrico iluminado mecanico grafito TECLOG1040", "LOGITECH", "computo/perifericos/teclados/inalambricos/mecanicos", "accessories"],
  ["Brother LC402XLY cartucho de tinta amarillo alto rendimiento 1500 paginas", "BROTHER", "impresion/consumibles/cartuchos-tinta/brother/lc402/amarillo-xl", "printers_scanners"],
  ["Lenovo ThinkPad Bluetooth Silent Mouse 4Y50X88823 2400 DPI negro", "LENOVO", "computo/perifericos/mouse/inalambricos/bluetooth/silenciosos", "accessories"],
  ["Nexxt Home NHE-T100 interruptor inteligente Wi-Fi de 3 circuitos blanco", "NEXXT SOLUTIONS HOME", "hogar/casa-inteligente/interruptores-wifi/3-circuitos", "accessories"],
  ["Hisense ARU122KAW minisplit inverter 12000 BTU frio calor 230V blanco", "HISENSE", "climatizacion/aires-acondicionados/minisplit/inverter/12000-btu", "accessories"],
  ["BRobotix 6005989 kit de limpieza 7 en 1 para audifonos y smartphones", "BROBOTIX", "computo/accesorios/limpieza/kits/telefonos-audifonos", "accessories"],
  ["ASUS TUF Gaming B550M-PLUS Wi-Fi motherboard micro ATX AM4", "ASUS", "computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx/wifi", "components"],
  ["CyberPower Smart App LCD OR500LCDRM1U UPS rack 1U 500VA 300W", "CYBERPOWER", "energia/no-breaks-ups/line-interactive/rack-1u/500va", "power"],
  ["Netis E3 AC1200 extensor de rango Wi-Fi dual band", "NETIS", "redes/extensores-wifi/dual-band/ac1200", "networking"],
  ["XFX Speedster SWFT 210 Radeon RX 7600 Core RX-76PSWFTFY 8GB GDDR6", "XFX", "computo/componentes/tarjetas-video/amd-radeon/rx-7000/rx-7600", "components"],
  ["BRobotix 170906 caja de mesa RJ45 Cat6 HDMI USB NEMA 5-15R negra", "BROBOTIX", "redes/cableado-estructurado/cajas-mesa/multimedia-rj45-hdmi-usb-corriente", "networking"],
  ["Tenda S105 switch no administrable Fast Ethernet 5 puertos 10/100 blanco", "TENDA", "redes/switches/no-administrables/fast-ethernet/5-puertos", "networking"],
  ["Silimex IsoPro 750300219690 alcohol isopropilico aerosol 250 ml", "SILIMEX", "computo/accesorios/limpieza/alcohol-isopropilico/250ml", "accessories"],
  ["Acteck Optimize Joy MI215 AC-933445 mouse inalambrico 1600 DPI negro", "ACTECK", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi", "accessories"],
  ["WAM WAM-RACK419 rack abierto de piso 25U 19 pulgadas acero negro", "WAM", "infraestructura/racks-enfriamiento/racks-piso/abiertos-25u", "networking"],
  ["Game Factor MPG500 mousepad gamer XL RGB 800 x 300 x 4 mm", "GAME FACTOR", "computo/accesorios/mousepads/gaming-rgb/extendidos", "accessories"],
  ["Zebra ZD220D impresora de etiquetas termica directa 4 pulgadas 203 dpi USB", "ZEBRA", "impresion/impresoras/etiquetas/termicas-directas/desktop-4-pulgadas", "printers_scanners"],
  ["Silimex 7503018454009 toallitas humedas limpiadoras Gamer 30 piezas", "SILIMEX", "computo/accesorios/limpieza/toallitas/gamer-30-piezas", "accessories"],
  ["Logitech M110 Silent 910-006757 mouse alambrico USB 1000 DPI gris", "LOGITECH", "computo/perifericos/mouse/alambricos/basicos/1000-dpi", "accessories"],
  ["Logitech Z207 bocinas Bluetooth 2.0 10W pico 5W RMS 3.5mm negras", "LOGITECH", "computo/perifericos/bocinas-audio/2-0", "headphones"],
  ["Dell Pro Max 16 Core Ultra 9 285H 32GB 1TB RTX PRO 2000 Blackwell", "DELL", "computo/laptops/workstations/16-pulgadas/dell-pro-max-16", "laptops"],
  ["Uniarch NVR-104E2-P4 NVR 4 canales PoE Ultra265 HDMI 4K", "UNIARCH", "seguridad/cctv/dvr-nvr/nvr-poe", "cameras"],
  ["Perfect Choice Meucci PC-117223 manos libres Bluetooth 20h USB-C", "PERFECT CHOICE", "audio/audifonos/bluetooth/monoaurales-uc", "headphones"],
  ["LG UltraGear 24GS60F-B monitor gaming 24 FHD IPS 180Hz 1ms", "LG", "computo/monitores/gaming/24-fhd/180hz", "monitors"],
  ["Naceb Gaming NA-0122 cable HDMI 2.1 3m 8K 48Gbps eARC", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad/3m", "accessories"],
  ["BRobotix 651855 funda City poliester gris para laptop 15.6 pulgadas", "BROBOTIX", "computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas", "accessories"],
  ["Generico cargador compatible Dell 65W 19.5V 3.34A punta 4.5 x 3.0", "GENERICO", "computo/accesorios/cargadores-laptop/compatibles-dell/65w-19-5v-4-5x3-0", "laptops"],
  ["Grandstream GRP2602P telefono IP 2 lineas 4 cuentas SIP PoE", "GRANDSTREAM", "telefonia/telefonos-ip/escritorio/2-lineas/poe", "networking"],
  ["DBUGG DB-USB-SE12 memoria USB 128GB USB-A plata", "DBUGG", "computo/almacenamiento/memorias-flash/usb/128gb", "storage"],
  ["Logitech Signature M650 L mouse inalambrico Bluetooth Logi Bolt grafito", "LOGITECH", "computo/perifericos/mouse/inalambricos/productividad", "accessories"],
  ["Acteck Flux Core EC303HR silla ergonomica de oficina malla gris", "ACTECK", "oficina/mobiliario-accesorios/sillas-oficina/ergonomicas-malla", "accessories"],
  ["Epson EcoTank L8180 C11CJ21301 multifuncional fotografica A3 Plus 6 tintas", "EPSON", "impresion/impresoras/multifuncionales-ecotank/fotografica-a3-plus", "printers_scanners"],
  ["Necnon NSG-RGB-1 silla gamer RGB reclinable 145 grados negra", "NECNON", "gaming/mobiliario/sillas-gamer/rgb", "gaming"],
  ["Orvibo VS10ZW-1UO miniHub Zigbee Wi-Fi 2.4GHz blanco", "ORVIBO", "domotica/hubs/zigbee", "accessories"],
  ["BRobotix 6005835 audifonos Bluetooth TWS in-ear 5.3 blancos", "BROBOTIX", "audio/audifonos/bluetooth/tws/in-ear", "headphones"],
  ["Swann SWDVK-846806MQB-US kit DVR 8 canales 6 camaras 1080p 1TB", "SWANN", "seguridad/cctv/kits-dvr/8-canales/6-camaras-1080p", "cameras"],
  ["be quiet! Light Base 600 LX White gabinete ATX panoramico ARGB", "BE QUIET", "computo/componentes/gabinetes/gaming/atx-mid-tower/panoramicos-argb", "components"],
  ["Generico AP2-60W cargador Apple MagSafe 2 60W 16.5V 3.65A blanco", "GENERICO", "computo/accesorios/cargadores-laptop/apple-magsafe-2/60w", "laptops"],
  ["LG VO182H1 Smart Inverter Minisplit 1.5 toneladas frio calor 18000 BTU 230V", "LG", "climatizacion/aires-acondicionados/minisplit/inverter/18000-btu", "accessories"],
  ["UNV IPC3616SB-ADF28KMC-I1 camara IP turret ColorHunter Wise-ISP 6MP 2.8mm PoE", "UNV", "seguridad/cctv/camaras-ip-poe/turret/6mp-dual-light", "cameras"],
  ["Perfect Choice PC-171652 hub USB-C 4 puertos negro", "PERFECT CHOICE", "computo/accesorios/docks-hubs/usb-c", "accessories"],
  ["Vorago AU-600 cargador de pared USB-C PD 100W 5 puertos", "VORAGO", "energia/cargadores-usb/pared-usb-c/100w-multipuerto", "accessories"],
  ["Bixolon SPP-R310 impresora movil termica 3 pulgadas para recibos y etiquetas", "BIXOLON", "impresion/impresoras/etiquetas/termicas-moviles", "printers_scanners"],
  ["Balam Rush Eolox Blaze EX50KW kit 3 ventiladores ARGB 120mm blancos", "BALAM RUSH", "computo/componentes/enfriamiento/ventiladores-gabinete/120mm-argb", "components"],
  ["Complet Tulum 1500 no-break UPS 1500VA 750W 10 contactos", "COMPLET", "energia/no-breaks-ups/line-interactive/1500va", "power"],
  ["Logitech G309 LIGHTSPEED mouse gaming inalambrico Bluetooth blanco", "LOGITECH", "computo/perifericos/mouse/inalambricos/gaming", "accessories"],
  ["Dahua DH-HAC-HFW1239TLMN-A-LED-0360B camara bullet HDCVI Full Color 2MP 3.6mm con microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-full-color", "cameras"],
  ["Kyocera TK-5282K toner negro original rendimiento 13000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5282k", "printers_scanners"],
  ["Manhattan 461481 soporte de pared inclinable TV 37 a 80 pulgadas 80 kg", "MANHATTAN", "video/soportes-tv/pared/inclinables-37-80-80kg", "tvs"],
  ["Ghia GCD581 cajon de dinero metalico RJ11 5 billetes 8 monedas negro", "GHIA", "punto-de-venta/cajones-dinero/metalicos/rj11/5-billetes-8-monedas", "accessories"],
  ["Ovaltech OTHHT03XL bateria para laptop HP 11.55V 41Wh 3 celdas", "OVALTECH", "computo/accesorios/baterias-laptop/hp/ht03xl", "laptops"],
  ["CyberPower CPS1215RM PDU rack 1U 15A 10 contactos NEMA 5-15R", "CYBERPOWER", "energia/pdu-rack/1u-15a-10-contactos", "power"],
  ["Ultimate Ears WONDERBOOM 4 bocina Bluetooth portatil IP67 14h azul", "ULTIMATE EARS", "audio/bocinas/bluetooth/portatiles/ip67", "audio"],
  ["Naceb NA-632 mouse gaming alambrico USB con mousepad 1200 DPI negro", "NACEB TECHNOLOGY", "gaming/accesorios/mouse-y-mousepad", "gaming"],
  ["Ovaltech OVMDP-VGA adaptador Mini DisplayPort a VGA blanco", "OVALTECH", "accesorios/cables-adaptadores/video-displayport-vga/mini-displayport", "accessories"],
  ["Uniarch IPC-B233-APF40W camara IP bullet Dual-light 3MP 4mm PoE", "UNIARCH", "seguridad/cctv/camaras-ip-poe/bullet/3mp-dual-light", "cameras"],
  ["Omada ER7206 gateway VPN Gigabit multi-WAN SFP USB", "OMADA", "redes/routers/vpn/omada/er7206", "networking"],
  ["Necnon NB-08Y bafle Bluetooth inalambrico 8 pulgadas LED con microfono", "NECNON", "audio/bocinas/bafles-portatiles/8-pulgadas", "audio"],
  ["Dahua HAC-HFW1200T camara bullet HDCVI 2MP 3.6mm IR IP67", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-ir-ip67", "cameras"],
  ["Balam Rush Tank Mini GI930 gabinete gamer Micro-ATX mini tower ARGB negro", "BALAM RUSH", "computo/componentes/gabinetes/gaming/micro-atx/mini-tower-argb", "components"],
  ["Provision ISR DB-320WIPN videoportero IP WiFi PoE 2MP ONVIF", "PROVISION-ISR", "seguridad/videoporteros/ip/wifi-poe", "security"],
  ["BRobotix 6000380 duo pack lapiz stylus universal azul", "BROBOTIX", "computo/tabletas/accesorios/stylus/universales-duopack", "accessories"],
  ["Ghia Whale G43W25 Smart TV 43 pulgadas Full HD WiFi Bluetooth", "GHIA", "video/televisores/smart-tv/43-fhd", "tvs"],
  ["Naceb Silver Fang NA-0969 teclado gaming mecanico 75 por ciento RGB", "NACEB TECHNOLOGY", "computo/perifericos/teclados/gaming/mecanicos/75-rgb", "gaming"],
  ["Tenda IC7-PRS-4 camara IP concha PoE 4MP IR microfono", "TENDA", "seguridad/cctv/camaras-ip-poe/domo/4mp-ir-poe", "cameras"],
  ["Vorago CAB-M01W cable USB-A a Micro-USB 2.0 1m blanco", "VORAGO", "accesorios/cables-adaptadores/usb/usb-a-micro-b/2-0-1m", "accessories"],
  ["Smartbitt SBOL30KTII-3K UPS online trifasico 30kVA 30kW", "SMARTBITT", "energia/no-breaks-ups/doble-conversion/trifasicos/30000va", "power"],
  ["Naceb Boreal NA-0656N enfriamiento liquido AIO 360mm ARGB con pantalla", "NACEB GAMING", "computo/componentes/enfriamiento/liquido-cpu/360mm/argb-pantalla", "components"],
  ["Dahua DH-IPC-HFW1239S1-LED-S4 camara IP bullet Full-Color 2MP PoE 3.6mm", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/bullet/2mp-full-color", "cameras"],
  ["BRobotix 188533-2 kit teclado y mouse gaming USB alambrico RGB espanol", "BROBOTIX", "computo/perifericos/combos-teclado-mouse/gaming/alambricos-rgb", "gaming"],
  ["TP-Link TL-SL1226P switch PoE+ no administrable 24 puertos Fast Ethernet 250W", "TP LINK", "redes/switches/poe-no-administrables/fast-ethernet/24-puertos-250w", "networking"],
  ["Dahua HAC-HFW1200D-0360B camara bullet HDCVI IR 2MP 3.6mm 80m IP67", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-ir", "cameras"],
  ["Kingston KCP432SD8/16 memoria RAM SO-DIMM DDR4 16GB 3200MT/s CL22", "KINGSTON", "computo/componentes/memoria-ram/sodimm-ddr4", "components"],
  ["Dahua DH-IPC-T1E20 camara IP domo eyeball 2MP IR 30m PoE", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/domo/2mp-ir", "cameras"],
  ["UNV IPC2B24SA-AHDZK-PI-I1 camara IP bullet LightHunter 4MP varifocal PoE", "UNV", "seguridad/cctv/camaras-ip-poe/bullet/4mp-lighthunter-varifocal", "cameras"],
  ["Grandstream UCM6304 PBX IP 2000 usuarios 4 FXS 4 FXO", "GRANDSTREAM", "telefonia/pbx-ip/grandstream-ucm6300/4fxs-4fxo", "networking"],
  ["PCM 50000B0161A etiquetas termicas directas 4x6 pulgadas caja 12 rollos", "PCM", "impresion/consumibles/etiquetas-papel/termicas-directas/102x152mm", "printers_scanners"],
  ["BRobotix 810533 rack abierto 19 pulgadas 24U 1.20m con tornilleria M6", "BROBOTIX", "infraestructura/racks-enfriamiento/racks-piso/abiertos-24u", "networking"],
  ["Dahua DH-PFA134 caja de conexion para camaras CCTV blanca", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-montaje/cajas-conexion/dahua-pfa134", "cameras"],
  ["Vorago AU-402-WH cargador pared GaN 45W 2 USB-C blanco", "VORAGO", "energia/cargadores-usb/pared-gan/45w-dual-usb-c", "accessories"],
  ["UNV OEU-301S-HMKA kit videoportero IP departamental con monitor OEI-371S-H-W 7 pulgadas", "UNV", "seguridad/videoporteros/ip/kits-departamentales/7-pulgadas", "security"],
  ["Dahua DH-HAC-HFW1509TN-A-LED-0360B camara HDCVI bullet 5MP Full-Color microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/5mp-full-color-mic", "cameras"],
  ["Acteck BE220 Frezze Book Prime base enfriadora para laptop 15.5 pulgadas", "ACTECK", "computo/accesorios/soportes-laptop/bases-enfriadoras", "laptops"],
  ["Necnon NBAB042600 NBH-04 Pro audifonos Bluetooth over-ear radio FM MicroSD verdes", "NECNON", "audio/audifonos/bluetooth/diadema-over-ear/radio-fm-microsd", "headphones"],
  ["Kyocera TK-5292K toner negro original rendimiento 17000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5292k", "printers_scanners"],
  ["Tripp Lite N001-005-WH cable patch Cat5e UTP RJ45 5ft blanco", "TRIPP-LITE", "redes/cableado-estructurado/patch-cords/cat5e/1-5m-blanco", "networking"],
  ["Dell Premier KM7321W combo teclado y mouse inalambrico multi-dispositivo", "DELL", "computo/perifericos/combos-teclado-mouse/inalambricos/productividad", "accessories"],
  ["Redragon Hylas Lunar White H260-W headset gaming alambrico RGB 50mm", "REDRAGON", "gaming/audio/headsets/alambricos/rgb", "gaming"],
  ["Kensington K58352WW MagPro filtro de privacidad magnetico laptop 14 16:9", "KENSINGTON", "computo/accesorios/filtros-privacidad/laptops/14-16-9", "accessories"],
  ["Netis ST3126GS switch Gigabit no administrable 26 puertos 24 RJ45 2 SFP", "NETIS", "redes/switches/no-administrables/gigabit/26-puertos-sfp", "networking"],
  ["Stylos STMUS564B ST500 memoria USB 64GB USB-A 2.0 plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/64gb/usb-2-metalicas", "storage"],
  ["Necnon NBHK-PUG audifonos infantiles alambricos 3.5mm volumen seguro 95dB", "NECNON", "audio/audifonos/alambricos-3-5mm/infantiles", "headphones"],
  ["HPE Q2079A cinta LTO-9 Ultrium 45TB RW", "HEWLETT PACKARD ENTERPRISE", "computo/almacenamiento/cintas-lto/lto-9", "storage"],
  ["Perfect Choice PC-084761 mochila laptop Essential 17 pulgadas morada", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/mochilas-laptop/17-pulgadas", "accessories"],
  ["Kingston KCP432SS8/8 memoria RAM SO-DIMM DDR4 8GB 3200MT/s CL22", "KINGSTON", "computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200", "components"],
  ["Naceb Gaming NA-0972G teclado mecanico Red Phyton RGB switch Brown", "NACEB GAMING", "computo/perifericos/teclados/gaming/mecanicos/full-size-rgb", "gaming"],
  ["Dahua DH-HAC-HFW1801TN-A-0280B camara HDCVI bullet 8MP IR con microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/8mp-ir-mic", "cameras"],
  ["Forza HT-650LCD UPS line-interactive 650VA 390W con LCD", "FORZA", "energia/no-breaks-ups/line-interactive/650va/lcd", "power"],
  ["BRobotix 963579 convertidor USB-A a serial RS-232 DB9 macho 1.8m", "BROBOTIX", "accesorios/cables-adaptadores/usb-serial/db9-rs232", "accessories"],
  ["Smartbitt SBBA12-5 bateria sellada VRLA para UPS 12V 5Ah", "SMARTBITT", "energia/baterias-ups/selladas-12v/5ah", "power"],
  ["Ubiquiti UniFi U6 Pro access point Wi-Fi 6 AX5400 PoE techo", "UBIQUITI", "redes/access-points/wifi-6/techo/ax5400", "networking"],
  ["DataShield MI-4235 bateria AGM ciclo profundo solar 12V 100Ah", "DATASHIELD", "energia/baterias-solares/agm-ciclo-profundo/12v-100ah", "power"],
  ["Hyundai HYLine Pro HY65PA1402NABL smartphone Android 6GB 128GB azul", "HYUNDAI", "telefonia/smartphones/android/hyundai-hyline-pro/6gb-128gb", "smartphones"],
  ["Cooler Master Hyper 212 Spectrum V3 RR-S4NA-17PA-R1 disipador CPU ARGB", "COOLER MASTER", "computo/componentes/enfriamiento/disipadores-cpu/torre-120mm-argb", "components"],
  ["VICA Optima 1250 no-break line-interactive 1250VA 600W 6 contactos", "VICA", "energia/no-breaks-ups/line-interactive/1250va", "power"],
  ["Kaspersky Small Office Security KL4541Z5EFS 5 licencias 1 ano", "KASPERSKY", "software/seguridad/antivirus/kaspersky-small-office/5-licencias-1-ano", "software"],
  ["Kaspersky Next EDR Foundations KL4065ZAQFS 50-99 licencias 1 ano", "KASPERSKY", "software/seguridad/edr/kaspersky-next-edr-foundations/50-99-licencias-1-ano", "software"],
  ["Kingston A400 SA400S37/240G SSD SATA III 2.5 pulgadas 240GB", "KINGSTON", "computo/almacenamiento/ssd/2-5-sata/240gb", "storage"],
  ["Naceb NA-595AZ baston selfie para smartphone 18-74 cm azul plug 3.5 mm", "NACEB TECHNOLOGY", "foto-video/accesorios/selfie-sticks", "accessories"],
  ["Complet SIGNAL 3KT120M UPS online doble conversion 3000VA 3000W rack torre 120V", "COMPLET", "energia/no-breaks-ups/doble-conversion/rack-torre/3000va/120v", "power"],
  ["Naceb NA-0123 kit teclado y mouse inalambrico 2.4GHz espanol negro", "NACEB TECHNOLOGY", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos", "accessories"],
  ["Vorago PSU-101 fuente de poder ATX 500W no modular gris", "VORAGO", "computo/componentes/fuentes-poder/atx-500w", "components"],
  ["Ovaltech OTD6420 bateria Dell Latitude E5420 E6420 11.1V 6 celdas negra", "OVALTECH", "computo/accesorios/baterias-laptop/dell/latitude-e5420-e6420", "laptops"],
  ["Logitech G PRO X SUPERLIGHT 2 910-006629 mouse gamer inalambrico LIGHTSPEED negro 60g", "LOGITECH G", "computo/perifericos/mouse/inalambricos/gaming/esports-60g", "gaming"],
  ["Kyocera TK-5417Y toner amarillo original rendimiento 13000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera/tk-5417/amarillo", "printers_scanners"],
  ["Patriot Signature Premium PSP48G3200H1 memoria RAM DDR4 8GB 3200MHz CL22 UDIMM", "PATRIOT", "computo/componentes/memoria-ram/udimm-ddr4/8gb-3200", "components"],
  ["Redragon Storm Elite White M988W mouse gamer alambrico RGB Pixart P3389 32000 DPI", "REDRAGON", "computo/perifericos/mouse/alambricos/gaming/alto-dpi/32000-dpi", "gaming"],
  ["TP-Link Omada TL-SG3428X switch administrable L2+ JetStream 24 puertos Gigabit 4 SFP+ 10G", "TP LINK", "redes/switches/administrables/gigabit/24-puertos-4-sfp-plus", "networking"],
  ["Smartbitt SBEC-HD08M extension electrica uso rudo 8m 3 tomas naranja", "SMARTBITT", "energia/extensiones-electricas/uso-rudo", "power"],
  ["Perfect Choice Lusso PC-084464 mochila ejecutiva slim para laptop 15.6 pulgadas negra", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6/ejecutivas-slim", "accessories"],
  ["Brother PT-E110 rotuladora industrial portatil P-touch para cintas TZe hasta 12mm", "BROTHER", "impresion/rotuladoras/portatiles-industriales", "printers_scanners"],
  ["Brother TZe-221 cinta laminada P-touch 9mm x 8m negro sobre blanco", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-tze/laminadas/9mm/negro-sobre-blanco", "printers_scanners"],
  ["Manhattan 353595 cable DisplayPort 1.4 8K 60Hz macho-macho 1m negro", "MANHATTAN", "accesorios/cables-adaptadores/video-displayport/1m/8k", "accessories"],
  ["TechZone TZBE5B8M100 cajon electronico de dinero POS RJ11 5 billetes 8 monedas", "TECH ZONE POS", "punto-de-venta/cajones-dinero/metalicos/rj11/5-billetes-8-monedas", "accessories"],
  ["Honeywell Voyager 1400g lector codigo de barras 1D 2D area-imaging cableado USB", "HONEYWELL", "punto-de-venta/lectores-codigo-barras/2d-usb/area-imager", "accessories"],
  ["be quiet! Light Base 600 DX White gabinete panoramico ATX ARGB blanco BGW66", "BE QUIET", "computo/componentes/gabinetes/gaming/atx-mid-tower/panoramicos-argb/sin-ventiladores", "components"],
  ["Cisco CAB-AC-C5 cable alimentacion AC NEMA 5-15P a IEC C5", "CISCO", "redes/accesorios/cables-de-alimentacion/cisco-c5", "networking"],
  ["XPG GAMMIX S60 AGAMMIXS60-512G-CS SSD M.2 2280 PCIe Gen4 x4 NVMe 512GB", "ADATA", "computo/almacenamiento/ssd/m2-nvme/512gb-gen4", "storage"],
  ["Xerox 006R04824 toner cian estandar 1800 paginas para C320 C325", "XEROX", "impresion/consumibles/toner-laser/xerox/006r04824-cian", "printers_scanners"],
  ["Naceb NA-0110 adaptador USB-C macho a VGA hembra plata", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/video-usb-c-vga/usb-c-macho-vga-hembra", "accessories"],
  ["Eaton Tripp Lite ECO1300LCD no-break UPS line-interactive 1300VA 720W LCD 120V", "TRIPP LITE", "energia/no-breaks-ups/line-interactive/1300va/lcd", "power"],
  ["Cooler Master Mobius 120P ARGB MFZ-M2DN-24NP2-R1 ventilador 120mm PWM ARGB negro", "COOLER MASTER", "computo/componentes/enfriamiento/ventiladores-gabinete/120mm-pwm-argb", "components"],
  ["Manhattan 355247 cable USB-C a USB-C 2m USB 2.0 480Mbps 100W negro", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-c-c/2m", "accessories"],
  ["Bixolon XD5-40tK impresora de etiquetas 4 pulgadas transferencia termica 203 dpi USB negra", "BIXOLON", "impresion/impresoras/etiquetas/transferencia-termica/desktop-4-pulgadas", "printers_scanners"],
  ["Lenovo ThinkCentre neo 30s Gen 5 13DG001NLS PC de escritorio SFF Core i5-13420H 16GB DDR5 512GB SSD Wi-Fi Windows 11 Pro", "LENOVO", "computo/desktops/slim/lenovo-thinkcentre-neo-30s-gen-5", "desktops"],
  ["Provision-ISR NVR5-4100PXN(MM) NVR PoE 4 canales 5MP NDAA", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/nvr-poe/4-canales-5mp", "cameras"],
  ["Intellinet 520959 panel de parcheo Cat6 UTP 24 puertos 1U rack 19 pulgadas negro", "INTELLINET", "redes/cableado-estructurado/paneles-parcheo/cat6/24-puertos-1u", "networking"],
  ["BRobotix 406306 soporte antirrobo ajustable para laptop hasta 17.3 pulgadas con candado y llave plata", "BROBOTIX", "computo/accesorios/soportes-laptop/antirrobo-ajustables", "accessories"],
  ["Aspel Sellado CFDI FACTE/400 paquete 400 timbres para facturacion electronica", "ASPEL", "software/licencias/aspel-sellado-cfdi/timbres-400", "software"],
  ["Epson ERC-38BR cinta para impresora matriz punto negro rojo", "EPSON", "impresion/consumibles/cintas-matriz-punto/epson-erc-38", "printers_scanners"],
  ["Dahua DH-HAC-B2A21N-U-IL-A camara HDCVI bullet 2MP dual-light con microfono", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet/2mp-dual-light-mic", "cameras"],
  ["Naceb NA-0646 escritorio gamer fibra carbono con plataforma para monitor", "NACEB TECHNOLOGY", "gaming/mobiliario/escritorios/fibra-carbono/plataforma-monitor", "gaming"],
  ["CyberPower CL1500VR regulador AVR 1500VA 750W 8 contactos", "CYBERPOWER", "energia/supresores-reguladores/reguladores-voltaje/avr/1500va", "power"],
  ["Dahua DH-XVR1B08-I/T XVR pentahibrido WizSense 8 canales", "DAHUA TECHNOLOGY", "seguridad/cctv/dvr-nvr/xvr-pentahibrido/8-canales-wizsense", "cameras"],
  ["Cooler Master Storm Controller CMI-GSCX-BK1 gamepad Bluetooth USB-C negro", "COOLER MASTER", "gaming/accesorios/controles-gamepad/bluetooth-usb-c", "gaming"],
  ["Manhattan MWK7400 180788 combo teclado y mouse inalambrico 2.4GHz", "MANHATTAN", "computo/perifericos/combos-teclado-mouse/inalambricos/productividad/2-4ghz", "accessories"],
  ["Vorago PSU-101 fuente de poder ATX 500W gris", "VORAGO", "computo/componentes/fuentes-poder/atx-500w", "components"],
  ["Gigabyte Radeon RX 9060 XT Gaming OC 16G tarjeta de video PCIe", "GIGABYTE", "computo/componentes/tarjetas-video/amd-radeon/rx-9000/rx-9060-xt", "gaming"],
  ["Kaspersky Plus KL1042Z5KFS-22 licencia 10 dispositivos 1 ano Windows Mac Android iOS", "KASPERSKY", "software/seguridad/antivirus/kaspersky-plus/10-dispositivos-1-ano", "software"],
  ["TP-Link TL-WR845N router Wi-Fi 4 N300 2.4GHz con 3 antenas", "TP LINK", "redes/routers/wifi-n/n300", "networking"],
  ["StarTech PXT101 cable de alimentacion NEMA 5-15P a IEC C13 1.8m 10A 125V", "STARTECH.COM", "accesorios/cables-adaptadores/alimentacion/nema-5-15p-c13/1-8m", "accessories"],
  ["MSI PRO B760M-P DDR4 tarjeta madre micro ATX Intel B760 LGA1700 DDR4", "MSI", "computo/componentes/tarjetas-madre/intel-lga1700/b760/micro-atx/ddr4", "components"],
  ["Dahua DH-PFM320D-015 fuente de poder CCTV 12V 1.5A con indicador", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-alimentacion/fuentes-12v/1-5a", "cameras"],
  ["Hisense ARU362HBW minisplit inverter 3 toneladas 36000 BTU 230V blanco", "HISENSE", "climatizacion/aires-acondicionados/minisplit/inverter/36000-btu/230v", "accessories"],
  ["Nextep NE-410E mouse inalambrico ergonomico USB 1600 DPI negro", "NEXTEP", "computo/perifericos/mouse/inalambricos/basicos/1600-dpi", "accessories"],
  ["Zebra ZD421t impresora de etiquetas transferencia termica 4 pulgadas 203 dpi USB", "ZEBRA", "impresion/impresoras/etiquetas/transferencia-termica/desktop-4-pulgadas", "printers_scanners"],
  ["Vorago AU-302-BK cargador de pared USB-A Fast Charge 5V negro", "VORAGO", "energia/cargadores-usb/pared-usb-a/fast-charge", "accessories"],
  ["Vorago CAB-AB018 cable USB 2.0 A macho a USB-B macho para impresora 1.8m negro", "VORAGO", "accesorios/cables-adaptadores/usb/usb-a-b/2-0-1-8m", "accessories"],
  ["Ruijie Reyee RG-EW1800GX PRO router Wi-Fi 6 AX1800 dual-band gigabit", "RUIJIE", "redes/routers/wifi-6/ax1800", "networking"],
  ["ASRock B550M-HDV tarjeta madre micro ATX AMD AM4 B550 DDR4", "ASROCK", "computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx", "components"],
  ["StarTech SDOCK2U313R duplicador dock SATA USB-C dual bay HDD SSD", "STARTECH.COM", "computo/almacenamiento/docks-duplicadores/sata/usb-c-dual-bay", "storage"],
  ["Azor Uni-ball Deluxe UB155NE1 boligrafo roller negro 0.5mm blister", "AZOR", "oficina/papeleria/boligrafos/roller/uni-ball-deluxe", "accessories"],
  ["Imou Cruiser SE+ IPC-S41FEN camara IP WiFi PT exterior 4MP 2K", "IMOU", "seguridad/cctv/camaras-ip-wifi/pt-exterior/4mp-2k", "cameras"],
  ["PNY GeForce RTX 4080 SUPER XLR8 VERTO EPIC-X RGB OC 16GB VCG4080S16TFXXPB1-O", "PNY", "computo/componentes/tarjetas-video/nvidia-geforce/rtx-40/rtx-4080-super", "gaming"],
  ["HPE HK1Y0E Foundation Care 3Y NBD Exchange Instant On Access Point service", "HEWLETT PACKARD ENTERPRISE", "servicios-ti/soporte-garantias/hpe-foundation-care/exchange", "software"],
  ["HP T1A62AA Keyed Cable Lock 10 mm candado para laptop 1.83m", "HP", "accesorios/seguridad-fisica/candados-laptop/llave", "accessories"],
  ["Badgy Evolis CBGR0500K ribbon monocromo negro 500 impresiones", "BADGY", "punto-de-venta/credenciales-identificacion/consumibles/ribbons-monocromo-negro", "accessories"],
  ["Epson FX-2190II C11CF38201 impresora matriz de punto 9 pines formato ancho", "EPSON", "impresion/impresoras/matriz-punto/formato-ancho/9-pines", "printers_scanners"],
  ["Vorago BP-150-BL mochila rPET ecologica para laptop 15.6 pulgadas azul negro", "VORAGO", "computo/accesorios/mochilas-fundas/mochilas-laptop/15-6/rpet-ecologicas", "accessories"],
  ["Canon PG-210 2974B017AA cartucho tinta negra FINE 9ml 250 paginas", "CANON", "impresion/consumibles/cartuchos-tinta/canon/pg-210/negro", "printers_scanners"],
  ["Perfect Choice PC-030362 kit limpieza pantallas 30ml con microfibra", "PERFECT CHOICE", "computo/accesorios/limpieza/limpiadores-pantalla/kits/30ml-microfibra", "accessories"],
  ["Naceb Iron Knight NA-0318 headset gamer 3.5mm microfono desmontable PS4 Xbox", "NACEB GAMING", "gaming/audio/headsets/alambricos/3-5mm-microfono-desmontable", "gaming"],
  ["Acteck Onex GS455 AC-943079 gabinete mini torre slim Micro-ATX fuente SFX 500W", "ACTECK", "computo/componentes/gabinetes/mini-tower/micro-atx-itx-fuente-500w/slim-sfx", "components"],
  ["TP-Link CPE710 CPE exterior 5GHz AC 867Mbps 23dBi Pharos", "TP LINK", "redes/radioenlaces-antenas/cpe-exterior/5ghz-ac-867mbps-23dbi", "networking"],
  ["XPG PROBE700B-BKCUS fuente poder ATX 700W 80 Plus Bronze", "ADATA", "computo/componentes/fuentes-poder/atx-80-plus-bronze/700w", "components"],
  ["Dell AC027075 memoria RAM 16GB DDR5 4800MHz ECC UDIMM", "DELL", "computo/componentes/memoria-ram/udimm-ddr5/ecc-16gb-4800", "components"],
  ["Manhattan 153966 USB-C PD docking station 7 en 1 HDMI Ethernet", "MANHATTAN", "computo/accesorios/docks-hubs/usb-c/7-en-1-hdmi-ethernet-pd", "accessories"],
  ["BRobotix 372782 cable USB 2.0 extension activa 15m macho hembra", "BROBOTIX", "accesorios/cables-adaptadores/usb/extensiones/activas/15m", "accessories"],
] as const;

describe("manual taxonomy batches 160 plus", () => {
  it.each(batch160PlusCases)("%s -> %s", (name, brand, path, legacyCategory) => {
    const result = classifyManualCategory({ name, brand, category: "laptops" });
    expect(result.path).toBe(path);
    expect(result.legacyCategory).toBe(legacyCategory);
  });
});
