import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const researchedBatchCases = [
  ["Naceb Technology NA-0310R audifonos tipo diadema con microfono 3.5 mm rojo negro", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono"],
  ["Streamax ADPLUS 2.0-V1.1 MDVR dashcam vehicular 4G GPS Wi-Fi MOD4AMER33", "STREAMAX", "seguridad/cctv/camaras-moviles/mdvr/4g-gps"],
  ["Acteck TE-200 teclado estandar alambrico USB negro AC-928946", "ACTECK", "computo/perifericos/teclados/alambricos/usb"],
  ["Dell Pro 14 Plus laptop 14 pulgadas Core Ultra 7 266V 16GB Windows 11 Pro", "DELL", "computo/laptops/empresariales/14-pulgadas/dell-pro-14-plus"],
  ["Ocelot Gaming OMPXL01 mouse pad de tela extendido RGB con software", "OCELOT GAMING", "computo/accesorios/mousepads/gaming-rgb/extendidos"],
  ["Hisense ART121KAW minisplit inverter 1 tonelada 11500 BTU solo frio Wi-Fi", "HISENSE", "hogar/electrodomesticos/aires-acondicionados/minisplit/1-tonelada"],
  ["Hisense 40A45NV Smart TV LED 40 pulgadas Full HD VIDAA Wi-Fi", "HISENSE", "video/televisores/led-vidaa-tv/40-fhd"],
  ["Perfect Choice PC-085010 bolso crossbody para tablet 10.8 pulgadas azul", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/maletines-tablet/10-8-pulgadas"],
  ["TP-Link Omada ER605 router VPN Gigabit Multi-WAN SDN", "TP-LINK", "redes/routers/vpn/omada/er605"],
  ["Balam Rush GR Burst GR750G fuente ATX 750W 80 Plus Gold full modular", "BALAM RUSH", "computo/componentes/fuentes-poder/atx-80-plus-gold/750w"],
  ["Dahua DHI-USB-U106-20-16GB USB 2.0 Flash Drive 16GB MEMNCB020", "DAHUA TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/16gb/metalicas"],
  ["Dahua DH-PFM800-E balun pasivo HDCVI 1080p ACCDAH650", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-cableado/baluns-video/hdcvi-1080p"],
  ["Dahua DHI-USB-U106-20-8GB USB 2.0 Flash Drive 8GB MEMNCB010", "DAHUA TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/8gb/metalicas"],
  ["TP-Link TL-WR840N router Wi-Fi N300 2.4GHz ROUTPL560", "TP-LINK", "redes/routers/wifi-n/n300"],
  ["Dahua DH-PFM979-1S4P divisor alimentacion DC 1 a 4 CCTV", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-cableado/conectores-corriente/divisores-energia-dc"],
  ["Brother BT5001Y botella tinta amarilla 48.8 ml 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-bt5001/amarillo"],
  ["Logitech M90 910-004053 mouse USB alambrico 1000 DPI negro", "LOGITECH", "computo/perifericos/mouse/alambricos/basicos/1000-dpi"],
  ["Stylos ST100 STMUSB2B memoria USB 16GB USB 2.0 plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/16gb/metalicas"],
  ["Epson T504420-AL botella tinta amarilla 504 EcoTank 70 ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t504/amarillo"],
  ["TP-Link TL-WA850RE extensor Wi-Fi N300 2.4GHz", "TP-LINK", "redes/extensores-wifi/n300"],
  ["ADATA C008 AC008-16G-RKD memoria USB 2.0 retractil 16GB negro", "ADATA", "computo/almacenamiento/memorias-flash/usb/16gb/retractiles"],
  ["Epson T504120-AL botella tinta negra 504 EcoTank 127 ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t504/negro"],
  ["Xerox Marathon 003M02051 papel bond carta 5000 hojas 70 g", "XEROX", "oficina/papel-consumibles/papel-bond/carta/5000-hojas"],
  ["Perfect Choice PC-030331 E-Duster aire comprimido 230 g", "PERFECT CHOICE", "computo/accesorios/limpieza/aire-comprimido/e-duster"],
  ["Brother DCP-T530DW multifuncional tinta continua duplex Wi-Fi", "BROTHER", "impresion/impresoras/multifuncionales-tinta-continua/brother-dcp"],
  ["Koblenz RS-1410 regulador voltaje AVR 1410VA 700W 8 contactos", "KOBLENZ", "energia/supresores-reguladores/reguladores-voltaje/avr/1410va"],
  ["Brother DCP-T730DW multifuncional tinta continua duplex Wi-Fi 23 ppm", "BROTHER", "impresion/impresoras/multifuncionales-tinta-continua/brother-dcp"],
  ["Epson T544120-AL botella tinta negra Dye EcoTank L3110 65 ml", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t544/negro"],
  ["LG 24U411A-B.AWMQ monitor 23.8 FHD IPS 120Hz HDR10", "LG", "computo/monitores/oficina/24-fhd-120hz"],
  ["PCM T8070S rollo termico 80 x 70 mm paquete 50", "PCM", "punto-de-venta/consumibles/rollos-termicos/80x70"],
  ["Dell KM3322W 580-AKCU combo teclado y mouse inalambrico espanol", "DELL", "computo/perifericos/combos-teclado-mouse/inalambricos/basicos"],
  ["Kingston DataTraveler Exodia M DTXM/64GB USB 3.2 retractil azul", "KINGSTON TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb/64gb/retractiles"],
  ["Mercusys MW150US adaptador nano USB Wi-Fi N150 150Mbps", "MERCUSYS", "redes/adaptadores-wifi/usb/n150-nano"],
  ["Nextep NE-528 rollo termico 57 x 40 mm paquete 10", "NEXTEP", "punto-de-venta/consumibles/rollos-termicos/57x40"],
  ["Dell KM300C 580-AKKW combo teclado y mouse USB espanol", "DELL", "computo/perifericos/combos-teclado-mouse/alambricos/basicos"],
  ["Intellinet 210591 jack keystone RJ45 Cat6 blanco de impacto", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat6"],
  ["Xerox Ecologico papel bond carta 5000 hojas 75 g 93 blancura", "XEROX", "oficina/papel-consumibles/papel-bond/carta/5000-hojas/ecologico"],
  ["Brother BTD100M botella de tinta magenta 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/magenta"],
  ["ADATA UV250 AUV250-16G-RBK memoria USB 2.0 16GB plata", "ADATA", "computo/almacenamiento/memorias-flash/usb/16gb/metalicas"],
  ["Brother BTD100Y botella de tinta amarilla 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/amarillo"],
  ["Stylos STMUSB3B memoria USB 2.0 32GB plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/32gb/metalicas"],
  ["Dell KB216 teclado alambrico USB ingles negro", "DELL", "computo/perifericos/teclados/alambricos/usb/ingles"],
  ["Samsung Galaxy Tab A11 Enterprise Edition 8.7 pulgadas 4GB 64GB Wi-Fi", "SAMSUNG", "computo/tabletas/android/8-pulgadas/enterprise"],
  ["Brother BTD100C botella de tinta cian 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/cian"],
  ["TP-Link LS1005G LiteWave switch gigabit no administrable 5 puertos", "TP-LINK", "redes/switches/no-administrables/gigabit/5-puertos"],
  ["Brother BT5001C botella de tinta cian 48.8 ml 5000 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-bt5001/cian"],
  ["Brother BTD100BK botella de tinta negra 7500 paginas", "BROTHER", "impresion/consumibles/botellas-tinta/brother-btd100/negro"],
  ["Nextep NE-529 rollo termico 80 x 70 mm paquete 5", "NEXTEP", "punto-de-venta/consumibles/rollos-termicos/80x70"],
  ["TP-Link Tapo C500 camara Wi-Fi exterior 360 1080p IP65", "TP-LINK", "seguridad/cctv/camaras-ip-wifi/pt-exterior/2mp"],
  ["Dell MS116 mouse USB optico alambrico 1000 DPI negro", "DELL", "computo/perifericos/mouse/alambricos/basicos/1000-dpi"],
  ["Epson ERC-38B cinta negra para miniprinter TM-U200", "EPSON", "impresion/consumibles/cintas-matriz-punto/epson-erc-38"],
  ["Lexar JumpDrive V40 LJDV40-32GAB memoria USB 2.0 32GB negra", "LEXAR", "computo/almacenamiento/memorias-flash/usb/32gb"],
  ["Brobotix 497202 mouse basico USB optico negro 3 botones", "BROBOTIX", "computo/perifericos/mouse/alambricos/basicos"],
  ["Perfect Choice PC-034087 alcohol isopropilico antiestatico 250 ml", "PERFECT CHOICE", "computo/accesorios/limpieza/alcohol-isopropilico"],
  ["TP-Link UB500 adaptador nano USB Bluetooth 5.0", "TP-LINK", "redes/adaptadores-bluetooth/usb"],
  ["Logitech M170 mouse inalambrico gris 1000 DPI", "LOGITECH", "computo/perifericos/mouse/inalambricos/basicos/1000-dpi"],
  ["Provision ISR PTR-102VP-HD+ video balun energia 4 en 1", "PROVISION ISR", "seguridad/cctv/accesorios-cableado/baluns-video/video-poder"],
  ["Stylos STMUSB4B memoria USB 2.0 64GB plata", "STYLOS", "computo/almacenamiento/memorias-flash/usb/64gb/metalicas"],
  ["HP GT53 1VV22AL botella de tinta negra", "HP", "impresion/consumibles/botellas-tinta/hp-gt53/negro"],
  ["Intellinet 163286 faceplate tapa keystone 1 perforacion blanco", "INTELLINET", "redes/cableado-estructurado/placas-keystone/1-puerto"],
  ["BRobotix 497264 mouse pad ultra delgado negro con bolsa", "BROBOTIX", "computo/accesorios/mousepads/basicos-ultradelgados"],
  ["Mercusys MW300UM adaptador mini USB Wi-Fi N300 300Mbps", "MERCUSYS", "redes/adaptadores-wifi/usb/n300-mini"],
  ["Perfect Choice PC-201038 teclado USB resistente a salpicaduras negro", "PERFECT CHOICE", "computo/perifericos/teclados/alambricos/usb/resistentes-salpicaduras"],
  ["TP-Link TL-WA855RE extensor Wi-Fi N300 2 antenas externas", "TP-LINK", "redes/extensores-wifi/n300"],
  ["TP-Link Archer T2U Nano adaptador USB Wi-Fi AC600 dual band", "TP-LINK", "redes/adaptadores-wifi/usb/ac600-nano"],
  ["HP Poly Blackwire 3220 8X228A6 diadema USB-C con adaptador USB-A", "PLANTRONICS", "audio/audifonos/usb/diadema-microfono"],
  ["BRobotix 500074N mouse pad ergonomico con gel negro", "BROBOTIX", "computo/accesorios/mousepads/ergonomicos-con-gel"],
  ["ADATA SU630 ASU630SS-480GQ-R SSD 480GB 2.5 SATA", "ADATA", "computo/almacenamiento/ssd/2-5-sata/480gb"],
  ["Intellinet 210737 jack keystone Cat6 azul de impacto", "INTELLINET", "redes/cableado-estructurado/conectores-keystone/rj45-cat6"],
  ["Acteck Captive Lite CL185 monitor 18.5 HD 1366x768", "ACTECK", "computo/monitores/oficina/18-5-hd"],
  ["Manhattan 151467 convertidor HDMI a VGA bolsa", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Dell DW316 unidad DVD externa USB 884116288473", "DELL", "computo/almacenamiento/unidades-opticas/dvd-externas"],
  ["SanDisk Cruzer Blade 16GB memoria USB SDCZ50", "SANDISK", "computo/almacenamiento/memorias-flash/usb/16gb"],
  ["Provision ISR PR-12V3A fuente de poder CCTV 12V 3A", "PROVISION ISR", "seguridad/cctv/fuentes-poder/12v-3a"],
  ["IMOU IPC-PS8D-3V0 camara domo IP PoE 3MP", "IMOU", "seguridad/cctv/camaras-ip-poe/domo/3mp"],
  ["IMOU IPC-PS3D-3M0 camara bala IP PoE 3MP", "IMOU", "seguridad/cctv/camaras-ip-poe/bullet/3mp"],
  ["TP-Link Archer C50 router Wi-Fi AC1200 dual band", "TP-LINK", "redes/routers/wifi-5/ac1200"],
  ["Dell KM5221W kit teclado y mouse inalambrico espanol", "DELL", "computo/perifericos/combos-teclado-mouse/inalambricos/productividad"],
  ["Provision ISR PR-12V5A fuente de poder CCTV 12V 5A", "PROVISION ISR", "seguridad/cctv/fuentes-poder/12v-5a"],
  ["Naceb Technology NA-620 aire comprimido 440ml", "NACEB TECHNOLOGY", "computo/accesorios/limpieza/aire-comprimido/440ml"],
] as const;

describe("manual taxonomy researched post-100 batches", () => {
  it.each(researchedBatchCases)("%s -> %s", (name, brand, path) => {
    expect(classifyManualCategory({ name, brand, category: "laptops" }).path).toBe(path);
  });
});
