import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const researchedBatchCases = [
  ["Dbugg DB-PD64 cargador de pared USB-C PD GaN 67W", "DBUGG", "energia/cargadores-usb"],
  ["Fujitsu fi-70F escaner plano A6 USB", "FUJITSU", "impresion/escaneres"],
  ["Perfect Choice PC-085058 bolso cruzado Holdi negro", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Creative Sound Blaster GS5 barra de sonido compacta", "CREATIVE", "audio/barras-sonido"],
  ["Game Factor HSG500 headset gamer USB 7.1 RGB", "GAME FACTOR", "audio/audifonos"],
  ["Huawei M-Pencil CD54-S1 lapiz optico blanco", "HUAWEI", "computo/accesorios/stylus-tablets"],
  ["Perfect Choice PC-085249 mochila escolar Bookery purpura", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["HP GT52 3YP17AL botella de tinta amarilla 70 ml", "HP", "impresion/consumibles/tinta-toner"],
  ["Perfect Choice PC-084433 mochila escolar Delfin Astro", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Duosmart E21 camara inteligente WiFi 3MP PIR", "DUOSMART", "seguridad/cctv/camaras-ip-wifi"],
  ["KSA GKSA01-B goggles de proteccion anti empanante", "KSA", "seguridad/epp/proteccion-ocular"],
  ["TopVision TBDL200A camara HD bullet 2MP TVI AHD CVI", "TOPVISION", "seguridad/cctv/camaras-turbohd"],
  ["Laces LA100KSP kit de soportes de pared para rack", "LACES", "infraestructura/racks-accesorios/soportes-pared"],
  ["Logitech PRO X 60 920-011921 teclado gaming wireless", "LOGITECH", "computo/perifericos/teclados"],
  ["Dell PowerEdge R470 R470271 servidor rack 1U", "DELL", "computo/servidores/rack"],
  ["TechZone TZLBP02 mochila laptop 15.6 pulgadas", "TECHZONE", "computo/accesorios/mochilas-fundas"],
  ["Nexxt AW222NXT67 NPS-V11U3B charola para rack 1U", "NEXXT", "infraestructura/racks-accesorios/charolas"],
  ["Vorago KSP-205 mini bafle karaoke bluetooth RGB", "VORAGO", "audio/bocinas"],
  ["Syble XB-VP1106 verificador de precios POS", "SYBLE", "punto-de-venta/verificadores-precio"],
  ["Perfect Choice PC-085027 bolso cruzado Holdy avellana", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-085294 mochila escolar Kiddo Corazon", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Pacific Soft PSF030 punto de venta para farmacias", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Redragon Sacarab White A130W-SP keycaps PBT", "REDRAGON", "computo/perifericos/teclados/keycaps"],
  ["TP-Link Omada OC200 controlador cloud", "OMADA", "redes/controladores-cloud"],
  ["North System NORTH109-BKL organizador horizontal rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/organizadores-cable"],
  ["Vorago BSP-400 Pool Bluetooth IPX67 bocina", "VORAGO", "audio/bocinas"],
  ["PCM 10B13 papel bond plotter 0.61 x 50", "PCM", "impresion/consumibles/papel-plotter"],
  ["Necnon NPW-10FC power bank 10000 mAh", "NECNON", "energia/power-banks"],
  ["Huawei 55037722 M-Pen Lite AF63-R lapiz optico", "HUAWEI", "computo/accesorios/stylus-tablets"],
  ["Perfect Choice PC-084730 Sportiva bolso deportivo", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Vorago KSP-180 mini bafle karaoke bluetooth RGB", "VORAGO", "audio/bocinas"],
  ["Perfect Choice PC-270157 smartwatch Mercury negro", "PERFECT CHOICE", "wearables/smartwatches"],
  ["Perfect Choice PC-270218 smartwatch Minoro llamadas", "PERFECT CHOICE", "wearables/smartwatches"],
  ["Nexxt AW222NXT66 NPS-S11U3B charola lisa rack", "NEXXT", "infraestructura/racks-accesorios/charolas"],
  ["TopVision TDDL500A camara HD turret 5MP", "TOPVISION", "seguridad/cctv/camaras-turbohd"],
  ["Meriva MDL-3202A camara HD turret 2MP", "MERIVA", "seguridad/cctv/camaras-turbohd"],
  ["Vorago KSP-350 bocina bluetooth 30W", "VORAGO", "audio/bocinas"],
  ["Redragon Sacarab Pink A130P-SP keycaps PBT", "REDRAGON", "computo/perifericos/teclados/keycaps"],
  ["Verbatim 95310 DVD+R DL 8.5GB 20 pack", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Fujitsu ScanSnap SV600 escaner elevado A3", "FUJITSU", "impresion/escaneres"],
  ["Nexxt AW251NXT05 PTKCKKBSDKT01 kit basico herramientas red", "NEXXT", "redes/herramientas-cableado"],
  ["Pacific Soft SF020 punto de venta para autoservicios", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Pacific Soft PSF040 comandera movil restaurantes Android", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Kensington K64704WW VeriMark Pro fingerprint key", "KENSINGTON", "computo/accesorios/seguridad-biometrica"],
  ["Huawei Band 10 55020EKW Aluminum Blue smartwatch", "HUAWEI", "wearables/smartwatches"],
  ["Perfect Choice PC-085164 mochila escolar Arcade", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Pacific Soft KITPSF070 punto de venta para farmacias", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Orvibo SM11 sensor de puerta ventana Zigbee", "ORVIBO", "domotica/sensores"],
  ["Multimedia Screens MSC-265 pantalla de proyeccion 120", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Poly EncorePro 510 783Q1AA headset Quick Disconnect", "POLY", "audio/audifonos"],
  ["Anviz AN-C2Slim-BT control de acceso lector de huella", "ANVIZ", "seguridad/control-acceso/biometricos"],
  ["Anviz AN-EMICARD tarjeta RFID 125Khz PVC", "ANVIZ", "seguridad/control-acceso/tarjetas-rfid"],
  ["IMOU ARD311-SW contacto magnetico inalambrico", "IMOU", "domotica/sensores"],
  ["Multimedia Screens MSC-332 pantalla manual 150 16:9", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Multimedia Screens MSE-332 pantalla electrica 150 16:9", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Perfect Choice PC-085089 Kiddo Monstruos mochila escolar", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-114024 Emphoria barra de audio RGB 70W", "PERFECT CHOICE", "audio/barras-sonido"],
  ["Tripp Lite N206-FP02-IND bulkhead wall plate", "TRIPP-LITE", "redes/cableado-estructurado/placas-keystone"],
  ["DataShield IS-1000 inversor cargador solar", "DATASHIELD", "energia/inversores-solares"],
  ["DataShield IS-3000 inversor solar hibrido", "DATASHIELD", "energia/inversores-solares"],
  ["Logitech G335 wired gaming headset blanco azul", "LOGITECH", "audio/audifonos"],
  ["Mirati MBJ01N exprimidor de citricos 700 ml 25 W", "MIRATI", "hogar/electrodomesticos/exprimidores"],
  ["Naceb Fornax NA-0308N diadema Bluetooth", "NACEB TECHNOLOGY", "audio/audifonos"],
  ["PCM 10B11 papel bond plotter 0.91 x 100", "PCM", "impresion/consumibles/papel-plotter"],
  ["PCM 10B5 papel bond plotter 0.91 x 100", "PCM", "impresion/consumibles/papel-plotter"],
  ["Perfect Choice PC-085225 mochila escolar Loopy rojo", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-085300 mochila escolar Brooklyn Dinosaurios", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Poly Voyager 4310 ACCPTS1960 headset Bluetooth BT700", "POLY", "audio/audifonos"],
  ["Targus ASP71GLX-S DEFCON Compact Serialized Combo Cable Lock", "TARGUS", "accesorios/seguridad-fisica"],
  ["Verbatim 95179 DVD-RW 4.7GB 30 pack", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Zebra Z-Band Direct 10006995K pulsera termica", "ZEBRA", "impresion/consumibles/pulseras-termicas"],
  ["Acteck AC-937146 Energon S-Mate CI730 cargador inalambrico Qi", "ACTECK", "energia/cargadores-inalambricos"],
  ["Epson C33S021501 SJMB6000 maintenance box", "EPSON", "impresion/consumibles/mantenimiento"],
  ["Hisense AC121CF minisplit 1 tonelada solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["Kensington K60604WW Slim NanoSaver combination lock", "KENSINGTON", "accesorios/seguridad-fisica"],
  ["Lanix 14996 XAir 1 purificador de aire", "LANIX", "hogar/electrodomesticos/purificadores-aire"],
  ["Lenovo 4XH7A83845 PCIe riser SR630 V3", "LENOVO", "computo/servidores/componentes"],
  ["Logitech 920-010478 MX Keys Mini rosa", "LOGITECH", "computo/perifericos/teclados"],
  ["MSI GeForce RTX 5060 8G Shadow 2X OC", "MSI", "computo/componentes/tarjetas-video"],
  ["Mobifree base de carga inalambrica 10W Qi", "MOBIFREE", "energia/cargadores-inalambricos"],
  ["North System NORTH115-BKL organizador vertical rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/organizadores-cable"],
  ["Verbatim 95093 DVD-R 4.7GB 16X", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Manhattan 438889 London maletin laptop 15.4", "MANHATTAN", "computo/accesorios/mochilas-fundas"],
  ["Badgy VBDG204EU kit YMCKO ribbon 100 impresiones", "BADGY", "punto-de-venta/credenciales-identificacion"],
  ["Zebra 10011042 Z-Perform 1000D receipt paper 3 x 80", "ZEBRA", "punto-de-venta/consumibles/rollos-termicos"],
  ["Polaroid PASU85-63 papel de sublimacion", "POLAROID", "impresion/consumibles/papel-fotografico-sublimacion"],
  ["Perfect Choice EL-994787 auriculares diadema", "PERFECT CHOICE", "audio/audifonos"],
  ["Orvibo SN11 sensor de movimiento PIR Zigbee", "ORVIBO", "domotica/sensores/movimiento"],
  ["Kingston SNA-BR2/35 SSD bracket 2.5 to 3.5", "KINGSTON TECHNOLOGY", "computo/almacenamiento/accesorios-montaje"],
  ["Jabra Speak 510 speakerphone USB Bluetooth", "JABRA", "audio/conferencia-speakerphones"],
  ["Naceb NA-0801 toallas humedas para computadoras", "NACEB TECHNOLOGY", "computo/accesorios/limpieza"],
  ["DataShield IN-5000 inversor cargador solar hibrido", "DATASHIELD", "energia/inversores-solares"],
  ["Manhattan 439893 London maletin laptop 14.1", "MANHATTAN", "computo/accesorios/mochilas-fundas"],
  ["HP ScanJet Pro N4000 snw1 6FW08A escaner ADF", "HP", "impresion/escaneres"],
  ["Bin Zun R6 termometro infrarrojo sin contacto", "BIN ZUN", "salud/equipo-medico/monitoreo"],
  ["Sonolife LMT-01 oximetro de pulso digital", "SONOLIFE", "salud/equipo-medico/monitoreo"],
  ["Multimedia Screens PM-87IR pizarron interactivo 87 20 toques", "MULTIMEDIA SCREENS", "oficina/pizarrones-interactivos"],
  ["Clar Systems CSY090 dispensador de toalla", "CLAR SYSTEMS", "oficina/limpieza-higiene/dispensadores"],
  ["Kensington K64430S MicroSaver 2.0 keyed chassis lock", "KENSINGTON", "accesorios/seguridad-fisica"],
  ["Kensington K60412WW SmartFit Conform Back Rest", "KENSINGTON", "oficina/ergonomia/soportes-lumbares"],
  ["Lenovo 5PS0A23193 3 year ADP warranty extension", "LENOVO", "servicios/garantias-extendidas"],
  ["HP ScanJet Pro N4600 fnw1 escaner documental", "HP", "impresion/escaneres"],
  ["Targus AEH101TT Wired Mono Headset", "TARGUS", "audio/audifonos"],
  ["Acteck AC-934961 Glee Max AP460 bocina Bluetooth 10W", "ACTECK", "audio/bocinas"],
  ["Hisense AC122CF minisplit 1 tonelada solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["Pacific Soft KITPSF060 punto de venta para restaurantes", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Pacific Soft KITPSF050 punto de venta para restaurantes", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Acteck BS685 Dynamic Exact bocinas tipo estudio 80W", "ACTECK", "audio/bocinas"],
  ["Acteck CP20W cargador de pared USB-C 20W", "ACTECK", "energia/cargadores-usb"],
  ["Acteck BS465 Dynamic Trim barra de sonido 2.1 60W", "ACTECK", "audio/barras-sonido"],
  ["APC AP9643 Network Management Card 3 NMC3", "APC", "energia/accesorios-ups/tarjetas-snmp"],
  ["Verbatim 49976 CD DVD paper sleeves with clear window", "VERBATIM", "computo/almacenamiento/medios-opticos/accesorios"],
  ["Acteck CI710 cargador de pared USB", "ACTECK", "energia/cargadores-usb"],
  ["Perfect Choice PC-084396 mochila", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["HP DesignJet T200/T600 automatic sheet feeder 8AJ60A", "HP", "impresion/accesorios/bandejas-alimentadores"],
  ["DataShield IN-6000 inversor cargador solar", "DATASHIELD", "energia/inversores-solares"],
  ["Stylos STASWM3CA smartwatch azul", "STYLOS", "wearables/smartwatches"],
  ["Stylos STASWM3CB smartwatch negro", "STYLOS", "wearables/smartwatches"],
  ["Stylos STASWM3CP smartwatch rosa", "STYLOS", "wearables/smartwatches"],
  ["Acteck Shift Plus AB424 receptor Bluetooth 3.5 mm", "ACTECK", "audio/adaptadores-bluetooth"],
  ["Microsoft Windows 11 Pro FQC-10572 ESD descarga digital", "MICROSOFT", "software/sistemas-operativos"],
  ["CDP UPO22-10 UPS online doble conversion 10 kVA", "CDP", "energia/no-breaks-ups/doble-conversion"],
  ["Acteck Dynamic Exact R BS700 bocinas Bluetooth 50W", "ACTECK", "audio/bocinas"],
  ["Hisense WSA1102PCN lavadora semiautomatica doble tina", "HISENSE", "hogar/electrodomesticos/lavadoras"],
  ["Hisense ACR242KG minisplit 2 toneladas solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["TP-Link DeltaStream DS-P7001-16 OLT GPON", "TP-LINK", "redes/fibra-optica/olt-gpon"],
  ["Norton 360 Deluxe 21414731 3 dispositivos 1 ano", "NORTON", "software/seguridad"],
  ["Autodesk AutoCAD LT 2025 057Q1-WW6525-L347", "AUTODESK", "software/cad-diseno"],
  ["Zoomy ZWF01 bebedero fuente para mascotas 1.5 L", "ZOOMY", "mascotas/bebederos-fuentes"],
  ["Dell Essential Backpack 15 ES1520P mochila laptop", "DELL", "computo/accesorios/mochilas-fundas"],
  ["Microsoft Office Home 2024 EP2-06874 ESD", "MICROSOFT", "software/productividad-oficina"],
  ["Scooter electrico Stylos M2 STSCM02B negro", "STYLOS", "movilidad/scooters-electricos"],
  ["Hisense HS1000 barra de sonido 2.0 120W", "HISENSE", "audio/barras-sonido"],
  ["Poly TC10 875K5AA touch controller video conferencia", "POLYCOM", "colaboracion/video-conferencia/controladores"],
  ["Jabra Speak 510 MS 7510-109 speakerphone USB Bluetooth", "JABRA", "audio/conferencia-speakerphones"],
  ["BenQ InstaShare Button TWY31 transmisor inalambrico", "BENQ", "colaboracion/presentacion-inalambrica"],
  ["Scooter electrico Stylos M3 STSCM03O naranja", "STYLOS", "movilidad/scooters-electricos"],
  ["Vorago BSP-320 mini barra de sonido Bluetooth RGB", "VORAGO", "audio/barras-sonido"],
  ["TP-Link Tapo RV30 Max robot aspirador y trapeador", "TP-LINK", "hogar/electrodomesticos/aspiradoras-robot"],
  ["Perfect Choice PC-085317 mochila escolar Brooklyn Flores", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Netis NB50 CPE 450Mbps exterior punto a punto", "NETIS", "redes/radioenlaces-antenas"],
  ["Huawei WATCH FIT 4 Pro 55020FAD smartwatch verde", "HUAWEI", "wearables/smartwatches"],
  ["Acteck BS600 Dynamic Thin barra de sonido 2.1 60W", "ACTECK", "audio/barras-sonido"],
  ["Uniarch UHO-S2E-M3 camara IP mini PT WiFi 3MP", "UNIARCH", "seguridad/cctv/camaras-ip-wifi"],
  ["APC RBC35 bateria de reemplazo UPS Back-UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["Condumex 664464 bobina cable UTP Cat5e exterior con gel", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["Condumex 66446815 bobina cable UTP Cat6 interior azul", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["Condumex 66446835 bobina cable UTP Cat6 interior gris", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["WAM RG59UL-305B cable siames RG-59 CCTV", "WAM", "seguridad/cctv/cable-coaxial-siames"],
  ["Condumex 66445632 bobina cable UTP Cat5e Bravotwist gris", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["Condunet 8699862CPC patch cord UTP Cat6 gris 2m", "CONDUNET", "redes/cableado-estructurado/patch-cords"],
  ["Complet BRC-1-002 supresor de picos 504J 8 contactos", "COMPLET", "energia/supresores-reguladores/supresores-picos"],
  ["Manhattan 423526 mousepad 6mm granel negro", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Manhattan 205146 convertidor USB a Serial DB9 RS232", "MANHATTAN", "accesorios/cables-adaptadores/usb-serial"],
  ["Manhattan 205153 convertidor USB a Serial DB9M bolsa", "MANHATTAN", "accesorios/cables-adaptadores/usb-serial"],
  ["Manhattan 432528 bateria pila CMOS 3V CR2032 2 piezas", "MANHATTAN", "energia/pilas-baterias/boton-cmos"],
  ["Intellinet 210836 pinza para crimpear RJ12 RJ45", "INTELLINET", "redes/herramientas-cableado/crimpadoras"],
  ["Intellinet 522533 tarjeta red Gigabit PCI Express", "INTELLINET", "redes/tarjetas-red/pcie"],
  ["Manhattan 160599 hub USB V2.0 4 puertos mini", "MANHATTAN", "computo/accesorios/hubs-usb"],
  ["Manhattan 179195 adaptador USB 2.0 a HDD IDE40 SATA OTB", "MANHATTAN", "computo/almacenamiento/adaptadores-usb"],
  ["Intellinet 504195 distribuidor modular 1x2 RJ45 Cat5e", "INTELLINET", "redes/cableado-estructurado/divisores-adaptadores"],
  ["Manhattan 422871 mousepad 3 en 1 microfibra gris", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Intellinet 211048 pinza para crimpear RJ11 RJ12 RJ45", "INTELLINET", "redes/herramientas-cableado/crimpadoras"],
  ["Manhattan 434362 mousepad tipo gel negro", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Intellinet 211055 pinza para ponchar jacks terminal blocks", "INTELLINET", "redes/herramientas-cableado/ponchadoras-impacto"],
  ["Manhattan 421010 limpiador pantallas 60cc", "MANHATTAN", "computo/accesorios/limpieza/limpiadores-pantalla"],
  ["Manhattan 421027 limpiador LCD kit 200cc", "MANHATTAN", "computo/accesorios/limpieza/limpiadores-pantalla"],
  ["Manhattan 140065 pasta termica jeringa 20g CPU", "MANHATTAN", "computo/componentes/pasta-termica"],
  ["Manhattan 161572 hub USB V2.0 10 puertos con fuente", "MANHATTAN", "computo/accesorios/hubs-usb"],
  ["Manhattan 423533 mousepad 6mm bolsa negro", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Intellinet 504225 cople CAT 5E modular beige", "INTELLINET", "redes/cableado-estructurado/acopladores-rj45"],
  ["Manhattan 701662 pasta termica jeringa 1.5g CPU", "MANHATTAN", "computo/componentes/pasta-termica"],
  ["Manhattan 150859 convertidor USB 2.0 a tarjeta sonido 5.1", "MANHATTAN", "computo/componentes/tarjetas-audio/usb"],
  ["Manhattan 328883 adaptador DVI 29M a HD15H", "MANHATTAN", "accesorios/cables-adaptadores/video-dvi-vga"],
  ["Manhattan 372503 cable HDMI a DVI-D M-M 1.8m", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi-dvi"],
  ["Topaz T-L460-HSB-R digitalizador de firma USB", "TOPAZ", "punto-de-venta/digitalizadores-firma"],
  ["Perfect Choice PC-030324 toallas limpiadoras pantallas", "PERFECT CHOICE", "computo/accesorios/limpieza/toallas-limpiadoras"],
  ["Perfect Choice PC-033066 limpiador liquido antiestatico 250 ml", "PERFECT CHOICE", "computo/accesorios/limpieza/liquidos-antiestaticos"],
  ["Perfect Choice PC-030089 espuma limpiadora E-Foam 400 g", "PERFECT CHOICE", "computo/accesorios/limpieza/espumas-limpiadoras"],
  ["Multimedia Screens 4365 soporte para proyector techo 20 kg", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion/soportes-proyector"],
  ["North System NORTH001-BKL rack de piso 45U 19 negro", "NORTH SYSTEM", "infraestructura/racks-enfriamiento/racks-piso"],
  ["North System NORTH051-BKL charola para monitor rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/charolas-monitor"],
  ["North System NORTH054-BKL charola para teclado 19 pulgadas", "NORTH SYSTEM", "infraestructura/racks-accesorios/charolas-teclado"],
  ["North System NORTH080-BKL charola para servidor 19 x 30", "NORTH SYSTEM", "infraestructura/racks-accesorios/charolas-servidor"],
  ["Okidata 70047803 unidad duplex B6500 B6500n", "OKIDATA", "impresion/accesorios/unidades-duplex"],
  ["OvalTech OTAC-E50 cargador laptop 65W 18.5V 4.8 x 1.7 USB", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E52 cargador laptop 90W 19.5V 7.4 x 5.0 pin central", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E51 cargador laptop 90W 19V 5.5 x 2.5 USB", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E53 adaptador computadora portatil HP 90W pin central", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E56 cargador laptop Acer 40W punta 5.5 x 1.7", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E72 adaptador netbook Asus 19V 2.1A", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E55 cargador laptop Acer 90W 19V 4.74A", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E60 cargador laptop ASUS 65W 4.0 x 1.35", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E71 cargador laptop Samsung 60W 16V 5.5 x 3.0", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["3nStar CD250 cajon de dinero negro RJ11 4 billetes 8 monedas", "3NSTAR", "punto-de-venta/cajones-dinero"],
  ["3nStar RPT001 miniprinter termica recibos 58mm USB", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar RPT004 impresora termica recibos 80mm USB Ethernet", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar RPT006S miniprinter termica 80mm USB serial ethernet", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar RPT008 thermal receipt printer 80mm RS-232 USB Ethernet", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar SC050 lector codigo de barras laser 1D USB gris", "3NSTAR", "punto-de-venta/lectores-codigo-barras"],
  ["3nStar SC100 lector codigo de barras laser USB con base", "3NSTAR", "punto-de-venta/lectores-codigo-barras"],
  ["3nStar SC310BT lector codigo de barras Bluetooth USB 1D", "3NSTAR", "punto-de-venta/lectores-codigo-barras"],
  ["4Gamers UGS-V1-BLK-4G gaming station PS5 con headset", "4GAMERS", "gaming/accesorios/estaciones-carga"],
  ["AMD Ryzen 7 5700G 100-100000263BOX AM4 8 nucleos", "AMD", "computo/componentes/procesadores"],
] as const;

describe("manual taxonomy researched batches", () => {
  it.each(researchedBatchCases)("%s -> %s", (name, brand, path) => {
    expect(classifyManualCategory({ name, brand, category: "laptops" }).path).toBe(path);
  });
});
