import { describe, expect, it } from "vitest";
import { classifyManualCategory } from "../../pb/lib/manualTaxonomy.mjs";

const researchedBatchCases = [
  ["Dbugg DB-PD64 cargador de pared USB-C PD GaN 67W", "DBUGG", "energia/cargadores-usb"],
  ["Fujitsu fi-70F escaner plano A6 USB", "FUJITSU", "impresion/escaneres"],
  ["Perfect Choice PC-085058 bolso cruzado Holdi negro", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Creative Sound Blaster GS5 barra de sonido compacta", "CREATIVE", "audio/barras-sonido"],
  ["Game Factor HSG500 headset gamer USB 7.1 RGB", "GAME FACTOR", "audio/audifonos/usb"],
  ["Huawei M-Pencil CD54-S1 lapiz optico blanco", "HUAWEI", "computo/accesorios/stylus-tablets"],
  ["Perfect Choice PC-085249 mochila escolar Bookery purpura", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["HP GT52 3YP17AL botella de tinta amarilla 70 ml", "HP", "impresion/consumibles/tinta-toner"],
  ["Perfect Choice PC-084433 mochila escolar Delfin Astro", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Duosmart E21 camara inteligente WiFi 3MP PIR", "DUOSMART", "seguridad/cctv/camaras-ip-wifi"],
  ["KSA GKSA01-B goggles de proteccion anti empanante", "KSA", "seguridad/epp/proteccion-ocular"],
  ["TopVision TBDL200A camara HD bullet 2MP TVI AHD CVI", "TOPVISION", "seguridad/cctv/camaras-turbohd"],
  ["Laces LA100KSP kit de soportes de pared para rack", "LACES", "infraestructura/racks-accesorios/soportes-pared"],
  ["Logitech PRO X 60 920-011921 teclado gaming wireless", "LOGITECH", "computo/perifericos/teclados"],
  ["Dell PowerEdge R470 R470271 servidor rack 1U", "DELL", "computo/servidores/rack"],
  ["TechZone TZLBP02 mochila laptop 15.6 pulgadas", "TECHZONE", "computo/accesorios/mochilas-fundas/mochilas-laptop"],
  ["Nexxt AW222NXT67 NPS-V11U3B charola para rack 1U", "NEXXT", "infraestructura/racks-accesorios/charolas"],
  ["Vorago KSP-205 mini bafle karaoke bluetooth RGB", "VORAGO", "audio/bocinas"],
  ["Syble XB-VP1106 verificador de precios POS", "SYBLE", "punto-de-venta/verificadores-precio"],
  ["Perfect Choice PC-085027 bolso cruzado Holdy avellana", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-085294 mochila escolar Kiddo Corazon", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Pacific Soft PSF030 punto de venta para farmacias", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Redragon Sacarab White A130W-SP keycaps PBT", "REDRAGON", "computo/perifericos/teclados/keycaps"],
  ["TP-Link Omada OC200 controlador cloud", "OMADA", "redes/controladores-cloud"],
  ["North System NORTH109-BKL organizador horizontal rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/organizadores-cable"],
  ["Vorago BSP-400 Pool Bluetooth IPX67 bocina", "VORAGO", "audio/bocinas"],
  ["PCM 10B13 papel bond plotter 0.61 x 50", "PCM", "impresion/consumibles/papel-plotter"],
  ["Necnon NPW-10FC power bank 10000 mAh", "NECNON", "energia/power-banks"],
  ["Huawei 55037722 M-Pen Lite AF63-R lapiz optico", "HUAWEI", "computo/accesorios/stylus-tablets"],
  ["Perfect Choice PC-084730 Sportiva bolso deportivo", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Vorago KSP-180 mini bafle karaoke bluetooth RGB", "VORAGO", "audio/bocinas"],
  ["Perfect Choice PC-270157 smartwatch Mercury negro", "PERFECT CHOICE", "wearables/smartwatches"],
  ["Perfect Choice PC-270218 smartwatch Minoro llamadas", "PERFECT CHOICE", "wearables/smartwatches"],
  ["Nexxt AW222NXT66 NPS-S11U3B charola lisa rack", "NEXXT", "infraestructura/racks-accesorios/charolas"],
  ["TopVision TDDL500A camara HD turret 5MP", "TOPVISION", "seguridad/cctv/camaras-turbohd"],
  ["Meriva MDL-3202A camara HD turret 2MP", "MERIVA", "seguridad/cctv/camaras-turbohd"],
  ["Vorago KSP-350 bocina bluetooth 30W", "VORAGO", "audio/bocinas"],
  ["Redragon Sacarab Pink A130P-SP keycaps PBT", "REDRAGON", "computo/perifericos/teclados/keycaps"],
  ["Verbatim 95310 DVD+R DL 8.5GB 20 pack", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Fujitsu ScanSnap SV600 escaner elevado A3", "FUJITSU", "impresion/escaneres"],
  ["Nexxt AW251NXT05 PTKCKKBSDKT01 kit basico herramientas red", "NEXXT", "redes/herramientas-cableado"],
  ["Pacific Soft SF020 punto de venta para autoservicios", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Pacific Soft PSF040 comandera movil restaurantes Android", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Kensington K64704WW VeriMark Pro fingerprint key", "KENSINGTON", "computo/accesorios/seguridad-biometrica"],
  ["Huawei Band 10 55020EKW Aluminum Blue smartwatch", "HUAWEI", "wearables/smartwatches"],
  ["Perfect Choice PC-085164 mochila escolar Arcade", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Pacific Soft KITPSF070 punto de venta para farmacias", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Orvibo SM11 sensor de puerta ventana Zigbee", "ORVIBO", "domotica/sensores"],
  ["Multimedia Screens MSC-265 pantalla de proyeccion 120", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Poly EncorePro 510 783Q1AA headset Quick Disconnect", "POLY", "audio/audifonos"],
  ["Anviz AN-C2Slim-BT control de acceso lector de huella", "ANVIZ", "seguridad/control-acceso/biometricos"],
  ["Anviz AN-EMICARD tarjeta RFID 125Khz PVC", "ANVIZ", "seguridad/control-acceso/tarjetas-rfid"],
  ["IMOU ARD311-SW contacto magnetico inalambrico", "IMOU", "domotica/sensores"],
  ["Multimedia Screens MSC-332 pantalla manual 150 16:9", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Multimedia Screens MSE-332 pantalla electrica 150 16:9", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion"],
  ["Perfect Choice PC-085089 Kiddo Monstruos mochila escolar", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-114024 Emphoria barra de audio RGB 70W", "PERFECT CHOICE", "audio/barras-sonido"],
  ["Tripp Lite N206-FP02-IND bulkhead wall plate", "TRIPP-LITE", "redes/cableado-estructurado/placas-keystone"],
  ["DataShield IS-1000 inversor cargador solar", "DATASHIELD", "energia/inversores-solares"],
  ["DataShield IS-3000 inversor solar hibrido", "DATASHIELD", "energia/inversores-solares"],
  ["Logitech G335 wired gaming headset blanco azul", "LOGITECH", "audio/audifonos"],
  ["Mirati MBJ01N exprimidor de citricos 700 ml 25 W", "MIRATI", "hogar/electrodomesticos/exprimidores"],
  ["Naceb Fornax NA-0308N diadema Bluetooth", "NACEB TECHNOLOGY", "audio/audifonos"],
  ["PCM 10B11 papel bond plotter 0.91 x 100", "PCM", "impresion/consumibles/papel-plotter"],
  ["PCM 10B5 papel bond plotter 0.91 x 100", "PCM", "impresion/consumibles/papel-plotter"],
  ["Perfect Choice PC-085225 mochila escolar Loopy rojo", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Perfect Choice PC-085300 mochila escolar Brooklyn Dinosaurios", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Poly Voyager 4310 ACCPTS1960 headset Bluetooth BT700", "POLY", "audio/audifonos"],
  ["Targus ASP71GLX-S DEFCON Compact Serialized Combo Cable Lock", "TARGUS", "accesorios/seguridad-fisica"],
  ["Verbatim 95179 DVD-RW 4.7GB 30 pack", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Zebra Z-Band Direct 10006995K pulsera termica", "ZEBRA", "impresion/consumibles/pulseras-termicas"],
  ["Acteck AC-937146 Energon S-Mate CI730 cargador inalambrico Qi", "ACTECK", "energia/cargadores-inalambricos"],
  ["Epson C33S021501 SJMB6000 maintenance box", "EPSON", "impresion/consumibles/mantenimiento"],
  ["Hisense AC121CF minisplit 1 tonelada solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["Kensington K60604WW Slim NanoSaver combination lock", "KENSINGTON", "accesorios/seguridad-fisica"],
  ["Lanix 14996 XAir 1 purificador de aire", "LANIX", "hogar/electrodomesticos/purificadores-aire"],
  ["Lenovo 4XH7A83845 PCIe riser SR630 V3", "LENOVO", "computo/servidores/componentes"],
  ["Logitech 920-010478 MX Keys Mini rosa", "LOGITECH", "computo/perifericos/teclados"],
  ["MSI GeForce RTX 5060 8G Shadow 2X OC", "MSI", "computo/componentes/tarjetas-video"],
  ["Mobifree base de carga inalambrica 10W Qi", "MOBIFREE", "energia/cargadores-inalambricos"],
  ["North System NORTH115-BKL organizador vertical rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/organizadores-cable"],
  ["Verbatim 95093 DVD-R 4.7GB 16X", "VERBATIM", "computo/almacenamiento/medios-opticos"],
  ["Manhattan 438889 London maletin laptop 15.4", "MANHATTAN", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["Badgy VBDG204EU kit YMCKO ribbon 100 impresiones", "BADGY", "punto-de-venta/credenciales-identificacion"],
  ["Zebra 10011042 Z-Perform 1000D receipt paper 3 x 80", "ZEBRA", "punto-de-venta/consumibles/rollos-termicos"],
  ["Polaroid PASU85-63 papel de sublimacion", "POLAROID", "impresion/consumibles/papel-fotografico-sublimacion"],
  ["Perfect Choice EL-994787 auriculares diadema", "PERFECT CHOICE", "audio/audifonos"],
  ["Orvibo SN11 sensor de movimiento PIR Zigbee", "ORVIBO", "domotica/sensores/movimiento"],
  ["Kingston SNA-BR2/35 SSD bracket 2.5 to 3.5", "KINGSTON TECHNOLOGY", "computo/almacenamiento/accesorios-montaje"],
  ["Jabra Speak 510 speakerphone USB Bluetooth", "JABRA", "audio/conferencia-speakerphones"],
  ["Naceb NA-0801 toallas humedas para computadoras", "NACEB TECHNOLOGY", "computo/accesorios/limpieza"],
  ["DataShield IN-5000 inversor cargador solar hibrido", "DATASHIELD", "energia/inversores-solares"],
  ["Manhattan 439893 London maletin laptop 14.1", "MANHATTAN", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["HP ScanJet Pro N4000 snw1 6FW08A escaner ADF", "HP", "impresion/escaneres"],
  ["Bin Zun R6 termometro infrarrojo sin contacto", "BIN ZUN", "salud/equipo-medico/monitoreo"],
  ["Sonolife LMT-01 oximetro de pulso digital", "SONOLIFE", "salud/equipo-medico/monitoreo"],
  ["Multimedia Screens PM-87IR pizarron interactivo 87 20 toques", "MULTIMEDIA SCREENS", "oficina/pizarrones-interactivos"],
  ["Clar Systems CSY090 dispensador de toalla", "CLAR SYSTEMS", "oficina/limpieza-higiene/dispensadores"],
  ["Kensington K64430S MicroSaver 2.0 keyed chassis lock", "KENSINGTON", "accesorios/seguridad-fisica"],
  ["Kensington K60412WW SmartFit Conform Back Rest", "KENSINGTON", "oficina/ergonomia/soportes-lumbares"],
  ["Lenovo 5PS0A23193 3 year ADP warranty extension", "LENOVO", "servicios/garantias-extendidas"],
  ["HP ScanJet Pro N4600 fnw1 escaner documental", "HP", "impresion/escaneres"],
  ["Targus AEH101TT Wired Mono Headset", "TARGUS", "audio/audifonos"],
  ["Acteck AC-934961 Glee Max AP460 bocina Bluetooth 10W", "ACTECK", "audio/bocinas"],
  ["Hisense AC122CF minisplit 1 tonelada solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["Pacific Soft KITPSF060 punto de venta para restaurantes", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Pacific Soft KITPSF050 punto de venta para restaurantes", "PACIFIC SOFT", "punto-de-venta/software-pos"],
  ["Acteck BS685 Dynamic Exact bocinas tipo estudio 80W", "ACTECK", "audio/bocinas"],
  ["Acteck CP20W cargador de pared USB-C 20W", "ACTECK", "energia/cargadores-usb"],
  ["Acteck BS465 Dynamic Trim barra de sonido 2.1 60W", "ACTECK", "audio/barras-sonido"],
  ["APC AP9643 Network Management Card 3 NMC3", "APC", "energia/accesorios-ups/tarjetas-snmp"],
  ["Verbatim 49976 CD DVD paper sleeves with clear window", "VERBATIM", "computo/almacenamiento/medios-opticos/accesorios"],
  ["Acteck CI710 cargador de pared USB", "ACTECK", "energia/cargadores-usb"],
  ["Perfect Choice PC-084396 mochila", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["HP DesignJet T200/T600 automatic sheet feeder 8AJ60A", "HP", "impresion/accesorios/bandejas-alimentadores"],
  ["DataShield IN-6000 inversor cargador solar", "DATASHIELD", "energia/inversores-solares"],
  ["Stylos STASWM3CA smartwatch azul", "STYLOS", "wearables/smartwatches"],
  ["Stylos STASWM3CB smartwatch negro", "STYLOS", "wearables/smartwatches"],
  ["Stylos STASWM3CP smartwatch rosa", "STYLOS", "wearables/smartwatches"],
  ["Acteck Shift Plus AB424 receptor Bluetooth 3.5 mm", "ACTECK", "audio/adaptadores-bluetooth"],
  ["Microsoft Windows 11 Pro FQC-10572 ESD descarga digital", "MICROSOFT", "software/sistemas-operativos"],
  ["CDP UPO22-10 UPS online doble conversion 10 kVA", "CDP", "energia/no-breaks-ups/doble-conversion"],
  ["Acteck Dynamic Exact R BS700 bocinas Bluetooth 50W", "ACTECK", "audio/bocinas"],
  ["Hisense WSA1102PCN lavadora semiautomatica doble tina", "HISENSE", "hogar/electrodomesticos/lavadoras"],
  ["Hisense ACR242KG minisplit 2 toneladas solo frio", "HISENSE", "hogar/electrodomesticos/aires-acondicionados"],
  ["TP-Link DeltaStream DS-P7001-16 OLT GPON", "TP-LINK", "redes/fibra-optica/olt-gpon"],
  ["Norton 360 Deluxe 21414731 3 dispositivos 1 ano", "NORTON", "software/seguridad"],
  ["Autodesk AutoCAD LT 2025 057Q1-WW6525-L347", "AUTODESK", "software/cad-diseno"],
  ["Zoomy ZWF01 bebedero fuente para mascotas 1.5 L", "ZOOMY", "mascotas/bebederos-fuentes"],
  ["Dell Essential Backpack 15 ES1520P mochila laptop", "DELL", "computo/accesorios/mochilas-fundas/mochilas-laptop"],
  ["Microsoft Office Home 2024 EP2-06874 ESD", "MICROSOFT", "software/productividad-oficina"],
  ["Scooter electrico Stylos M2 STSCM02B negro", "STYLOS", "movilidad/scooters-electricos"],
  ["Hisense HS1000 barra de sonido 2.0 120W", "HISENSE", "audio/barras-sonido"],
  ["Poly TC10 875K5AA touch controller video conferencia", "POLYCOM", "colaboracion/video-conferencia/controladores"],
  ["Jabra Speak 510 MS 7510-109 speakerphone USB Bluetooth", "JABRA", "audio/conferencia-speakerphones"],
  ["BenQ InstaShare Button TWY31 transmisor inalambrico", "BENQ", "colaboracion/presentacion-inalambrica"],
  ["Scooter electrico Stylos M3 STSCM03O naranja", "STYLOS", "movilidad/scooters-electricos"],
  ["Vorago BSP-320 mini barra de sonido Bluetooth RGB", "VORAGO", "audio/barras-sonido"],
  ["TP-Link Tapo RV30 Max robot aspirador y trapeador", "TP-LINK", "hogar/electrodomesticos/aspiradoras-robot"],
  ["Perfect Choice PC-085317 mochila escolar Brooklyn Flores", "PERFECT CHOICE", "oficina/mochilas-bolsas"],
  ["Netis NB50 CPE 450Mbps exterior punto a punto", "NETIS", "redes/radioenlaces-antenas"],
  ["Huawei WATCH FIT 4 Pro 55020FAD smartwatch verde", "HUAWEI", "wearables/smartwatches"],
  ["Acteck BS600 Dynamic Thin barra de sonido 2.1 60W", "ACTECK", "audio/barras-sonido"],
  ["Uniarch UHO-S2E-M3 camara IP mini PT WiFi 3MP", "UNIARCH", "seguridad/cctv/camaras-ip-wifi"],
  ["APC RBC35 bateria de reemplazo UPS Back-UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["Condumex 664464 bobina cable UTP Cat5e exterior con gel", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["Condumex 66446815 bobina cable UTP Cat6 interior azul", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["Condumex 66446835 bobina cable UTP Cat6 interior gris", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["WAM RG59UL-305B cable siames RG-59 CCTV", "WAM", "seguridad/cctv/cable-coaxial-siames"],
  ["Condumex 66445632 bobina cable UTP Cat5e Bravotwist gris", "CONDUMEX", "redes/cableado-estructurado/bobinas-utp"],
  ["Condunet 8699862CPC patch cord UTP Cat6 gris 2m", "CONDUNET", "redes/cableado-estructurado/patch-cords"],
  ["Complet BRC-1-002 supresor de picos 504J 8 contactos", "COMPLET", "energia/supresores-reguladores/supresores-picos"],
  ["Manhattan 423526 mousepad 6mm granel negro", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Manhattan 205146 convertidor USB a Serial DB9 RS232", "MANHATTAN", "accesorios/cables-adaptadores/usb-serial"],
  ["Manhattan 205153 convertidor USB a Serial DB9M bolsa", "MANHATTAN", "accesorios/cables-adaptadores/usb-serial"],
  ["Manhattan 432528 bateria pila CMOS 3V CR2032 2 piezas", "MANHATTAN", "energia/pilas-baterias/boton-cmos"],
  ["Intellinet 210836 pinza para crimpear RJ12 RJ45", "INTELLINET", "redes/herramientas-cableado/crimpadoras"],
  ["Intellinet 522533 tarjeta red Gigabit PCI Express", "INTELLINET", "redes/tarjetas-red/pcie"],
  ["Manhattan 160599 hub USB V2.0 4 puertos mini", "MANHATTAN", "computo/accesorios/hubs-usb"],
  ["Manhattan 179195 adaptador USB 2.0 a HDD IDE40 SATA OTB", "MANHATTAN", "computo/almacenamiento/adaptadores-usb"],
  ["Intellinet 504195 distribuidor modular 1x2 RJ45 Cat5e", "INTELLINET", "redes/cableado-estructurado/divisores-adaptadores"],
  ["Manhattan 422871 mousepad 3 en 1 microfibra gris", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Intellinet 211048 pinza para crimpear RJ11 RJ12 RJ45", "INTELLINET", "redes/herramientas-cableado/crimpadoras"],
  ["Manhattan 434362 mousepad tipo gel negro", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Intellinet 211055 pinza para ponchar jacks terminal blocks", "INTELLINET", "redes/herramientas-cableado/ponchadoras-impacto"],
  ["Manhattan 421010 limpiador pantallas 60cc", "MANHATTAN", "computo/accesorios/limpieza/limpiadores-pantalla"],
  ["Manhattan 421027 limpiador LCD kit 200cc", "MANHATTAN", "computo/accesorios/limpieza/limpiadores-pantalla"],
  ["Manhattan 140065 pasta termica jeringa 20g CPU", "MANHATTAN", "computo/componentes/pasta-termica"],
  ["Manhattan 161572 hub USB V2.0 10 puertos con fuente", "MANHATTAN", "computo/accesorios/hubs-usb"],
  ["Manhattan 423533 mousepad 6mm bolsa negro", "MANHATTAN", "computo/accesorios/mousepads"],
  ["Intellinet 504225 cople CAT 5E modular beige", "INTELLINET", "redes/cableado-estructurado/acopladores-rj45"],
  ["Manhattan 701662 pasta termica jeringa 1.5g CPU", "MANHATTAN", "computo/componentes/pasta-termica"],
  ["Manhattan 150859 convertidor USB 2.0 a tarjeta sonido 5.1", "MANHATTAN", "computo/componentes/tarjetas-audio/usb"],
  ["Manhattan 328883 adaptador DVI 29M a HD15H", "MANHATTAN", "accesorios/cables-adaptadores/video-dvi-vga"],
  ["Manhattan 372503 cable HDMI a DVI-D M-M 1.8m", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi-dvi"],
  ["Topaz T-L460-HSB-R digitalizador de firma USB", "TOPAZ", "punto-de-venta/digitalizadores-firma"],
  ["Perfect Choice PC-030324 toallas limpiadoras pantallas", "PERFECT CHOICE", "computo/accesorios/limpieza/toallas-limpiadoras"],
  ["Perfect Choice PC-033066 limpiador liquido antiestatico 250 ml", "PERFECT CHOICE", "computo/accesorios/limpieza/liquidos-antiestaticos"],
  ["Perfect Choice PC-030089 espuma limpiadora E-Foam 400 g", "PERFECT CHOICE", "computo/accesorios/limpieza/espumas-limpiadoras"],
  ["Multimedia Screens 4365 soporte para proyector techo 20 kg", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion/soportes-proyector"],
  ["North System NORTH001-BKL rack de piso 45U 19 negro", "NORTH SYSTEM", "infraestructura/racks-enfriamiento/racks-piso"],
  ["North System NORTH051-BKL charola para monitor rack", "NORTH SYSTEM", "infraestructura/racks-accesorios/charolas-monitor"],
  ["North System NORTH054-BKL charola para teclado 19 pulgadas", "NORTH SYSTEM", "infraestructura/racks-accesorios/charolas-teclado"],
  ["North System NORTH080-BKL charola para servidor 19 x 30", "NORTH SYSTEM", "infraestructura/racks-accesorios/charolas-servidor"],
  ["Okidata 70047803 unidad duplex B6500 B6500n", "OKIDATA", "impresion/accesorios/unidades-duplex"],
  ["OvalTech OTAC-E50 cargador laptop 65W 18.5V 4.8 x 1.7 USB", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E52 cargador laptop 90W 19.5V 7.4 x 5.0 pin central", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E51 cargador laptop 90W 19V 5.5 x 2.5 USB", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E53 adaptador computadora portatil HP 90W pin central", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E56 cargador laptop Acer 40W punta 5.5 x 1.7", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E72 adaptador netbook Asus 19V 2.1A", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E55 cargador laptop Acer 90W 19V 4.74A", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E60 cargador laptop ASUS 65W 4.0 x 1.35", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["OvalTech OTAC-E71 cargador laptop Samsung 60W 16V 5.5 x 3.0", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["3nStar CD250 cajon de dinero negro RJ11 4 billetes 8 monedas", "3NSTAR", "punto-de-venta/cajones-dinero"],
  ["3nStar RPT001 miniprinter termica recibos 58mm USB", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar RPT004 impresora termica recibos 80mm USB Ethernet", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar RPT006S miniprinter termica 80mm USB serial ethernet", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar RPT008 thermal receipt printer 80mm RS-232 USB Ethernet", "3NSTAR", "punto-de-venta/impresoras-recibos"],
  ["3nStar SC050 lector codigo de barras laser 1D USB gris", "3NSTAR", "punto-de-venta/lectores-codigo-barras"],
  ["3nStar SC100 lector codigo de barras laser USB con base", "3NSTAR", "punto-de-venta/lectores-codigo-barras"],
  ["3nStar SC310BT lector codigo de barras Bluetooth USB 1D", "3NSTAR", "punto-de-venta/lectores-codigo-barras"],
  ["4Gamers UGS-V1-BLK-4G gaming station PS5 con headset", "4GAMERS", "gaming/accesorios/estaciones-carga"],
  ["AMD Ryzen 7 5700G 100-100000263BOX AM4 8 nucleos", "AMD", "computo/componentes/procesadores"],
  ["AMD Ryzen 5 5500 100-100000457BOX AM4 6 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 7 7800X3D 100-100000910WOF AM5 8 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-x3d"],
  ["AMD Ryzen 7 9800X3D 100-100001084WOF AM5 8 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-x3d"],
  ["AMD Ryzen 7 8700G 100-100001236SBX AM5 Radeon 780M", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 5 5600XT 100-100001585BOX AM4 6 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 7 8700F 100-100001590BOX AM5 sin graficos", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 5 8400F 100-100001591BOX AM5 sin graficos", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 5 4500 100-100000644BOX AM4 6 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 5 5500 CPUAMD2520 AM4 6 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 5 5600GT 100-100001488BOX AM4 Radeon", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 5 5600X CPUAMD2140 AM4 6 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 7 5700X CPUAMD2500 AM4 8 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am4"],
  ["AMD Ryzen 7 9700X CPUAMD2740 AM5 Zen 5", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 5 7600X CPUAMD2420 AM5 6 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 9 7900 CPUAMD2480 AM5 12 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 7 8700G CPUAMD2580 AM5 Radeon 780M", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 9 9900X CPUAMD2750 AM5 12 nucleos", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Athlon 3000G CPUAMD2050 Radeon Vega 3", "AMD", "computo/componentes/procesadores/amd-athlon"],
  ["AMD Ryzen 5 8600G CPUAMD2670 AM5 Radeon 760M", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AMD Ryzen 5 8500G CPUAMD2680 AM5 Radeon 740M", "AMD", "computo/componentes/procesadores/amd-ryzen-am5"],
  ["AOC 22B35HM23 monitor 21.5 FHD 120Hz", "AOC", "computo/monitores/oficina"],
  ["AOC 24B35H3 monitor 23.8 FHD IPS", "AOC", "computo/monitores/oficina"],
  ["AOC 24G50F monitor gamer 23.8 FHD 144Hz", "AOC", "computo/monitores/gaming"],
  ["AOC 27B35H3 monitor 27 FHD IPS 120Hz", "AOC", "computo/monitores/oficina"],
  ["AOC 27G4E monitor gamer 27 FHD 180Hz", "AOC", "computo/monitores/gaming"],
  ["AOC 27G50F monitor gamer 27 FHD 180Hz", "AOC", "computo/monitores/gaming"],
  ["AOC C24G2 monitor gamer curvo 23.6 165Hz", "AOC", "computo/monitores/gaming"],
  ["AOC CQ32G2S monitor gamer curvo QHD 165Hz", "AOC", "computo/monitores/gaming"],
  ["AOC CU34V5CW/BK monitor curvo ultrawide USB-C webcam", "AOC", "computo/monitores/oficina"],
  ["AOC G2490VX monitor gamer 23.8 FHD 144Hz", "AOC", "computo/monitores/gaming"],
  ["AOC G2790VX monitor gamer 27 FHD 144Hz", "AOC", "computo/monitores/gaming"],
  ["AOC Q27P3CW monitor profesional USB-C webcam QHD", "AOC", "computo/monitores/oficina"],
  ["APC AP6037A NetShelter Basic Rack PDU 208V 8.6kW", "APC", "energia/pdu-rack"],
  ["APC AP9335TH sensor de temperatura y humedad NetBotz", "APC", "energia/accesorios-ups/sensores-ambientales"],
  ["APC AP9562 Basic Rack PDU 1U 15A 120V", "APC", "energia/pdu-rack"],
  ["APC AP9641 UPS Network Management Card 3 NMC3", "APC", "energia/accesorios-ups/tarjetas-snmp"],
  ["APC APCRBC110 cartucho bateria reemplazo UPS 12V 7Ah", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC115 cartucho bateria reemplazo UPS 48V", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC123 cartucho bateria reemplazo hot-swap", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC124 bateria de reemplazo Back-UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC133 cartucho de bateria de sustitucion APC", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC143 replacement battery cartridge 143", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC152 cartucho bateria UPS Smart-UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC154 replacement battery cartridge 154", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC155 bateria de reemplazo UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC159 cartucho bateria reemplazo 12V 9Ah", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC APCRBC160 bateria de reemplazo Back-UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC BE425M-LM Back-UPS 425VA standby 120V", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BE600M1-LM Back-UPS ES 600VA USB", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BE650G1-LM Back-UPS 650VA 390W", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BE850M2-LM Back-UPS ES 850VA 2 USB", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BR1100M2-LM Back-UPS Pro 1100VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BR1350M2-LM Back-UPS Pro 1350VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BR1500M2-LM Back-UPS Pro 1500VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BR1500RM2U Back-UPS Pro 1500VA rack tower 2U", "APC", "energia/no-breaks-ups/rack"],
  ["APC BR700G Back-UPS Pro 700VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BV1000 Easy UPS BV 1000VA AVR", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BV500 Easy UPS 500VA AVR", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BV650 Easy UPS 650VA AVR", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BVX700LU-LM Back-UPS 700VA AVR USB", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BVX900L-LM Back-UPS 900VA AVR", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BX1000M-LM60 Back-UPS Pro 1000VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BX1200M-LM Back-UPS 1200VA AVR", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BX1350M-LM60 Back-UPS Pro 1350VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC BX850M-LM60 Back-UPS Pro 850VA AVR LCD", "APC", "energia/no-breaks-ups/line-interactive"],
  ["APC RBC2 cartucho de bateria de recambio", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["APC RBC23 bateria de reemplazo Smart-UPS", "APC", "energia/baterias-ups/cartuchos-reemplazo"],
  ["Acer Aspire Lite AL14-32P-39TB laptop Core 3 N355 14 WUXGA", "ACER", "computo/laptops"],
  ["Acer Aspire Lite AL16-54P-580M laptop Core i5 16 WUXGA", "ACER", "computo/laptops"],
  ["Acer EAK030 kit teclado y mouse USB negro", "ACER", "computo/perifericos/combos-teclado-mouse"],
  ["Acer EK221Q Hbi monitor 21.5 FHD 100Hz", "ACER", "computo/monitores/oficina"],
  ["Acer EK241Y P0bi monitor 23.8 FHD 144Hz", "ACER", "computo/monitores/gaming"],
  ["Acer EK271 GBI monitor 27 FHD 120Hz", "ACER", "computo/monitores/oficina"],
  ["Acer EKW111 combo teclado y mouse inalambrico", "ACER", "computo/perifericos/combos-teclado-mouse"],
  ["Acer EMR213-BK mouse inalambrico 1600 DPI", "ACER", "computo/perifericos/mouse/inalambricos"],
  ["Acer EMR213-WH wireless mouse blanco 1600 DPI", "ACER", "computo/perifericos/mouse/inalambricos"],
  ["Acer EMW211 mouse inalambrico gris 1600 DPI", "ACER", "computo/perifericos/mouse/inalambricos"],
  ["Acer TravelMate P2 TMP214-55-G2-56PW laptop empresarial 14", "ACER", "computo/laptops"],
  ["Acer TravelMate P2 TMP214-56-G2-56G4 laptop Core Ultra 5", "ACER", "computo/laptops"],
  ["Acer TravelMate P2 TMP214-76-G2-51B9 laptop Core Ultra 5", "ACER", "computo/laptops"],
  ["Acer TravelMate P2 TMP216-51-51NA laptop 16 Core i5", "ACER", "computo/laptops"],
  ["Acer TravelMate P2 TMP216-51-G2-59U9 laptop 16 Core i5", "ACER", "computo/laptops"],
  ["Acer TravelMate P2 TMP216-51-G2-79K7 laptop 16 Core i7", "ACER", "computo/laptops"],
  ["Acer KC272 P6BIP monitor 27 FHD 144Hz IPS", "ACER", "computo/monitores/gaming"],
  ["Acer EK241Y P0BI UM.QE1AA.009 monitor 23.8 144Hz", "ACER", "computo/monitores/gaming"],
  ["Acer KA242Y GOBI monitor 23.8 FHD 120Hz IPS", "ACER", "computo/monitores/oficina"],
  ["Acer XZ320Q X2bmiiphx monitor curvo 31.5 240Hz", "ACER", "computo/monitores/gaming"],
  ["Acteck Inspire TI215 AC-913973 teclado inalambrico multimedia", "ACTECK", "computo/perifericos/teclados/inalambricos"],
  ["Acteck Optimize MI440 R100 AC-916462 mouse inalambrico 1600 DPI", "ACTECK", "computo/perifericos/mouse/inalambricos"],
  ["Acteck Optimize MA210 AC-928830 mouse alambrico USB 1200 DPI", "ACTECK", "computo/perifericos/mouse/alambricos"],
  ["Acteck Optimize MI240 AC-928885 mouse inalambrico 1200 DPI", "ACTECK", "computo/perifericos/mouse/inalambricos"],
  ["Acteck Inspire TA210 AC-928946 teclado alambrico USB", "ACTECK", "computo/perifericos/teclados/alambricos"],
  ["Acteck Creator MK210 AC-928984 kit teclado y mouse USB", "ACTECK", "computo/perifericos/combos-teclado-mouse"],
  ["Acteck Atom GS240 AC-929042 gabinete micro torre slim", "ACTECK", "computo/componentes/gabinetes"],
  ["Acteck Kioto GC240 AC-932547 gabinete mini torre", "ACTECK", "computo/componentes/gabinetes"],
  ["Acteck Inspire TN220 AC-932622 teclado numerico USB", "ACTECK", "computo/perifericos/teclados/numericos"],
  ["Acteck Kioto GC220 AC-933063 gabinete micro ATX slim", "ACTECK", "computo/componentes/gabinetes"],
  ["OvalTech OTAC-E65 adaptador corriente laptop ASUS 19V 1.75A USB", "OVALTECH", "computo/accesorios/cargadores-laptop"],
  ["PCM B7670 rollo papel bond 76 x 70 punto venta", "PCM", "punto-de-venta/consumibles/rollos-bond"],
  ["PCM EBA5760 rollo autocopia blanco amarillo 57 x 60", "PCM", "punto-de-venta/consumibles/rollos-autocopia"],
  ["PCM BRA7670 rollo autocopiante 76 x 70 R/B/A", "PCM", "punto-de-venta/consumibles/rollos-autocopia"],
  ["PCM B38X70 rollo bond blanco", "PCM", "punto-de-venta/consumibles/rollos-bond"],
  ["PCM B5760 rollo bond satinado 57 x 60", "PCM", "punto-de-venta/consumibles/rollos-bond"],
  ["PCM T5760 rollo termico 57 x 60 c100", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T5745 rollo termico 57 x 45 c175", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T8070C50 rollo termico 80 x 70 c50", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T8080 rollo termico 80 x 80", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["PCM T5736MMS12K rollo termico 57 x 36", "PCM", "punto-de-venta/consumibles/rollos-termicos"],
  ["Provision ISR PR-C08 adaptador alimentacion DC macho CCTV", "PROVISION-ISR", "seguridad/cctv/accesorios-cableado"],
  ["Provision ISR PR-C13 conector BNC macho RG59", "PROVISION-ISR", "seguridad/cctv/accesorios-cableado"],
  ["Provision ISR PR-10A9CH+ fuente poder CCTV 12V 10A 9 canales", "PROVISION-ISR", "seguridad/cctv/fuentes-poder"],
  ["Provision ISR PR-12A16CH+ fuente poder CCTV 12V 12A 16 canales", "PROVISION-ISR", "seguridad/cctv/fuentes-poder"],
  ["Provision ISR PR-12V1A-A fuente poder individual 12V 1A", "PROVISION ISR", "seguridad/cctv/fuentes-poder"],
  ["Provision ISR PR-C14 divisor fuente poder 1 entrada 4 salidas", "PROVISION ISR", "seguridad/cctv/accesorios-cableado"],
  ["Provision ISR PR-C09 adaptador alimentacion CCTV", "PROVISION-ISR", "seguridad/cctv/accesorios-cableado"],
  ["TechZone TZEST01N maletin laptop 15.6 nylon negro", "TECHZONE", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["TechZone TZBTS10BLK mochila laptop 15.6 negro", "TECHZONE", "computo/accesorios/mochilas-fundas/mochilas-laptop"],
  ["UNV IPC3624LE-ADF28K-WP-L camara IP turret PoE ColorHunter", "UNV", "seguridad/cctv/camaras-ip-poe"],
  ["Brobotix 406351 cable HDMI 2.0 espiral 8K 60Hz", "BROBOTIX", "accesorios/cables-adaptadores/video-hdmi"],
  ["TP-Link Omada EAP773 BE11000 Wi-Fi 7 access point", "TP-LINK", "redes/access-points/wifi-7"],
  ["Brobotix 6006528 maletin portafolio neopreno laptop", "BROBOTIX", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["Brobotix 263786 plug RJ45 Cat5e bote 100 piezas", "BROBOTIX", "redes/cableado-estructurado/conectores-rj45"],
  ["Perfect Choice PC-084716 Branston portafolio laptop", "PERFECT CHOICE", "computo/accesorios/mochilas-fundas/maletines-laptop"],
  ["Silimex Laptop Cleaner kit limpieza laptop", "SILIMEX", "computo/accesorios/limpieza/kits-limpieza"],
  ["Game Factor MAG500 brazo para microfono ajustable", "GAME FACTOR", "audio/microfonos/soportes-brazos"],
  ["Gigabyte B850 Eagle WiFi6E tarjeta madre socket AM5", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am5"],
  ["Lenovo ThinkPad T14 Gen 6 21QK000WLM laptop empresarial", "LENOVO", "computo/laptops/empresariales"],
  ["Xzeal X-Tron XZGAXT1B gabinete gamer Mid Tower ATX 4 ARGB", "XZEAL", "computo/componentes/gabinetes/gaming"],
  ["Uniarch Uho-S3S-M33D camara IP doble lente WiFi interior", "UNIARCH", "seguridad/cctv/camaras-ip-wifi/interior"],
  ["UNV IPC3K28SE-ADF28KMC-DL-I0 turret ColorHunter Omniview", "UNV", "seguridad/cctv/camaras-ip-poe/panoramicas"],
  ["Provision ISR Z4-25IPEN-2 IR camara PTZ IP x25", "PROVISION-ISR", "seguridad/cctv/camaras-ip-poe/ptz"],
  ["BRobotix 6006627 cargador de pared USB tipo C 20W", "BROBOTIX", "energia/cargadores-usb/pared-usb-c"],
  ["Dahua S042-1A120300HU adaptador 12VDC 3A CCTV", "DAHUA", "seguridad/cctv/fuentes-poder"],
  ["Epson T504320-AL botella tinta magenta EcoTank", "EPSON", "impresion/consumibles/botellas-tinta-ecotank"],
  ["Grandstream UCM6304A conmutador IP PBX 4 FXO 4 FXS", "GRANDSTREAM", "telefonia/pbx-ip"],
  ["Logitech PRO X SUPERLIGHT 2 910-006637 mouse inalambrico", "LOGITECH", "computo/perifericos/mouse/inalambricos/gaming"],
  ["Manhattan 179843 audifonos USB con microfono flexible", "MANHATTAN", "audio/audifonos/usb"],
  ["TP-Link Omada EAP660 HD access point AX3600 Wi-Fi 6", "TP-LINK", "redes/access-points/wifi-6"],
  ["Naceb Boreal NA-0656B enfriamiento liquido 360 mm blanco", "NACEB", "computo/componentes/enfriamiento/liquido-cpu"],
  ["Brother WT229CL waste toner box contenedor de desperdicio", "BROTHER", "impresion/consumibles/contenedores-desperdicio"],
  ["MSI A520M-A PRO tarjeta madre AMD AM4 micro ATX", "MSI", "computo/componentes/tarjetas-madre/amd-am4"],
  ["Logitech Ultimate Ears BOOM 3 984-001358 bocina bluetooth roja", "LOGITECH", "audio/bocinas/bluetooth"],
  ["Manhattan 353243 cable HDMI activo fibra optica 20 m", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/fibra-optica"],
  ["Brother DR433CL drum unit unidad de tambor color", "BROTHER", "impresion/consumibles/tambores"],
  ["Gigabyte H610M K V2 tarjeta madre Intel LGA1700 DDR5", "GIGABYTE", "computo/componentes/tarjetas-madre/intel-lga1700"],
  ["Meriva MDL-5202A camara HD bullet 4 en 1 AHD TVI CVI", "MERIVA", "seguridad/cctv/camaras-turbohd/bullet"],
  ["ASUS ExpertBook P1 P1403CVA-i58G512-P1 laptop empresarial", "ASUS", "computo/laptops/empresariales"],
  ["TP-Link Archer TXE70UH adaptador USB Wi-Fi 6E tribanda", "TP-LINK", "redes/adaptadores-wifi/usb"],
  ["Brother TN815Y toner amarillo alto rendimiento 12000 paginas", "BROTHER", "impresion/consumibles/toner-laser"],
  ["Seagate ST2000LM015 BarraCuda disco duro 2TB 2.5 SATA 5400RPM", "SEAGATE", "computo/almacenamiento/discos-duros/2-5-sata"],
  ["WD Green SN350 WDS500G2G0C SSD 500GB M.2 2280 NVMe PCIe Gen3", "SANDISK", "computo/almacenamiento/ssd/m2-nvme"],
  ["Hikvision DS-2CD3T86G2H-LISU camara bala IP 8MP", "HIKVISION", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Forza FSI-3011RUL UPS 3000VA 2700W bastidor torre", "FORZA", "energia/no-breaks-ups/rack-torre"],
  ["Manhattan 190329 mouse optico inalambrico USB", "MANHATTAN", "computo/perifericos/mouse/inalambricos"],
  ["HPE ProLiant ML350 Gen11 servidor torre P75341-DM5", "HPE", "computo/servidores/torre"],
  ["Panasonic KX-TGB310MEB telefono inalambrico LCD ambar", "PANASONIC", "telefonia/telefonos/inalambricos"],
  ["CyberPower AVRG750LCD no break 760VA 450W interactivo LCD", "CYBERPOWER", "energia/no-breaks-ups/line-interactive"],
  ["Acteck ONEX GS450 AC-943086 gabinete mini torre slim", "ACTECK", "computo/componentes/gabinetes/mini-tower"],
  ["Manhattan 333405 cable USB 2.0 A-B 1.8m", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-b"],
  ["Perfect Choice PC-113102 Goliat bocina Bluetooth 50W", "PERFECT CHOICE", "audio/bocinas/bluetooth"],
  ["Creative Labs ZEN Hybrid 2 CR audifonos Bluetooth ANC", "CREATIVE", "audio/audifonos/bluetooth"],
  ["Brother TN433Y toner amarillo 4000 paginas", "BROTHER", "impresion/consumibles/toner-laser"],
  ["Xerox 113R00670 tambor Phaser 5500", "XEROX", "impresion/consumibles/tambores"],
  ["BRobotix 000140 cable corriente CPU NEMA 5-15 C13", "BROBOTIX", "accesorios/cables-adaptadores/energia/corriente-cpu"],
  ["TP-Link Deco S7 2 Pack router WiFi Mesh AC1900", "TP-LINK", "redes/routers/mesh-wifi"],
  ["Acteck MI790 mouse trackball ergonomico inalambrico", "ACTECK", "computo/perifericos/mouse/inalambricos/trackball"],
  ["Grandstream GXP1630 telefono IP 3 cuentas SIP PoE", "GRANDSTREAM", "telefonia/telefonos-ip"],
  ["ADATA AD5S480016G-S memoria SO-DIMM DDR5 16GB 4800MHz CL40", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr5"],
  ["Intellinet 517874 caja para pared single gang 4.8cm", "INTELLINET", "redes/cableado-estructurado/cajas-pared"],
  ["Creative Stage SE mini MF8460 soundbar Bluetooth USB-C", "CREATIVE LABS", "audio/barras-sonido/pc"],
  ["Game Factor MDTD400 cable Mini DisplayPort a DisplayPort 2m 4K", "GAME FACTOR", "accesorios/cables-adaptadores/video-displayport"],
  ["Dahua DH-HAC-T1A51N-U-IL-A camara HDCVI 5MP Smart Dual Light", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi"],
  ["Corsair USB100 CU-9000003-NA hub USB-C USB-A 7 puertos", "CORSAIR", "computo/accesorios/hubs-usb/usb-c"],
  ["Vortred Helmet V-930174 audifonos TWS gamer Bluetooth", "VORTRED", "audio/audifonos/bluetooth/tws"],
  ["Huawei MatePad SE 11 53014GYW tableta 8GB 128GB", "HUAWEI", "computo/tabletas"],
  ["Urban Balance UBSC11 dock USB-C 11 en 1 100W", "URBAN BALANCE", "computo/accesorios/docks-hubs/usb-c"],
  ["Zebra 800033-840 cinta YMCKO ZXP Series 3 200 impresiones", "ZEBRA", "impresion/consumibles/cintas-tarjetas"],
  ["UNV IPC2B18SE-ADF28K-WP-I1 OwlView Plus camara IP bullet 8MP PoE", "UNIVIEW", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Naceb Raptor KITNCB100 kit teclado y mouse gamer", "NACEB TECHNOLOGY", "computo/perifericos/combos-teclado-mouse/gaming"],
  ["Microsoft 365 Business Standard KLQ-00698 licencia FPP 1 usuario", "MICROSOFT", "software/productividad-oficina/microsoft-365"],
  ["Epson EcoTank L3210 C11CJ68301 multifuncional tinta continua", "EPSON", "impresion/impresoras/multifuncionales-ecotank"],
  ["TP-Link SG2016P Omada switch 16 puertos 8 puertos PoE", "TP-LINK", "redes/switches/poe-administrables"],
  ["Balam Rush MRX8000 escritorio gamer Olympus Spot Glow RGB", "BALAM RUSH", "gaming/mobiliario/escritorios"],
  ["Mercusys MW325R router inalambrico 300Mbps 4 antenas", "TP-LINK", "redes/routers/wifi-n"],
  ["Acteck Captive Vivid SP245 monitor 24.5 FHD 75Hz", "ACTECK", "computo/monitores/oficina/24-25-fhd"],
  ["Provision-ISR NVR16-641600RFAN(2U) NVR 64CH 16MP", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/nvr-ip"],
  ["Logitech Brio 300 960-001440 webcam FHD 1080p USB-C", "LOGITECH", "computo/perifericos/webcams/usb-fhd"],
  ["Lenovo ThinkSystem ST45 V3 7DH4A00GLA servidor torre AMD EPYC", "LENOVO", "computo/servidores/torre"],
  ["BRobotix 938276 tapa faceplate 1 panel para jack", "BROBOTIX", "redes/cableado-estructurado/placas-keystone"],
  ["Manhattan 460941 soporte TV pared 32 a 55 35kg ajuste vertical", "MANHATTAN", "video/soportes-tv/pared"],
  ["EZVIZ CSH5/3MP/POE camara H5 PoE 3MP", "EZVIZ", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Dell 460-BCYY GM1720PM Gaming Backpack 17 pulgadas", "DELL", "computo/accesorios/mochilas-fundas/mochilas-gaming"],
  ["Grandstream GWN7615 access point WiFi 5 MU-MIMO 3x3", "GRANDSTREAM", "redes/access-points/wifi-5"],
  ["Silimex 7503018454344 alcohol isopropilico 500 ml mini trigger", "SILIMEX", "computo/accesorios/limpieza/alcohol-isopropilico"],
  ["Uniarch NVR-108S3-P8-ECO NVR 8 canales PoE 6MP", "UNIARCH", "seguridad/cctv/dvr-nvr/nvr-ip"],
  ["Dahua DH-XVR1B08-I/T XVR HDCVI 8 canales WizSense", "DAHUA", "seguridad/cctv/dvr-nvr/xvr-hdcvi"],
  ["Naceb Gaming NA-0925 kit gamer teclado mouse USB 2400 DPI headset mousepad", "NACEB", "computo/perifericos/kits-gamer/4-en-1"],
  ["MSI GeForce RTX 3050 LP 6G OC GDDR6 96-bit", "MSI", "computo/componentes/tarjetas-video/nvidia-geforce"],
  ["Xerox 108R01420 tambor negro WorkCentre 6515 48000 paginas", "XEROX", "impresion/consumibles/tambores/xerox"],
  ["Ajax TurretCam5MP CI121AJX01 camara IP turret 5MP NVR Ajax", "AJAX", "seguridad/cctv/camaras-ip-poe/turret"],
  ["Brother DCPB7640DW multifuncional laser 36 ppm duplex WiFi", "BROTHER", "impresion/impresoras/multifuncionales-laser"],
  ["Perfect Choice PC-241041 Voltus cargador magnetico MagSafe", "PERFECT CHOICE", "energia/cargadores-inalambricos/magneticos-magsafe"],
  ["UNV IPC2314LE-ADF28K-WP-L OwlView 4MP bullet PoE", "UNV", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["BRobotix 497127 patch cord Cat5e 0.5m RJ45 gris", "BROBOTIX", "redes/cableado-estructurado/patch-cords/cat5e"],
  ["Acteck AS450 Elant Brick bocinas 2.0 6W USB 3.5 mm", "ACTECK", "computo/perifericos/bocinas-audio/2-0"],
  ["Kyocera TK-5442K 1T0C0A0US0 toner negro 2800 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera"],
  ["Epson T574520-AL botella T574 light cyan L8050", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t574"],
  ["Multimedia Screens MST-246 pantalla proyeccion tripie 137 246 cm x 246 cm", "MULTIMEDIA SCREENS", "video/accesorios-proyeccion/pantallas-tripie"],
  ["TP-Link Omada EAP783 access point Wi-Fi 7 BE22000 2 puertos 10G", "TP-LINK", "redes/access-points/wifi-7"],
  ["HPE Instant On SG1004 secure gateway firewall VPN IDS IPS", "ARUBA", "redes/seguridad/firewalls"],
  ["Naceb NA-0103R cable USB a Micro USB 1m rojo", "NACEB TECHNOLOGY", "accesorios/cables-adaptadores/usb/micro-usb"],
  ["Dahua KTP02 KITKTP02-V2 videoportero IP monitor 7 1024 x 600", "DAHUA TECHNOLOGY", "seguridad/control-acceso/videoporteros-ip/kits"],
  ["ADATA AD4S26664G19-SGN memoria SO-DIMM DDR4 4GB 2666MHz", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr4"],
  ["Brother TN227C toner cyan alto rendimiento 2300 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother"],
  ["Roku Premiere 3920RW reproductor streaming 4K UHD HDR", "ROKU", "video/streaming/reproductores"],
  ["Intellinet 704823 bobina Cat5e CCA UTP 305m gris", "INTELLINET", "redes/cableado-estructurado/bobinas-utp/cat5e"],
  ["Hikvision AE-VC222T-ITS camara movil Turbo HD 1080p conector aviacion", "HIKVISION", "seguridad/cctv/camaras-moviles/turbo-hd"],
  ["Manhattan 461344 soporte TV pared movimiento completo 32-55 40kg", "MANHATTAN", "video/soportes-tv/pared"],
  ["Brother TN229BK toner negro rendimiento estandar 1500 paginas", "BROTHER", "impresion/consumibles/toner-laser/brother"],
  ["Perfect Choice PC-113294 Sugary bocina Bluetooth IPX6 35 h", "PERFECT CHOICE", "audio/bocinas/bluetooth"],
  ["ESET HOME Security Essential TMESET-506 antivirus 10 licencias 1 ano", "ESET", "software/seguridad/antivirus"],
  ["BRobotix 406269 soporte para celular plegable magnetico", "BROBOTIX", "telefonia/accesorios/soportes-celular/magneticos"],
  ["Bixolon XM7-20iK impresora movil de etiquetas termica directa Bluetooth", "BIXOLON", "impresion/impresoras/etiquetas/termicas-moviles"],
  ["Urban Balance VGA A HDMI - UB adaptador HDMI a VGA 1080p", "URBAN BALANCE", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Kensington K52801WW ErgoSoft descansa munecas teclado compacto", "KENSINGTON", "computo/perifericos/teclados/descansa-munecas"],
  ["IMOU IPC-K3DN-5H0WF Bullet 2E 5MP WiFi microfono IP67", "IMOU", "seguridad/cctv/camaras-ip-wifi/bullet-exterior"],
  ["Canon GI-10 C tanque de tinta cyan 7700 paginas", "CANON", "impresion/consumibles/botellas-tinta-megatank/canon-gi10"],
  ["Balam Rush EXL95 Eolox Link ventilador 120mm 1800 RPM RGB", "BALAM RUSH", "computo/componentes/enfriamiento/ventiladores-gabinete"],
  ["Gigabyte X870 AORUS ELITE WIFI7 ICE motherboard AM5 DDR5", "GIGABYTE", "computo/componentes/tarjetas-madre/amd-am5"],
  ["BenQ EX3410R MOBIUZ monitor gaming ultrawide curvo 34 3440x1440", "BENQ", "computo/monitores/gaming/ultrawide-curvos"],
  ["TP-Link TL-WN725N adaptador USB Nano Wireless N 150Mbps", "TP LINK", "redes/adaptadores-wifi/usb"],
  ["Uniarch IPC-B122-APF28-E camara IP mini bala 2MP PoE IR 30m", "UNIARCH", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["BRobotix 6001356 combo carga rapida cargador USB V3.0 cable Lightning", "BROBOTIX", "energia/cargadores-usb/kits-carga-lightning"],
  ["Lenovo ThinkCentre Neo 50q Gen 5 13C50022LS i3-1315U mini PC", "LENOVO", "computo/desktops/mini-pc"],
  ["Getttech GPI-GVN100A-01M PC Desktop Intel N100 8GB 240GB SSD", "GETTTECH", "computo/desktops/mini-pc"],
  ["Logitech BRIO 500 960-001412 webcam FHD USB-C", "LOGITECH", "computo/perifericos/webcams/usb-fhd"],
  ["Dahua DH-PFA120 caja de conexiones PTZ junction box", "DAHUA TECHNOLOGY", "seguridad/cctv/accesorios-montaje/cajas-conexion"],
  ["BRobotix 110910N convertidor HDMI macho a VGA hembra 24.5 cm", "BROBOTIX", "accesorios/cables-adaptadores/video-hdmi-vga"],
  ["Dell 24 AIO EC24250 XNT23 Core i7-1355U 16GB 1TB", "DELL", "computo/desktops/all-in-one"],
  ["TP-Link Tapo P100 mini contacto inteligente Wi-Fi 1200W", "TP LINK", "domotica/enchufes-inteligentes"],
  ["BRobotix 6001431 cable adaptador PCI Express 6 pines a 8 pines", "BROBOTIX", "computo/componentes/cables-internos/alimentacion-pcie"],
  ["TP-Link Omada ER7212PC router VPN 3 en 1 PoE controlador", "TP-LINK", "redes/routers/vpn/omada"],
  ["Naceb NA-0321 audifonos in-ear USB-C con control", "NACEB TECHNOLOGY", "audio/audifonos/in-ear/usb-c"],
  ["Kingston DTXM/128GB DataTraveler Exodia M USB 3.2 rojo", "KINGSTON", "computo/almacenamiento/memorias-flash/usb"],
  ["Logitech M720 Triathlon 910-004790 mouse Unifying Bluetooth", "LOGITECH", "computo/perifericos/mouse/inalambricos/multi-dispositivo"],
  ["ADATA AX5S5600C468G-SBHT XPG Hunter DDR5 SO-DIMM 8GB 5600", "ADATA", "computo/componentes/memoria-ram/sodimm-ddr5"],
  ["EZVIZ CS-H9C/6MP camara PT doble lente 3MP+3MP WiFi", "EZVIZ", "seguridad/cctv/camaras-ip-wifi/pt-doble-lente"],
  ["Silimex Silitek 28.33grs pasta termica grasa disipadora de calor", "SILIMEX", "computo/componentes/pasta-termica"],
  ["Kensington SD1650P estacion de acoplamiento portatil USB-C", "KENSINGTON", "computo/accesorios/docks-hubs/usb-c"],
  ["BRobotix 6006658 cargador 18W dual USB-A USB-C negro", "BROBOTIX", "energia/cargadores-usb/pared-dual-usb-a-usb-c"],
  ["Brother PTE560BTVP rotulador industrial P-touch etiquetas 24 mm", "BROTHER", "impresion/impresoras/etiquetas/rotuladores-p-touch"],
  ["TCL 50Q5K televisor QLED Google TV 50 4K UHD", "TCL", "video/televisores/qled-google-tv"],
  ["Manhattan 153218 cable DisplayPort a HDMI M-M 4K 60Hz 3m", "MANHATTAN", "accesorios/cables-adaptadores/video-displayport-hdmi"],
  ["Logitech MX Vertical 910-005449 mouse ergonomico inalambrico 4000 DPI", "LOGITECH", "computo/perifericos/mouse/inalambricos/ergonomicos"],
  ["Meriva MOB-800FS4 camara IP bullet 8MP 4K H.265+ PoE", "MERIVA", "seguridad/cctv/camaras-ip-poe/bullet"],
  ["Generico AC-LENOVO-CH cargador laptop 45W 20V 2.25A 4.0x1.7", "GENERICO", "computo/accesorios/cargadores-laptop"],
  ["Brother PTM95 rotulador P-touch termica directa etiquetas 12 mm", "BROTHER", "impresion/impresoras/etiquetas/rotuladores-p-touch"],
  ["Manhattan 506847 adaptador USB 3.0 a Ethernet Gigabit", "MANHATTAN", "redes/adaptadores-ethernet/usb-gigabit"],
  ["Acteck RV1200 regulador de voltaje AVR 1200VA 600W", "ACTECK", "energia/supresores-reguladores/reguladores-voltaje/avr"],
  ["Dahua DH-IPC-HDW1431SN-S4 camara IP turret 4MP PoE IR 30m", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/turret"],
  ["Dahua DH-IPC-HDW1239T1P-A-LED camara IP Full Color 2MP PoE", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-ip-poe/turret/full-color"],
  ["Dahua DH-HAC-B1A51N-U-0280B camara bullet HDCVI 5MP", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-hdcvi/bullet"],
  ["CyberPower CP1000PFCLCDa UPS PFC Sinewave 1000VA 600W LCD", "CYBERPOWER", "energia/no-breaks-ups/line-interactive/senoidal-pura"],
  ["Meriva MVD-EB200ZA camara IP domo varifocal motorizado 2.8-12mm PoE", "MERIVA", "seguridad/cctv/camaras-ip-poe/domo-varifocal"],
  ["XPG RIFT R24F2-BKCMX monitor gamer 23.8 FHD 120Hz 1ms", "XPG", "computo/monitores/gaming/24-fhd"],
  ["DataShield MI-4217 bateria sellada UPS 12V 4.5Ah", "DATASHIELD", "energia/baterias-ups/selladas-12v"],
  ["Xzeal XZCO413B enfriamiento liquido AIO 240mm ARGB", "XZEAL", "computo/componentes/enfriamiento/liquido-cpu/240mm"],
  ["Kingston KCP432SD8/16 memoria SO-DIMM DDR4 16GB 3200 CL22", "KINGSTON TECHNOLOGY", "computo/componentes/memoria-ram/sodimm-ddr4"],
  ["BRobotix 350323 bateria CMOS CR2032 litio 3V pack 5 piezas", "BROBOTIX", "energia/pilas-baterias/boton-cmos"],
  ["Epson T504220-AL botella tinta cyan T504 EcoTank L4150", "EPSON", "impresion/consumibles/botellas-tinta-ecotank/epson-t504"],
  ["Xerox 106R04054 toner cyan alta capacidad VersaLink C8000", "XEROX", "impresion/consumibles/toner-laser/xerox"],
  ["Kingston DataTraveler Exodia DTX/64GB memoria USB 3.2", "KINGSTON TECHNOLOGY", "computo/almacenamiento/memorias-flash/usb"],
  ["Xzeal X-Zynergy XZGAZNY1B gabinete Micro-ATX ITX RGB", "XZEAL", "computo/componentes/gabinetes/gaming"],
  ["Naceb NA-0963G teclado mecanico 60 con teclas intercambiables", "NACEB TECHNOLOGY", "computo/perifericos/teclados/mecanicos-compactos"],
  ["BRobotix 6000762 mouse inalambrico optico negro 1000 DPI", "BROBOTIX", "computo/perifericos/mouse/inalambricos"],
  ["Uniarch CAB-6-CCA cable UTP Cat6 100m CCA interior", "UNIARCH", "redes/cableado-estructurado/bobinas-utp/cat6"],
  ["Hikvision DS-3WR3N router WISP 2.4GHz 300Mbps 4 puertos", "HIKVISION", "redes/routers/wisp"],
  ["Hikvision DS-KIS313-P kit videoportero hibrido TurboHD pantalla touch 7 pulgadas", "HIKVISION", "seguridad/control-acceso/videoporteros-hibridos/kits"],
  ["Logitech Lift Vertical mouse ergonomico grafito Bluetooth Logi Bolt", "LOGITECH", "computo/perifericos/mouse/inalambricos/ergonomicos"],
  ["ADATA SU630 ASU630SS-240GQ-R SSD 240GB 2.5 SATA 3D QLC", "ADATA", "computo/almacenamiento/ssd/2-5-sata"],
  ["EC Line EC-LS-9620-USB lector codigo barras laser 1D USB", "EC LINE", "punto-de-venta/lectores-codigo-barras"],
  ["BRobotix 6000298 candado Nano combinacion laptop 1.80 m", "BROBOTIX", "accesorios/seguridad-fisica/candados-laptop"],
  ["BRobotix 764786 adaptador CCTV BNC macho a bornera", "BROBOTIX", "seguridad/cctv/accesorios-cableado/conectores-bnc"],
  ["Easy Line Storm audifonos in-ear 3.5mm microfono desmontable", "EASY LINE", "audio/audifonos/alambricos-3-5mm"],
  ["MSI GeForce RTX 5050 8G Ventus 2X OC GDDR6 Blackwell", "MSI OEM", "computo/componentes/tarjetas-video/nvidia-geforce/rtx-50/rtx-5050"],
  ["Dahua S5PRO dashcam doble canal 4K 1080p Wi-Fi GPS", "DAHUA TECHNOLOGY", "seguridad/cctv/camaras-moviles/dashcam"],
  ["VICA ALPHA 2K UPS online doble conversion rack torre 2000VA 2000W", "VICA", "energia/no-breaks-ups/doble-conversion/rack-torre"],
  ["Uniarch UHO-P2A-M3F4D camara IP WiFi PT exterior 3MP auto tracking", "UNIARCH", "seguridad/cctv/camaras-ip-wifi/pt-exterior"],
  ["Provision ISR PoES-0460C+2I-V2 switch PoE 4 puertos 60W modo CCTV", "PROVISION-ISR", "redes/switches/poe-no-administrables/cctv"],
  ["Manhattan 323222 cable HDMI alta velocidad con Ethernet 3m 10.2Gbps", "MANHATTAN", "accesorios/cables-adaptadores/video-hdmi/alta-velocidad"],
  ["BRobotix 053161 adaptador OTG USB-C a USB-A 3.2 20cm", "BROBOTIX", "accesorios/cables-adaptadores/usb/otg-usb-c"],
  ["Nexxt Solutions Home NHB-W310 foco inteligente Wi-Fi GU10 4W blanco ajustable", "NEXXT SOLUTIONS HOME", "domotica/iluminacion-inteligente/focos-wifi"],
  ["MSI SPATIUM S270 SATA 2.5 480GB SSD 3D NAND", "MSI OEM", "computo/almacenamiento/ssd/2-5-sata"],
  ["Grandstream GWN7801P switch administrable L2+ PoE Gigabit 8 puertos 2 SFP", "GRANDSTREAM", "redes/switches/poe-administrables/gigabit"],
  ["Naceb NA-589R audifonos diadema alambricos 3.5mm rojo con microfono", "NACEB TECHNOLOGY", "audio/audifonos/alambricos-3-5mm/diadema-con-microfono"],
  ["Manhattan 340458 cable USB 2.0 A-B 3m plata 480Mbps", "MANHATTAN", "accesorios/cables-adaptadores/usb/usb-a-b/3m"],
  ["TP-Link TL-SF1008D switch no administrable Fast Ethernet 8 puertos", "TP LINK", "redes/switches/no-administrables/fast-ethernet"],
  ["TP-Link EAP211-Bridge Kit Omada puente inalambrico exterior 5GHz 867Mbps 1km", "TP LINK", "redes/radioenlaces-antenas/puentes-wifi-exterior"],
  ["Huawei MateBook D16 53014MUD laptop 16 pulgadas i5-13420H 16GB 512GB", "HUAWEI", "computo/laptops/16-pulgadas"],
  ["Thermaltake Core P6 TG Snow CA-1V2-00M6WN-00 gabinete ATX mid tower open frame", "THERMALTAKE", "computo/componentes/gabinetes/atx-mid-tower"],
  ["Balam Rush GK9791 Dominate Expert teclado gamer mecanico inalambrico RGB", "BALAM RUSH", "computo/perifericos/teclados/inalambricos/mecanicos-gaming"],
  ["Koblenz 10017 USB/R no break linea pro 1000VA 500W 8 contactos", "KOBLENZ", "energia/no-breaks-ups/line-interactive/1000va"],
  ["Tech Zone TZACMOA01 mouse alambrico negro 1200 DPI 1.5m", "TECH ZONE ACCESORIOS", "computo/perifericos/mouse/alambricos/basicos"],
  ["Uniarch UAC-B112-F28-W camara bala analog HD ColourHunter 2MP", "UNIARCH", "seguridad/cctv/camaras-analogicas/bullet-hd"],
  ["Nextep NE-650BG silla basica gris altura ajustable sin brazos soporta 120 kg", "NEXTEP", "oficina/mobiliario-accesorios/sillas-oficina/operativas-sin-brazos"],
  ["Vorago KSP-530 bafle karaoke 40W RMS 5400mAh flame light TWS Bluetooth", "VORAGO", "audio/bocinas/portatiles/karaoke-party"],
  ["Manhattan 421010 mini kit limpiador LCD 60cc pantalla", "MANHATTAN", "computo/accesorios/limpieza/limpiadores-pantalla"],
  ["Saxxon SUA-HAC-B20M-0280B camara bala analog HD 2MP 1080P IR 30m IP67", "SAXXON", "seguridad/cctv/camaras-analogicas/bullet-hd"],
  ["CDP R-UPR1008 no break interactivo 1000VA 500W 8 contactos", "CDP", "energia/no-breaks-ups/line-interactive/1000va"],
  ["BRobotix 206823 cable USB 2.0 Tipo A a Tipo A 0.9m negro", "BROBOTIX", "accesorios/cables-adaptadores/usb/usb-a-a"],
  ["Kaspersky Standard KL1041Z5KFS 10 dispositivos 1 ano fisica", "KASPERSKY", "software/seguridad/antivirus/multidispositivo"],
  ["TP-Link TL-WN8200ND adaptador USB Wi-Fi alta potencia 300Mbps 2 antenas", "TP LINK", "redes/adaptadores-wifi/usb/alta-potencia"],
  ["Koblenz SS-460 C supresor de picos 460 joules 6 contactos", "KOBLENZ", "energia/supresores-reguladores/supresores-picos/multicontactos"],
  ["IMOU IPC-S3EN-3M0WE Bullet 3MP Wi-Fi Full Color IMOU Sense", "IMOU", "seguridad/cctv/camaras-ip-wifi/bullet-exterior"],
  ["TP-Link RE450 extensor de rango Wi-Fi AC1750 dual band", "TP LINK", "redes/extensores-wifi/dual-band"],
  ["DataShield UT-3000 no break 3000VA 2700W 8h recarga", "DATASHIELD", "energia/no-breaks-ups/doble-conversion/rack-torre/3000va"],
  ["Qian QMF-REF19-01 Monitor Office Mate 19 pulgadas 1440x900 75Hz", "QIAN", "computo/monitores/oficina/19-wxga"],
  ["EZVIZ CS-EB3 camara IP Wi-Fi 2K bateria cero cables exterior", "EZVIZ", "seguridad/cctv/camaras-ip-wifi/bateria-exterior"],
  ["Provision ISR SH-4100A5S-2L DVR pentahibrido 4 canales 2MP H265", "PROVISION-ISR", "seguridad/cctv/dvr-nvr/xvr-pentahibrido"],
  ["Uniarch IPC-T122-APF28-E camara IP turret 2MP PoE techo", "UNIARCH", "seguridad/cctv/camaras-ip-poe/turret/2mp"],
  ["Vorago AU-303 cargador auto micro USB 2.4A negro", "VORAGO", "energia/cargadores-usb/auto-micro-usb"],
  ["Perfect Choice PC-045274 mini mouse dual Bluetooth 2.4GHz USB-C recargable", "PERFECT CHOICE", "computo/perifericos/mouse/inalambricos/multi-dispositivo"],
  ["HPE Microsoft Windows Server 2025 Remote Desktop Services 5 User CAL", "HEWLETT PACKARD ENTERPRISE", "software/licencias/windows-server/cal-rds"],
  ["Acteck TI747 Inspire Trek teclado inalambrico multidispositivo Bluetooth 5.1", "ACTECK", "computo/perifericos/teclados/inalambricos/multidispositivo"],
  ["Brother M531 cinta etiqueta azul 12mm x 8m P-touch M", "BROTHER", "impresion/consumibles/cintas-etiquetas/brother-m"],
  ["Kyocera TK-1262 toner negro 10000 paginas", "KYOCERA", "impresion/consumibles/toner-laser/kyocera"],
  ["Tenda N6P-8H NVR PoE 8 canales 4K UHD HDD 10TB", "TENDA", "seguridad/cctv/dvr-nvr/nvr-poe"],
] as const;

describe("manual taxonomy researched batches", () => {
  it.each(researchedBatchCases)("%s -> %s", (name, brand, path) => {
    expect(classifyManualCategory({ name, brand, category: "laptops" }).path).toBe(path);
  });
});
