export const MANUAL_CATEGORY_TREE_CYCLE003_PART004 = [
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos', name: 'Marcadores Azor Signal punto fino surtidos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos/5-piezas', name: 'Azor Signal punto fino surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos/5-piezas/azor-signal-30653', name: 'Azor Signal 30653 surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro', name: 'Azor Pin Point cuerpo transparente negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro/12-piezas', name: 'Azor Pin Point 6830NE negro 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro/12-piezas/azor-pinpoint-6830ne', name: 'Azor Pin Point 6830NE negro 1.0 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe', name: 'Marcadores Azor Signal punto fino cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe/12-piezas', name: 'Azor Signal 30007 cafe 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe/12-piezas/azor-signal-30007', name: 'Azor Signal Fino 30007 cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta', name: 'Marcadores base agua doble punta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta/12-colores', name: 'Marcadores base agua doble punta 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta/12-colores/azor-aquarelo-duo-29412', name: 'Azor Aquarelo Duo 29412 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul', name: 'Marcadores Azor Signal Xtra azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul/12-piezas', name: 'Azor Signal Xtra azul 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul/12-piezas/azor-signal-xtra-40003', name: 'Azor Signal Xtra 40003 azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo', name: 'Marcadores Azor Signal Xtra rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo/12-piezas', name: 'Azor Signal Xtra rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo/12-piezas/azor-signal-xtra-40002', name: 'Azor Signal Xtra 40002 rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo', name: 'Marcadores Azor Signal punto fino amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo/12-piezas', name: 'Azor Signal 30005 amarillo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo/12-piezas/azor-signal-30005', name: 'Azor Signal Fino 30005 amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta', name: 'Marcadores Azor Signal punto fino violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta/12-piezas', name: 'Azor Signal 30008 violeta 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta/12-piezas/azor-signal-30008', name: 'Azor Signal Fino 30008 violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul', name: 'Uni-ball Deluxe roller azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul/blister-1-pieza', name: 'Uni-ball Deluxe azul blister 1 pieza', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul/blister-1-pieza/azor-ub155az1', name: 'Uni-ball Deluxe UB155AZ1 azul 0.5 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/broches-archivo/7cm', name: 'Broches para archivo 7 cm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/broches-archivo/7cm/baco-b072-50-piezas', name: 'Baco B-072 broche archivo 7 cm 50 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/lapices-bicolor', name: 'Lapices bicolor escolares', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/lapices-bicolor/baco-55408-12p', name: 'BACO 55408 lapiz bicolor 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/ergonomia/cojines-asiento/espuma-viscoelastica/kensington-p4936', name: 'Kensington P4936 cojin de asiento', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95/azul-valvula', name: 'Cubrebocas KN95 azul con valvula', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95/azul-valvula/ksa-ph007', name: 'KSA PH007 KN95 azul con valvula', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/crema', name: 'Folders carta color crema', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/crema/100-piezas', name: 'Folders carta crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/crema/100-piezas/diem-mf01c100', name: 'DIEM MF01C100 folder carta crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/crema', name: 'Folders oficio color crema', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/crema/100-piezas', name: 'Folders oficio crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/crema/100-piezas/diem-mf01oc100', name: 'DIEM MF01OC100 folder oficio crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'redes/controladoras/omada', name: 'Controladoras TP-Link Omada', legacyCategory: 'networking' },
  { path: 'redes/controladoras/omada/hardware-controller', name: 'Controladoras hardware Omada SDN', legacyCategory: 'networking' },
  { path: 'redes/controladoras/omada/hardware-controller/tp-link-oc300', name: 'TP-Link Omada OC300 controladora hardware', legacyCategory: 'networking' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/combinacion', name: 'Candados laptop de combinacion', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/combinacion/n17-slim', name: 'Candados Kensington N17 Slim de combinacion', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/combinacion/n17-slim/kensington-k68009ww', name: 'Kensington K68009WW Slim N17 combinacion', legacyCategory: 'accessories' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra/gk420d-gx420d-203dpi', name: 'Cabezales Zebra GK420d/GX420d 203 dpi', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra/gk420d-gx420d-203dpi/105934-037', name: 'Zebra 105934-037 cabezal GK420d/GX420d', legacyCategory: 'printers_scanners' },
  { path: 'gaming/mobiliario/sillas-gamer/accesorios', name: 'Accesorios para sillas gamer', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/accesorios/cojines', name: 'Cojines y almohadas para sillas gamer', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/accesorios/cojines/yeyian-yka-20705', name: 'Yeyian YKA-20705 kit de almohadas', legacyCategory: 'gaming' },
  { path: 'video/accesorios-proyeccion/filtros-aire', name: 'Filtros de aire para proyectores', legacyCategory: 'accessories' },
  { path: 'video/accesorios-proyeccion/filtros-aire/epson-elpaf32-v13h134a32', name: 'Epson ELPAF32 V13H134A32 filtro de aire', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina', name: 'Papel y cartulina de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-opalina', name: 'Papel opalina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-opalina/carta', name: 'Papel opalina tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-opalina/carta/diem-pobtcc100-100h', name: 'DIEM POBTCC100 papel opalina carta 100 hojas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-opalina', name: 'Cartulina opalina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-opalina/carta', name: 'Cartulina opalina tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-opalina/carta/diem-cobtcc100-100p', name: 'DIEM COBTCC100 cartulina opalina carta 100 piezas', legacyCategory: 'accessories' },
  { path: 'telefonia/telefonos-ip/escritorio/1-linea', name: 'Telefonos IP de escritorio una linea', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/escritorio/1-linea/poe', name: 'Telefonos IP una linea con PoE', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/escritorio/1-linea/poe/cisco-7811-3pcc', name: 'Cisco 7811 3PCC telefono IP una linea PoE', legacyCategory: 'networking' },
  { path: 'oficina/papeleria/sobres/coin', name: 'Sobres coin', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/coin/ante', name: 'Sobres coin color ante', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/coin/ante/8-8x16-4', name: 'Sobres coin ante 8.8 x 16.4 cm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/coin/ante/8-8x16-4/mae-nassa-im0130-500p', name: 'NASSA MAE IM0130 sobre coin ante 500 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera', name: 'Marcadores de cera', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera/pelikan', name: 'Marcadores de cera Pelikan', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera/pelikan/rojo-10-piezas', name: 'Marcadores de cera Pelikan rojos 10 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera/pelikan/rojo-10-piezas/50800103', name: 'Pelikan 50800103 marcador de cera rojo 10 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus', name: 'BIC Cristal Dura+ punto mediano', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus/azul', name: 'BIC Cristal Dura+ azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus/azul/12-piezas', name: 'BIC Cristal Dura+ azul 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus/azul/12-piezas/923996', name: 'BIC 923996 Cristal Dura+ azul 1.0 mm 12 piezas', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz', name: 'Digitalizadores y accesorios Topaz', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz/accesorios', name: 'Accesorios Topaz para firma digital', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz/accesorios/protectores-pantalla', name: 'Protectores de pantalla Topaz', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz/accesorios/protectores-pantalla/a-olsl-3', name: 'Topaz A-OLSL-3 protector SigLite 1x5 3 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/blocks', name: 'Blocks de notas adhesivas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/blocks/3x3', name: 'Blocks de notas adhesivas 3 x 3 pulgadas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/blocks/3x3/janel-memotip-1173', name: 'Janel Memo Tip 1173 notas adhesivas 3 x 3', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves', name: 'Lapices de color Blanca Nieves', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/cortos-12p', name: 'Blanca Nieves lapices de color cortos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/cortos-12p/45075', name: 'Blanca Nieves 45075 colores cortos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/largos-12p', name: 'Blanca Nieves lapices de color largos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/largos-12p/45074', name: 'Blanca Nieves 45074 colores largos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/foliadores', name: 'Foliadores de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/foliadores/automaticos-6-digitos', name: 'Foliadores automaticos de 6 digitos', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/foliadores/automaticos-6-digitos/generico-kwp010', name: 'Generico KWP010 foliador metalico 6 digitos', legacyCategory: 'accessories' },
  { path: 'audio/microfonos/escritorio-usb', name: 'Microfonos USB de escritorio', legacyCategory: 'audio' },
  { path: 'audio/microfonos/escritorio-usb/xzeal-xzst250b', name: 'Xzeal XZST250B microfono USB con tripode', legacyCategory: 'audio' },
  { path: 'video/accesorios-foto-video', name: 'Accesorios de foto y video', legacyCategory: 'accessories' },
  { path: 'video/accesorios-foto-video/iluminacion', name: 'Iluminacion para foto y video', legacyCategory: 'accessories' },
  { path: 'video/accesorios-foto-video/iluminacion/aros-luz', name: 'Aros de luz para foto y video', legacyCategory: 'accessories' },
  { path: 'video/accesorios-foto-video/iluminacion/aros-luz/elgato-ring-light-10lac9901', name: 'Elgato Ring Light 10LAC9901 aro de luz', legacyCategory: 'accessories' },
  { path: 'software/servicios-nube/ct-cloud/servidores-virtuales', name: 'Servidores virtuales CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/servidores-virtuales/cq-duo-ncsvduocq', name: 'CT Cloud NCSVDUOCQ servidor virtual CQ Duo', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/gestion-nube/plus-cq-ncsvpluscq', name: 'CT Cloud NCSVPLUSCQ servicio nube Plus CQ', legacyCategory: 'software' },
  { path: 'computo/componentes/enfriamiento/pasta-termica/game-factor-tp200-4g', name: 'Game Factor TP200 4 g', legacyCategory: 'components' },
  { path: 'oficina/equipo-oficina/manejo-efectivo', name: 'Manejo de efectivo de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/manejo-efectivo/cera-para-contar', name: 'Cera para contar billetes y documentos', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/manejo-efectivo/cera-para-contar/azor-301-64', name: 'Azor 301.64 cera para contar', legacyCategory: 'accessories' },
  { path: 'software/servicios-nube/ct-cloud/configuracion-servidores/iis-servidor-virtual', name: 'Configuracion IIS en servidores virtuales CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/configuracion-servidores/iis-servidor-virtual/iiis', name: 'CT Cloud IIIS configuracion IIS', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/redes-vpn', name: 'Redes y VPN CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/redes-vpn/cliente-servidor', name: 'VPN cliente-servidor CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/redes-vpn/cliente-servidor/vpncs', name: 'CT Cloud VPNCS cliente-servidor', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/seguridad-web', name: 'Seguridad web CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/seguridad-web/certificados-ssl', name: 'Certificados SSL CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/seguridad-web/certificados-ssl/standard', name: 'Certificados SSL Standard CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/seguridad-web/certificados-ssl/standard/csslstd', name: 'CT Cloud CSSLSTD SSL Standard', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/seguridad-web/certificados-ssl/wildcard', name: 'Certificados SSL Wildcard CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/seguridad-web/certificados-ssl/wildcard/csslwdcd', name: 'CT Cloud CSSLWDCD SSL Wildcard', legacyCategory: 'software' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/numericos', name: 'Separadores numericos carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/numericos/31-divisiones', name: 'Separadores carta 31 divisiones', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/numericos/31-divisiones/wilson-jones-p1366', name: 'Wilson Jones P1366 31 divisiones carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/numericos/12-divisiones', name: 'Separadores carta 12 divisiones', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/numericos/12-divisiones/wilson-jones-p1348', name: 'Wilson Jones P1348 12 divisiones carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-iris', name: 'Cartulina Iris', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-iris/50x65', name: 'Cartulina Iris 50 x 65 cm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-iris/50x65/negro-10-pliegos', name: 'Cartulina Iris negra 10 pliegos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-iris/50x65/negro-10-pliegos/euromac-ei0042', name: 'Euromac EI0042 cartulina Iris negra', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales/base-aceite/uni-paint-px20-oro', name: 'Uni Paint PX-20 oro', legacyCategory: 'accessories' },
  { path: 'impresion/escaneres/documentales/adf/duplex/a3/epson-ds-30000-b11b256201', name: 'Epson DS-30000 B11B256201 ADF duplex A3', legacyCategory: 'printers_scanners' },
  { path: 'oficina/papeleria/material-escolar/plastilina/barras-10p', name: 'Plastilina escolar en barras 10 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/barras-10p/baco-65018', name: 'BACO 65018 plastilina barras 10 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/clips/cuadraditos', name: 'Clips cuadraditos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/clips/cuadraditos/no-1', name: 'Clips cuadraditos No. 1', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/clips/cuadraditos/no-1/baco-12067-100-piezas', name: 'BACO 12067 clip cuadradito No. 1 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/clips/cuadraditos/no-2', name: 'Clips cuadraditos No. 2', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/clips/cuadraditos/no-2/baco-12043-100-piezas', name: 'BACO 12043 clip cuadradito No. 2 100 piezas', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/llave/microsaver-2-0/kensington-k65048ww-twin', name: 'Kensington K65048WW MicroSaver 2.0 Twin', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales/base-aceite/uni-paint-px20-negro', name: 'Uni Paint PX-20 negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales/base-aceite/uni-paint-px20-azul', name: 'Uni Paint PX-20 azul', legacyCategory: 'accessories' },
  { path: 'salud/equipo-medico/monitoreo/termometros-infrarrojos/dispensador-gel', name: 'Termometros infrarrojos con dispensador de gel', legacyCategory: 'accessories' },
  { path: 'salud/equipo-medico/monitoreo/termometros-infrarrojos/dispensador-gel/ksa-k9-pro', name: 'KSA K9 Pro termometro con dispensador', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/pastel', name: 'Folders oficio color pastel', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/pastel/rosa', name: 'Folders oficio rosa pastel', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/pastel/rosa/diem-fpto10005-100p', name: 'DIEM FPTO10005 folder oficio rosa 100 piezas', legacyCategory: 'accessories' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/tensionadas', name: 'Pantallas electricas tensionadas', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/tensionadas/106-pulgadas', name: 'Pantallas electricas tensionadas 106 pulgadas', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/tensionadas/106-pulgadas/multimedia-screens-mset106', name: 'Multimedia Screens MSET106 106 pulgadas', legacyCategory: 'monitors' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/mesas-interactivas/32-pulgadas/jc-vision-jc-mt320pcap', name: 'JC Vision JC-MT320PCAP mesa 32 pulgadas', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/mesas-interactivas/43-pulgadas', name: 'Mesas interactivas 43 pulgadas', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/mesas-interactivas/43-pulgadas/jc-vision-jc-mt430pcap', name: 'JC Vision JC-MT430PCAP mesa 43 pulgadas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/lapices-grafito/baco-bacopencil-53329-50p', name: 'BACO Bacopencil 53329 lapiz grafito 50 piezas', legacyCategory: 'accessories' },
  { path: 'video/accesorios-proyeccion/pantallas-inflables', name: 'Pantallas inflables de proyeccion', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-inflables/piso', name: 'Pantallas inflables de piso', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-inflables/piso/multimedia-screens-msi120', name: 'Multimedia Screens MSI120 inflable', legacyCategory: 'monitors' },
  { path: 'electronica/wearables/smartwatches/stylos-staswm3b', name: 'Stylos SW2 STASWM3B negro', legacyCategory: 'accessories' },
  { path: 'energia/solar/inversores-ups/line-interactive/mppt-12v/cdp-es-avr-1012-sol', name: 'CDP ES-AVR-1012 SOL 700W 12V', legacyCategory: 'power' },
  { path: 'energia/solar/inversores-ups/line-interactive/mppt-48v', name: 'Inversores UPS solares MPPT 48V', legacyCategory: 'power' },
  { path: 'energia/solar/inversores-ups/line-interactive/mppt-48v/cdp-es-avr-3048-sol', name: 'CDP ES-AVR-3048 SOL 3000VA 48V', legacyCategory: 'power' },
  { path: 'energia/solar/inversores-ups/line-interactive/mppt-48v/cdp-es-avr-5048-sol', name: 'CDP ES-AVR-5048 SOL 5kVA 48V', legacyCategory: 'power' },
  { path: 'oficina/papeleria/sobres/medios-opticos', name: 'Sobres para medios opticos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/medios-opticos/cd-dvd', name: 'Sobres para CD y DVD', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/medios-opticos/cd-dvd/mapasa-ha0126-50p', name: 'Mapasa HA0126 sobre CD/DVD 50 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-color', name: 'Papel de color', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-color/carta', name: 'Papel de color tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-color/carta/eurocolors-ec0012-100h', name: 'Eurocolors EC0012 carta 100 hojas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/registradores', name: 'Registradores de archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/registradores/carta', name: 'Registradores tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/registradores/carta/lefort-1530-amarillo', name: 'Lefort 1530 registrador carta amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/registradores/carta/lefort-1230-rojo', name: 'Lefort 1230 registrador carta rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/registradores/carta/lefort-1330-verde', name: 'Lefort 1330 registrador carta verde', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/encuadernacion', name: 'Encuadernacion de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/encuadernacion/cubiertas', name: 'Cubiertas para encuadernar', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/encuadernacion/cubiertas/polipropileno', name: 'Cubiertas de polipropileno', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/encuadernacion/cubiertas/polipropileno/carta', name: 'Cubiertas de polipropileno carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/encuadernacion/cubiertas/polipropileno/carta/mae-pent-25-negro', name: 'MAE PENT-25 cubierta carta negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/sacapuntas', name: 'Sacapuntas escolares', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/sacapuntas/plastico', name: 'Sacapuntas de plastico', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/sacapuntas/plastico/mae-sss-25-25p', name: 'MAE SSS-25 sacapuntas 25 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/adhesivos/silicon-termofusible', name: 'Silicon termofusible', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/adhesivos/silicon-termofusible/barras-delgadas', name: 'Barras delgadas para pistola de silicon', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/adhesivos/silicon-termofusible/barras-delgadas/janel-bas7420101-1kg', name: 'Janel BAS7420101 silicon delgado 1 kg', legacyCategory: 'accessories' },
  { path: 'gaming/accesorios/controles-gamepad/mobile-usb-c', name: 'Controles moviles USB-C', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios/controles-gamepad/mobile-usb-c/android', name: 'Controles moviles USB-C Android', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios/controles-gamepad/mobile-usb-c/android/razer-kishi-rz06-02900100-rf', name: 'Razer Kishi Android RZ06-02900100/RF', legacyCategory: 'gaming' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0010a', name: 'Etiquetas PCM 50000I0010A blancas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0008b', name: 'Etiquetas PCM 50000I0008B blancas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0011a', name: 'Etiquetas PCM 50000I0011A blancas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0013a', name: 'Etiquetas PCM 50000I0013A blancas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0016a', name: 'Etiquetas PCM 50000I0016A blancas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0020a', name: 'Etiquetas PCM 50000I0020A blancas', legacyCategory: 'printers_scanners' },
  { path: 'energia/pdu-rack/basicos', name: 'PDU basicos para rack', legacyCategory: 'power' },
  { path: 'energia/pdu-rack/basicos/0u-30a-208v-c13-c19', name: 'PDU basicos 0U 30A 208V C13/C19', legacyCategory: 'power' },
  { path: 'energia/pdu-rack/basicos/0u-30a-208v-c13-c19/tripp-lite-pduv30hv', name: 'Tripp Lite PDUV30HV 0U 30A', legacyCategory: 'power' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/150-pulgadas', name: 'Pantallas electricas de proyeccion 150 pulgadas', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/150-pulgadas/multimedia-screens-mse-229', name: 'Multimedia Screens MSE-229 150 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/perifericos/teclados/keycaps/pbt', name: 'Keycaps PBT', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/keycaps/pbt/redragon-a130b-sp-scarab-black', name: 'Redragon Scarab Black A130B-SP', legacyCategory: 'gaming' },
  { path: 'software/servicios-nube/ct-cloud/respaldo-nube/10tb', name: 'CT Cloud respaldo 10TB', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/respaldo-nube/10tb/ct-cloud-ncbu10tb', name: 'CT Cloud NCBU10TB backup 10TB', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/respaldo-nube/personalizado', name: 'CT Cloud respaldo personalizado', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/respaldo-nube/personalizado/ct-cloud-ncbuper', name: 'CT Cloud NCBUPER backup personalizado', legacyCategory: 'software' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/carta/plastico', name: 'Cajas plasticas carta para archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/carta/plastico/geo-026', name: 'GEO 026 caja plastica carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/brights', name: 'Folders carta DIEM Brights', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/brights/25-piezas', name: 'Folders carta Brights 25 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/brights/25-piezas/diem-brights', name: 'DIEM Brights carta 25 piezas', legacyCategory: 'accessories' },
  { path: 'telefonia/audio', name: 'Audio para telefonia', legacyCategory: 'headphones' },
  { path: 'telefonia/audio/manos-libres', name: 'Manos libres para telefonia', legacyCategory: 'headphones' },
  { path: 'telefonia/audio/manos-libres/bluetooth-monoaural', name: 'Manos libres Bluetooth monoaurales', legacyCategory: 'headphones' },
  { path: 'telefonia/audio/manos-libres/bluetooth-monoaural/mobifree-mb-02007', name: 'Mobifree MB-02007 blanco', legacyCategory: 'headphones' },
  { path: 'impresion/escaneres/documentales/cama-plana-adf/a4-legal', name: 'Escaneres cama plana ADF A4 y legal', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/cama-plana-adf/a4-legal/hp-scanjet-enterprise-flow-n6600-fnw1', name: 'HP ScanJet Enterprise Flow N6600 fnw1', legacyCategory: 'printers_scanners' },
  { path: 'foto-video/accesorios/tripodes', name: 'Tripodes de fotografia y video', legacyCategory: 'accessories' },
  { path: 'foto-video/accesorios/tripodes/compactos-smartphone', name: 'Tripodes compactos para smartphone y camara', legacyCategory: 'accessories' },
  { path: 'foto-video/accesorios/tripodes/compactos-smartphone/yeyian-yss-swfl-01-bl', name: 'Yeyian YSS-SWFL-01-BL Glitnir Master', legacyCategory: 'accessories' },
  { path: 'seguridad/control-acceso/asistencia/biometricos/facial-temperatura', name: 'Terminales faciales con temperatura', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/asistencia/biometricos/facial-temperatura/anviz-facedeep3irt', name: 'Anviz FaceDeep 3 IRT', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/asistencia/biometricos/facial-temperatura/anviz-facedeep5irt', name: 'Anviz FaceDeep 5 IRT', legacyCategory: 'security' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-gold/850w/modular/corsair-rm850x-cp-9020200-na', name: 'Corsair RM850x CP-9020200-NA 850W', legacyCategory: 'components' },
  { path: 'impresion/escaneres/documentales/produccion/adf/a3/kodak-alaris-s3120-max', name: 'Kodak Alaris S3120 Max A3 120 ppm', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/produccion/adf/a3/kodak-alaris-s3100f', name: 'Kodak Alaris S3100f A3 con cama plana', legacyCategory: 'printers_scanners' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/baco', name: 'Lapices de color BACO', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/baco/largos-12p', name: 'Colores BACO largos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/baco/largos-12p/lp001-52537', name: 'BACO LP001/52537 colores largos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/baco/cortos-12p', name: 'Colores BACO cortos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/baco/cortos-12p/lp002-52520', name: 'BACO LP002/52520 colores cortos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/marfil', name: 'Folders carta color marfil', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/marfil/100-piezas', name: 'Folders carta marfil 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/marfil/100-piezas/diem-750623155144', name: 'DIEM 750623155144 folder carta marfil', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/marfil', name: 'Folders oficio color marfil', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/marfil/100-piezas', name: 'Folders oficio marfil 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/marfil/100-piezas/diem-750623155149', name: 'DIEM 750623155149 folder oficio marfil', legacyCategory: 'accessories' },
  { path: 'redes/red-activa', name: 'Red activa', legacyCategory: 'networking' },
  { path: 'redes/red-activa/extensores-red', name: 'Extensores de red', legacyCategory: 'networking' },
  { path: 'redes/red-activa/extensores-red/wifi-ac1200', name: 'Extensores WiFi AC1200', legacyCategory: 'networking' },
  { path: 'redes/red-activa/extensores-red/wifi-ac1200/nexxt-kronos1200-aeiel905u1', name: 'Nexxt Kronos1200-AC AEIEL905U1', legacyCategory: 'networking' },
  { path: 'redes/iot-telemetria', name: 'IoT y telemetria', legacyCategory: 'networking' },
  { path: 'redes/iot-telemetria/rastreadores-gps', name: 'Rastreadores GPS IoT', legacyCategory: 'networking' },
  { path: 'redes/iot-telemetria/rastreadores-gps/activos', name: 'Rastreadores GPS de activos', legacyCategory: 'networking' },
  { path: 'redes/iot-telemetria/rastreadores-gps/activos/teltonika-tat140', name: 'Teltonika TAT140 rastreador de activos', legacyCategory: 'networking' },
  { path: 'electronica/localizadores-gps', name: 'Localizadores GPS', legacyCategory: 'security' },
  { path: 'electronica/localizadores-gps/rastreadores-personales', name: 'Rastreadores GPS personales', legacyCategory: 'security' },
  { path: 'electronica/localizadores-gps/rastreadores-personales/seguridad-laboral', name: 'Rastreadores personales para seguridad laboral', legacyCategory: 'security' },
  { path: 'electronica/localizadores-gps/rastreadores-personales/seguridad-laboral/teltonika-gh5200', name: 'Teltonika GH5200 Worker BadgePLUS', legacyCategory: 'security' },
  { path: 'electronica/localizadores-gps/rastreadores-personales/seguridad-personal', name: 'Rastreadores personales de seguridad', legacyCategory: 'security' },
  { path: 'electronica/localizadores-gps/rastreadores-personales/seguridad-personal/teltonika-tmt250', name: 'Teltonika TMT250 rastreador personal', legacyCategory: 'security' },
  { path: 'impresion/consumibles/cabezales/canon-pixma-megatank/canon-bh-10-gi-10-pgbk', name: 'Canon BH-10 + GI-10 PGBK', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cabezales/canon-maxify-gx', name: 'Cabezales Canon MAXIFY GX', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cabezales/canon-maxify-gx/ph-s-gi-16-kit', name: 'Canon PH-S + GI-16 BK/C/M/Y', legacyCategory: 'printers_scanners' },
  { path: 'energia/no-breaks-ups/accesorios/transformadores-aislamiento-reductores', name: 'Transformadores de aislamiento reductores para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/transformadores-aislamiento-reductores/6kva', name: 'Transformadores de aislamiento 6kVA', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/transformadores-aislamiento-reductores/6kva/tripp-lite-su6000xfmr2u', name: 'Tripp Lite SU6000XFMR2U 6kVA', legacyCategory: 'power' },
  { path: 'oficina/equipo-oficina/perforadoras', name: 'Perforadoras de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/perforadoras/3-orificios', name: 'Perforadoras de 3 orificios', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/perforadoras/3-orificios/pegaso-333', name: 'Pegaso 333 perforadora 3 orificios', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/blanco', name: 'Plastilina marqueta 180 g blanco', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/blanco/baco-pl012', name: 'BACO PL012 plastilina blanca', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/naranja', name: 'Plastilina marqueta 180 g naranja', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/naranja/baco-pl004', name: 'BACO PL004 plastilina naranja', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/amarillo-pastel', name: 'Plastilina marqueta 180 g amarillo pastel', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/amarillo-pastel/baco-pl043', name: 'BACO PL043 plastilina amarillo pastel', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/cafe', name: 'Plastilina marqueta 180 g cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/cafe/baco-pl010', name: 'BACO PL010 plastilina cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/verde-oscuro', name: 'Plastilina marqueta 180 g verde oscuro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/verde-oscuro/baco-pl014', name: 'BACO PL014 plastilina verde oscuro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/negro', name: 'Plastilina marqueta 180 g negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/negro/baco-pl013', name: 'BACO PL013 plastilina negra', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/violeta', name: 'Plastilina marqueta 180 g violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/violeta/baco-pl015', name: 'BACO PL015 plastilina violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/azul-cielo', name: 'Plastilina marqueta 180 g azul cielo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/azul-cielo/baco-pl045', name: 'BACO PL045 plastilina azul cielo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/gris-oscuro', name: 'Plastilina marqueta 180 g gris oscuro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/gris-oscuro/baco-pl091', name: 'BACO PL091 plastilina gris oscuro', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/15-6/manhattan-cambridge-439947', name: 'Manhattan Cambridge 439947 15.6 pulgadas', legacyCategory: 'accessories' },
  { path: 'oficina/papel-consumibles/papel-bond/carta/5000-hojas/paperline-70g-95-blancura', name: 'Paperline carta 70 g 95 blancura 5000 hojas', legacyCategory: 'accessories' },
  { path: 'impresion/impresoras/multifuncionales-laser/monocromaticas/canon-imagerunner-advance-dx-617if', name: 'Canon imageRUNNER ADVANCE DX 617iF', legacyCategory: 'printers_scanners' },
  { path: 'electronica/wearables/smartwatches/stylos-staswm3a', name: 'Stylos SW2 STASWM3A azul', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/cajas-mantenimiento', name: 'Cajas de mantenimiento de impresion', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cajas-mantenimiento/epson-surecolor', name: 'Cajas de mantenimiento Epson SureColor', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cajas-mantenimiento/epson-surecolor/c13s210057', name: 'Epson C13S210057 tanque de mantenimiento', legacyCategory: 'printers_scanners' },
  { path: 'electronica/wearables/smartwatches/outdoor-gps', name: 'Smartwatches outdoor GPS resistentes', legacyCategory: 'accessories' },
  { path: 'electronica/wearables/smartwatches/outdoor-gps/amazfit-t-rex-2', name: 'Amazfit T-Rex 2 outdoor GPS', legacyCategory: 'accessories' },
];
