export const MANUAL_CATEGORY_TREE_CYCLE003_PART002 = [
  { path: 'punto-de-venta/kioscos/accesorios/montaje-pared', name: 'Montaje de pared para kioscos POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/kioscos/accesorios/montaje-pared/zebra-cc600-mk500', name: 'Montaje pared Zebra CC600 y MK500', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores', name: 'Marcadores de papeleria', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores', name: 'Resaltadores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/amarillos', name: 'Resaltadores amarillos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/amarillos/12-piezas', name: 'Resaltadores amarillos caja 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papel-consumibles/papel-bond/carta/5000-hojas/impress-70g-95-blancura', name: 'Papel bond Impress carta 70 g 95 blancura', legacyCategory: 'accessories' },
  { path: 'salud', name: 'Salud', legacyCategory: 'accessories' },
  { path: 'salud/higiene', name: 'Higiene y proteccion personal', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas', name: 'Cubrebocas', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95', name: 'Cubrebocas KN95', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95/50-piezas-blanco', name: 'Cubrebocas KN95 blanco 50 piezas', legacyCategory: 'accessories' },
  { path: 'infraestructura/racks-accesorios/organizadores-cable/verticales/tripp-lite-srvrtbar-42u', name: 'Barras verticales Tripp Lite SRVRTBAR 42U', legacyCategory: 'networking' },
  { path: 'audio/bocinas/bluetooth/portatiles/ipx7-20w', name: 'Bocinas Bluetooth portatiles IPX7 20W', legacyCategory: 'audio' },
  { path: 'audio/bocinas/bluetooth/portatiles/ipx7-20w/creative-muvo-go', name: 'Creative MUVO Go Bluetooth IPX7 20W', legacyCategory: 'audio' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000', name: 'Dell ProSupport para OptiPlex 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/1y-nbd-a-3y-prosupport', name: 'Dell OptiPlex 3000 1Y NBD a 3Y ProSupport', legacyCategory: 'software' },
  { path: 'impresion/consumibles/etiquetas', name: 'Etiquetas para impresion', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica', name: 'Etiquetas de transferencia termica', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas', name: 'Etiquetas blancas de transferencia termica', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0012a', name: 'Etiquetas PCM 50000I0012A blancas', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/alarmas/sensores/movimiento-pir', name: 'Sensores PIR de movimiento', legacyCategory: 'security' },
  { path: 'seguridad/alarmas/sensores/movimiento-pir/inalambricos', name: 'Sensores PIR inalambricos', legacyCategory: 'security' },
  { path: 'seguridad/alarmas/sensores/movimiento-pir/inalambricos/qian-pa-96r', name: 'Sensores Qian PA-96R', legacyCategory: 'security' },
  { path: 'hogar/electrodomesticos/refrigeradores', name: 'Refrigeradores', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door', name: 'Refrigeradores French Door', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door/25-pies', name: 'Refrigeradores French Door 25 pies', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door/25-pies/lg-gm25bpt', name: 'Refrigeradores LG GM25BPT 25 pies', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/software-pos/restaurantes/timbres-cfdi', name: 'Timbres CFDI para software POS restaurante', legacyCategory: 'software' },
  { path: 'punto-de-venta/software-pos/restaurantes/timbres-cfdi/10000', name: 'Soft Restaurant 10000 timbres CFDI', legacyCategory: 'software' },
  { path: 'energia/movilidad-electrica', name: 'Movilidad electrica', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev', name: 'Cargadores para vehiculos electricos', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev/wallbox', name: 'Cargadores EV Wallbox', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev/wallbox/tipo-2', name: 'Cargadores EV Wallbox Tipo 2', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev/wallbox/tipo-2/7kw-32a', name: 'Cargadores EV Wallbox Tipo 2 7kW 32A', legacyCategory: 'power' },
  { path: 'computo/accesorios/mochilas-fundas/bolsos-crossbody', name: 'Bolsos crossbody para tecnologia', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/bolsos-crossbody/tablet', name: 'Bolsos crossbody para tablet', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/bolsos-crossbody/tablet/targus-newport', name: 'Targus Newport Crossbody para tablet', legacyCategory: 'accessories' },
  { path: 'audio/bocinas/karaoke', name: 'Bocinas para karaoke', legacyCategory: 'audio' },
  { path: 'audio/bocinas/karaoke/bafles-bluetooth', name: 'Bafles Bluetooth para karaoke', legacyCategory: 'audio' },
  { path: 'audio/bocinas/karaoke/bafles-bluetooth/15-pulgadas', name: 'Bafles Bluetooth karaoke 15 pulgadas', legacyCategory: 'audio' },
  { path: 'audio/bocinas/karaoke/bafles-bluetooth/15-pulgadas/80w', name: 'Bafles Bluetooth karaoke 15 pulgadas 80W', legacyCategory: 'audio' },
  { path: 'oficina/papeleria/marcadores/permanentes', name: 'Marcadores permanentes', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/metalicos', name: 'Marcadores permanentes metalicos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/metalicos/plata', name: 'Marcadores permanentes metalicos plata', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/metalicos/plata/12-piezas', name: 'Marcadores metalicos plata caja 12 piezas', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/extension-generica', name: 'Extension generica de garantia Dell', legacyCategory: 'software' },
  { path: 'seguridad/control-acceso', name: 'Control de acceso', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/asistencia', name: 'Control de asistencia', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/asistencia/biometricos', name: 'Terminales biometricas de asistencia', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/asistencia/biometricos/huella-rfid', name: 'Terminales biometricas huella y RFID', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/asistencia/biometricos/huella-rfid/anviz-w1-pro', name: 'Anviz W1 Pro huella y RFID', legacyCategory: 'security' },
  { path: 'punto-de-venta/terminales-pos', name: 'Terminales POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-pos/accesorios', name: 'Accesorios para terminales POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-pos/accesorios/docking', name: 'Bases docking para terminales POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-pos/accesorios/docking/ec-line-ec-wt-cradle', name: 'Docking EC Line EC-WT-CRADLE', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles', name: 'Terminales moviles POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios', name: 'Accesorios para terminales moviles POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/gatillos', name: 'Gatillos para terminales moviles', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/gatillos/zebra-tc22-tc27', name: 'Gatillos Zebra TC22 y TC27', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/juegos-geometria', name: 'Juegos de geometria escolar', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/juegos-geometria/medianos', name: 'Juegos de geometria medianos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/juegos-geometria/medianos/baco-5050', name: 'Juego de geometria Baco 5050', legacyCategory: 'accessories' },
  { path: 'computo/componentes/enfriamiento/pasta-termica', name: 'Pastas termicas', legacyCategory: 'components' },
  { path: 'computo/componentes/enfriamiento/pasta-termica/corsair-xtm70-3g', name: 'Corsair XTM70 3 g', legacyCategory: 'components' },
  { path: 'computo/colaboracion', name: 'Colaboracion y videoconferencia', legacyCategory: 'desktops' },
  { path: 'computo/colaboracion/salas-reunion', name: 'Soluciones para salas de reunion', legacyCategory: 'desktops' },
  { path: 'computo/colaboracion/salas-reunion/microsoft-teams-rooms', name: 'Salas Microsoft Teams Rooms', legacyCategory: 'desktops' },
  { path: 'computo/colaboracion/salas-reunion/microsoft-teams-rooms/lenovo-thinksmart-core-gen-2-full-room', name: 'Lenovo ThinkSmart Core Gen 2 Full Room MTR', legacyCategory: 'desktops' },
  { path: 'impresion/consumibles/papel', name: 'Papel para impresion', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/bright-white-pro', name: 'Epson Bright White Pro Paper', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/bright-white-pro/carta-500-hojas', name: 'Epson Bright White Pro carta 500 hojas', legacyCategory: 'printers_scanners' },
  { path: 'audio/audifonos/diadema', name: 'Audifonos de diadema', legacyCategory: 'audio' },
  { path: 'audio/audifonos/diadema/alambricos', name: 'Diademas alambricas', legacyCategory: 'audio' },
  { path: 'audio/audifonos/diadema/alambricos/3-5mm-microfono', name: 'Diademas 3.5 mm con microfono', legacyCategory: 'audio' },
  { path: 'audio/audifonos/diadema/alambricos/3-5mm-microfono/techzone-tz15pcaud', name: 'TechZone TZ15PCAUD', legacyCategory: 'audio' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/llave/microsaver-2-0-master-k64434ww', name: 'Kensington MicroSaver 2.0 K64434WW', legacyCategory: 'accessories' },
  { path: 'telefonia/conmutadores-ip', name: 'Conmutadores IP', legacyCategory: 'software' },
  { path: 'telefonia/conmutadores-ip/panasonic-kx-ns500', name: 'Panasonic KX-NS500', legacyCategory: 'software' },
  { path: 'telefonia/conmutadores-ip/panasonic-kx-ns500/licencias', name: 'Licencias Panasonic KX-NS500', legacyCategory: 'software' },
  { path: 'telefonia/conmutadores-ip/panasonic-kx-ns500/licencias/activacion-full', name: 'Activacion full Panasonic KX-NS500', legacyCategory: 'software' },
  { path: 'infraestructura/racks-accesorios/contencion-pasillos', name: 'Contencion de pasillos para racks', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/contencion-pasillos/puertas-deslizantes', name: 'Puertas deslizantes para contencion de pasillos', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/contencion-pasillos/puertas-deslizantes/tripp-lite-srctmtsdd', name: 'Puertas deslizantes Tripp Lite SRCTMTSDD', legacyCategory: 'networking' },
  { path: 'energia/baterias-portatiles', name: 'Baterias portatiles', legacyCategory: 'power' },
  { path: 'energia/baterias-portatiles/power-banks', name: 'Power banks', legacyCategory: 'power' },
  { path: 'energia/baterias-portatiles/power-banks/5000mah', name: 'Power banks 5000 mAh', legacyCategory: 'power' },
  { path: 'energia/baterias-portatiles/power-banks/5000mah/necnon-npw-05fb', name: 'NECNON NPW-05FB 5000 mAh', legacyCategory: 'power' },
  { path: 'software/servicios-nube', name: 'Servicios en la nube', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud', name: 'CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/gestion-nube', name: 'Gestion en la nube CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/gestion-nube/xplus-cq', name: 'CT Cloud XPLUS CQ', legacyCategory: 'software' },
  { path: 'energia/cargadores-usb/pared-usb-c-usb-a', name: 'Cargadores USB-C y USB-A de pared', legacyCategory: 'power' },
  { path: 'energia/cargadores-usb/pared-usb-c-usb-a/35w-gan', name: 'Cargadores GaN 35W USB-C USB-A', legacyCategory: 'power' },
  { path: 'energia/cargadores-usb/pared-usb-c-usb-a/35w-gan/adata-qcpdwh', name: 'ADATA CHARGERU-0352-QCPDWH 35W', legacyCategory: 'power' },
  { path: 'audio-video', name: 'Audio y video', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores', name: 'Proyectores', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios', name: 'Accesorios para proyectores', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios/lamparas', name: 'Lamparas para proyectores', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios/lamparas/epson-elplp88', name: 'Epson ELPLP88 V13H010L88', legacyCategory: 'accessories' },
  { path: 'software/servicios-nube/ct-cloud/configuracion-servidores', name: 'Configuracion de servidores CT Cloud', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/configuracion-servidores/ftp-sftp', name: 'Configuracion FTP SFTP CT Cloud', legacyCategory: 'software' },
  { path: 'seguridad/control-acceso/credenciales-rfid', name: 'Credenciales RFID', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/credenciales-rfid/tarjetas-pvc', name: 'Tarjetas PVC RFID', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/credenciales-rfid/tarjetas-pvc/em-125khz', name: 'Tarjetas EM 125 kHz', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/credenciales-rfid/tarjetas-pvc/em-125khz/anviz-10-pack', name: 'Anviz EMIDCARD 10 piezas', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-camaras', name: 'Accesorios para camaras CCTV', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion', name: 'Cajas de conexion para camaras', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/turret-metalicas', name: 'Cajas para camaras turret metalicas', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/turret-metalicas/unv-tr-jb03-h-in-v2', name: 'UNV TR-JB03-H-IN-V2', legacyCategory: 'security' },
  { path: 'punto-de-venta/accesorios-pos', name: 'Accesorios POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/accesorios-pos/lectores-banda-magnetica', name: 'Lectores de banda magnetica POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/accesorios-pos/lectores-banda-magnetica/ec-line-ec-msr-vp1100', name: 'EC-Line EC-MSR-VP1100', legacyCategory: 'accessories' },
  { path: 'impresion/refacciones', name: 'Refacciones de impresion', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales', name: 'Cabezales de impresion', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos', name: 'Cabezales termicos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos/datamax-i-4212e-203dpi', name: 'Datamax I-4212e 203 dpi', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra-105sl-203dpi', name: 'Zebra 105SL 203 dpi', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/toner-laser/pantum', name: 'Toner laser Pantum', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/toner-laser/pantum/pb-210rb-recarga', name: 'Pantum PB-210RB kit recarga', legacyCategory: 'printers_scanners' },
  { path: 'software/licencias/microsoft', name: 'Licencias Microsoft', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/visio', name: 'Microsoft Visio', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/visio/ltsc-standard-2024-education', name: 'Visio LTSC Standard 2024 Education', legacyCategory: 'software' },
  { path: 'hogar/electrodomesticos/refrigeradores/top-freezer', name: 'Refrigeradores top freezer', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/refrigeradores/top-freezer/20-pies', name: 'Refrigeradores top freezer 20 pies', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/refrigeradores/top-freezer/20-pies/lg-lt57bt', name: 'LG LT57BT 20 pies', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/etiquetas/transferencia-termica/blancas/pcm-50000i0017a', name: 'Etiquetas PCM 50000I0017A blancas', legacyCategory: 'printers_scanners' },
  { path: 'computo/accesorios/stylus-tablets/apple-pencil', name: 'Apple Pencil', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/stylus-tablets/apple-pencil/2-generacion', name: 'Apple Pencil 2a generacion', legacyCategory: 'accessories' },
  { path: 'redes/extensores-wifi/dual-band/ac1200/tenda-a18', name: 'Tenda A18 AC1200', legacyCategory: 'networking' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/mangos', name: 'Mangos para terminales moviles', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/mangos/datalogic-skorpio-x5', name: 'Mango Datalogic Skorpio X5', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/rosa', name: 'Resaltadores rosas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/rosa/12-piezas', name: 'Resaltadores rosas caja 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/rosa/12-piezas/azor-2600rs', name: 'Azor Vision Plus 2600RS rosa', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/borradores', name: 'Borradores escolares', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/borradores/blancos', name: 'Borradores blancos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/borradores/blancos/baco-g30', name: 'Baco G-30 blanco', legacyCategory: 'accessories' },
  { path: 'energia/cargadores-inalambricos/10w', name: 'Cargadores inalambricos 10W', legacyCategory: 'power' },
  { path: 'energia/cargadores-inalambricos/10w/hune-hoja', name: 'Hune Hoja 10W', legacyCategory: 'power' },
  { path: 'servicios-ti/soporte-garantias/dell/premium-support', name: 'Dell Premium Support', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/premium-support/alienware-x14', name: 'Dell Premium Support Alienware X14', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/premium-support/alienware-x14/1y-carry-in-a-3y-premium', name: 'Dell Alienware X14 1Y Carry-In a 3Y Premium Support', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios', name: 'Accesorios para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion', name: 'Tarjetas de comunicacion para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/modbus', name: 'Tarjetas Modbus para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/modbus/cdp-upomodbus', name: 'CDP UPOMODBUS', legacyCategory: 'power' },
  { path: 'seguridad/control-acceso/lectores-biometricos', name: 'Lectores biometricos de acceso', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/lectores-biometricos/huella-rfid', name: 'Lectores huella y RFID', legacyCategory: 'security' },
  { path: 'seguridad/control-acceso/lectores-biometricos/huella-rfid/anviz-m5-plus', name: 'Anviz M5 Plus', legacyCategory: 'security' },
  { path: 'climatizacion/aires-acondicionados/minisplit/estandar/24000-btu/solo-frio-230v', name: 'Minisplit estandar 24000 BTU solo frio 230V', legacyCategory: 'accessories' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip66', name: 'Cajas de conexion IP66', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip66/provision-pr-jb12ip66-g', name: 'Provision-ISR PR-JB12IP66-G', legacyCategory: 'security' },
  { path: 'audio/bocinas/bluetooth/portatiles/ipx5-5w', name: 'Bocinas Bluetooth IPX5 5W', legacyCategory: 'audio' },
  { path: 'audio/bocinas/bluetooth/portatiles/ipx5-5w/acteck-ap420', name: 'Acteck Glee Mini AP420', legacyCategory: 'audio' },
  { path: 'redes/cableado-estructurado/conectores-rj45/cat5e/blindados', name: 'Plugs RJ45 Cat5e blindados', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-rj45/cat5e/blindados/enson-ens-srj45-cat5e', name: 'Enson ENS-SRJ45-CAT5E', legacyCategory: 'networking' },
  { path: 'energia/movilidad-electrica/cargadores-ev/portatiles', name: 'Cargadores EV portatiles', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev/portatiles/tipo-2', name: 'Cargadores EV portatiles Tipo 2', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev/portatiles/tipo-2/16a', name: 'Cargadores EV portatiles Tipo 2 16A', legacyCategory: 'power' },
  { path: 'energia/movilidad-electrica/cargadores-ev/portatiles/tipo-2/16a/alter-ev-omb141', name: 'Alter EV-OMB141', legacyCategory: 'power' },
  { path: 'servicios-ti/soporte-garantias/dell/carry-in', name: 'Dell Carry-In', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/carry-in/inspiron-2-en-1', name: 'Dell Carry-In Inspiron 2 en 1', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/carry-in/inspiron-2-en-1/1y-a-3y', name: 'Dell Inspiron 2 en 1 1Y a 3Y Carry-In', legacyCategory: 'software' },
  { path: 'impresion/escaneres/documentales', name: 'Escaneres documentales', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf', name: 'Escaneres documentales con ADF', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf/alto-volumen', name: 'Escaneres ADF de alto volumen', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf/alto-volumen/kodak-i3500', name: 'Kodak Alaris i3500 alto volumen', legacyCategory: 'printers_scanners' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables', name: 'Marcadores lavables base agua', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/12-colores', name: 'Marcadores lavables base agua 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/12-colores/azor-aquarelo-grip-20012', name: 'Azor Aquarelo Grip 20012', legacyCategory: 'accessories' },
  { path: 'electronica', name: 'Electronica', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores', name: 'Pantallas y monitores', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos', name: 'Pizarrones y mesas interactivas', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/mesas-interactivas', name: 'Mesas interactivas tactiles', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/mesas-interactivas/32-pulgadas', name: 'Mesas interactivas tactiles 32 pulgadas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/baco-le-plume-negro-12-piezas', name: 'BACO Le Plume negro 12 piezas', legacyCategory: 'accessories' },
  { path: 'impresion/escaneres/documentales/adf/duplex', name: 'Escaneres ADF duplex', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf/duplex/kodak-e1035', name: 'Kodak Alaris E1035 duplex', legacyCategory: 'printers_scanners' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd', name: 'Dell Basic Next Business Day', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/optiplex-3000', name: 'Dell Basic NBD para OptiPlex 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/optiplex-3000/1y-a-5y', name: 'Dell OptiPlex 3000 1Y a 5Y Basic NBD', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia', name: 'Soporte y garantias GHIA', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3286', name: 'Garantias GHIA PCGHIA-3286', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3286/24-meses-adicionales', name: 'GHIA PCGHIA-3286 24 meses adicionales', legacyCategory: 'software' },
  { path: 'punto-de-venta/software-pos/restaurantes/comandero-movil', name: 'Comanderos moviles Soft Restaurant', legacyCategory: 'software' },
  { path: 'punto-de-venta/software-pos/restaurantes/comandero-movil/tablet-android', name: 'Comanderos moviles con tablet Android', legacyCategory: 'software' },
  { path: 'punto-de-venta/software-pos/restaurantes/comandero-movil/tablet-android/lenovo-tab-one-8-7', name: 'Soft Restaurant Movil Lenovo Tab One 8.7', legacyCategory: 'software' },
  { path: 'computo/desktops/workstations', name: 'Workstations de escritorio', legacyCategory: 'desktops' },
  { path: 'computo/desktops/workstations/lenovo-thinkstation-p3-ultra-sff-gen-2', name: 'Lenovo ThinkStation P3 Ultra SFF Gen 2', legacyCategory: 'desktops' },
  { path: 'computo/desktops/workstations/lenovo-thinkstation-p3-ultra-sff-gen-2/pa0012-5y-onsite', name: 'Lenovo ThinkStation P3 Ultra PA0012 5Y Onsite', legacyCategory: 'desktops' },
  { path: 'punto-de-venta/software-pos/restaurantes/pacific-soft-psf010', name: 'Pacific Soft PSF010 restaurantes', legacyCategory: 'software' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos', name: 'Correctores electromagneticos de voltaje', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/8000va', name: 'Correctores electromagneticos 8000VA', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/8000va/sola-basic-15-81-120-8000', name: 'Sola Basic ISB 15-81-120-8000 8000VA', legacyCategory: 'power' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/vostro-3000', name: 'Dell ProSupport para Vostro 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/vostro-3000/1y-basic-onsite-a-3y-prosupport', name: 'Dell Vostro 3000 1Y Basic Onsite a 3Y ProSupport', legacyCategory: 'software' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino', name: 'Marcadores permanentes Azor Signal punto fino', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/naranja', name: 'Marcadores Azor Signal punto fino naranja', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/naranja/12-piezas', name: 'Azor Signal 30006 naranja 12 piezas', legacyCategory: 'accessories' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip64', name: 'Cajas de conexion IP64', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip64/provision-pr-jb14ip64', name: 'Provision-ISR PR-JB14IP64', legacyCategory: 'security' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales', name: 'Marcadores permanentes industriales', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales/base-aceite', name: 'Marcadores industriales base aceite', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales/base-aceite/uni-paint-px20-blanco', name: 'Uni Paint PX-20 blanco', legacyCategory: 'accessories' },
  { path: 'accesorios/montaje-soportes/audio-video/adaptadores-pantalla', name: 'Adaptadores de montaje para pantallas', legacyCategory: 'accessories' },
  { path: 'accesorios/montaje-soportes/audio-video/adaptadores-pantalla/peerless-plp-unl', name: 'Peerless-AV PLP-UNL', legacyCategory: 'accessories' },
  { path: 'impresion/impresoras/gran-formato', name: 'Impresoras de gran formato', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/gran-formato/multifuncionales', name: 'Multifuncionales de gran formato', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/gran-formato/multifuncionales/24-pulgadas', name: 'Multifuncionales gran formato 24 pulgadas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/gran-formato/multifuncionales/24-pulgadas/hp-designjet-t830', name: 'HP DesignJet T830 24 pulgadas', legacyCategory: 'printers_scanners' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-cableados', name: 'Lectores 2D cableados', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-cableados/industriales-powerscan-9600', name: 'Datalogic PowerScan 9600 cableados', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-cableados/industriales-powerscan-9600/rs232-pd9630-srk2', name: 'Datalogic PD9630-SRK2 RS-232', legacyCategory: 'accessories' },
  { path: 'redes/radioenlaces-antenas/radios-cpe', name: 'Radios CPE para radioenlaces', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/radios-cpe/ptp-ptmp', name: 'Radios CPE PTP y PTMP', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/radios-cpe/ptp-ptmp/mimosa-c5c', name: 'Mimosa C5c conectorizado', legacyCategory: 'networking' },
  { path: 'audio/bocinas/pc', name: 'Bocinas para PC', legacyCategory: 'audio' },
  { path: 'audio/bocinas/pc/gaming', name: 'Bocinas gaming para PC', legacyCategory: 'audio' },
  { path: 'audio/bocinas/pc/gaming/2-1-rgb', name: 'Bocinas gaming 2.1 RGB', legacyCategory: 'audio' },
  { path: 'audio/bocinas/pc/gaming/2-1-rgb/logitech-g560', name: 'Logitech G560 LIGHTSYNC', legacyCategory: 'audio' },
  { path: 'impresion/impresoras/etiquetas/accesorios', name: 'Accesorios para impresoras de etiquetas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/etiquetas/accesorios/servidores-impresion', name: 'Servidores de impresion para etiquetadoras', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/etiquetas/accesorios/servidores-impresion/zebra-zt200-p1037974-001', name: 'Zebra ZT200 P1037974-001 ZebraNet', legacyCategory: 'printers_scanners' },
  { path: 'audio/audifonos/bluetooth/diadema-over-ear/dual-2-4ghz-enc', name: 'Diademas Bluetooth 2.4GHz con ENC', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth/diadema-over-ear/dual-2-4ghz-enc/perfect-choice-noctune', name: 'Perfect Choice Noctune PC-117278', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/subwoofers', name: 'Subwoofers', legacyCategory: 'audio' },
  { path: 'audio/bocinas/subwoofers/bluetooth', name: 'Subwoofers Bluetooth', legacyCategory: 'audio' },
  { path: 'audio/bocinas/subwoofers/bluetooth/50w', name: 'Subwoofers Bluetooth 50W', legacyCategory: 'audio' },
  { path: 'audio/bocinas/subwoofers/bluetooth/50w/acteck-bw676', name: 'Acteck Dynamic Bass BW676', legacyCategory: 'audio' },
  { path: 'computo/accesorios/mousepads/gaming-xl', name: 'Mousepads gamer XL', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mousepads/gaming-xl/speed-control', name: 'Mousepads gamer XL speed-control', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mousepads/gaming-xl/speed-control/vorago-mpg-301', name: 'Vorago Start The Game MPG-301', legacyCategory: 'accessories' },
  { path: 'servicios-ti/capacitacion', name: 'Capacitacion TI', legacyCategory: 'software' },
  { path: 'servicios-ti/capacitacion/telefonia-ip-redes', name: 'Capacitacion telefonia IP y redes', legacyCategory: 'software' },
  { path: 'servicios-ti/capacitacion/telefonia-ip-redes/grandstream-remota', name: 'Grandstream capacitacion remota', legacyCategory: 'software' },
  { path: 'computo/componentes/enfriamiento/pasta-termica/vorago-tp-100-3g', name: 'Vorago TP-100 3 g', legacyCategory: 'components' },
  { path: 'energia/no-breaks-ups/accesorios/paneles-bypass', name: 'Paneles bypass para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/paneles-bypass/40kw-208v', name: 'Paneles bypass UPS 40kW 208V', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/paneles-bypass/40kw-208v/apc-sbp40kfc1m1', name: 'APC SBP40KFC1M1 40kW 208V', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias', name: 'Bancos externos de baterias UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre', name: 'Bancos de baterias UPS rack torre', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/48v', name: 'Bancos de baterias UPS 48V', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/48v/cyberpower-bp48v75art2u', name: 'CyberPower BP48V75ART2U 48V 2U', legacyCategory: 'power' },
  { path: 'impresion/refacciones/cabezales/inkjet', name: 'Cabezales inkjet', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/inkjet/hp-designjet-744', name: 'Cabezales HP DesignJet 744', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/inkjet/hp-designjet-744/f9j86a-photo-black-cyan', name: 'HP 744 F9J86A Photo Black Cyan', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas', name: 'Formas continuas y papel stock', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock', name: 'Papel stock PCM Data Stock', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5', name: 'Papel stock 9.5 x 5.5 pulgadas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/3-tantos', name: 'Papel stock 3 tantos 9.5 x 5.5', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/3-tantos/pcm-ds00232000b', name: 'PCM DS00232000B 3 tantos 2000 hojas', legacyCategory: 'printers_scanners' },
  { path: 'software/seguridad/privacidad-antirrastreo', name: 'Privacidad y antirrastreo', legacyCategory: 'software' },
  { path: 'software/seguridad/privacidad-antirrastreo/norton-antitrack', name: 'Norton AntiTrack', legacyCategory: 'software' },
  { path: 'software/seguridad/privacidad-antirrastreo/norton-antitrack/1-dispositivo-2-anos', name: 'Norton AntiTrack 1 dispositivo 2 anos', legacyCategory: 'software' },
  { path: 'hogar/higiene', name: 'Higiene y limpieza', legacyCategory: 'accessories' },
  { path: 'hogar/higiene/dispensadores-jabon', name: 'Dispensadores de jabon', legacyCategory: 'accessories' },
  { path: 'hogar/higiene/dispensadores-jabon/manuales', name: 'Dispensadores manuales de jabon', legacyCategory: 'accessories' },
  { path: 'hogar/higiene/dispensadores-jabon/manuales/rellenables-1-1l', name: 'Dispensadores rellenables 1.1L', legacyCategory: 'accessories' },
  { path: 'hogar/higiene/dispensadores-jabon/manuales/rellenables-1-1l/clar-innova-csy060', name: 'Clar Systems Innova CSY060 1.1L', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/rosa/12-piezas/baco-bacoflash-99365', name: 'BACO Bacoflash 99365 rosa 12 piezas', legacyCategory: 'accessories' },
  { path: 'impresion/escaneres/documentales/adf/alto-volumen/hp-scanjet-7000-s3', name: 'HP ScanJet Enterprise Flow 7000 s3', legacyCategory: 'printers_scanners' },
  { path: 'infraestructura/racks-accesorios/ventilacion', name: 'Ventilacion para racks', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/ventilacion/extractores', name: 'Extractores para racks', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/ventilacion/extractores/laces-la200kea2', name: 'LACES LA200KEA2 kit de extractores', legacyCategory: 'networking' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus', name: 'Dell ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops', name: 'Dell ProSupport Plus para desktops', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-24-aio', name: 'Dell ProSupport Plus Pro 24 AIO', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-24-aio/3y-basic-a-3y-prosupport-plus', name: 'Dell Pro 24 AIO 3Y Basic a 3Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'software/gestion-ti/endpoint-management/ivanti-endpoint-manager/pma-4zn1q45636', name: 'Ivanti Endpoint Manager PMA 4ZN1Q45636', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/poly', name: 'Soporte y garantias Poly', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/poly/blackwire', name: 'Poly Blackwire Plus Service', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/poly/blackwire/plus-service-3y', name: 'Poly Blackwire Plus Service 3 anos', legacyCategory: 'software' },
  { path: 'redes/cableado-estructurado/placas-keystone/2-puertos/enson-ens-fp62', name: 'Enson ENS-FP62 faceplate 2 puertos', legacyCategory: 'networking' },
  { path: 'computo/componentes/enfriamiento/pasta-termica/corsair-xtm60-3g', name: 'Corsair XTM60 3 g', legacyCategory: 'components' },
  { path: 'punto-de-venta/software-pos/restaurantes/licencias-renta-mensual', name: 'Licencias mensuales Soft Restaurant', legacyCategory: 'software' },
  { path: 'punto-de-venta/software-pos/restaurantes/licencias-renta-mensual/lite-2-nodos', name: 'Soft Restaurant 11 Lite renta mensual 2 nodos', legacyCategory: 'software' },
  { path: 'electronica/wearables', name: 'Wearables', legacyCategory: 'accessories' },
  { path: 'electronica/wearables/smartwatches', name: 'Smartwatches', legacyCategory: 'accessories' },
  { path: 'electronica/wearables/smartwatches/amazfit-gts-4', name: 'Amazfit GTS 4', legacyCategory: 'accessories' },
  { path: 'software/licencias/microsoft/visio/professional-2024-esd', name: 'Visio Professional 2024 ESD', legacyCategory: 'software' },
  { path: 'salud/higiene/cubrebocas/kn95/20-piezas', name: 'Cubrebocas KN95 20 piezas', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95/20-piezas/ksa', name: 'KSA KN95 caja 20 piezas', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-7010', name: 'Dell ProSupport Plus OptiPlex 7010', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-7010/3y-basic-a-5y-prosupport-plus', name: 'Dell OptiPlex 7010 3Y Basic a 5Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra', name: 'Marcadores Azor Signal Xtra', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/negro', name: 'Marcadores Signal Xtra negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/negro/12-piezas', name: 'Azor Signal Xtra 40001 negro 12 piezas', legacyCategory: 'accessories' },
  { path: 'infraestructura/racks-accesorios/ventilacion/ductos-descarga', name: 'Ductos de descarga para racks', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/ventilacion/ductos-descarga/tripp-lite-srcool7kduct', name: 'Tripp Lite SRCOOL7KDUCT', legacyCategory: 'networking' },
  { path: 'software/servicios-nube/ct-cloud/respaldo-nube', name: 'CT Cloud respaldo en la nube', legacyCategory: 'software' },
  { path: 'software/servicios-nube/ct-cloud/respaldo-nube/250gb', name: 'CT Cloud NCBU250 respaldo 250GB', legacyCategory: 'software' },
  { path: 'redes/radioenlaces-antenas/radios-backhaul', name: 'Radios backhaul para radioenlaces', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/radios-backhaul/ptp-licenciados', name: 'Radios backhaul PTP licenciados', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/radios-backhaul/ptp-licenciados/mimosa-b11', name: 'Mimosa B11 10.0-11.7GHz', legacyCategory: 'networking' },
  { path: 'computo/perifericos/tabletas-digitalizadoras', name: 'Tabletas digitalizadoras', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/tabletas-digitalizadoras/adesso-cybertablet-k10', name: 'Adesso CyberTablet K10', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/lenovo', name: 'Soporte y garantias Lenovo', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci', name: 'Lenovo Depot CCI', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci/3y-upgrade', name: 'Lenovo Depot CCI upgrade 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci/3y-upgrade/5ws0k76347', name: 'Lenovo 5WS0K76347 3Y Depot CCI', legacyCategory: 'software' },
  { path: 'oficina/papeleria/archivo', name: 'Archivo y organizacion', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/protectores-hojas', name: 'Protectores de hojas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/protectores-hojas/carta', name: 'Protectores de hojas carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/protectores-hojas/carta/100-piezas', name: 'Protectores de hojas carta 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/protectores-hojas/carta/100-piezas/mae-ph100b', name: 'MAE PH-100B protectores carta 100 piezas', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/nano-lock', name: 'Candados laptop Nano Lock', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/nano-lock/techzone-tzkl703kd', name: 'TechZone TZKL703KD Nano Lock', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco', name: 'Marcadores para pizarron blanco', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico', name: 'Marcadores Magistral Didactico', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico/negro', name: 'Marcadores Magistral Didactico negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico/negro/12-piezas', name: 'Azor Magistral 8350NE negro 12 piezas', legacyCategory: 'accessories' },
  { path: 'software/licencias/seguridad-red', name: 'Licencias de seguridad de red', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/hillstone', name: 'Licencias Hillstone', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/hillstone/a200', name: 'Licencias Hillstone A200', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/hillstone/a200/bdl1-24m', name: 'Hillstone BDL1-A200-IN24 24 meses', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-3000', name: 'Dell ProSupport Plus OptiPlex 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-3000/3y-basic-a-3y-prosupport-plus', name: 'Dell OptiPlex 3000 3Y Basic a 3Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/cisco-meraki', name: 'Licencias Cisco Meraki', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/cisco-meraki/mx64', name: 'Licencias Cisco Meraki MX64', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/cisco-meraki/mx64/advanced-security-1y', name: 'Cisco Meraki MX64 Advanced Security 1 ano', legacyCategory: 'software' },
  { path: 'energia/solar/inversores-ups', name: 'Inversores y UPS solares', legacyCategory: 'power' },
  { path: 'energia/solar/inversores-ups/line-interactive', name: 'Inversores UPS solares line-interactive', legacyCategory: 'power' },
  { path: 'energia/solar/inversores-ups/line-interactive/mppt-12v', name: 'Inversores UPS solares MPPT 12V', legacyCategory: 'power' },
  { path: 'energia/solar/inversores-ups/line-interactive/mppt-12v/cdp-es-avr-612-sol', name: 'CDP ES-AVR-612 SOL 400W', legacyCategory: 'power' },
  { path: 'energia/cargadores-usb/pared-usb-c/30w', name: 'Cargadores USB-C de pared 30W', legacyCategory: 'accessories' },
  { path: 'energia/cargadores-usb/pared-usb-c/30w/baseus-palm-1c', name: 'Baseus Palm 1C 30W blanco', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/serial-db9', name: 'Adaptadores seriales DB9', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/serial-db9/cambiadores-genero', name: 'Cambiadores de genero serial DB9', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/serial-db9/cambiadores-genero/startech-gc9sm', name: 'StarTech GC9SM DB9 macho-macho', legacyCategory: 'accessories' },
  { path: 'audio/audifonos/diadema/gaming', name: 'Audifonos gaming de diadema', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/diadema/gaming/alambricos', name: 'Audifonos gaming alambricos', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/diadema/gaming/alambricos/3-5mm-usb', name: 'Audifonos gaming 3.5mm y USB', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/diadema/gaming/alambricos/3-5mm-usb/corsair-hs35-surround-v2', name: 'Corsair HS35 Surround v2', legacyCategory: 'headphones' },
  { path: 'energia/cargadores-usb/pared-usb-c-usb-a/65w-gan', name: 'Cargadores GaN 65W USB-C USB-A', legacyCategory: 'power' },
  { path: 'energia/cargadores-usb/pared-usb-c-usb-a/65w-gan/adata-chargeru-0653-qcpdwh', name: 'ADATA CHARGERU-0653-QCPDWH 65W', legacyCategory: 'power' },
  { path: 'servicios-ti/soporte-garantias/dell/premium-support-plus', name: 'Dell Premium Support Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/premium-support-plus/inspiron-3000', name: 'Dell Premium Support Plus Inspiron 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/premium-support-plus/inspiron-3000/1y-carry-in-a-3y-premium-support-plus', name: 'Dell Inspiron 3000 1Y Carry-In a 3Y Premium Support Plus', legacyCategory: 'software' },
  { path: 'punto-de-venta/digitalizadores-firma/accesorios', name: 'Accesorios para digitalizadores de firma', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/accesorios/plumas', name: 'Plumas para digitalizadores de firma', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/accesorios/plumas/topaz-p-ts01-b', name: 'Topaz P-TS01-B pluma SigLite', legacyCategory: 'accessories' },
  { path: 'seguridad/cctv/accesorios-cableado/cables-camaras-moviles/streamax-m6pin-dj-transfer', name: 'Streamax M6PIN DJ-TRANSFER 6 pines', legacyCategory: 'cameras' },
  { path: 'oficina/papeleria/archivo/cajas-archivo', name: 'Cajas para archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/carta', name: 'Cajas para archivo carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/carta/20-piezas', name: 'Cajas para archivo carta 20 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/carta/20-piezas/geo-004', name: 'GEO 004 caja archivo carta 20 piezas', legacyCategory: 'accessories' },
  { path: 'software/licencias/microsoft/visio/ltsc-professional-2024-commercial', name: 'Visio LTSC Professional 2024 Commercial CSP', legacyCategory: 'software' },
  { path: 'oficina/papeleria/engrapadoras-grapas', name: 'Engrapadoras y grapas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/engrapadoras-grapas/grapas-estandar', name: 'Grapas estandar', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/engrapadoras-grapas/grapas-estandar/baco-g1000-1000p', name: 'BACO G-1000 Superflex 1000 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/engrapadoras-grapas/grapas-estandar/baco-g5000-5040p', name: 'BACO G-5000 Superflex 5040 piezas', legacyCategory: 'accessories' },
  { path: 'audio/audifonos/wearables', name: 'Audifonos wearables', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/wearables/lentes-inteligentes', name: 'Lentes inteligentes con audio', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/wearables/lentes-inteligentes/perfect-choice-evoir', name: 'Perfect Choice Evoir PC-117292', legacyCategory: 'headphones' },
  { path: 'computo/colaboracion/videoconferencia', name: 'Videoconferencia', legacyCategory: 'audio' },
  { path: 'computo/colaboracion/videoconferencia/accesorios', name: 'Accesorios de videoconferencia', legacyCategory: 'audio' },
  { path: 'computo/colaboracion/videoconferencia/accesorios/hubs-microfono', name: 'Hubs para microfonos de videoconferencia', legacyCategory: 'audio' },
  { path: 'computo/colaboracion/videoconferencia/accesorios/hubs-microfono/logitech-rally-mic-pod-hub', name: 'Logitech Rally Mic Pod Hub', legacyCategory: 'audio' },
  { path: 'audio-video/proyectores/accesorios/lamparas/epson-elplp75', name: 'Epson ELPLP75 V13H010L75', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios/lamparas/epson-elplp71', name: 'Epson ELPLP71 V13H010L71', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios/lamparas/epson-elplp76', name: 'Epson ELPLP76 V13H010L76', legacyCategory: 'accessories' },
  { path: 'infraestructura/monitoreo-ambiental', name: 'Monitoreo ambiental de infraestructura', legacyCategory: 'power' },
  { path: 'infraestructura/monitoreo-ambiental/sensores-temperatura', name: 'Sensores de temperatura', legacyCategory: 'power' },
  { path: 'infraestructura/monitoreo-ambiental/sensores-temperatura/apc-ap9335t', name: 'APC NetBotz AP9335T', legacyCategory: 'power' },
  { path: 'electronica/wearables/smartwatches/stylos-staswm3p', name: 'Stylos SW2 STASWM3P rosa', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/alienware-elite-care', name: 'Dell Alienware Elite Care', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/alienware-elite-care/notebooks', name: 'Dell Alienware Elite Care notebooks', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/alienware-elite-care/notebooks/1y-basic-carry-in-a-3y', name: 'Dell Alienware notebooks 1Y Basic Carry-In a 3Y Elite Care', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/72v', name: 'Bancos de baterias UPS 72V rack torre', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/72v/cyberpower-bp72v60art2u', name: 'CyberPower BP72V60ART2U 72V 60A', legacyCategory: 'power' },
  { path: 'oficina/papeleria/adhesivos', name: 'Adhesivos de oficina y escuela', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/adhesivos/lapices-adhesivos', name: 'Lapices adhesivos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/adhesivos/lapices-adhesivos/kores-124029-40g-6p', name: 'Kores 124029 lapiz adhesivo 40 g 6 piezas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas/techzone-max-iii', name: 'TechZone Max III TZLBP27-A 16 pulgadas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/surtidos', name: 'Resaltadores surtidos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/surtidos/5-piezas', name: 'Resaltadores surtidos 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/surtidos/5-piezas/azor-vision-plus-2625p', name: 'Azor Vision Plus 2625P surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/vostro-3000', name: 'Dell Basic NBD para Vostro 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/vostro-3000/1y-a-3y', name: 'Dell Vostro 3000 1Y a 3Y Basic NBD', legacyCategory: 'software' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus-rojo-12-piezas', name: 'BIC Cristal Dura Plus rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte', name: 'Dibujo y arte escolar', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/crayones', name: 'Crayones escolares', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/crayones/baco-jumbo-65483-12p', name: 'BACO Jumbo 65483 crayones 12 piezas', legacyCategory: 'accessories' },
  { path: 'infraestructura/racks-accesorios/contencion-pasillos/kits-terminacion', name: 'Kits de terminacion para contencion de pasillos', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/contencion-pasillos/kits-terminacion/tripp-lite-srctmtfrm', name: 'Tripp Lite SRCTMTFRM kit de terminacion', legacyCategory: 'networking' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-150m', name: 'Rollos papel bond plotter 91 cm x 150', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-150m/pcm-10b24', name: 'PCM 10B24 papel bond plotter 0.91 x 150', legacyCategory: 'printers_scanners' },
  { path: 'oficina/ergonomia', name: 'Ergonomia de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/ergonomia/cojines-asiento', name: 'Cojines ergonomicos de asiento', legacyCategory: 'accessories' },
  { path: 'oficina/ergonomia/cojines-asiento/espuma-viscoelastica', name: 'Cojines de espuma viscoelastica', legacyCategory: 'accessories' },
  { path: 'oficina/ergonomia/cojines-asiento/espuma-viscoelastica/kensington-k55805ww', name: 'Kensington K55805WW cojin de asiento', legacyCategory: 'accessories' },
];
