export const MANUAL_CATEGORY_TREE_CYCLE003_PART005 = [
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/pantallas-colaboracion/98-pulgadas', name: 'Pantallas colaborativas 98 pulgadas', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/pantallas-colaboracion/98-pulgadas/quinyx-qtx-te-qs1-98', name: 'Quinyx QTX-TE-QS1-98 pantalla interactiva 98 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/servidores/rack/1u/dell-poweredge-r360', name: 'Dell PowerEdge R360 servidor rack 1U', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door/29-pies/lg-gm39bvp', name: 'LG GM39BVP InstaView French Door 29 pies', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops', name: 'Dell Basic NBD para Dell Pro laptops', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops/1y-a-3y', name: 'Dell Pro laptops 1Y a 3Y Basic NBD', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops/1y-a-3y/n-dprovl1-n1-n3', name: 'Dell N_DPROVL1_N1_N3 Basic NBD 3Y', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/excel', name: 'Microsoft Excel', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/excel/ltsc-2024', name: 'Microsoft Excel LTSC 2024', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/excel/ltsc-2024/commercial-perpetual', name: 'Microsoft Excel LTSC 2024 Commercial perpetuo', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/cdp-snmptxwebpro', name: 'CDP SNMPTXWEBPRO tarjeta SNMP Web Pro', legacyCategory: 'power' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door/29-pies/lg-gm29bip', name: 'LG GM29BIP French Door 29 pies', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops/1y-a-3y/n-dol2-n1-n3', name: 'Dell N_DOL2_N1_N3 Basic NBD 3Y', legacyCategory: 'software' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete/kits-120mm-argb', name: 'Kits de ventiladores ARGB 120 mm para gabinete', legacyCategory: 'components' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete/kits-120mm-argb/ocelot-ofkit-2', name: 'Ocelot OFKIT-2 kit 3 ventiladores 120 mm ARGB', legacyCategory: 'components' },
  { path: 'punto-de-venta/software-pos/restaurantes/licencias-renta-anual/soft-restaurant-12-pro-10-nodos', name: 'Soft Restaurant 12 Pro renta anual 10 nodos', legacyCategory: 'software' },
  { path: 'domotica/contactos-inteligentes/wifi/perfect-choice-pc-108054', name: 'Perfect Choice PC-108054 enchufe Wi-Fi 10A', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-slim-mff', name: 'Dell ProSupport Plus Dell Pro Slim y MFF', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-slim-mff/3y-basic-nbd-a-3y-prosupport-plus', name: 'Dell Pro Slim/MFF 3Y Basic NBD a ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-slim-mff/3y-basic-nbd-a-3y-prosupport-plus/n-ptl1-n3-m3', name: 'Dell N_PTL1_N3_M3 ProSupport Plus 3Y', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales', name: 'Servicios profesionales TI', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales/lenovo', name: 'Servicios profesionales Lenovo', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales/lenovo/cfs-transition-handling', name: 'Lenovo CFS transition handling', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales/lenovo/cfs-transition-handling/5ts1b66173', name: 'Lenovo 5TS1B66173 Transition CFS Handling Charge', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3169', name: 'Garantias GHIA PCGHIA-3169', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3169/24-meses-adicionales', name: 'GHIA PCGHIA-3169 24 meses adicionales', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3169/24-meses-adicionales/pol-8171', name: 'GHIA POL-8171 garantia 24 meses', legacyCategory: 'software' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/4000va', name: 'Correctores electromagneticos 4000VA', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/4000va/sola-basic-15-81-120-4000', name: 'Sola Basic ISB 15-81-120-4000 4000VA', legacyCategory: 'power' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/modelo-pendiente', name: 'Camaras IP WiFi interiores con modelo pendiente', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/modelo-pendiente/tp-link-tapo-familia', name: 'TP-Link Tapo camara interior modelo pendiente', legacyCategory: 'cameras' },
  { path: 'software/productividad-oficina/microsoft-365/apps-for-business', name: 'Microsoft 365 Apps for Business', legacyCategory: 'software' },
  { path: 'software/productividad-oficina/microsoft-365/apps-for-business/esd-anual-1-usuario', name: 'Microsoft 365 Apps for Business ESD anual 1 usuario', legacyCategory: 'software' },
  { path: 'software/productividad-oficina/microsoft-365/apps-for-business/esd-anual-1-usuario/spp-00005', name: 'Microsoft SPP-00005 Apps for Business ESD', legacyCategory: 'software' },
  { path: 'impresion/escaneres/documentales/portatiles/adf/duplex/canon-imageformula-p-215ii', name: 'Canon imageFORMULA P-215II Scan-tini', legacyCategory: 'printers_scanners' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/vostro-3000', name: 'Dell ProSupport Plus Vostro desktops 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/vostro-3000/1y-basic-nbd-a-3y-prosupport-plus', name: 'Dell Vostro 3000 1Y Basic NBD a 3Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/vostro-3000/1y-basic-nbd-a-3y-prosupport-plus/n-vosdtm2-n1-m3', name: 'Dell N_VOSDTM2_N1_M3 Vostro ProSupport Plus', legacyCategory: 'software' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-techo', name: 'Soportes de techo para camaras CCTV', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-techo/pendant-domo', name: 'Soportes pendant de techo para domos', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-techo/pendant-domo/unv-tr-cm24-in', name: 'UNV TR-CM24-IN soporte pendant interior', legacyCategory: 'security' },
];
