export const MANUAL_CATEGORY_TREE_RECENT = [
  { path: 'video/accesorios-proyeccion/soportes-proyector/techo', name: 'Soportes de techo para proyector', legacyCategory: 'accessories' },
  { path: 'video/accesorios-proyeccion/soportes-proyector/techo/13-5kg', name: 'Soportes de techo para proyector hasta 13.5 kg', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/mouse/inalambricos/ergonomicos/silenciosos-dual-receptor-1000-dpi', name: 'Mouse ergonomicos inalambricos silenciosos USB-A USB-C 1000 DPI', legacyCategory: 'accessories' },
  { path: 'telefonia/pbx-ip/grandstream-ucm6300/audio-2fxo-2fxs', name: 'PBX IP Grandstream UCM6300 Audio 2 FXS 2 FXO', legacyCategory: 'networking' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas', name: 'Pantallas electricas de proyeccion', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/203-pulgadas', name: 'Pantallas electricas de proyeccion 203 pulgadas', legacyCategory: 'monitors' },
  { path: 'impresion/consumibles/tambores/brother', name: 'Tambores Brother para impresoras laser', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/tambores/brother/dr890', name: 'Tambores Brother DR890', legacyCategory: 'printers_scanners' },
  { path: 'computo/monitores/profesionales', name: 'Monitores profesionales', legacyCategory: 'monitors' },
  { path: 'computo/monitores/profesionales/27-qhd-120hz', name: 'Monitores profesionales QHD de 27 pulgadas 120Hz', legacyCategory: 'monitors' },
  { path: 'energia/cargadores-usb/estaciones-carga', name: 'Estaciones de carga USB multipuerto', legacyCategory: 'accessories' },
  { path: 'energia/cargadores-usb/estaciones-carga/usb-9-en-1-140w', name: 'Estaciones de carga USB 9 en 1 de 140W', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/teclados/gaming', name: 'Teclados gaming', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos', name: 'Teclados gaming mecanicos', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/tkl-rgb', name: 'Teclados mecanicos gaming TKL RGB', legacyCategory: 'gaming' },
];
