export const MANUAL_CATEGORY_TREE_CORE = [
  { path: 'computo/laptops', name: 'Laptops', legacyCategory: 'laptops' },
  { path: 'computo/laptops/empresariales', name: 'Laptops empresariales', legacyCategory: 'laptops' },
  { path: 'computo/laptops/empresariales/14-pulgadas', name: 'Laptops empresariales de 14 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/laptops/empresariales/14-pulgadas/dell-pro-14-plus', name: 'Dell Pro 14 Plus empresariales', legacyCategory: 'laptops' },
  { path: 'computo/laptops/empresariales/14-pulgadas/thinkpad-t14', name: 'Lenovo ThinkPad T14 empresariales de 14 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/laptops/empresariales/15-6-pulgadas', name: 'Laptops empresariales de 15.6 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/laptops/consumo', name: 'Laptops de consumo', legacyCategory: 'laptops' },
  { path: 'computo/laptops/consumo/16-pulgadas', name: 'Laptops de consumo de 16 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/laptops/16-pulgadas', name: 'Laptops de 16 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/desktops', name: 'Computadoras de escritorio', legacyCategory: 'laptops' },
  { path: 'computo/desktops/slim', name: 'Computadoras slim de escritorio', legacyCategory: 'laptops' },
  { path: 'computo/desktops/all-in-one', name: 'Computadoras All-in-One', legacyCategory: 'laptops' },
  { path: 'computo/desktops/mini-pc', name: 'Mini PCs y desktops compactas', legacyCategory: 'laptops' },
  { path: 'computo/desktops/mini-pc/barebone', name: 'Mini PCs barebone', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes', name: 'Servidores y componentes', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes/discos-hdd', name: 'Discos duros para servidor', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes/fuentes-poder', name: 'Fuentes de poder para servidor', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes/fuentes-poder/flex-slot', name: 'Fuentes HPE Flex Slot para servidor', legacyCategory: 'laptops' },
  { path: 'computo/servidores/torre', name: 'Servidores torre', legacyCategory: 'laptops' },
  { path: 'computo/servidores/rack', name: 'Servidores rack', legacyCategory: 'laptops' },
  { path: 'computo/servidores/almacenamiento-cintas', name: 'Almacenamiento LTO y cintas', legacyCategory: 'laptops' },
  { path: 'computo/monitores', name: 'Monitores', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina', name: 'Monitores de oficina', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/18-5-hd', name: 'Monitores HD de 18.5 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/19-wxga', name: 'Monitores WXGA de 19 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/22-fhd-75hz', name: 'Monitores FHD de 22 pulgadas 75Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/24-25-fhd', name: 'Monitores FHD de 24 a 25 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/24-fhd-100hz', name: 'Monitores FHD de 24 pulgadas 100Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/24-fhd-120hz', name: 'Monitores FHD de 24 pulgadas 120Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/portatiles', name: 'Monitores portatiles', legacyCategory: 'monitors' },
  { path: 'computo/monitores/portatiles/15-6-fhd', name: 'Monitores portatiles 15.6 pulgadas FHD', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming', name: 'Monitores gaming', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/27-fhd', name: 'Monitores gaming FHD de 27 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/24-fhd', name: 'Monitores gaming FHD de 24 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/24-fhd/180hz', name: 'Monitores gaming FHD de 24 pulgadas 180Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/ultrawide-curvos', name: 'Monitores gaming ultrawide curvos', legacyCategory: 'monitors' },
  { path: 'computo/componentes/procesadores', name: 'Procesadores', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-ryzen-am4', name: 'Procesadores AMD Ryzen AM4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-ryzen-am5', name: 'Procesadores AMD Ryzen AM5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-ryzen-x3d', name: 'Procesadores AMD Ryzen X3D', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-athlon', name: 'Procesadores AMD Athlon', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/intel-core-i5-lga1700', name: 'Procesadores Intel Core i5 LGA1700', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre', name: 'Tarjetas madre', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/amd-am4', name: 'Tarjetas madre AMD AM4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/amd-am5', name: 'Tarjetas madre AMD AM5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/amd-am5/b850m', name: 'Tarjetas madre AMD AM5 B850M', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1700', name: 'Tarjetas madre Intel LGA1700', legacyCategory: 'components' },
  { path: 'computo/componentes/memoria-ram', name: 'Memoria RAM', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/udimm-ddr4', name: 'Memoria RAM UDIMM DDR4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/udimm-ddr4/16gb-2666', name: 'Memoria RAM UDIMM DDR4 16GB 2666MHz', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/udimm-ddr5', name: 'Memoria RAM UDIMM DDR5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/udimm-ddr5/rgb-expo', name: 'Memoria RAM DDR5 RGB EXPO', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr4', name: 'Memoria RAM SO-DIMM DDR4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr4/8gb-3200', name: 'Memoria RAM SO-DIMM DDR4 8GB 3200MHz', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr4/16gb-3200', name: 'Memoria RAM SO-DIMM DDR4 16GB 3200MHz', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr4/32gb-3200', name: 'Memoria RAM SO-DIMM DDR4 32GB 3200MHz', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr5', name: 'Memoria RAM SO-DIMM DDR5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder', name: 'Fuentes de poder', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-bronze', name: 'Fuentes ATX 80 Plus Bronze', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-bronze/550w', name: 'Fuentes ATX 80 Plus Bronze 550W', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-gold', name: 'Fuentes ATX 80 Plus Gold', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-gold/750w', name: 'Fuentes ATX 80 Plus Gold 750W', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-gold/850w', name: 'Fuentes ATX 80 Plus Gold 850W', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-white', name: 'Fuentes ATX 80 Plus White', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-white/650w', name: 'Fuentes ATX 80 Plus White 650W', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder/atx-500w', name: 'Fuentes ATX 500W', legacyCategory: 'components' },
  { path: 'computo/componentes/fuentes-poder/atx-600w', name: 'Fuentes ATX 600W', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-video', name: 'Tarjetas de video', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/amd-radeon', name: 'Tarjetas de video AMD Radeon', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/amd-radeon/rx-9000', name: 'Tarjetas AMD Radeon RX 9000', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/amd-radeon/rx-9000/rx-9060-xt', name: 'Tarjetas AMD Radeon RX 9060 XT', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce', name: 'Tarjetas de video NVIDIA GeForce', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/gt-700', name: 'Tarjetas NVIDIA GeForce GT 700', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-50', name: 'Tarjetas NVIDIA GeForce RTX 50', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-50/rtx-5050', name: 'Tarjetas NVIDIA GeForce RTX 5050', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-50/rtx-5060-ti', name: 'Tarjetas NVIDIA GeForce RTX 5060 Ti', legacyCategory: 'gaming' },
  { path: 'computo/componentes/gabinetes', name: 'Gabinetes para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/gaming', name: 'Gabinetes gamer para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/gaming/full-atx', name: 'Gabinetes gamer Full ATX', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/gaming/atx-alto-flujo', name: 'Gabinetes gamer ATX de alto flujo', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/mini-tower', name: 'Gabinetes mini tower', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/atx-mid-tower', name: 'Gabinetes ATX mid tower', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/full-tower', name: 'Gabinetes full tower', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/full-tower/e-atx', name: 'Gabinetes full tower E-ATX', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/open-frame', name: 'Gabinetes open frame y showcase', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento', name: 'Enfriamiento para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/liquido-cpu', name: 'Enfriamiento liquido para CPU', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/liquido-cpu/240mm', name: 'Enfriamiento liquido CPU 240 mm', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/liquido-cpu/240mm/pantalla-lcd', name: 'Enfriamiento liquido CPU 240 mm con pantalla LCD', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete', name: 'Ventiladores para gabinete', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete/140mm-pwm', name: 'Ventiladores PWM de 140 mm para gabinete', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento-gabinetes', name: 'Enfriamiento y gabinetes', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos', name: 'Cables internos para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos/alimentacion-pcie', name: 'Adaptadores de alimentacion PCIe', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos/alimentacion-sata', name: 'Cables internos de alimentacion SATA', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos/alimentacion-molex', name: 'Cables internos de alimentacion Molex', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos/datos-sata', name: 'Cables internos de datos SATA', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd', name: 'SSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/m2-nvme', name: 'SSD M.2 NVMe', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/m2-nvme/1tb-gen3', name: 'SSD M.2 NVMe Gen3 de 1TB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/m2-nvme/1tb-gen4', name: 'SSD M.2 NVMe Gen4 de 1TB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/2-5-sata', name: 'SSD 2.5 SATA', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/2-5-sata/480gb', name: 'SSD 2.5 SATA de 480GB', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/ssd/2-5-sata/1tb', name: 'SSD 2.5 SATA de 1TB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/2-5-sata/2tb', name: 'SSD 2.5 SATA de 2TB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/discos-duros', name: 'Discos duros', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/discos-duros/2-5-sata', name: 'Discos duros 2.5 SATA', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/gabinetes-externos', name: 'Gabinetes externos para almacenamiento', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/gabinetes-externos/2-5-usb-3-1', name: 'Gabinetes externos 2.5 USB 3.1', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/nas', name: 'NAS y almacenamiento en red', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/nas/2-bahias', name: 'NAS de 2 bahias', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/nas/4-bahias', name: 'NAS de 4 bahias', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/nas/8-bahias', name: 'NAS de 8 bahias', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/lectores-memoria', name: 'Lectores de tarjetas de memoria', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/lectores-memoria/usb-2-microsd', name: 'Lectores microSD USB 2.0', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/unidades-opticas', name: 'Unidades opticas externas e internas', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/unidades-opticas/dvd-externas', name: 'Unidades DVD externas USB', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash', name: 'Memorias flash y microSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/microsd', name: 'Tarjetas microSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/microsd/64gb-clase-10', name: 'Tarjetas microSD 64GB Clase 10', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/microsd/256gb-v30-a2', name: 'Tarjetas microSD 256GB V30 A2', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/microsd/512gb-nintendo-switch', name: 'Tarjetas microSD 512GB para Nintendo Switch', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/sd', name: 'Tarjetas SD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/sd/64gb-v30', name: 'Tarjetas SD 64GB V30', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb', name: 'Memorias USB flash', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/8gb', name: 'Memorias USB de 8GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/8gb/metalicas', name: 'Memorias USB metalicas de 8GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/16gb', name: 'Memorias USB de 16GB', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb/16gb/metalicas', name: 'Memorias USB metalicas de 16GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/16gb/retractiles', name: 'Memorias USB retractiles de 16GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/32gb', name: 'Memorias USB de 32GB', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb/32gb/metalicas', name: 'Memorias USB metalicas de 32GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/64gb', name: 'Memorias USB de 64GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/64gb/metalicas', name: 'Memorias USB metalicas de 64GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/64gb/retractiles', name: 'Memorias USB retractiles de 64GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb/128gb', name: 'Memorias USB de 128GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb-c', name: 'Memorias USB-C flash', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb-c/64gb', name: 'Memorias USB-C de 64GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb-dual', name: 'Memorias USB duales', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb-dual/128gb', name: 'Memorias USB duales de 128GB', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos', name: 'Medios opticos CD/DVD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos/accesorios', name: 'Accesorios para medios opticos', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/accesorios-montaje', name: 'Accesorios de montaje para almacenamiento', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/adaptadores-usb', name: 'Adaptadores USB para discos SATA IDE', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados', name: 'Teclados', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/alambricos', name: 'Teclados alambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/alambricos/usb', name: 'Teclados USB alambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/alambricos/usb/basicos', name: 'Teclados USB basicos', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/teclados/alambricos/usb/ingles', name: 'Teclados USB alambricos en ingles', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/alambricos/usb/resistentes-salpicaduras', name: 'Teclados USB resistentes a salpicaduras', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/teclados/inalambricos', name: 'Teclados inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/compactos', name: 'Teclados inalambricos compactos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/multidispositivo', name: 'Teclados inalambricos multidispositivo', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/multidispositivo/rf-bluetooth', name: 'Teclados multidispositivo RF y Bluetooth', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/touchpad-tv', name: 'Teclados inalambricos con touchpad para TV', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/productividad', name: 'Teclados inalambricos de productividad', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/gaming', name: 'Teclados gaming inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos/mecanicos-gaming', name: 'Teclados mecanicos gaming inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/mecanicos-compactos', name: 'Teclados mecanicos compactos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/numericos', name: 'Teclados numericos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/keycaps', name: 'Keycaps y accesorios de teclado', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/descansa-munecas', name: 'Descansa munecas para teclado', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse', name: 'Mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos', name: 'Mouse inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/basicos', name: 'Mouse inalambricos basicos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/basicos/1000-dpi', name: 'Mouse inalambricos basicos 1000 DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/basicos/1200-dpi', name: 'Mouse inalambricos basicos 1200 DPI', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/mouse/inalambricos/basicos/1600-dpi', name: 'Mouse inalambricos basicos hasta 1600 DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/mini', name: 'Mini mouse inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/multi-dispositivo', name: 'Mouse inalambricos multidispositivo', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/ergonomicos', name: 'Mouse inalambricos ergonomicos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/trackball', name: 'Mouse trackball inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/gaming', name: 'Mouse gaming inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/gaming/2-4ghz', name: 'Mouse gaming inalambricos 2.4GHz', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/alto-dpi', name: 'Mouse inalambricos de alto DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos', name: 'Mouse alambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos/basicos', name: 'Mouse alambricos basicos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos/basicos/1000-dpi', name: 'Mouse alambricos basicos 1000 DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos/basicos/1600-dpi', name: 'Mouse alambricos basicos hasta 1600 DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos/gaming', name: 'Mouse gaming alambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos/gaming/3200-dpi', name: 'Mouse gaming alambricos hasta 3200 DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos/gaming/alto-dpi', name: 'Mouse gaming alambricos de alto DPI', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse', name: 'Combos de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse/inalambricos', name: 'Combos inalambricos de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse/inalambricos/basicos', name: 'Combos inalambricos basicos de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse/inalambricos/productividad', name: 'Combos inalambricos de teclado y mouse de productividad', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/combos-teclado-mouse/alambricos', name: 'Combos alambricos de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse/alambricos/basicos', name: 'Combos alambricos basicos de teclado y mouse', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/combos-teclado-mouse/gaming', name: 'Combos gaming de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/kits-gamer', name: 'Kits gamer de perifericos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/kits-gamer/4-en-1', name: 'Kits gamer 4 en 1', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/webcams', name: 'Webcams', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/webcams/usb-fhd', name: 'Webcams USB Full HD', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/webcams/usb-2k', name: 'Webcams USB 2K', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/bocinas-audio', name: 'Bocinas y audio PC', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/bocinas-audio/2-0', name: 'Bocinas 2.0 para escritorio', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/bocinas-audio/2-1', name: 'Bocinas 2.1 para escritorio', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/bocinas-audio/2-1/bluetooth', name: 'Bocinas 2.1 Bluetooth para escritorio', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/presentadores', name: 'Presentadores inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza', name: 'Limpieza de computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/limpiadores-pantalla', name: 'Limpiadores para pantalla', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/limpiadores-pantalla/kits', name: 'Kits limpiadores para pantalla', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/limpieza/toallas-limpiadoras', name: 'Toallas limpiadoras para computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/liquidos-antiestaticos', name: 'Liquidos antiestaticos de limpieza', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/lociones-limpiadoras', name: 'Lociones limpiadoras para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/espumas-limpiadoras', name: 'Espumas limpiadoras para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/espumas-limpiadoras/590ml', name: 'Espumas limpiadoras 590 ml', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/kits-limpieza', name: 'Kits de limpieza para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/alcohol-isopropilico', name: 'Alcohol isopropilico para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/aire-comprimido', name: 'Aire comprimido para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/aire-comprimido/440ml', name: 'Aire comprimido 440 ml para electronica', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/limpieza/aire-comprimido/e-duster', name: 'E-Duster y aire comprimido ecologico', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/removedores-polvo', name: 'Removedores de polvo para electronica', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/docks-hubs', name: 'Docks y hubs', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs/usb-c', name: 'Docks USB-C multipuerto', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs/usb-c/hdmi-usb-pd', name: 'Adaptadores USB-C HDMI USB y Power Delivery', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs/usb-c/profesionales', name: 'Docks USB-C profesionales', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb', name: 'Hubs USB', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb/usb-a', name: 'Hubs USB-A', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb/usb-a/4-puertos', name: 'Hubs USB-A de 4 puertos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb/usb-c', name: 'Hubs USB-C', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb/usb-c/4-puertos', name: 'Hubs USB-C de 4 puertos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb/usb-c/7-en-1', name: 'Hubs USB-C 7 en 1', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas', name: 'Mochilas y fundas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop', name: 'Maletines para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-tablet', name: 'Maletines para tablet', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-tablet/10-8-pulgadas', name: 'Maletines para tablet 10.8 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/fundas-laptop', name: 'Fundas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/fundas-laptop/15-6-pulgadas', name: 'Fundas para laptop 15.6 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/fundas-laptop/17-pulgadas', name: 'Fundas para laptop 17 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop', name: 'Mochilas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop/15-6', name: 'Mochilas para laptop 15.6 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas', name: 'Mochilas para laptop 16 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-gaming', name: 'Mochilas gaming para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/stylus-tablets', name: 'Stylus para tablets', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/seguridad-biometrica', name: 'Seguridad biometrica para computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/cargadores-laptop', name: 'Cargadores para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/cargadores-laptop/hp-pin-central', name: 'Cargadores HP pin central', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/cargadores-laptop/asus-aguja-40w', name: 'Cargadores Asus aguja 40W', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/baterias-laptop', name: 'Baterias para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/baterias-laptop/acer', name: 'Baterias para laptop Acer', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/baterias-laptop/dell', name: 'Baterias para laptop Dell', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/baterias-laptop/hp', name: 'Baterias para laptop HP', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/bases-enfriadoras', name: 'Bases enfriadoras para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/bases-enfriadoras/15-pulgadas', name: 'Bases enfriadoras para laptop hasta 15 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-audio', name: 'Tarjetas de sonido', legacyCategory: 'headphones' },
  { path: 'computo/componentes/tarjetas-audio/usb', name: 'Tarjetas de sonido USB', legacyCategory: 'headphones' },
  { path: 'computo/componentes/pasta-termica', name: 'Pasta termica y compuestos', legacyCategory: 'laptops' },
  { path: 'computo/tabletas', name: 'Tabletas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/android', name: 'Tabletas Android', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/android/8-pulgadas', name: 'Tabletas Android de 8 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/android/8-pulgadas/enterprise', name: 'Tabletas Android Enterprise de 8 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/android/8-pulgadas/kids', name: 'Tabletas Android kids de 8 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/accesorios', name: 'Accesorios para tabletas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/accesorios/fundas', name: 'Fundas para tabletas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/accesorios/fundas-con-teclado', name: 'Fundas con teclado para tabletas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/accesorios/fundas-con-teclado/ipad-air-11', name: 'Fundas con teclado para iPad Air 11 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/accesorios/fundas-uso-rudo', name: 'Fundas uso rudo para tabletas', legacyCategory: 'laptops' },
  { path: 'computo/tabletas/accesorios/stylus', name: 'Stylus para tabletas', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups', name: 'No-breaks y UPS', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive', name: 'UPS line-interactive de torre', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/500va', name: 'UPS line-interactive 500VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/700va', name: 'UPS line-interactive 700VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/800va-lcd', name: 'UPS line-interactive 800VA con LCD', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/750va', name: 'UPS line-interactive 750VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/1000va', name: 'UPS line-interactive 1000VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/1000va/lcd', name: 'UPS line-interactive 1000VA con LCD', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/1200va', name: 'UPS line-interactive 1200VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/1200va/lcd', name: 'UPS line-interactive 1200VA con LCD', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/2200va-lcd', name: 'UPS line-interactive 2200VA con LCD', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/3000va', name: 'UPS line-interactive 3000VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/senoidal-pura', name: 'UPS line-interactive de onda senoidal pura', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/rack', name: 'UPS para rack', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/rack-torre', name: 'UPS rack torre', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion', name: 'UPS doble conversion online', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion/2000va', name: 'UPS doble conversion online 2000VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion/rack-torre', name: 'UPS online rack torre', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion/rack-torre/1000va', name: 'UPS online rack torre 1000VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion/rack-torre/3000va', name: 'UPS online rack torre 3000VA', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion/rack-torre/5000va', name: 'UPS online rack torre 5000VA', legacyCategory: 'laptops' },
  { path: 'energia/pdu-rack', name: 'PDU y distribucion de energia para rack', legacyCategory: 'laptops' },
  { path: 'energia/pdu-rack/multicontactos-8', name: 'PDU multicontactos de 8 salidas', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups', name: 'Accesorios para UPS', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/bancos-baterias-rack-torre', name: 'Bancos externos de baterias UPS rack torre', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/bancos-baterias-rack-torre/96v-srt', name: 'Bancos de baterias APC SRT 96V', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/sensores-ambientales', name: 'Sensores ambientales para UPS y racks', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/tarjetas-snmp', name: 'Tarjetas SNMP para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/cartuchos-reemplazo', name: 'Cartuchos de reemplazo para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/selladas-12v', name: 'Baterias selladas 12V para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/selladas-12v/7ah', name: 'Baterias selladas 12V 7Ah para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/selladas-12v/9ah', name: 'Baterias selladas 12V 9Ah para UPS', legacyCategory: 'laptops' },
  { path: 'energia/pilas-baterias/boton-cmos', name: 'Pilas de boton y CMOS', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb', name: 'Cargadores USB y USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/auto-micro-usb', name: 'Cargadores USB de auto con cable Micro USB', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/kits-carga-lightning', name: 'Kits de carga USB con cable Lightning', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/pared-dual-usb-a-usb-c', name: 'Cargadores de pared dual USB-A y USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/pared-usb-c', name: 'Cargadores de pared USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-inalambricos', name: 'Cargadores inalambricos Qi', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-inalambricos/magneticos-magsafe', name: 'Cargadores inalambricos magneticos MagSafe', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups', name: 'Baterias para UPS', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/supresores-picos', name: 'Supresores de picos', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/supresores-picos/multicontactos', name: 'Multicontactos con supresor de picos', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/supresores-picos/multicontactos-pared-tv', name: 'Supresores de picos de pared para TV', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores', name: 'Supresores y reguladores', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje', name: 'Reguladores de voltaje', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/avr', name: 'Reguladores de voltaje AVR', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/avr/1200va', name: 'Reguladores AVR 1200VA', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/avr/1410va', name: 'Reguladores AVR 1410VA', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/avr/2000va', name: 'Reguladores AVR 2000VA', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/avr/linea-blanca', name: 'Reguladores AVR para linea blanca', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/equipo-motor', name: 'Reguladores para linea blanca y motores', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/equipo-motor/1900va', name: 'Reguladores para motores 1900VA', legacyCategory: 'laptops' },
  { path: 'energia/inversores-solares', name: 'Inversores y cargadores solares', legacyCategory: 'laptops' },
  { path: 'domotica/sensores', name: 'Sensores inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/movimiento', name: 'Sensores de movimiento inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/fugas-agua', name: 'Sensores de fuga de agua', legacyCategory: 'laptops' },
  { path: 'domotica/interruptores-inteligentes', name: 'Interruptores inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/interruptores-inteligentes/wifi', name: 'Interruptores inteligentes Wi-Fi', legacyCategory: 'laptops' },
  { path: 'domotica/enchufes-inteligentes', name: 'Enchufes inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/iluminacion-inteligente', name: 'Iluminacion inteligente', legacyCategory: 'networking' },
  { path: 'domotica/iluminacion-inteligente/focos-wifi', name: 'Focos Wi-Fi inteligentes', legacyCategory: 'networking' },
  { path: 'domotica/iluminacion-inteligente/focos-wifi/rgb', name: 'Focos Wi-Fi RGB inteligentes', legacyCategory: 'networking' },
  { path: 'domotica/iluminacion-inteligente/focos-wifi/rgb/e26-4-pack', name: 'Focos Wi-Fi RGB E26 en paquete', legacyCategory: 'networking' },
  { path: 'hogar/electrodomesticos', name: 'Electrodomesticos', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/microondas', name: 'Hornos de microondas', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/lavadoras', name: 'Lavadoras', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aspiradoras-robot', name: 'Aspiradoras robot', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/exprimidores', name: 'Exprimidores y extractores de jugo', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aires-acondicionados', name: 'Aires acondicionados y minisplits', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aires-acondicionados/minisplit', name: 'Minisplits', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aires-acondicionados/minisplit/1-tonelada', name: 'Minisplits de 1 tonelada', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/purificadores-aire', name: 'Purificadores de aire', legacyCategory: 'laptops' },
  { path: 'mantenimiento', name: 'Mantenimiento y consumibles tecnicos', legacyCategory: 'laptops' },
  { path: 'mantenimiento/quimicos', name: 'Quimicos de mantenimiento', legacyCategory: 'laptops' },
  { path: 'mantenimiento/quimicos/aflojatodo-anticorrosivo', name: 'Aflojatodo y anticorrosivos', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-enfriamiento', name: 'Racks y enfriamiento', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-enfriamiento/gabinetes-pared', name: 'Gabinetes de pared para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-enfriamiento/gabinetes-pared/12u', name: 'Gabinetes de pared 12U', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios', name: 'Accesorios para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/herrajes', name: 'Herrajes y tornilleria para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/herrajes/m6', name: 'Herrajes M6 para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/herrajes/m6/50-piezas', name: 'Kits M6 de 50 piezas para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/soportes-pared', name: 'Soportes de pared para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas', name: 'Charolas y bandejas para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas-monitor', name: 'Charolas para monitor en rack', legacyCategory: 'monitors' },
  { path: 'infraestructura/racks-accesorios/charolas-teclado', name: 'Charolas para teclado en rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas-servidor', name: 'Charolas para servidor en rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/organizadores-cable', name: 'Organizadores de cable para rack', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/organizadores-cable/horizontales-1u', name: 'Organizadores horizontales 1U para rack', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-enfriamiento/racks-piso', name: 'Racks de piso', legacyCategory: 'laptops' },
  { path: 'infraestructura/cajas-registro', name: 'Cajas de registro y montaje', legacyCategory: 'laptops' },
  { path: 'redes/access-points', name: 'Access points', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-5', name: 'Access points Wi-Fi 5', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-5/exterior', name: 'Access points Wi-Fi 5 de exterior', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-6', name: 'Access points Wi-Fi 6', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-7', name: 'Access points Wi-Fi 7', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi', name: 'Adaptadores Wi-Fi', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb', name: 'Adaptadores Wi-Fi USB', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb/n150-nano', name: 'Adaptadores Wi-Fi USB nano N150', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb/n300-mini', name: 'Adaptadores Wi-Fi USB mini N300', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb/ac600-nano', name: 'Adaptadores Wi-Fi USB nano AC600', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb/wifi-6-nano', name: 'Adaptadores Wi-Fi 6 USB nano', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb/alta-potencia', name: 'Adaptadores Wi-Fi USB de alta potencia', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-bluetooth', name: 'Adaptadores Bluetooth', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-bluetooth/usb', name: 'Adaptadores Bluetooth USB', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi', name: 'Extensores de rango Wi-Fi', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi/n300', name: 'Extensores Wi-Fi N300', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi/dual-band', name: 'Extensores Wi-Fi dual band', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi/dual-band/ac750', name: 'Extensores Wi-Fi dual band AC750', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi/tri-band', name: 'Extensores Wi-Fi tri-band', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi/tri-band/wifi-6e-axe5400', name: 'Extensores Wi-Fi 6E AXE5400', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-ethernet', name: 'Adaptadores Ethernet', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-ethernet/usb-fast-ethernet', name: 'Adaptadores USB a Fast Ethernet', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-ethernet/usb-gigabit', name: 'Adaptadores USB a Ethernet Gigabit', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas', name: 'Radioenlaces y antenas', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/antenas-parabolicas', name: 'Antenas parabolicas para radioenlace', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/antenas-parabolicas/5ghz-30dbi', name: 'Antenas parabolicas 5GHz 30dBi', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/radios-base', name: 'Radios base para enlaces inalambricos', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/radios-base/airmax-ac', name: 'Radios base airMAX AC', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/puentes-wifi-exterior', name: 'Puentes Wi-Fi de exterior', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores', name: 'Transceptores y convertidores', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado', name: 'Cableado estructurado', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/cajas-pared', name: 'Cajas de pared para red', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp', name: 'Bobinas de cable UTP', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp/cat5e', name: 'Bobinas UTP Cat5e', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp/cat6', name: 'Bobinas UTP Cat6', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords', name: 'Patch cords de red', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat5e', name: 'Patch cords Cat5e', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat5e/0-5m', name: 'Patch cords Cat5e de 0.5 m', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat5e/4-2m', name: 'Patch cords Cat5e de 4.2 m', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat6', name: 'Patch cords Cat6', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat6/3m', name: 'Patch cords Cat6 de 3 m', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/divisores-adaptadores', name: 'Divisores y adaptadores RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/acopladores-rj45', name: 'Acopladores y coples RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-rj45', name: 'Conectores RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-rj45/cat5e', name: 'Plugs RJ45 Cat5e', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-rj45/cat6', name: 'Plugs RJ45 Cat6', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-keystone', name: 'Conectores keystone RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-keystone/rj11-rj12', name: 'Jacks keystone RJ11/RJ12', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-keystone/rj45-cat5e', name: 'Conectores keystone RJ45 Cat5e', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-keystone/rj45-cat6', name: 'Conectores keystone RJ45 Cat6', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-keystone/rj45-cat6-industrial', name: 'Conectores keystone RJ45 Cat6 industriales', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/placas-keystone', name: 'Placas keystone y faceplates', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/placas-keystone/1-puerto', name: 'Placas keystone de 1 puerto', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/placas-keystone/2-puertos', name: 'Placas keystone de 2 puertos', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado', name: 'Herramientas para cableado', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/probadores-cable', name: 'Probadores de cable de red', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/crimpadoras', name: 'Crimpadoras para conectores modulares', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/ponchadoras-impacto', name: 'Ponchadoras de impacto para jacks', legacyCategory: 'networking' },
  { path: 'redes/controladores-cloud', name: 'Controladores cloud de red', legacyCategory: 'networking' },
  { path: 'redes/fibra-optica/olt-gpon', name: 'OLT GPON de fibra optica', legacyCategory: 'networking' },
  { path: 'redes/tarjetas-red/pcie', name: 'Tarjetas de red PCI Express', legacyCategory: 'networking' },
  { path: 'redes/poe', name: 'PoE e inyectores de red', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/convertidores-medios', name: 'Convertidores de medios', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/convertidores-medios/fibra-rj45', name: 'Convertidores fibra a RJ45', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/convertidores-medios/fibra-rj45/gigabit-sfp', name: 'Convertidores fibra RJ45 Gigabit con SFP', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/convertidores-medios/fibra-rj45/fast-ethernet-wdm-monomodo-sc', name: 'Convertidores WDM monomodo SC Fast Ethernet', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/convertidores-medios/fibra-rj45/gigabit-multimodo-sc', name: 'Convertidores Gigabit multimodo SC', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/convertidores-medios/fibra-rj45/gigabit-monomodo-sc', name: 'Convertidores Gigabit monomodo SC', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/modulos-sfp', name: 'Modulos SFP y miniGBIC', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/modulos-sfp/sfp-1g', name: 'Modulos SFP 1G', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/modulos-sfp/sfp-1g/multimodo-1000base-sx', name: 'Modulos SFP 1G multimodo 1000Base-SX', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/modulos-sfp/sfp-1g/monomodo-1000base-lx', name: 'Modulos SFP 1G monomodo 1000Base-LX', legacyCategory: 'networking' },
];
