export const MANUAL_CATEGORY_TREE = [
  { path: 'computo/laptops', name: 'Laptops', legacyCategory: 'laptops' },
  { path: 'computo/laptops/empresariales', name: 'Laptops empresariales', legacyCategory: 'laptops' },
  { path: 'computo/desktops', name: 'Computadoras de escritorio', legacyCategory: 'laptops' },
  { path: 'computo/desktops/all-in-one', name: 'Computadoras All-in-One', legacyCategory: 'laptops' },
  { path: 'computo/desktops/mini-pc', name: 'Mini PCs y desktops compactas', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes', name: 'Servidores y componentes', legacyCategory: 'laptops' },
  { path: 'computo/servidores/torre', name: 'Servidores torre', legacyCategory: 'laptops' },
  { path: 'computo/servidores/rack', name: 'Servidores rack', legacyCategory: 'laptops' },
  { path: 'computo/servidores/almacenamiento-cintas', name: 'Almacenamiento LTO y cintas', legacyCategory: 'laptops' },
  { path: 'computo/monitores', name: 'Monitores', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina', name: 'Monitores de oficina', legacyCategory: 'monitors' },
  { path: 'computo/monitores/oficina/24-25-fhd', name: 'Monitores FHD de 24 a 25 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming', name: 'Monitores gaming', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/24-fhd', name: 'Monitores gaming FHD de 24 pulgadas', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/ultrawide-curvos', name: 'Monitores gaming ultrawide curvos', legacyCategory: 'monitors' },
  { path: 'computo/componentes/procesadores', name: 'Procesadores', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-ryzen-am4', name: 'Procesadores AMD Ryzen AM4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-ryzen-am5', name: 'Procesadores AMD Ryzen AM5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-ryzen-x3d', name: 'Procesadores AMD Ryzen X3D', legacyCategory: 'laptops' },
  { path: 'computo/componentes/procesadores/amd-athlon', name: 'Procesadores AMD Athlon', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre', name: 'Tarjetas madre', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/amd-am4', name: 'Tarjetas madre AMD AM4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/amd-am5', name: 'Tarjetas madre AMD AM5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1700', name: 'Tarjetas madre Intel LGA1700', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram', name: 'Memoria RAM', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr4', name: 'Memoria RAM SO-DIMM DDR4', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram/sodimm-ddr5', name: 'Memoria RAM SO-DIMM DDR5', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder', name: 'Fuentes de poder', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-video', name: 'Tarjetas de video', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce', name: 'Tarjetas de video NVIDIA GeForce', legacyCategory: 'gaming' },
  { path: 'computo/componentes/gabinetes', name: 'Gabinetes para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/gaming', name: 'Gabinetes gamer para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/gabinetes/mini-tower', name: 'Gabinetes mini tower', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento', name: 'Enfriamiento para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/liquido-cpu', name: 'Enfriamiento liquido para CPU', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/liquido-cpu/240mm', name: 'Enfriamiento liquido CPU 240 mm', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete', name: 'Ventiladores para gabinete', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento-gabinetes', name: 'Enfriamiento y gabinetes', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos', name: 'Cables internos para PC', legacyCategory: 'laptops' },
  { path: 'computo/componentes/cables-internos/alimentacion-pcie', name: 'Adaptadores de alimentacion PCIe', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd', name: 'SSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd/m2-nvme', name: 'SSD M.2 NVMe', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/discos-duros', name: 'Discos duros', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/discos-duros/2-5-sata', name: 'Discos duros 2.5 SATA', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash', name: 'Memorias flash y microSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash/usb', name: 'Memorias USB flash', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos', name: 'Medios opticos CD/DVD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos/accesorios', name: 'Accesorios para medios opticos', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/accesorios-montaje', name: 'Accesorios de montaje para almacenamiento', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/adaptadores-usb', name: 'Adaptadores USB para discos SATA IDE', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados', name: 'Teclados', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/alambricos', name: 'Teclados alambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/inalambricos', name: 'Teclados inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/mecanicos-compactos', name: 'Teclados mecanicos compactos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/numericos', name: 'Teclados numericos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/keycaps', name: 'Keycaps y accesorios de teclado', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/descansa-munecas', name: 'Descansa munecas para teclado', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse', name: 'Mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos', name: 'Mouse inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/multi-dispositivo', name: 'Mouse inalambricos multidispositivo', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/ergonomicos', name: 'Mouse inalambricos ergonomicos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/trackball', name: 'Mouse trackball inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/gaming', name: 'Mouse gaming inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/alambricos', name: 'Mouse alambricos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse', name: 'Combos de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/combos-teclado-mouse/gaming', name: 'Combos gaming de teclado y mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/kits-gamer', name: 'Kits gamer de perifericos', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/kits-gamer/4-en-1', name: 'Kits gamer 4 en 1', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/webcams', name: 'Webcams', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/webcams/usb-fhd', name: 'Webcams USB Full HD', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/bocinas-audio', name: 'Bocinas y audio PC', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/bocinas-audio/2-0', name: 'Bocinas 2.0 para escritorio', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/presentadores', name: 'Presentadores inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza', name: 'Limpieza de computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/limpiadores-pantalla', name: 'Limpiadores para pantalla', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/toallas-limpiadoras', name: 'Toallas limpiadoras para computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/liquidos-antiestaticos', name: 'Liquidos antiestaticos de limpieza', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/espumas-limpiadoras', name: 'Espumas limpiadoras para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/kits-limpieza', name: 'Kits de limpieza para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/alcohol-isopropilico', name: 'Alcohol isopropilico para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs', name: 'Docks y hubs', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs/usb-c', name: 'Docks USB-C multipuerto', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb', name: 'Hubs USB', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb/usb-c', name: 'Hubs USB-C', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas', name: 'Mochilas y fundas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop', name: 'Maletines para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop', name: 'Mochilas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-gaming', name: 'Mochilas gaming para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/stylus-tablets', name: 'Stylus para tablets', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/seguridad-biometrica', name: 'Seguridad biometrica para computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/cargadores-laptop', name: 'Cargadores para laptop', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-audio', name: 'Tarjetas de sonido', legacyCategory: 'headphones' },
  { path: 'computo/componentes/tarjetas-audio/usb', name: 'Tarjetas de sonido USB', legacyCategory: 'headphones' },
  { path: 'computo/componentes/pasta-termica', name: 'Pasta termica y compuestos', legacyCategory: 'laptops' },
  { path: 'computo/tabletas', name: 'Tabletas', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups', name: 'No-breaks y UPS', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive', name: 'UPS line-interactive de torre', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/senoidal-pura', name: 'UPS line-interactive de onda senoidal pura', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/rack', name: 'UPS para rack', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/rack-torre', name: 'UPS rack torre', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion', name: 'UPS doble conversion online', legacyCategory: 'laptops' },
  { path: 'energia/pdu-rack', name: 'PDU y distribucion de energia para rack', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups', name: 'Accesorios para UPS', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/sensores-ambientales', name: 'Sensores ambientales para UPS y racks', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/tarjetas-snmp', name: 'Tarjetas SNMP para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/cartuchos-reemplazo', name: 'Cartuchos de reemplazo para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/selladas-12v', name: 'Baterias selladas 12V para UPS', legacyCategory: 'laptops' },
  { path: 'energia/pilas-baterias/boton-cmos', name: 'Pilas de boton y CMOS', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb', name: 'Cargadores USB y USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/kits-carga-lightning', name: 'Kits de carga USB con cable Lightning', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/pared-dual-usb-a-usb-c', name: 'Cargadores de pared dual USB-A y USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb/pared-usb-c', name: 'Cargadores de pared USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-inalambricos', name: 'Cargadores inalambricos Qi', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-inalambricos/magneticos-magsafe', name: 'Cargadores inalambricos magneticos MagSafe', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups', name: 'Baterias para UPS', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/supresores-picos', name: 'Supresores de picos', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores', name: 'Supresores y reguladores', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje', name: 'Reguladores de voltaje', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/avr', name: 'Reguladores de voltaje AVR', legacyCategory: 'laptops' },
  { path: 'energia/inversores-solares', name: 'Inversores y cargadores solares', legacyCategory: 'laptops' },
  { path: 'domotica/sensores', name: 'Sensores inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/movimiento', name: 'Sensores de movimiento inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/fugas-agua', name: 'Sensores de fuga de agua', legacyCategory: 'laptops' },
  { path: 'domotica/enchufes-inteligentes', name: 'Enchufes inteligentes', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos', name: 'Electrodomesticos', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/microondas', name: 'Hornos de microondas', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/lavadoras', name: 'Lavadoras', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aspiradoras-robot', name: 'Aspiradoras robot', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/exprimidores', name: 'Exprimidores y extractores de jugo', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aires-acondicionados', name: 'Aires acondicionados y minisplits', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/purificadores-aire', name: 'Purificadores de aire', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-enfriamiento', name: 'Racks y enfriamiento', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios', name: 'Accesorios para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/herrajes', name: 'Herrajes y tornilleria para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/soportes-pared', name: 'Soportes de pared para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas', name: 'Charolas y bandejas para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas-monitor', name: 'Charolas para monitor en rack', legacyCategory: 'monitors' },
  { path: 'infraestructura/racks-accesorios/charolas-teclado', name: 'Charolas para teclado en rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas-servidor', name: 'Charolas para servidor en rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/organizadores-cable', name: 'Organizadores de cable para rack', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-enfriamiento/racks-piso', name: 'Racks de piso', legacyCategory: 'laptops' },
  { path: 'infraestructura/cajas-registro', name: 'Cajas de registro y montaje', legacyCategory: 'laptops' },
  { path: 'redes/access-points', name: 'Access points', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-5', name: 'Access points Wi-Fi 5', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-6', name: 'Access points Wi-Fi 6', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-7', name: 'Access points Wi-Fi 7', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi', name: 'Adaptadores Wi-Fi', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-wifi/usb', name: 'Adaptadores Wi-Fi USB', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-ethernet', name: 'Adaptadores Ethernet', legacyCategory: 'networking' },
  { path: 'redes/adaptadores-ethernet/usb-gigabit', name: 'Adaptadores USB a Ethernet Gigabit', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas', name: 'Radioenlaces y antenas', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores', name: 'Transceptores y convertidores', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado', name: 'Cableado estructurado', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/cajas-pared', name: 'Cajas de pared para red', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp', name: 'Bobinas de cable UTP', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp/cat5e', name: 'Bobinas UTP Cat5e', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp/cat6', name: 'Bobinas UTP Cat6', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords', name: 'Patch cords de red', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat5e', name: 'Patch cords Cat5e', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/divisores-adaptadores', name: 'Divisores y adaptadores RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/acopladores-rj45', name: 'Acopladores y coples RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/conectores-rj45', name: 'Conectores RJ45', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado', name: 'Herramientas para cableado', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/crimpadoras', name: 'Crimpadoras para conectores modulares', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/ponchadoras-impacto', name: 'Ponchadoras de impacto para jacks', legacyCategory: 'networking' },
  { path: 'redes/controladores-cloud', name: 'Controladores cloud de red', legacyCategory: 'networking' },
  { path: 'redes/fibra-optica/olt-gpon', name: 'OLT GPON de fibra optica', legacyCategory: 'networking' },
  { path: 'redes/tarjetas-red/pcie', name: 'Tarjetas de red PCI Express', legacyCategory: 'networking' },
  { path: 'redes/switches', name: 'Switches', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables', name: 'Switches PoE administrables', legacyCategory: 'networking' },
  { path: 'redes/seguridad', name: 'Seguridad de red', legacyCategory: 'networking' },
  { path: 'redes/seguridad/firewalls', name: 'Firewalls y gateways seguros', legacyCategory: 'networking' },
  { path: 'redes/routers', name: 'Routers', legacyCategory: 'networking' },
  { path: 'redes/routers/vpn', name: 'Routers VPN', legacyCategory: 'networking' },
  { path: 'redes/routers/vpn/omada', name: 'Routers VPN Omada', legacyCategory: 'networking' },
  { path: 'redes/routers/wisp', name: 'Routers WISP', legacyCategory: 'networking' },
  { path: 'redes/routers/wifi-n', name: 'Routers Wi-Fi N', legacyCategory: 'networking' },
  { path: 'redes/routers/mesh-wifi', name: 'Routers mesh Wi-Fi', legacyCategory: 'networking' },
  { path: 'telefonia/pbx-ip', name: 'PBX y conmutadores IP', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos', name: 'Telefonos', legacyCategory: 'laptops' },
  { path: 'telefonia/telefonos/inalambricos', name: 'Telefonos inalambricos', legacyCategory: 'laptops' },
  { path: 'telefonia/telefonos-ip', name: 'Telefonos IP', legacyCategory: 'networking' },
  { path: 'telefonia/accesorios', name: 'Accesorios para telefonia movil', legacyCategory: 'laptops' },
  { path: 'telefonia/accesorios/soportes-celular', name: 'Soportes para celular', legacyCategory: 'laptops' },
  { path: 'telefonia/accesorios/soportes-celular/magneticos', name: 'Soportes magneticos para celular', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras', name: 'Impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/etiquetas', name: 'Impresoras de etiquetas', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/etiquetas/rotuladores-p-touch', name: 'Rotuladores P-touch y etiquetadoras portatiles', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/etiquetas/termicas-moviles', name: 'Impresoras termicas moviles de etiquetas', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/multifuncionales-laser', name: 'Multifuncionales laser', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/multifuncionales-ecotank', name: 'Multifuncionales EcoTank', legacyCategory: 'laptops' },
  { path: 'impresion/escaneres', name: 'Escaneres documentales', legacyCategory: 'cameras' },
  { path: 'impresion/accesorios/bandejas-alimentadores', name: 'Bandejas y alimentadores de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/accesorios/unidades-duplex', name: 'Unidades duplex para impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cabezales', name: 'Cabezales de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tinta-toner', name: 'Tinta, toner y cintas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser', name: 'Toner laser', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother', name: 'Toner laser Brother', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/kyocera', name: 'Toner laser Kyocera', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/xerox', name: 'Toner laser Xerox', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cintas-tarjetas', name: 'Cintas para impresoras de tarjetas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-ecotank', name: 'Botellas de tinta EcoTank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-ecotank/epson-t504', name: 'Botellas Epson T504', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-ecotank/epson-t574', name: 'Botellas Epson T574', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-megatank', name: 'Botellas de tinta MegaTank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-megatank/canon-gi10', name: 'Botellas Canon GI-10 MegaTank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/contenedores-desperdicio', name: 'Contenedores de toner residual', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tambores', name: 'Tambores y unidades de imagen', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tambores/xerox', name: 'Tambores Xerox', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/etiquetas-papel', name: 'Etiquetas y papel', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-fotografico-sublimacion', name: 'Papel fotografico y sublimacion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-plotter', name: 'Papel para plotter', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/mantenimiento', name: 'Mantenimiento de impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/unidades-transferencia', name: 'Unidades de transferencia', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/pulseras-termicas', name: 'Pulseras termicas de identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras', name: 'Lectores de codigo de barras', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/cajones-dinero', name: 'Cajones de dinero POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/impresoras-recibos', name: 'Impresoras termicas de recibos POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/digitalizadores-firma', name: 'Digitalizadores de firma', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/verificadores-precio', name: 'Verificadores de precio POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/terminales-accesorios', name: 'Terminales y accesorios POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/software-pos', name: 'Software punto de venta', legacyCategory: 'software' },
  { path: 'punto-de-venta/credenciales-identificacion', name: 'Credenciales e identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-bond', name: 'Rollos bond POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-autocopia', name: 'Rollos autocopia POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/etiquetas-termicas', name: 'Etiquetas termicas POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-termicos', name: 'Rollos termicos POS', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/biometricos', name: 'Biometricos de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/tarjetas-rfid', name: 'Tarjetas RFID de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/cerraduras-inteligentes', name: 'Cerraduras inteligentes', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/videoporteros-ip', name: 'Videoporteros IP', legacyCategory: 'cameras' },
  { path: 'seguridad/control-acceso/videoporteros-ip/kits', name: 'Kits de videoportero IP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras', name: 'Camaras CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi', name: 'Camaras HDCVI analogicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi/bullet', name: 'Camaras HDCVI bullet', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi', name: 'Camaras IP WiFi', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior', name: 'Camaras IP WiFi de interior', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/bullet-exterior', name: 'Camaras IP WiFi bullet de exterior', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-doble-lente', name: 'Camaras IP WiFi PT doble lente', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe', name: 'Camaras IP PoE', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet', name: 'Camaras IP PoE bullet', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret', name: 'Camaras IP PoE turret', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/full-color', name: 'Camaras IP PoE turret Full Color', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo-varifocal', name: 'Camaras IP PoE domo varifocal', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/panoramicas', name: 'Camaras IP PoE panoramicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/ptz', name: 'Camaras IP PoE PTZ', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd', name: 'Camaras TurboHD analogicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd/bullet', name: 'Camaras TurboHD bullet', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles', name: 'Camaras moviles vehiculares', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles/turbo-hd', name: 'Camaras moviles TurboHD vehiculares', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/kits-vigilancia', name: 'Kits de videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado', name: 'Accesorios y cableado CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-montaje', name: 'Accesorios de montaje CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-montaje/cajas-conexion', name: 'Cajas de conexion CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/cable-coaxial-siames', name: 'Cable coaxial siames CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/fuentes-poder', name: 'Fuentes de poder para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr', name: 'DVR y NVR', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/nvr-ip', name: 'NVR IP para videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/xvr-hdcvi', name: 'XVR y DVR HDCVI', legacyCategory: 'cameras' },
  { path: 'seguridad/epp/proteccion-facial', name: 'Proteccion facial EPP', legacyCategory: 'laptops' },
  { path: 'seguridad/epp/proteccion-ocular', name: 'Proteccion ocular EPP', legacyCategory: 'laptops' },
  { path: 'salud/equipo-medico/monitoreo', name: 'Monitoreo medico domestico', legacyCategory: 'laptops' },
  { path: 'telefonia/smartphones', name: 'Smartphones', legacyCategory: 'smartphones' },
  { path: 'wearables/smartwatches', name: 'Smartwatches y bandas inteligentes', legacyCategory: 'smartphones' },
  { path: 'audio/audifonos', name: 'Audifonos', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/in-ear', name: 'Audifonos in-ear', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/in-ear/usb-c', name: 'Audifonos in-ear USB-C', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/usb', name: 'Audifonos USB con microfono', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth', name: 'Audifonos Bluetooth', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth/tws', name: 'Audifonos Bluetooth TWS', legacyCategory: 'headphones' },
  { path: 'audio/microfonos', name: 'Microfonos', legacyCategory: 'headphones' },
  { path: 'audio/microfonos/soportes-brazos', name: 'Soportes y brazos para microfono', legacyCategory: 'headphones' },
  { path: 'audio/conferencia-speakerphones', name: 'Bocinas de conferencia', legacyCategory: 'headphones' },
  { path: 'audio/adaptadores-bluetooth', name: 'Adaptadores Bluetooth de audio', legacyCategory: 'headphones' },
  { path: 'audio/bocinas', name: 'Bocinas', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/bluetooth', name: 'Bocinas Bluetooth portatiles', legacyCategory: 'headphones' },
  { path: 'audio/barras-sonido', name: 'Barras de sonido', legacyCategory: 'headphones' },
  { path: 'audio/barras-sonido/pc', name: 'Barras de sonido para PC', legacyCategory: 'headphones' },
  { path: 'colaboracion/video-conferencia/controladores', name: 'Controladores de videoconferencia', legacyCategory: 'laptops' },
  { path: 'colaboracion/presentacion-inalambrica', name: 'Presentacion inalambrica', legacyCategory: 'laptops' },
  { path: 'video/televisores', name: 'Televisores', legacyCategory: 'tvs' },
  { path: 'video/televisores/qled-google-tv', name: 'Televisores QLED Google TV', legacyCategory: 'tvs' },
  { path: 'video/proyectores', name: 'Proyectores', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion', name: 'Accesorios de proyeccion', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion/pantallas-tripie', name: 'Pantallas de proyeccion con tripie', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion/soportes-proyector', name: 'Soportes para proyector', legacyCategory: 'tvs' },
  { path: 'video/streaming', name: 'Streaming y reproductores multimedia', legacyCategory: 'tvs' },
  { path: 'video/streaming/reproductores', name: 'Reproductores de streaming', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv', name: 'Soportes para television', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/pared', name: 'Soportes de pared para television', legacyCategory: 'tvs' },
  { path: 'gaming/consolas', name: 'Consolas', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios', name: 'Accesorios gaming', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios/estaciones-carga', name: 'Estaciones de carga y soportes gaming', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario', name: 'Mobiliario gaming', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/escritorios', name: 'Escritorios gaming', legacyCategory: 'gaming' },
  { path: 'oficina/mobiliario-accesorios', name: 'Mobiliario y accesorios de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/mochilas-bolsas', name: 'Mochilas y bolsas de uso diario', legacyCategory: 'laptops' },
  { path: 'oficina/papel-consumibles', name: 'Papel y consumibles de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/pizarrones-interactivos', name: 'Pizarrones interactivos', legacyCategory: 'laptops' },
  { path: 'oficina/limpieza-higiene/dispensadores', name: 'Dispensadores de higiene', legacyCategory: 'laptops' },
  { path: 'oficina/ergonomia/soportes-lumbares', name: 'Soportes lumbares ergonomicos', legacyCategory: 'laptops' },
  { path: 'software/licencias', name: 'Licencias de software', legacyCategory: 'software' },
  { path: 'software/sistemas-operativos', name: 'Sistemas operativos', legacyCategory: 'software' },
  { path: 'software/seguridad', name: 'Software de seguridad', legacyCategory: 'software' },
  { path: 'software/seguridad/antivirus', name: 'Antivirus y proteccion endpoint', legacyCategory: 'software' },
  { path: 'software/cad-diseno', name: 'Software CAD y diseno', legacyCategory: 'software' },
  { path: 'software/productividad-oficina', name: 'Software de productividad y oficina', legacyCategory: 'software' },
  { path: 'software/productividad-oficina/microsoft-365', name: 'Microsoft 365', legacyCategory: 'software' },
  { path: 'servicios/garantias-extendidas', name: 'Garantias extendidas y servicios', legacyCategory: 'software' },
  { path: 'accesorios/seguridad-fisica', name: 'Seguridad fisica para equipos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mousepads', name: 'Mousepads y tapetes para mouse', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/herramientas-esd', name: 'Herramientas antiestaticas ESD', legacyCategory: 'laptops' },
  { path: 'energia/power-banks', name: 'Baterias externas y power banks', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores', name: 'Cables y adaptadores', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/energia', name: 'Cables de energia', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/energia/corriente-cpu', name: 'Cables de corriente CPU', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb', name: 'Cables USB', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-b', name: 'Cables USB A-B', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/micro-usb', name: 'Cables USB a Micro USB', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb-serial', name: 'Adaptadores USB a serial', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-dvi-vga', name: 'Adaptadores DVI VGA', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi-vga', name: 'Adaptadores HDMI a VGA', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi', name: 'Cables HDMI', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/fibra-optica', name: 'Cables HDMI activos de fibra optica', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi-dvi', name: 'Cables HDMI a DVI', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-displayport', name: 'Cables DisplayPort', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-displayport-hdmi', name: 'Cables DisplayPort a HDMI', legacyCategory: 'laptops' },
  { path: 'accesorios/montaje-soportes', name: 'Montaje y soportes', legacyCategory: 'laptops' },
  { path: 'redes/cableado-estructurado/placas-keystone', name: 'Placas keystone y faceplates', legacyCategory: 'networking' },
  { path: 'movilidad/scooters-electricos', name: 'Scooters electricos', legacyCategory: 'gaming' },
  { path: 'mascotas/bebederos-fuentes', name: 'Bebederos y fuentes para mascotas', legacyCategory: 'laptops' },
];
