export const MANUAL_CATEGORY_TREE_CYCLE003 = [
  { path: 'computo/componentes/enfriamiento/liquido-cpu/280mm', name: 'Enfriamiento liquido CPU 280 mm', legacyCategory: 'components' },
  { path: 'computo/componentes/enfriamiento/liquido-cpu/280mm/argb', name: 'Enfriamiento liquido CPU 280 mm ARGB', legacyCategory: 'components' },
  { path: 'computo/perifericos/teclados/inalambricos/mecanicos', name: 'Teclados mecanicos inalambricos', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/cartuchos-tinta/brother', name: 'Cartuchos de tinta Brother', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cartuchos-tinta/brother/lc402', name: 'Cartuchos Brother LC402', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cartuchos-tinta/brother/lc402/amarillo-xl', name: 'Cartuchos Brother LC402 amarillo XL', legacyCategory: 'printers_scanners' },
  { path: 'computo/perifericos/mouse/inalambricos/bluetooth', name: 'Mouse Bluetooth inalambricos', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/mouse/inalambricos/bluetooth/silenciosos', name: 'Mouse Bluetooth silenciosos', legacyCategory: 'accessories' },
  { path: 'hogar/casa-inteligente/interruptores-wifi/3-circuitos', name: 'Interruptores Wi-Fi inteligentes de 3 circuitos', legacyCategory: 'accessories' },
  { path: 'climatizacion', name: 'Climatizacion', legacyCategory: 'accessories' },
  { path: 'climatizacion/aires-acondicionados', name: 'Aires acondicionados', legacyCategory: 'accessories' },
  { path: 'climatizacion/aires-acondicionados/minisplit', name: 'Aires acondicionados minisplit', legacyCategory: 'accessories' },
  { path: 'climatizacion/aires-acondicionados/minisplit/inverter', name: 'Minisplit inverter', legacyCategory: 'accessories' },
  { path: 'climatizacion/aires-acondicionados/minisplit/inverter/12000-btu', name: 'Minisplit inverter 12000 BTU', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/limpieza/kits', name: 'Kits de limpieza para computo', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/limpieza/kits/telefonos-audifonos', name: 'Kits de limpieza para telefonos y audifonos', legacyCategory: 'accessories' },
  { path: 'computo/componentes/tarjetas-madre/amd-am4/b550', name: 'Tarjetas madre AMD AM4 B550', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx', name: 'Tarjetas madre AMD AM4 B550 micro ATX', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-madre/amd-am4/b550/micro-atx/wifi', name: 'Tarjetas madre AMD AM4 B550 micro ATX con Wi-Fi', legacyCategory: 'components' },
  { path: 'energia/no-breaks-ups/line-interactive/rack-1u', name: 'UPS line-interactive rack 1U', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/line-interactive/rack-1u/500va', name: 'UPS line-interactive rack 1U 500VA', legacyCategory: 'power' },
];
