export const MANUAL_CATEGORY_TREE_CYCLE003_PART003 = [
  { path: 'computo/accesorios/soportes-monitor/vesa/adaptadores-apple/mr3c2zma', name: 'Apple MR3C2ZM/A adaptador VESA iMac Pro', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/stylus-tablets/apple-pencil/pro', name: 'Apple Pencil Pro', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/apple', name: 'Soporte y garantias Apple', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus', name: 'AppleCare+', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad', name: 'AppleCare+ para iPad', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-air-11-m4', name: 'AppleCare+ iPad Air 11 M4', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-11-a16', name: 'AppleCare+ iPad 11 A16', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-air-11-m3', name: 'AppleCare+ iPad Air 11 M3', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-pro-11-m5', name: 'AppleCare+ iPad Pro 11 M5', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/mac', name: 'AppleCare+ para Mac', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/mac/imac-24-m4', name: 'AppleCare+ iMac 24 M4', legacyCategory: 'software' },
  { path: 'gaming/accesorios/controles-gamepad/bluetooth-usb-c/asus-rog-raikiri-pro', name: 'ASUS ROG Raikiri Pro', legacyCategory: 'gaming' },
  { path: 'computo/accesorios/mousepads/gaming-xl/speed-control/asus-rog-sheath', name: 'ASUS ROG Sheath XL', legacyCategory: 'accessories' },
  { path: 'software/cad-diseno/autodesk-autocad-lt', name: 'Autodesk AutoCAD LT', legacyCategory: 'software' },
  { path: 'software/cad-diseno/autodesk-autocad-lt/3y-1usuario-eld', name: 'AutoCAD LT 3 anos 1 usuario ELD', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp', name: 'Tarjetas SNMP para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/cdp-uposnmp-db9', name: 'CDP UPOSNMP-DB9 tarjeta externa SNMP', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos', name: 'Conectores electricos', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos/nema', name: 'Conectores electricos NEMA', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos/nema/l5-30r', name: 'Conectores NEMA L5-30R', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos/nema/l5-30r/datashield-mi-4100', name: 'DataShield MI-4100 NEMA L5-30R', legacyCategory: 'power' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc', name: 'Kits de mantenimiento para PC', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc/manhattan-400077-13p', name: 'Manhattan 400077 13 piezas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc/manhattan-530071-17p', name: 'Manhattan 530071 17 piezas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc/manhattan-530217-145p', name: 'Manhattan 530217 145 piezas', legacyCategory: 'accessories' },
  { path: 'video/accesorios-av/splitters-vga', name: 'Splitters y divisores VGA', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/splitters-vga/1x4', name: 'Splitters VGA 1 entrada 4 salidas', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/splitters-vga/1x4/manhattan-207348', name: 'Manhattan 207348 splitter VGA 1x4', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/extensores-vga', name: 'Extensores VGA', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/extensores-vga/audio-cat5e-cat6', name: 'Extensores VGA con audio por Cat5e/Cat6', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/extensores-vga/audio-cat5e-cat6/manhattan-177344', name: 'Manhattan 177344 extensor VGA audio', legacyCategory: 'tvs' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/15-4', name: 'Maletines para laptop 15.4 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/15-4/manhattan-times-square-421430', name: 'Manhattan Times Square 421430', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/papel-plotter/mate', name: 'Papel mate para plotter', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/mate/doubleweight', name: 'Epson Doubleweight Matte Paper', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/mate/doubleweight/rollos-24in-82ft', name: 'Rollos Doubleweight Matte 24 x 82 pies', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/mate/doubleweight/rollos-24in-82ft/epson-s041385', name: 'Epson S041385 Doubleweight Matte 24 x 82', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico', name: 'Papel fotografico', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico/luster', name: 'Papel fotografico luster', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico/luster/carta-50-hojas', name: 'Papel luster carta 50 hojas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico/luster/carta-50-hojas/epson-s041405', name: 'Epson S041405 Ultra Premium Luster carta', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/presentation-matte', name: 'Papel Presentation Matte', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/presentation-matte/carta-100-hojas', name: 'Presentation Matte carta 100 hojas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/presentation-matte/carta-100-hojas/epson-s041062', name: 'Epson S041062 Presentation Matte carta', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11', name: 'PCM Data Stock 9.5 x 11 pulgadas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/1-tanto', name: 'PCM Data Stock 9.5 x 11 1 tanto', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/1-tanto/pcm-ds00113000b', name: 'PCM DS00113000B 1 tanto 3000 hojas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/2-tantos', name: 'PCM Data Stock 9.5 x 11 2 tantos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/2-tantos/pcm-ds00121500b', name: 'PCM DS00121500B 2 tantos 1500 juegos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/3-tantos', name: 'PCM Data Stock 9.5 x 11 3 tantos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/3-tantos/pcm-ds00131000b', name: 'PCM DS00131000B 3 tantos 1000 juegos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/4-tantos', name: 'PCM Data Stock 9.5 x 11 4 tantos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x11/4-tantos/pcm-ds0014750b', name: 'PCM DS0014750B 4 tantos 750 juegos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/1-tanto', name: 'PCM Data Stock 9.5 x 5.5 1 tanto', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/1-tanto/pcm-ds00216000b', name: 'PCM DS00216000B 1 tanto 6000 hojas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/2-tantos', name: 'PCM Data Stock 9.5 x 5.5 2 tantos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel/formas-continuas/data-stock/9-5x5-5/2-tantos/pcm-ds00223000b', name: 'PCM DS00223000B 2 tantos 3000 juegos', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf/duplex/portatiles', name: 'Escaneres ADF duplex portatiles', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf/duplex/portatiles/kodak-scanmate-i940', name: 'Kodak ScanMate i940', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas-papel/termicas-directas/zebra/z-perform-2000d', name: 'Zebra Z-Perform 2000D', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas-papel/termicas-directas/zebra/z-perform-2000d/2x1-10010028', name: 'Zebra 10010028 Z-Perform 2000D 2 x 1', legacyCategory: 'printers_scanners' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc', name: 'Tarjetas PVC para credenciales', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc/zebra-104523-210', name: 'Zebra 104523-210 tarjetas PVC CR-80', legacyCategory: 'accessories' },
  { path: 'impresion/refacciones/cabezales/inkjet/canon-imageprograf', name: 'Cabezales inkjet Canon imagePROGRAF', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/inkjet/canon-imageprograf/pf-03-2251b003ac', name: 'Canon PF-03 2251B003AC', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/cctv/accesorios-alimentacion/distribuidores-dc', name: 'Distribuidores DC para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-alimentacion/distribuidores-dc/1-a-4', name: 'Distribuidores DC CCTV 1 a 4', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-alimentacion/distribuidores-dc/1-a-4/enson-ens-dc14', name: 'Enson ENS-DC14 distribuidor DC 1 a 4', legacyCategory: 'cameras' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/koblenz-45-0995-00-6', name: 'Koblenz 45-0995-00-6 tarjeta SNMP', legacyCategory: 'power' },
  { path: 'computo/accesorios/limpieza/espumas', name: 'Espumas limpiadoras para computo', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/limpieza/espumas/antibacterial', name: 'Espumas limpiadoras antibacteriales', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/limpieza/espumas/antibacterial/vorago-cln-101', name: 'Vorago CLN-101 espuma limpiadora', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc/zebra-premier-plus-104524-101', name: 'Zebra Premier Plus 104524-101 tarjetas PVC', legacyCategory: 'accessories' },
  { path: 'infraestructura/racks-accesorios/herrajes', name: 'Herrajes para racks', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/herrajes/tuercas-enjauladas', name: 'Tuercas enjauladas y tornilleria rack', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/herrajes/tuercas-enjauladas/m6', name: 'Herrajes rack M6', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/herrajes/tuercas-enjauladas/m6/tripp-lite-srcagenuts', name: 'Tripp Lite SRCAGENUTS M6', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/herrajes/tuercas-enjauladas/12-24', name: 'Herrajes rack 12-24', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/herrajes/tuercas-enjauladas/12-24/tripp-lite-srcagenuts1224', name: 'Tripp Lite SRCAGENUTS1224 12-24', legacyCategory: 'networking' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/datashield-pc-3704', name: 'DataShield PC-3704 tarjeta SNMP interna', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/36v', name: 'Bancos de baterias rack torre 36V', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/36v/cyberpower-bp36v60art2u', name: 'CyberPower BP36V60ART2U banco 36V', legacyCategory: 'power' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-100m', name: 'Rollos papel bond plotter 61 cm x 100 m', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-100m/pcm-10b2', name: 'PCM 10B2 papel bond plotter 0.61 x 100', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-150m', name: 'Rollos papel bond plotter 61 cm x 150 m', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-150m/pcm-10b3', name: 'PCM 10B3 papel bond plotter 0.61 x 150', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-50m/pcm-10b7', name: 'PCM 10B7 papel bond plotter 0.61 x 50', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-150m/pcm-10b9', name: 'PCM 10B9 papel bond plotter 0.61 x 150', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-50m', name: 'Rollos papel bond plotter 91 cm x 50 m', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-50m/pcm-10b10', name: 'PCM 10B10 papel bond plotter 0.91 x 50', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-150m/pcm-10b12', name: 'PCM 10B12 papel bond plotter 0.91 x 150', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-100m/pcm-10b14', name: 'PCM 10B14 papel bond plotter 0.61 x 100', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-150m/pcm-10b15', name: 'PCM 10B15 papel bond plotter 0.61 x 150', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-50m/pcm-10b16', name: 'PCM 10B16 papel bond plotter 0.91 x 50', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-150m/pcm-10b18', name: 'PCM 10B18 papel bond plotter 0.91 x 150', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-100m/pcm-10b20', name: 'PCM 10B20 papel bond plotter 0.61 x 100', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/unidades-transferencia/brother', name: 'Unidades de transferencia Brother', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/unidades-transferencia/brother/bu330cl', name: 'Brother BU330CL unidad de banda', legacyCategory: 'printers_scanners' },
  { path: 'video/soportes-tv/techo', name: 'Soportes de techo para TV y pantallas', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/techo/estructurales-multipantalla', name: 'Placas estructurales de techo multipantalla', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/techo/estructurales-multipantalla/peerless-dcs400', name: 'Peerless-AV DCS400 placa estructural', legacyCategory: 'tvs' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc/adhesivas', name: 'Tarjetas PVC adhesivas para credenciales', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc/adhesivas/zebra-104523-010', name: 'Zebra 104523-010 tarjetas PVC adhesivas', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-100m', name: 'Rollos papel bond plotter 91 cm x 100 m', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-91cm-100m/pcm-10b23', name: 'PCM 10B23 papel bond plotter 0.91 x 100', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/videoporteros/ip/wifi-cableado', name: 'Videoporteros IP Wi-Fi cableados', legacyCategory: 'security' },
  { path: 'seguridad/videoporteros/ip/wifi-cableado/ring-b08ckhpp52', name: 'Ring Video Doorbell Wired B08CKHPP52', legacyCategory: 'security' },
  { path: 'oficina/papeleria/archivo/guias-alfabeticas', name: 'Guias alfabeticas para archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/guias-alfabeticas/oficio', name: 'Guias alfabeticas tamano oficio', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/guias-alfabeticas/oficio/baco-bac3580', name: 'BACO BAC3580 guias oficio 25 piezas', legacyCategory: 'accessories' },
  { path: 'electronica/wearables/pulseras-inteligentes', name: 'Pulseras inteligentes', legacyCategory: 'accessories' },
  { path: 'electronica/wearables/pulseras-inteligentes/amazfit-band-7', name: 'Amazfit Band 7', legacyCategory: 'accessories' },
  { path: 'servicios-ti/instalacion-puesta-en-marcha/cyberpower', name: 'Puesta en marcha CyberPower', legacyCategory: 'software' },
  { path: 'servicios-ti/instalacion-puesta-en-marcha/cyberpower/ups-trifasicos', name: 'Puesta en marcha UPS trifasicos CyberPower', legacyCategory: 'software' },
  { path: 'servicios-ti/instalacion-puesta-en-marcha/cyberpower/ups-trifasicos/pol-5009', name: 'CyberPower POL-5009 arranque UPS trifasico', legacyCategory: 'software' },
  { path: 'oficina/papeleria/marcadores/resaltadores/surtidos/5-piezas/azor-vision-jr-2825', name: 'Azor Vision Jr 2825 surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/baco-le-plume-rojo-12-piezas', name: 'BACO Le Plume rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'gaming/audio/headsets/alambricos/3-5mm-microfono-desmontable/yeyian-proud-ydg-33405', name: 'Yeyian Proud YDG-33405 3.5 mm', legacyCategory: 'gaming' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3475b', name: 'Garantias GHIA PCGHIA-3475B', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3475b/24-meses-adicionales', name: 'GHIA PCGHIA-3475B 24 meses adicionales', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3475b/24-meses-adicionales/pol-10052', name: 'GHIA POL-10052 garantia 24 meses', legacyCategory: 'software' },
  { path: 'seguridad/control-acceso/credenciales-rfid/tarjetas-pvc/em-125khz/saxxon-asc-em02f', name: 'Saxxon ASC-EM02F 125 kHz', legacyCategory: 'security' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/3y-basic-onsite-a-3y-prosupport', name: 'Dell OptiPlex 3000 3Y Basic a ProSupport', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/vostro-notebooks-3000', name: 'Dell Basic NBD para Vostro notebooks 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/vostro-notebooks-3000/1y-a-3y', name: 'Dell Vostro notebooks 3000 1Y a 3Y Basic NBD', legacyCategory: 'software' },
  { path: 'oficina/papeleria/archivo/separadores-indices', name: 'Separadores e indices para archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta', name: 'Separadores e indices carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/a-z', name: 'Separadores alfabeticos A-Z carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/separadores-indices/carta/a-z/wilson-jones-p1367', name: 'Wilson Jones P1367 A-Z carta', legacyCategory: 'accessories' },
  { path: 'impresion/impresoras/multifuncionales-laser/color', name: 'Multifuncionales laser color', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/multifuncionales-laser/color/canon-imagerunner-advance-dx-c478if', name: 'Canon imageRUNNER ADVANCE DX C478iF', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/cctv/accesorios-camaras/cajas-conexion/impermeables-ip66/provision-pr-jb12ip66', name: 'Provision-ISR PR-JB12IP66', legacyCategory: 'security' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/crayones/baco-jumbo-65476-6p', name: 'BACO Jumbo 65476 crayones 6 piezas', legacyCategory: 'accessories' },
  { path: 'deportes', name: 'Deportes', legacyCategory: 'accessories' },
  { path: 'deportes/accesorios', name: 'Accesorios deportivos', legacyCategory: 'accessories' },
  { path: 'deportes/accesorios/bolsas-deportivas', name: 'Bolsas deportivas', legacyCategory: 'accessories' },
  { path: 'deportes/accesorios/bolsas-deportivas/mochilas-gimnasio', name: 'Mochilas y bolsos de gimnasio', legacyCategory: 'accessories' },
  { path: 'deportes/accesorios/bolsas-deportivas/mochilas-gimnasio/perfect-choice-sportiva-pc-084631', name: 'Perfect Choice Sportiva PC-084631', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/metalicos/dorado', name: 'Marcadores permanentes metalicos dorados', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/metalicos/dorado/12-piezas', name: 'Marcadores metalicos dorados caja 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/metalicos/dorado/12-piezas/azor-signal-metalink-30009', name: 'Azor Signal Metalink 30009 dorado 12 piezas', legacyCategory: 'accessories' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/1500va', name: 'Bancos de baterias UPS rack torre 1500VA', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/1500va/vica-alpha-1500', name: 'VICA banco externo Alpha 1500', legacyCategory: 'power' },
  { path: 'infraestructura/enfriamiento-centros-datos/unidades-rack', name: 'Unidades de enfriamiento para rack', legacyCategory: 'components' },
  { path: 'infraestructura/enfriamiento-centros-datos/unidades-rack/aire-acondicionado', name: 'Aire acondicionado para rack', legacyCategory: 'components' },
  { path: 'infraestructura/enfriamiento-centros-datos/unidades-rack/aire-acondicionado/8u-120v', name: 'Aire acondicionado rack 8U 120V', legacyCategory: 'components' },
  { path: 'infraestructura/enfriamiento-centros-datos/unidades-rack/aire-acondicionado/8u-120v/tripp-lite-srcool7krm', name: 'Eaton Tripp Lite SRCOOL7KRM 7000 BTU', legacyCategory: 'components' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/piel', name: 'Plastilina marqueta 180 g color piel', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/plastilina/marqueta-180g/piel/baco-pl002', name: 'BACO PL002 plastilina piel 180 g', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/cdp/polizas-sitio/ups-6kva', name: 'Polizas CDP en sitio para UPS 6KVA', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/cdp/polizas-sitio/ups-6kva/pol-11419', name: 'CDP POL-11419 garantia en sitio 6KVA', legacyCategory: 'software' },
  { path: 'energia/pdu-rack/ats', name: 'PDU ATS para rack', legacyCategory: 'power' },
  { path: 'energia/pdu-rack/ats/1u-15a-10-contactos', name: 'PDU ATS rack 1U 15A con 10 contactos', legacyCategory: 'power' },
  { path: 'energia/pdu-rack/ats/1u-15a-10-contactos/cyberpower-pdu24001', name: 'CyberPower PDU24001 ATS 15A 1U', legacyCategory: 'power' },
  { path: 'software/licencias/seguridad-red/cisco-meraki/mx64/advanced-security-3y', name: 'Cisco Meraki MX64 Advanced Security 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/inspiron-desktops-sff-3030', name: 'Dell ProSupport Inspiron Desktop SFF 3030', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/inspiron-desktops-sff-3030/1y-basic-nbd-a-3y-prosupport', name: 'Dell Inspiron SFF 3030 1Y Basic a 3Y ProSupport', legacyCategory: 'software' },
  { path: 'oficina/papeleria/marcadores/resaltadores/naranja', name: 'Resaltadores naranjas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/naranja/12-piezas', name: 'Resaltadores naranjas caja 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/resaltadores/naranja/12-piezas/baco-bacoflash-99396', name: 'BACO Bacoflash 99396 naranja 12 piezas', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/lenovo/thinksystem', name: 'Lenovo ThinkSystem Services', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/thinksystem/st50-v3', name: 'Lenovo ThinkSystem ST50 V3 Services', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/thinksystem/st50-v3/essential-1y-24x7-4hr', name: 'Lenovo ST50 V3 Essential 1Y 24x7 4HR', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/thinksystem/st50-v3/essential-1y-24x7-4hr/jz00ybcx', name: 'Lenovo JZ00YBCX Essential Service ST50 V3', legacyCategory: 'software' },
  { path: 'electronica/wearables/smartwatches/salud-presion-arterial', name: 'Smartwatches de salud con presion arterial', legacyCategory: 'accessories' },
  { path: 'electronica/wearables/smartwatches/salud-presion-arterial/huawei-watch-d2-55020fkg-dsr', name: 'Huawei Watch D2 55020FKG-DSR azul', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/cabezales/canon-pixma-megatank', name: 'Cabezales Canon PIXMA MegaTank', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cabezales/canon-pixma-megatank/canon-bh-10-gi-11-pgbk', name: 'Canon BH-10 + GI-11 PGBK', legacyCategory: 'printers_scanners' },
  { path: 'electronica/rastreo-gps-telematica', name: 'Rastreo GPS y telematica', legacyCategory: 'security' },
  { path: 'electronica/rastreo-gps-telematica/rastreadores-activos', name: 'Rastreadores GPS de activos', legacyCategory: 'security' },
  { path: 'electronica/rastreo-gps-telematica/rastreadores-activos/teltonika-tat100', name: 'Teltonika TAT100 rastreador de activos', legacyCategory: 'security' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color', name: 'Lapices de color escolares', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/baco-bacoiris-lp003-24p', name: 'BACO Bacoiris LP003 colores 24 piezas', legacyCategory: 'accessories' },
  { path: 'salud/equipo-medico/monitoreo/termometros-infrarrojos', name: 'Termometros infrarrojos sin contacto', legacyCategory: 'accessories' },
  { path: 'salud/equipo-medico/monitoreo/termometros-infrarrojos/kangji-ky-111', name: 'Kangji KY-111 termometro infrarrojo', legacyCategory: 'accessories' },
  { path: 'computo/almacenamiento/nas/4-bahias/synology-ds423-plus', name: 'Synology DiskStation DS423+', legacyCategory: 'storage' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/dell-pro-laptops', name: 'Dell ProSupport para Dell Pro laptops', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/dell-pro-laptops/1y-nbd-a-3y-prosupport', name: 'Dell Pro laptops 1Y NBD a 3Y ProSupport', legacyCategory: 'software' },
  { path: 'software/cad-diseno/autodesk-autocad/toolsets-3y-1usuario-eld', name: 'AutoCAD toolsets 3 anos 1 usuario ELD', legacyCategory: 'software' },
  { path: 'oficina/papeleria/notas-adhesivas/3x3/neon', name: 'Notas adhesivas 3 x 3 neon', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/3x3/neon/janel-memo-tip-6590303197-400h', name: 'Janel Memo Tip 6590303197 400 hojas neon', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders', name: 'Folders y carpetas de archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta', name: 'Folders tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/pastel', name: 'Folders carta colores pastel', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/pastel/rosa', name: 'Folders carta pastel rosa', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/pastel/rosa/diem-fp10005-100p', name: 'DIEM FP10005 folder rosa pastel 100 piezas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/bolsos-crossbody/compactos', name: 'Bolsos crossbody compactos', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/bolsos-crossbody/compactos/perfect-choice-holdi-pc-085041', name: 'Perfect Choice Holdi PC-085041 negro', legacyCategory: 'accessories' },
  { path: 'impresion/refacciones/cabezales/inkjet/canon-imageprograf/pf-08-5706c003aa', name: 'Canon PF-08 5706C003AA imagePROGRAF', legacyCategory: 'printers_scanners' },
  { path: 'servicios-ti/configuracion-remota', name: 'Configuracion remota TI', legacyCategory: 'software' },
  { path: 'servicios-ti/configuracion-remota/telefonia-ip', name: 'Configuracion remota telefonia IP', legacyCategory: 'software' },
  { path: 'servicios-ti/configuracion-remota/telefonia-ip/grandstream', name: 'Configuracion remota Grandstream', legacyCategory: 'software' },
  { path: 'servicios-ti/configuracion-remota/telefonia-ip/grandstream/horas-gs-configremota', name: 'Grandstream GS-CONFIGREMOTA horas remotas', legacyCategory: 'software' },
  { path: 'oficina/papeleria/marcadores/permanentes/tatoo', name: 'Marcadores permanentes BACO Tatoo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/tatoo/morado', name: 'Marcadores permanentes morados', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/tatoo/morado/6-piezas', name: 'Marcadores morados caja 6 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/tatoo/morado/6-piezas/baco-mr167-61218', name: 'BACO Tatoo MR167/61218 morado 6 piezas', legacyCategory: 'accessories' },
  { path: 'domotica/sensores/temperatura-humedad', name: 'Sensores inteligentes de temperatura y humedad', legacyCategory: 'accessories' },
  { path: 'domotica/sensores/temperatura-humedad/tapo-t315', name: 'TP-Link Tapo T315 temperatura y humedad', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/pizarrones', name: 'Pizarrones y accesorios', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/pizarrones/accesorios', name: 'Accesorios para pizarron', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/pizarrones/accesorios/borradores', name: 'Borradores para pizarron', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/pizarrones/accesorios/borradores/base-madera', name: 'Borradores base madera', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/pizarrones/accesorios/borradores/base-madera/baco-gs022', name: 'BACO GS022 borrador base madera', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punta-ultrafina/azor-pinpoint-6840ro-rojo-12-piezas', name: 'Azor Pin Point 6840RO rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/lenovo/onsite', name: 'Lenovo soporte onsite', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/onsite/thinkcentre', name: 'Lenovo Onsite ThinkCentre', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/onsite/thinkcentre/3y', name: 'Lenovo ThinkCentre onsite 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/onsite/thinkcentre/3y/5ws0d80967', name: 'Lenovo 5WS0D80967 onsite 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/premier-support', name: 'Lenovo Premier Support', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/premier-support/thinkcentre-aio', name: 'Lenovo Premier Support ThinkCentre AIO', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/premier-support/thinkcentre-aio/5y-nbd', name: 'Lenovo ThinkCentre AIO Premier Support 5Y NBD', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/premier-support/thinkcentre-aio/5y-nbd/5ws0t36189', name: 'Lenovo 5WS0T36189 Premier Support 5Y', legacyCategory: 'software' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/1080p/pan-tilt', name: 'Camaras IP WiFi interiores 1080p pan tilt', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/1080p/pan-tilt/sonoff-cam-pt2', name: 'SONOFF CAM-PT2 Pan-Tilt 2', legacyCategory: 'cameras' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fashion', name: 'Marcadores Azor Signal Fashion', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fashion/surtidos', name: 'Marcadores Signal Fashion surtidos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fashion/surtidos/5-piezas', name: 'Marcadores permanentes surtidos 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fashion/surtidos/5-piezas/azor-30655', name: 'Azor Signal Fashion 30655 estuche 5 piezas', legacyCategory: 'accessories' },
  { path: 'energia/supresores-reguladores/protectores-voltaje', name: 'Protectores de voltaje', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/protectores-voltaje/120v', name: 'Protectores de voltaje 120V', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/protectores-voltaje/120v/1-contacto', name: 'Protectores 120V de un contacto', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/protectores-voltaje/120v/1-contacto/forza-fvp-1201b', name: 'Forza FVP-1201B protector 900J', legacyCategory: 'power' },
  { path: 'impresion/escaneres/documentales/adf/duplex/a4', name: 'Escaneres ADF duplex A4', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/adf/duplex/a4/canon-imageformula-dr-c230-2646c003', name: 'Canon imageFORMULA DR-C230 2646C003', legacyCategory: 'printers_scanners' },
  { path: 'software/recursos-humanos', name: 'Software de recursos humanos', legacyCategory: 'software' },
  { path: 'software/recursos-humanos/control-asistencia', name: 'Control de asistencia y puntualidad', legacyCategory: 'software' },
  { path: 'software/recursos-humanos/control-asistencia/ingressio-nube', name: 'Ingressio en la Nube', legacyCategory: 'software' },
  { path: 'software/recursos-humanos/control-asistencia/ingressio-nube/pyme-50-empleados-1y', name: 'Ingressio PyME 50 empleados 1 ano', legacyCategory: 'software' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/oficio/plastico', name: 'Cajas plasticas oficio para archivo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/cajas-archivo/oficio/plastico/geo-027', name: 'GEO 027 caja plastica oficio', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico/rojo', name: 'Marcadores Magistral Didactico rojos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico/rojo/12-piezas', name: 'Azor Magistral rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/pizarron-blanco/magistral-didactico/rojo/12-piezas/azor-8350ro', name: 'Azor Magistral 8350RO rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'computo/colaboracion/presentacion-inalambrica', name: 'Presentacion inalambrica para salas', legacyCategory: 'desktops' },
  { path: 'computo/colaboracion/presentacion-inalambrica/benq-instashow', name: 'BenQ InstaShow', legacyCategory: 'desktops' },
  { path: 'computo/colaboracion/presentacion-inalambrica/benq-instashow/wdc15', name: 'BenQ InstaShow WDC15', legacyCategory: 'desktops' },
  { path: 'computo/accesorios/soportes-monitor/vesa/mini-pc', name: 'Soportes VESA para mini PC', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/soportes-monitor/vesa/mini-pc/dell-452-bdvb', name: 'Dell 452-BDVB soporte VESA Micro', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci', name: 'Lenovo Depot CCI', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci/ideapad', name: 'Lenovo Depot CCI IdeaPad', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci/ideapad/3y', name: 'Lenovo IdeaPad Depot CCI 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/depot-cci/ideapad/3y/5ws0k75663', name: 'Lenovo 5WS0K75663 IdeaPad 3Y Depot CCI', legacyCategory: 'software' },
  { path: 'seguridad/cctv/accesorios-alimentacion/distribuidores-dc/1-a-2', name: 'Distribuidores DC CCTV 1 a 2', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-alimentacion/distribuidores-dc/1-a-2/enson-ens-dc12', name: 'Enson ENS-DC12 distribuidor DC 1 a 2', legacyCategory: 'cameras' },
  { path: 'computo/componentes/tarjetas-video/nvidia-rtx-profesional', name: 'Tarjetas NVIDIA RTX profesionales', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-video/nvidia-rtx-profesional/rtx-a400', name: 'NVIDIA RTX A400 profesional', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-video/nvidia-rtx-profesional/rtx-a400/pny-vcnrtxa400atx-pb', name: 'PNY NVIDIA RTX A400 4GB', legacyCategory: 'components' },
  { path: 'oficina/papeleria/material-escolar/borradores/blancos/baco-g20-94124', name: 'BACO G-20 94124 borrador blanco', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-usb/area-imager/datalogic-magellan-1500i', name: 'Datalogic Magellan 1500i USB', legacyCategory: 'accessories' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-40/rtx-4080', name: 'Tarjetas de video NVIDIA GeForce RTX 4080', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-40/rtx-4080/gigabyte-eagle-gv-n4080eagle-16gd', name: 'Gigabyte RTX 4080 Eagle 16GB', legacyCategory: 'gaming' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/1y-basic-nbd-a-1y-prosupport', name: 'Dell OptiPlex 3000 1Y Basic NBD a 1Y ProSupport', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/1y-basic-nbd-a-1y-prosupport/n-optl1-n1-p1', name: 'Dell N_OPTL1_N1_P1 OptiPlex 3000 1Y ProSupport', legacyCategory: 'software' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punta-fina', name: 'Boligrafos de punta fina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punta-fina/azor-pinpoint-6810ro-rojo-12-piezas', name: 'Azor Pin Point 6810RO rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios/kits-interactivos', name: 'Kits interactivos para proyectores', legacyCategory: 'accessories' },
  { path: 'audio-video/proyectores/accesorios/kits-interactivos/benq-pointwrite-pw03', name: 'BenQ PointWrite PW03 kit interactivo', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/cyberpower', name: 'Soporte y garantias CyberPower', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/cyberpower/ups-line-interactive', name: 'Garantias CyberPower UPS line-interactive', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/cyberpower/ups-line-interactive/ut1000gu', name: 'Garantias CyberPower UT1000GU', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/cyberpower/ups-line-interactive/ut1000gu/3y', name: 'CyberPower UT1000GU garantia 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/cyberpower/ups-line-interactive/ut1000gu/3y/pol-10204', name: 'CyberPower POL-10204 UT1000GU 3 anos', legacyCategory: 'software' },
  { path: 'redes/switches/modulos-uplink', name: 'Modulos uplink para switches', legacyCategory: 'networking' },
  { path: 'redes/switches/modulos-uplink/cisco-catalyst-9200', name: 'Modulos Cisco Catalyst 9200', legacyCategory: 'networking' },
  { path: 'redes/switches/modulos-uplink/cisco-catalyst-9200/c9200-nm-4x', name: 'Cisco C9200-NM-4X modulo 4x 1G/10G', legacyCategory: 'networking' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra', name: 'Cabezales termicos Zebra', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra/zt111-zt211-zt231-300dpi', name: 'Cabezales Zebra ZT111/211/231 300 dpi', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra/zt111-zt211-zt231-300dpi/p1123335-057', name: 'Zebra P1123335-057 cabezal 300 dpi', legacyCategory: 'printers_scanners' },
  { path: 'computo/almacenamiento/nas/rack', name: 'NAS rackmount', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/nas/rack/16-bahias', name: 'NAS rackmount 16 bahias', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/nas/rack/16-bahias/synology-rs2825rp-plus', name: 'Synology RackStation RS2825RP+ 16 bahias', legacyCategory: 'storage' },
  { path: 'oficina/papeleria/marcadores/permanentes/industriales/base-aceite/uni-paint-px20-amarillo', name: 'Uni Paint PX-20 amarillo', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-3000/1y-basic-a-3y-prosupport-plus', name: 'Dell OptiPlex 3000 1Y Basic a 3Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/optiplex-3000/1y-basic-a-3y-prosupport-plus/n-optl1-n1-m3', name: 'Dell N_OPTL1_N1_M3 OptiPlex 3000 ProSupport Plus 3Y', legacyCategory: 'software' },
  { path: 'video/senalizacion-digital/media-players', name: 'Media players para senalizacion digital', legacyCategory: 'monitors' },
  { path: 'video/senalizacion-digital/media-players/webos', name: 'Media players webOS para senalizacion digital', legacyCategory: 'monitors' },
  { path: 'video/senalizacion-digital/media-players/webos/lg-wp600-b', name: 'LG WP600-B webOS Box', legacyCategory: 'monitors' },
  { path: 'oficina/papeleria/archivo/folders/oficio', name: 'Folders tamano oficio', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/canario', name: 'Folders oficio color canario', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/canario/100-piezas', name: 'Folders oficio canario 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/canario/100-piezas/nassa-pc1006', name: 'NASSA PC1006 folder canario 100 piezas', legacyCategory: 'accessories' },
  { path: 'software/licencias/seguridad-red/hillstone/a200/servicepack-12m', name: 'Hillstone A200 ServicePack 12 meses', legacyCategory: 'software' },
  { path: 'software/licencias/seguridad-red/hillstone/a200/servicepack-12m/sgsv-a200-in12u', name: 'Hillstone SGSV-A200-IN12U ServicePack 12 meses', legacyCategory: 'software' },
  { path: 'oficina/papeleria/marcadores/resaltadores/amarillo/12-piezas/azor-vision-plus-2600am', name: 'Azor Vision Plus 2600AM amarillo 12 piezas', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/correas', name: 'Correas para terminales moviles POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/correas/zebra-et5x', name: 'Correas Zebra ET5X/ET4X', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/correas/zebra-et5x/sg-et5x-shdrstp-01', name: 'Zebra SG-ET5X-SHDRSTP-01 correa de hombro', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/cajones-dinero/cajas-portatiles', name: 'Cajas portatiles para dinero', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/cajones-dinero/cajas-portatiles/con-llave', name: 'Cajas de dinero portatiles con llave', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/cajones-dinero/cajas-portatiles/con-llave/qian-qoc-143lk', name: 'Qian QOC-143LK caja de dinero con llave', legacyCategory: 'accessories' },
  { path: 'impresion/escaneres/documentales/adf/duplex/a4/canon-imageformula-dr-c225-ii', name: 'Canon imageFORMULA DR-C225 II', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/bond/rollos-61cm-150m/pcm-10b21', name: 'PCM 10B21 papel bond plotter 0.61 x 150', legacyCategory: 'printers_scanners' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/cdp-uposnmp-dp520', name: 'CDP UPOSNMP-DP520 tarjeta SNMP interna', legacyCategory: 'power' },
  { path: 'impresion/escaneres/documentales/adf/duplex/a4/canon-imageformula-dr-c240', name: 'Canon imageFORMULA DR-C240', legacyCategory: 'printers_scanners' },
  { path: 'infraestructura/racks-accesorios/iluminacion', name: 'Iluminacion interna para racks', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/iluminacion/1u', name: 'Iluminacion rack 1U', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-accesorios/iluminacion/1u/laces-la300kil', name: 'Laces LA300KIL kit de iluminacion 1U', legacyCategory: 'networking' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/cunas', name: 'Cunas para terminales moviles POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/cunas/honeywell-intermec', name: 'Cunas Honeywell Intermec', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-moviles/accesorios/cunas/honeywell-intermec/871-228-201', name: 'Honeywell Intermec 871-228-201 single dock', legacyCategory: 'accessories' },
  { path: 'energia/estaciones-carga-dispositivos', name: 'Estaciones de carga para dispositivos', legacyCategory: 'power' },
  { path: 'energia/estaciones-carga-dispositivos/carritos-ac', name: 'Carritos de carga AC', legacyCategory: 'power' },
  { path: 'energia/estaciones-carga-dispositivos/carritos-ac/32-dispositivos', name: 'Carritos de carga AC para 32 dispositivos', legacyCategory: 'power' },
  { path: 'energia/estaciones-carga-dispositivos/carritos-ac/32-dispositivos/tripp-lite-csc32ac', name: 'Tripp Lite CSC32AC carrito 32 dispositivos', legacyCategory: 'power' },
  { path: 'computo/accesorios/ergonomia', name: 'Ergonomia y mobiliario de computo', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/ergonomia/estaciones-trabajo-ajustables', name: 'Estaciones de trabajo ajustables', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/ergonomia/estaciones-trabajo-ajustables/sit-stand', name: 'Convertidores sit-stand', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/ergonomia/estaciones-trabajo-ajustables/sit-stand/abrazadera', name: 'Convertidores sit-stand con abrazadera', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/ergonomia/estaciones-trabajo-ajustables/sit-stand/abrazadera/tripp-lite-wwssdc', name: 'Tripp Lite WWSSDC sit-stand con abrazadera', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/ergonomia/estaciones-trabajo-ajustables/sit-stand/sobremesa', name: 'Convertidores sit-stand de sobremesa', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/ergonomia/estaciones-trabajo-ajustables/sit-stand/sobremesa/tripp-lite-wwssdt', name: 'Tripp Lite WWSSDT sit-stand sobremesa', legacyCategory: 'accessories' },
  { path: 'impresion/escaneres/documentales/portatiles', name: 'Escaneres documentales portatiles', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/portatiles/adf', name: 'Escaneres portatiles con ADF', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/portatiles/adf/duplex', name: 'Escaneres portatiles ADF duplex', legacyCategory: 'printers_scanners' },
  { path: 'impresion/escaneres/documentales/portatiles/adf/duplex/canon-imageformula-p-208ii', name: 'Canon imageFORMULA P-208II', legacyCategory: 'printers_scanners' },
  { path: 'redes/wisp', name: 'Wireless ISP', legacyCategory: 'networking' },
  { path: 'redes/wisp/airfiber', name: 'Ubiquiti airFiber', legacyCategory: 'networking' },
  { path: 'redes/wisp/airfiber/accesorios', name: 'Accesorios airFiber', legacyCategory: 'networking' },
  { path: 'redes/wisp/airfiber/accesorios/kits-conversion', name: 'Kits de conversion airFiber', legacyCategory: 'networking' },
  { path: 'redes/wisp/airfiber/accesorios/kits-conversion/af-5g-omt-s45', name: 'Ubiquiti AF-5G-OMT-S45 kit conversion 5 GHz', legacyCategory: 'networking' },
];
