import { normalizeCatalogText } from './catalogIndex.mjs';

export const MANUAL_TAXONOMY_VERSION = 'manual-taxonomy-mx-2026-05-27';

export const MANUAL_CATEGORY_TREE = [
  { path: 'computo/laptops', name: 'Laptops', legacyCategory: 'laptops' },
  { path: 'computo/desktops', name: 'Computadoras de escritorio', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes', name: 'Servidores y componentes', legacyCategory: 'laptops' },
  { path: 'computo/servidores/rack', name: 'Servidores rack', legacyCategory: 'laptops' },
  { path: 'computo/servidores/almacenamiento-cintas', name: 'Almacenamiento LTO y cintas', legacyCategory: 'laptops' },
  { path: 'computo/monitores', name: 'Monitores', legacyCategory: 'monitors' },
  { path: 'computo/componentes/procesadores', name: 'Procesadores', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre', name: 'Tarjetas madre', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram', name: 'Memoria RAM', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder', name: 'Fuentes de poder', legacyCategory: 'laptops' },
  { path: 'computo/componentes/enfriamiento-gabinetes', name: 'Enfriamiento y gabinetes', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd', name: 'SSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/discos-duros', name: 'Discos duros', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash', name: 'Memorias flash y microSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos', name: 'Medios opticos CD/DVD', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados', name: 'Teclados', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse', name: 'Mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/webcams', name: 'Webcams', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/bocinas-audio', name: 'Bocinas y audio PC', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/presentadores', name: 'Presentadores inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza', name: 'Limpieza de computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs', name: 'Docks y hubs', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas', name: 'Mochilas y fundas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-audio', name: 'Tarjetas de sonido', legacyCategory: 'headphones' },
  { path: 'computo/componentes/pasta-termica', name: 'Pasta termica y compuestos', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups', name: 'No-breaks y UPS', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/tarjetas-snmp', name: 'Tarjetas SNMP para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups', name: 'Baterias para UPS', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores', name: 'Supresores y reguladores', legacyCategory: 'laptops' },
  { path: 'domotica/sensores', name: 'Sensores inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/fugas-agua', name: 'Sensores de fuga de agua', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos', name: 'Electrodomesticos', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/microondas', name: 'Hornos de microondas', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aspiradoras-robot', name: 'Aspiradoras robot', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-enfriamiento', name: 'Racks y enfriamiento', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios', name: 'Accesorios para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/herrajes', name: 'Herrajes y tornilleria para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/organizadores-cable', name: 'Organizadores de cable para rack', legacyCategory: 'networking' },
  { path: 'infraestructura/cajas-registro', name: 'Cajas de registro y montaje', legacyCategory: 'laptops' },
  { path: 'redes/access-points', name: 'Access points', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas', name: 'Radioenlaces y antenas', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores', name: 'Transceptores y convertidores', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado', name: 'Cableado estructurado', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado', name: 'Herramientas para cableado', legacyCategory: 'networking' },
  { path: 'redes/switches', name: 'Switches', legacyCategory: 'networking' },
  { path: 'redes/routers', name: 'Routers', legacyCategory: 'networking' },
  { path: 'impresion/impresoras', name: 'Impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/escaneres', name: 'Escaneres documentales', legacyCategory: 'cameras' },
  { path: 'impresion/consumibles/cabezales', name: 'Cabezales de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tinta-toner', name: 'Tinta, toner y cintas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/etiquetas-papel', name: 'Etiquetas y papel', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-plotter', name: 'Papel para plotter', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/mantenimiento', name: 'Mantenimiento de impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/unidades-transferencia', name: 'Unidades de transferencia', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras', name: 'Lectores de codigo de barras', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/cajones-dinero', name: 'Cajones de dinero POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/terminales-accesorios', name: 'Terminales y accesorios POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/credenciales-identificacion', name: 'Credenciales e identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/etiquetas-termicas', name: 'Etiquetas termicas POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-termicos', name: 'Rollos termicos POS', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/biometricos', name: 'Biometricos de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/cerraduras-inteligentes', name: 'Cerraduras inteligentes', legacyCategory: 'laptops' },
  { path: 'seguridad/cctv/camaras', name: 'Camaras CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi', name: 'Camaras IP WiFi', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe', name: 'Camaras IP PoE', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd', name: 'Camaras TurboHD analogicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/kits-vigilancia', name: 'Kits de videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado', name: 'Accesorios y cableado CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/fuentes-poder', name: 'Fuentes de poder para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr', name: 'DVR y NVR', legacyCategory: 'cameras' },
  { path: 'seguridad/epp/proteccion-facial', name: 'Proteccion facial EPP', legacyCategory: 'laptops' },
  { path: 'seguridad/epp/proteccion-ocular', name: 'Proteccion ocular EPP', legacyCategory: 'laptops' },
  { path: 'salud/equipo-medico/monitoreo', name: 'Monitoreo medico domestico', legacyCategory: 'laptops' },
  { path: 'telefonia/smartphones', name: 'Smartphones', legacyCategory: 'smartphones' },
  { path: 'wearables/smartwatches', name: 'Smartwatches y bandas inteligentes', legacyCategory: 'smartphones' },
  { path: 'audio/audifonos', name: 'Audifonos', legacyCategory: 'headphones' },
  { path: 'audio/microfonos', name: 'Microfonos', legacyCategory: 'headphones' },
  { path: 'audio/bocinas', name: 'Bocinas', legacyCategory: 'headphones' },
  { path: 'audio/barras-sonido', name: 'Barras de sonido', legacyCategory: 'headphones' },
  { path: 'video/televisores', name: 'Televisores', legacyCategory: 'tvs' },
  { path: 'video/proyectores', name: 'Proyectores', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion', name: 'Accesorios de proyeccion', legacyCategory: 'tvs' },
  { path: 'gaming/consolas', name: 'Consolas', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios', name: 'Accesorios gaming', legacyCategory: 'gaming' },
  { path: 'oficina/mobiliario-accesorios', name: 'Mobiliario y accesorios de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/papel-consumibles', name: 'Papel y consumibles de oficina', legacyCategory: 'laptops' },
  { path: 'software/licencias', name: 'Licencias de software', legacyCategory: 'software' },
  { path: 'accesorios/seguridad-fisica', name: 'Seguridad fisica para equipos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/herramientas-esd', name: 'Herramientas antiestaticas ESD', legacyCategory: 'laptops' },
  { path: 'energia/power-banks', name: 'Baterias externas y power banks', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores', name: 'Cables y adaptadores', legacyCategory: 'laptops' },
  { path: 'accesorios/montaje-soportes', name: 'Montaje y soportes', legacyCategory: 'laptops' },
  { path: 'redes/cableado-estructurado/placas-keystone', name: 'Placas keystone y faceplates', legacyCategory: 'networking' },
  { path: 'movilidad/scooters-electricos', name: 'Scooters electricos', legacyCategory: 'gaming' },
];

const rules = [
  ['seguridad/control-acceso/cerraduras-inteligentes', /\b(dl05|cerradura inteligente|smart fingerprint lock|smart lock|fechadura inteligente)\b/],
  ['seguridad/cctv/kits-vigilancia', /\b(sua kit xvr1e04|sua-kit\/xvr1e04|kit de videovigilancia|kit cctv|4 b10p)\b/],
  ['seguridad/cctv/dvr-nvr', /\b(dvr|nvr|grabador|xvr)\b/],
  ['seguridad/cctv/camaras-ip-poe', /\b(mob 203d|mob-203d|mtd 203d|mtd-203d|camara ip bullet|camara ip domo|camara ip turret|poe)\b/],
  ['seguridad/cctv/camaras-ip-wifi', /\b(ezviz|tapo c210|tapoc210|cs h9c|csh9c10mp|230379|cs bc1c|cs eb3|cs h80f|scam3db|camara ip|camera ip|camara wifi|camera wifi)\b/],
  ['seguridad/cctv/camaras-turbohd', /\b(tddl200a|tddl 200a|mdl 2202a|mdl-2202a|uac t112|uac-t112|uniarch uac|turbohd|turbo hd|ds2ce|ds 2ce|b8turbo|b8 turbo|tbdl500a|topvision|thc b|thcb|colorvu|tvi ahd cvi cvbs)\b/],
  ['seguridad/cctv/camaras', /\b(camara|camera|ipc|hac|dahua|hikvision|uniview|bullet|domo|turret)\b/],
  ['redes/access-points', /\b(access point|ap\b|eap|uap|wifi|wi fi|wireless)\b/],
  ['redes/radioenlaces-antenas', /\b(airfiber|airmax|litebeam|nanobeam|powerbeam|rocketm|rocket|pbe|lbe|af\s?5|am\s?[25]g|amo\s?[25]g|rd\s?5g|horn\s?5|lap\s?120|lap\s?gps|antena|radioenlace)\b/],
  ['redes/transceptores-convertidores', /\b(sfp|transceiver|transceptor|gbic|media converter|convertidor|mc200cm\w*|mc110cs\w*|sm311\w*|uf mm|uf gp|uf loco|uf nano|fibra optica)\b/],
  ['redes/herramientas-cableado', /\b(aw250nxt11|accnxx170|punchdown|punzadora|herramienta de impacto|terminacion 110|bloques 110|blade 110)\b/],
  ['redes/cableado-estructurado', /\b(panduit|belden|jack modular|patch panel|faceplate|tapa ciega|rj45|cat6|cat 6|nk6|cj688|cfpe|wmph|wmp|ld10|sp688|intellinet \d+)\b/],
  ['redes/switches', /\b(switch|poe|gigabit|jetstream)\b/],
  ['redes/routers', /\b(router|gateway|firewall|mikrotik|fortigate)\b/],
  ['computo/servidores/rack', /\b(r760xs|poweredge r760xs|serddl180|servidor rack)\b/],
  ['infraestructura/racks-accesorios/herrajes', /\b(la100te1224x50|tuerca enjaulada|cage nut|12 24|12-24|acclcs230)\b/],
  ['infraestructura/racks-accesorios/organizadores-cable', /\b(aw222nxt62|npm dh2ub|npm-dh2ub|organizador de cable|horizontal duct|duct cable management)\b/],
  ['infraestructura/racks-enfriamiento', /\b(rack|gabinete mural|charola|shelf|panel|srcool|fanroof|cagenuts|srshelf|srwf|sr1upanel|cooling|enfriamiento)\b/],
  ['infraestructura/cajas-registro', /\b(enson ens pcb|ens pcb|pcb1010|caja de plastico|caja estanca|caja registro|ip66)\b/],
  ['energia/accesorios-ups/tarjetas-snmp', /\b(rmcard205|cyberpower rmcard205|remote management card|tarjeta snmp cyberpower|smartbitt snmp|snmp administrador|tarbit010|tarjeta de administracion de red|viewpower|snmpv3)\b/],
  ['energia/baterias-ups', /\b(cei 1 006|cei-1-006|12v 7ah|12 v 7 ah|rbc|replacement battery|bateria ups|battery cartridge|apcrbc)\b/],
  ['energia/supresores-reguladores', /\b(supresor|regulador|tlp\d|isotel|contactos|multicontacto|pv375usb|vp132|supvic010)\b/],
  ['energia/no-breaks-ups', /\b(ups|no break|nobreak|bateria|battery backup|regulador)\b/],
  ['domotica/sensores/fugas-agua', /\b(tapo t300|t300|sensor de fuga|water leak sensor|fugas de agua)\b/],
  ['hogar/electrodomesticos/aspiradoras-robot', /\b(tapo rv20 max|rv20 max|acctpl1210|robot vacuum|robot aspirador|aspiradora robot)\b/],
  ['hogar/electrodomesticos/microondas', /\b(hmms3411dsv|hmms2509sp|microondas|horno de microondas)\b/],
  ['audio/barras-sonido', /\b(creative stage 360|stage 360|dell sb521a|sb521a|creative stage v2|stage v2|hisense hs2100|hs2100|barra de sonido|soundbar)\b/],
  ['video/accesorios-proyeccion', /\b(msc 305|msc-305|panscr050|pantalla de proyeccion|pantalla para proyector|lampara proyector|lamp module|ls1st|ls1lt|botones adicionales|wdc10|v13h010|elplp)\b/],
  ['computo/monitores', /\b(monitor|display|odyssey|lcd|led\s?\d{2}|pulgadas)\b/],
  ['video/proyectores', /\b(proyector|projector|benq\s(mh|ms|mx|mw|th|tk|w)\d|acer\s(x|p)\d{4})\b/],
  ['computo/desktops', /\b(desktop|workstation|mini pc|all in one|aio)\b/],
  ['computo/servidores/almacenamiento-cintas', /\b(lto|ultrium|data cartridge|rDX|cinta de respaldo)\b/],
  ['computo/servidores/componentes', /\b(hewlett packard enterprise|hpe\b|proliant|smart array|dl\d{3}|ml\d{3}|p\d{5}\s?b21|j9150|dell 412|dell 470|poweredge)\b/],
  ['computo/accesorios/mochilas-fundas', /\b(tzlbp29|maltch440|pc 085201|pc-085201|malgen4870|loopy|cp5724s|ecoloop pro slim backpack|cb 300|cb-300|malvgo110|el 994312|el-994312|malgen3180|mochila|backpack|maletin|funda laptop)\b/],
  ['accesorios/seguridad-fisica', /\b(pa410s|defcon scl|serialized cable lock|nanosaver|kensington k64444|k64444ww|k64448ww|dual head laptop lock|candado seguridad|candado laptop|laptop lock|cable lock)\b/],
  ['computo/laptops', /\b(laptop|notebook|thinkpad|macbook|vivobook|latitude|elitebook|xps)\b/],
  ['computo/almacenamiento/memorias-flash', /\b(ud512gex3l1|premier extreme|sd7 1 express|high endurance|microsd|micro sd|ausdx64|ausdh32|memdat7020|memdat7310|tarjeta microsd|memoria flash)\b/],
  ['computo/almacenamiento/medios-opticos', /\b(verbatim 94776|cd-r|cd r|cdrwcb125|52x cd|700 mb|80 min)\b/],
  ['computo/componentes/procesadores', /\b(core i[3579]|ryzen|procesador|cpu\b)\b/],
  ['computo/componentes/tarjetas-madre', /\b(motherboard|tarjeta madre|mainboard|b\d{3}|z\d{3}|x\d{3})\b/],
  ['computo/componentes/memoria-ram', /\b(ram|ddr[345]|memoria)\b/],
  ['computo/componentes/fuentes-poder', /\b(fuente de poder|power supply|psu|cx\d{3}|cv\d{3}|rm\d{3}|cp 902|80 plus|80 bronze)\b/],
  ['computo/componentes/pasta-termica', /\b(br 937412|br-937412|na 0649|na-0649|ice shield|pasta termica|thermal paste|eolox)\b/],
  ['computo/componentes/enfriamiento-gabinetes', /\b(cooler|fan|ventilador|gabinete|case|h100|hydro|pwm|cc 901|cw 906|be quiet)\b/],
  ['computo/almacenamiento/ssd', /\b(ssd|nvme|m\.2|solid state)\b/],
  ['computo/almacenamiento/discos-duros', /\b(hdd|disco duro|hard drive|sata)\b/],
  ['computo/perifericos/teclados', /\b(teclado|keyboard)\b/],
  ['computo/perifericos/mouse', /\b(mouse|raton|logitech 910|trackball)\b/],
  ['computo/perifericos/webcams', /\b(webcam|camara web)\b/],
  ['audio/bocinas', /\b(pc 112716|pc-112716|miniglow|bocmst3900|bafle dual|vortred v 930280|v-930280|bocmst4110|bocinas gamer|bocina bluetooth|altavoz|speaker)\b/],
  ['computo/perifericos/bocinas-audio', /\b(bocina|as215|ac 935272|ac-935272|as430|ac 935265|ac-935265|bsp \d|ksp \d|audio pc|logitech h390|vorago au|hpb 401|hs 502)\b/],
  ['computo/perifericos/presentadores', /\b(tzapl03|acctch9960|apuntador laser|indicador 50 m|logitech spotlight|spotlight presenter|presentador|presentation remote|moulog1800)\b/],
  ['computo/componentes/tarjetas-audio', /\b(sb1870|sb1570|sound blaster audigy|tarjeta de sonido|sound card)\b/],
  ['computo/accesorios/limpieza', /\b(53 0083|53-0083|sablmp050|disperse electronico|desplazador de humedad|cln \d|limpiador|limpiadora|aire comprimido|toallitas|toallas humedas|kit limpieza|alcohol iso|alcohol isopropilico|silimex|prolicom|silitek|silimpo|compucare|aerosol)\b/],
  ['computo/accesorios/docks-hubs', /\b(docking|dock\b|hub usb|dell wd19|wd19s|dwm2655m|vorago plug)\b/],
  ['computo/accesorios/herramientas-esd', /\b(410144|accitl1055|pulsera antiestatica|antiestatica|anti static|esd)\b/],
  ['energia/power-banks', /\b(power bank|bateria externa|c100 digital|adata c100)\b/],
  ['redes/cableado-estructurado/placas-keystone', /\b(aw161nxt02|placa keystone|placa de pared|face plate|wall plate)\b/],
  ['punto-de-venta/consumibles/etiquetas-termicas', /\b(ev 3012c|ev-3012c|accevo020|etiquetas termicas 10\s?\*?\s?15|etiquetas termicas pos)\b/],
  ['impresion/consumibles/etiquetas-papel', /\b(tze|dk12|dk22|etiqueta|label|papel fotografico|rollo|zebra 10\d{3})\b/],
  ['impresion/consumibles/papel-plotter', /\b(10b4|accpcm595|papel bond pcm|plotter|0 91 x 50|914 mm)\b/],
  ['impresion/consumibles/unidades-transferencia', /\b(bu229cl|bu-229cl|belt unit|transfer belt|unidad de transferencia|cinturon de arrastre)\b/],
  ['impresion/consumibles/cabezales', /\b(bh 10|bh-10|ch 10|ch-10|0692c004aa|3yp86al|m0h50al|m0h51al|cabezal hp gt|cabezal de impresion|printhead)\b/],
  ['impresion/consumibles/tinta-toner', /\b(tinta|toner|cartucho|drum|tambor|ribbon|cinta|tn\d|dr\d|pfi|gpr|pg \d|cl \d|erc|s015|s041|t\d{5,}|lexmark|xerox|kyocera|okidata|canon \d{3}\b|brother t[nz]|epson t)\b/],
  ['impresion/consumibles/mantenimiento', /\b(t04d100|t04d1|maintenance box|caja de mantenimiento|maintenance kit)\b/],
  ['impresion/escaneres', /\b(scanjet pro 3000|scanjet pro 2000|scanjet pro 2600|6fw07a|6fw06a|20g05a|scahpi455|scahpi465|scahpi510|epson ds|workforce ds|document scanner|escaner documental)\b/],
  ['impresion/impresoras', /\b(impresora|printer|laserjet|deskjet|ecotank|multifuncional|zebra pc 200994)\b/],
  ['punto-de-venta/lectores-codigo-barras', /\b(scanner|scaner|lector codigo|codigo de barras|barcode|ev 3006|ev-3006|ev 3007|ev-3007|honeywell|xenon|ms7820|3nstar sc|3nstar cd|zebra ds|zebra ls|topaz t)\b/],
  ['punto-de-venta/cajones-dinero', /\b(qoc 143sk|qoc-143sk|cjnqia030|cajon de dinero|caja para dinero|cash drawer)\b/],
  ['punto-de-venta/consumibles/rollos-termicos', /\b(ev 3021c|ev-3021c|ev 3023c|ev-3023c|ev 3025c|ev-3025c|accevo030|accevo050|accevo070|rollos de papel termico|papel termico 57|papel termico 80)\b/],
  ['punto-de-venta/terminales-accesorios', /\b(cajon de dinero|cash drawer|pos\b|terminal punto de venta|3nstar ct|gaveta)\b/],
  ['punto-de-venta/credenciales-identificacion', /\b(evolis|hid \d|credencial|tarjeta pvc|pvc card|104523|zk teco|zkteco|biometrico)\b/],
  ['seguridad/control-acceso/biometricos', /\b(an gc150|an-gc150|gc150|sofavz580|digitalpersona|lector huella|fingerprint|huella digital|50013 001 104)\b/],
  ['seguridad/cctv/accesorios-cableado', /\b(video balun|balun|transceptor pasivo|ptr 101v|ptr101v|vb 03|vb03)\b/],
  ['seguridad/cctv/fuentes-poder', /\b(pr 12v5a|pr-12v5a|12v5a|fuente de poder cctv|fuente para camara)\b/],
  ['seguridad/epp/proteccion-facial', /\b(pco110|pco120|cubpco110|cubpco120|careta|proteccion facial|face shield|cpa nino)\b/],
  ['seguridad/epp/proteccion-ocular', /\b(gksa01|goggles|proteccion ocular|lentes de seguridad)\b/],
  ['salud/equipo-medico/monitoreo', /\b(gp 200|gp-200|teryob010|hg01|terhis010|termometro infrarrojo|bp 201m|bp-201m|tensiometro|baumanometro|presion sanguinea)\b/],
  ['oficina/papel-consumibles', /\b(papel navigator|navigator 802839500207|papel carta|papel a4|5000 hojas|500 hojas|764025932868|paphpb010)\b/],
  ['wearables/smartwatches', /\b(55020eku|55020ees|55020eel|55020ekx|huawei band 10|nsw 101|nsw-101|necnon smartwatch|pc 270225|pc-270225|pc 270164|pc-270164|smartwatch amber|smartwatch|smart watch|banda inteligente)\b/],
  ['telefonia/smartphones', /\b(iphone|galaxy|pixel|moto|smartphone|telefono)\b/],
  ['audio/microfonos', /\b(pc 110583|pc-110583|microfono|microphone|cardioide|noise barrier)\b/],
  ['audio/audifonos', /\b(audifonos|auriculares|diadema|headphones|headset|zone 300|h540|981 000510|hc560|ac 942935|ac-942935|na 0304r|na-0304r|hc580|ac 942386|ac-942386|tzdibt01|techzone monoaural|bose|sony wh|earbuds)\b/],
  ['video/televisores', /\b(tv|televisor|qled|oled|crystal uhd)\b/],
  ['gaming/consolas', /\b(playstation|xbox|nintendo|switch oled|ps5|consola)\b/],
  ['movilidad/scooters-electricos', /\b(stscm03a|accsty550|scooter electrico|stylos m3)\b/],
  ['gaming/accesorios', /\b(balam rush|kg 200|gamepad|joystick|silla gamer|gaming chair)\b/],
  ['oficina/mobiliario-accesorios', /\b(nextep|silla|escritorio|archivero|organizador oficina)\b/],
  ['software/licencias', /\b(licencia|license|bitdefender|kaspersky|windows server|office 365|office home business|ep2 06687|ep2-06687|microsoft cfq\w*|microsoft software|aspel|contpaqi|sofcpc|nominas)\b/],
  ['accesorios/cables-adaptadores', /\b(cable|adaptador|hdmi|usb|brobotix)\b/],
  ['accesorios/montaje-soportes', /\b(soporte|bracket|mount|rack|charola)\b/],
];

const categoryByPath = new Map(MANUAL_CATEGORY_TREE.map((category) => [category.path, category]));

export const getManualCategorySeeds = () => MANUAL_CATEGORY_TREE.map((category) => ({
  slug: category.path.split('/').at(-1),
  path: category.path,
  parent_slug: category.path.split('/').slice(0, -1).join('/'),
  name: category.name,
  legacy_category: category.legacyCategory,
  status: 'manual_verified',
  version: MANUAL_TAXONOMY_VERSION,
}));

export const classifyManualCategory = (product) => {
  const text = normalizeCatalogText([
    product.name,
    product.brand,
    product.category,
    product.model_number,
    product.description,
    JSON.stringify(product.specs || {}),
  ].filter(Boolean).join(' '));

  for (const [path, pattern] of rules) {
    if (!pattern.test(text)) continue;
    const category = categoryByPath.get(path);
    return {
      path,
      legacyCategory: category?.legacyCategory || product.category || 'laptops',
      reviewStatus: 'manual_rule_applied',
      confidence: 0.86,
      taxonomyVersion: MANUAL_TAXONOMY_VERSION,
    };
  }

  const fallback = MANUAL_CATEGORY_TREE.find((category) => category.legacyCategory === product.category);
  return {
    path: fallback?.path || 'computo/laptops',
    legacyCategory: fallback?.legacyCategory || product.category || 'laptops',
    reviewStatus: 'needs_manual_review',
    confidence: 0.45,
    taxonomyVersion: MANUAL_TAXONOMY_VERSION,
  };
};
