export const MANUAL_CATEGORY_TREE_CYCLE003_PART005 = [
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/pantallas-colaboracion/98-pulgadas', name: 'Pantallas colaborativas 98 pulgadas', legacyCategory: 'accessories' },
  { path: 'electronica/pantallas-y-monitores/pizarrones-interactivos/pantallas-colaboracion/98-pulgadas/quinyx-qtx-te-qs1-98', name: 'Quinyx QTX-TE-QS1-98 pantalla interactiva 98 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/servidores/rack/1u/dell-poweredge-r360', name: 'Dell PowerEdge R360 servidor rack 1U', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door/29-pies/lg-gm39bvp', name: 'LG GM39BVP InstaView French Door 29 pies', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops', name: 'Dell Basic NBD para Dell Pro laptops', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops/1y-a-3y', name: 'Dell Pro laptops 1Y a 3Y Basic NBD', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops/1y-a-3y/n-dprovl1-n1-n3', name: 'Dell N_DPROVL1_N1_N3 Basic NBD 3Y', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/excel', name: 'Microsoft Excel', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/excel/ltsc-2024', name: 'Microsoft Excel LTSC 2024', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/excel/ltsc-2024/commercial-perpetual', name: 'Microsoft Excel LTSC 2024 Commercial perpetuo', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/cdp-snmptxwebpro', name: 'CDP SNMPTXWEBPRO tarjeta SNMP Web Pro', legacyCategory: 'power' },
  { path: 'hogar/electrodomesticos/refrigeradores/french-door/29-pies/lg-gm29bip', name: 'LG GM29BIP French Door 29 pies', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-nbd/dell-pro-laptops/1y-a-3y/n-dol2-n1-n3', name: 'Dell N_DOL2_N1_N3 Basic NBD 3Y', legacyCategory: 'software' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete/kits-120mm-argb', name: 'Kits de ventiladores ARGB 120 mm para gabinete', legacyCategory: 'components' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete/kits-120mm-argb/ocelot-ofkit-2', name: 'Ocelot OFKIT-2 kit 3 ventiladores 120 mm ARGB', legacyCategory: 'components' },
  { path: 'punto-de-venta/software-pos/restaurantes/licencias-renta-anual/soft-restaurant-12-pro-10-nodos', name: 'Soft Restaurant 12 Pro renta anual 10 nodos', legacyCategory: 'software' },
  { path: 'domotica/contactos-inteligentes/wifi/perfect-choice-pc-108054', name: 'Perfect Choice PC-108054 enchufe Wi-Fi 10A', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-slim-mff', name: 'Dell ProSupport Plus Dell Pro Slim y MFF', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-slim-mff/3y-basic-nbd-a-3y-prosupport-plus', name: 'Dell Pro Slim/MFF 3Y Basic NBD a ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/dell-pro-slim-mff/3y-basic-nbd-a-3y-prosupport-plus/n-ptl1-n3-m3', name: 'Dell N_PTL1_N3_M3 ProSupport Plus 3Y', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales', name: 'Servicios profesionales TI', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales/lenovo', name: 'Servicios profesionales Lenovo', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales/lenovo/cfs-transition-handling', name: 'Lenovo CFS transition handling', legacyCategory: 'software' },
  { path: 'servicios-ti/servicios-profesionales/lenovo/cfs-transition-handling/5ts1b66173', name: 'Lenovo 5TS1B66173 Transition CFS Handling Charge', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3169', name: 'Garantias GHIA PCGHIA-3169', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3169/24-meses-adicionales', name: 'GHIA PCGHIA-3169 24 meses adicionales', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3169/24-meses-adicionales/pol-8171', name: 'GHIA POL-8171 garantia 24 meses', legacyCategory: 'software' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/4000va', name: 'Correctores electromagneticos 4000VA', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/correctores-electromagneticos/4000va/sola-basic-15-81-120-4000', name: 'Sola Basic ISB 15-81-120-4000 4000VA', legacyCategory: 'power' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/modelo-pendiente', name: 'Camaras IP WiFi interiores con modelo pendiente', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/modelo-pendiente/tp-link-tapo-familia', name: 'TP-Link Tapo camara interior modelo pendiente', legacyCategory: 'cameras' },
  { path: 'software/productividad-oficina/microsoft-365/apps-for-business', name: 'Microsoft 365 Apps for Business', legacyCategory: 'software' },
  { path: 'software/productividad-oficina/microsoft-365/apps-for-business/esd-anual-1-usuario', name: 'Microsoft 365 Apps for Business ESD anual 1 usuario', legacyCategory: 'software' },
  { path: 'software/productividad-oficina/microsoft-365/apps-for-business/esd-anual-1-usuario/spp-00005', name: 'Microsoft SPP-00005 Apps for Business ESD', legacyCategory: 'software' },
  { path: 'impresion/escaneres/documentales/portatiles/adf/duplex/canon-imageformula-p-215ii', name: 'Canon imageFORMULA P-215II Scan-tini', legacyCategory: 'printers_scanners' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/vostro-3000', name: 'Dell ProSupport Plus Vostro desktops 3000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/vostro-3000/1y-basic-nbd-a-3y-prosupport-plus', name: 'Dell Vostro 3000 1Y Basic NBD a 3Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/desktops/vostro-3000/1y-basic-nbd-a-3y-prosupport-plus/n-vosdtm2-n1-m3', name: 'Dell N_VOSDTM2_N1_M3 Vostro ProSupport Plus', legacyCategory: 'software' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-techo', name: 'Soportes de techo para camaras CCTV', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-techo/pendant-domo', name: 'Soportes pendant de techo para domos', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-techo/pendant-domo/unv-tr-cm24-in', name: 'UNV TR-CM24-IN soporte pendant interior', legacyCategory: 'security' },
  { path: 'energia/pdu-rack/basicos/1u-16a-8-c13', name: 'PDU basicos 1U 16A con 8 tomas C13', legacyCategory: 'power' },
  { path: 'energia/pdu-rack/basicos/1u-16a-8-c13/huawei-pdu2000-02120814-004n-dps', name: 'Huawei PDU2000 02120814-004N-DPS 8 C13', legacyCategory: 'power' },
  { path: 'telefonia/conmutadores-ip/panasonic-kx-ns1000', name: 'Panasonic KX-NS1000', legacyCategory: 'software' },
  { path: 'telefonia/conmutadores-ip/panasonic-kx-ns1000/licencias', name: 'Licencias Panasonic KX-NS1000', legacyCategory: 'software' },
  { path: 'telefonia/conmutadores-ip/panasonic-kx-ns1000/licencias/activacion-full/se-nsp960full', name: 'Panasonic SE-NSP960FULL activacion full KX-NS1000', legacyCategory: 'software' },
  { path: 'seguridad/cctv/camaras-turbohd/bullet/2mp-ir-audio-coaxitron', name: 'Camaras TurboHD bullet 2MP IR con audio Coaxitron', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd/bullet/2mp-ir-audio-coaxitron/epcom-b8-turbo-g2p-a', name: 'EPCOM B8-TURBO-G2P/A 2MP audio Coaxitron', legacyCategory: 'cameras' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-carry-in', name: 'Dell Basic Carry-In', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-carry-in/inspiron-notebooks-5000', name: 'Dell Basic Carry-In Inspiron notebooks 5000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/basic-carry-in/inspiron-notebooks-5000/1y-a-3y/n-inspnbl3-c1-c3', name: 'Dell N_INSPNBL3_C1_C3 Inspiron 5000 3Y Carry-In', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/vica-snmp-basica', name: 'VICA tarjeta SNMP basica para UPS', legacyCategory: 'power' },
  { path: 'servicios-ti/soporte-garantias/lenovo/adp', name: 'Lenovo Accidental Damage Protection', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/adp/3y', name: 'Lenovo ADP 3 anos', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/lenovo/adp/3y/5ps8c05777', name: 'Lenovo 5PS8C05777 3Y ADP ONE', legacyCategory: 'software' },
  { path: 'computo/accesorios/hubs-usb/usb-c/7-en-1/baseus-ultrajoy-b00052803811-00', name: 'Baseus UltraJoy B00052803811-00 hub USB-C 7 en 1', legacyCategory: 'laptops' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-7000/3y-basic-nbd-a-5y-prosupport', name: 'Dell OptiPlex 7000 3Y Basic NBD a 5Y ProSupport', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-7000/3y-basic-nbd-a-5y-prosupport/n-optl3-n3-p5', name: 'Dell N_OPTL3_N3_P5 OptiPlex 7000 5Y ProSupport', legacyCategory: 'software' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-40/rtx-4060-ti', name: 'Tarjetas de video NVIDIA GeForce RTX 4060 Ti', legacyCategory: 'gaming' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-40/rtx-4060-ti/gigabyte-aero-gv-n406taero-oc-16gd', name: 'Gigabyte RTX 4060 Ti AERO OC 16GB', legacyCategory: 'gaming' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/vostro-notebooks-5000', name: 'Dell ProSupport Vostro notebooks 5000', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/vostro-notebooks-5000/1y-basic-nbd-a-3y-prosupport', name: 'Dell Vostro 5000 1Y Basic NBD a 3Y ProSupport', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/vostro-notebooks-5000/1y-basic-nbd-a-3y-prosupport/n-vosnbm3-n1-p3', name: 'Dell N_VOSNBM3_N1_P3 Vostro 5000 3Y ProSupport', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/laptops/dell-pro-14-16/1y-basic-nbd-a-3y-prosupport-plus', name: 'Dell Pro 14/16 1Y Basic NBD a 3Y ProSupport Plus', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport-plus/laptops/dell-pro-14-16/1y-basic-nbd-a-3y-prosupport-plus/n-dol2-n1-m3', name: 'Dell N_DOL2_N1_M3 ProSupport Plus 3Y', legacyCategory: 'software' },
  { path: 'telefonia/audio/manos-libres/bluetooth-monoaural/poly-voyager-legend-30-av4p5aa-ac3', name: 'Poly Voyager Legend 30 AV4P5AA#AC3', legacyCategory: 'headphones' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/1y-basic-nbd-a-5y-prosupport', name: 'Dell OptiPlex 3000 1Y Basic NBD a 5Y ProSupport', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/dell/prosupport/optiplex-3000/1y-basic-nbd-a-5y-prosupport/n-optl1-n1-p5', name: 'Dell N_OPTL1_N1_P5 OptiPlex 3000 5Y ProSupport', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/office-ltsc/standard-for-mac-2024', name: 'Microsoft Office LTSC Standard for Mac 2024', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/office-ltsc/standard-for-mac-2024/education-perpetual', name: 'Office LTSC Standard for Mac 2024 Education perpetuo', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/office-ltsc/standard-for-mac-2024/education-perpetual/dg7gmgf0pn5c-0001-education', name: 'Microsoft DG7GMGF0PN5C:0001 Education Mac 2024', legacyCategory: 'software' },
  { path: 'punto-de-venta/kioscos/pantallas-interactivas/totems', name: 'Totems interactivos para kioscos POS', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/kioscos/pantallas-interactivas/totems/55-pulgadas', name: 'Totems interactivos 55 pulgadas', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/kioscos/pantallas-interactivas/totems/55-pulgadas/qian-qoi-a55tc', name: 'Qian QOI-A55TC totem interactivo 55 pulgadas', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/batidoras', name: 'Batidoras de cocina', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/batidoras/mano', name: 'Batidoras de mano', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/batidoras/mano/200w', name: 'Batidoras de mano 200W', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/batidoras/mano/200w/mirati-mbb01n', name: 'Mirati MBB01N batidora de mano 200W', legacyCategory: 'accessories' },
  { path: 'computo/componentes/enfriamiento/pasta-termica/corsair-tm30-3g', name: 'Corsair TM30 pasta termica 3g', legacyCategory: 'components' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3517', name: 'Garantias GHIA PCGHIA-3517', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3517/24-meses-adicionales', name: 'GHIA PCGHIA-3517 24 meses adicionales', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/ghia/pcghia-3517/24-meses-adicionales/pol-10531', name: 'GHIA POL-10531 garantia 24 meses', legacyCategory: 'software' },
  { path: 'hogar/electrodomesticos/cocina/tostadores', name: 'Tostadores de pan', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/tostadores/2-rebanadas', name: 'Tostadores de 2 rebanadas', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/tostadores/2-rebanadas/800w', name: 'Tostadores de 2 rebanadas 800W', legacyCategory: 'accessories' },
  { path: 'hogar/electrodomesticos/cocina/tostadores/2-rebanadas/800w/mirati-mbt01n', name: 'Mirati MBT01N tostador 800W', legacyCategory: 'accessories' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/vertiv-rdu101', name: 'Vertiv Liebert IntelliSlot RDU101', legacyCategory: 'power' },
  { path: 'seguridad/cctv/camaras-hdcvi/domo-eyeball/4k-full-color', name: 'Camaras HDCVI domo eyeball 4K full color', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi/domo-eyeball/4k-full-color/dahua-hac-hdw1809tlmn-a-led', name: 'Dahua DH-HAC-HDW1809TLMN-A-LED 4K Full-Color', legacyCategory: 'cameras' },
  { path: 'video/proyectores/laser', name: 'Proyectores laser', legacyCategory: 'tvs' },
  { path: 'video/proyectores/laser/wxga-4000-lumenes', name: 'Proyectores laser WXGA 4000 lumenes', legacyCategory: 'tvs' },
  { path: 'video/proyectores/laser/wxga-4000-lumenes/sonnoc-snp-lc40dw', name: 'Sonnoc SNP-LC40DW proyector WXGA 4000 lumenes', legacyCategory: 'tvs' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/2mp-varifocal-ir', name: 'Camaras IP PoE bullet 2MP varifocal IR', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/2mp-varifocal-ir/uniview-ipc2322lb-adzk-h', name: 'Uniview IPC2322LB-ADZK-H 2MP varifocal IR', legacyCategory: 'cameras' },
  { path: 'software/seguridad/endpoint', name: 'Seguridad endpoint empresarial', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/bitdefender', name: 'Bitdefender endpoint empresarial', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/bitdefender/gravityzone-business-security-premium', name: 'Bitdefender GravityZone Business Security Premium', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/bitdefender/gravityzone-business-security-premium/1-ano-sector-privado', name: 'GravityZone Business Security Premium 1 ano sector privado', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/bitdefender/gravityzone-business-security-premium/1-ano-sector-privado/tmbdl-103-s', name: 'Bitdefender TMBDL-103-S Business Security Premium', legacyCategory: 'software' },
  { path: 'accesorios/cables-adaptadores/usb/micro-usb/sustentables-1-2m', name: 'Cables Micro USB sustentables 1.2 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/micro-usb/sustentables-1-2m/hune-hiedra-at-acc-ca-316bos', name: 'Hune Hiedra AT-ACC-CA-316BOS Micro USB bosque', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/mouse/inalambricos/ergonomicos/logitech-lift-910-006469-off-white', name: 'Logitech Lift 910-006469 off-white ergonomico', legacyCategory: 'accessories' },
  { path: 'computo/componentes/enfriamiento/disipadores-cpu/torre-120mm-180w', name: 'Disipadores CPU torre 120 mm 180W', legacyCategory: 'components' },
  { path: 'computo/componentes/enfriamiento/disipadores-cpu/torre-120mm-180w/be-quiet-dark-rock-slim-bk024', name: 'be quiet! Dark Rock Slim BK024', legacyCategory: 'components' },
  { path: 'computo/monitores/portatiles/15-6-fhd/aoc-16t20', name: 'AOC 16T20 monitor portatil 15.6 FHD', legacyCategory: 'monitors' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/trifasicos/80-200kva', name: 'Bancos de baterias UPS trifasicos 80 a 200 kVA', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/trifasicos/80-200kva/cdp-upo33-120bc40-100', name: 'CDP UPO33-120BC40-100 banco baterias UPO3', legacyCategory: 'power' },
  { path: 'audio/audifonos/bluetooth/diadema-oficina', name: 'Diademas Bluetooth de oficina', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth/diadema-oficina/poly-voyager-focus-2-9t9j4aa-ac3', name: 'Poly Voyager Focus 2 9T9J4AA#AC3 Teams', legacyCategory: 'headphones' },
  { path: 'computo/tabletas/android/7-pulgadas', name: 'Tabletas Android de 7 pulgadas', legacyCategory: 'tablets' },
  { path: 'computo/tabletas/android/7-pulgadas/stylos-stta3g5a', name: 'Stylos STTA3G5A tablet Android 7 pulgadas', legacyCategory: 'tablets' },
  { path: 'computo/almacenamiento/memorias-flash/usb/32gb/diseno-animado', name: 'Memorias USB 32GB con diseno animado', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb/32gb/diseno-animado/brobotix-190432-36-cerdito-rosa', name: 'BRobotix 190432-36 USB 32GB cerdito rosa', legacyCategory: 'storage' },
  { path: 'audio/audifonos/alambricos-3-5mm/diadema-con-microfono/getttech-gh-3100p-rosa', name: 'Getttech GH-3100P Sonority rosa 3.5mm', legacyCategory: 'headphones' },
  { path: 'energia/no-breaks-ups/line-interactive/1600va', name: 'UPS line-interactive 1600VA', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/line-interactive/1600va/sola-basic-xr-21-162', name: 'Sola Basic ISB Micro SR XR-21-162 1600VA', legacyCategory: 'power' },
  { path: 'impresion/consumibles/cartuchos-tinta/canon/imageprograf-pfi-007', name: 'Tanques Canon imagePROGRAF PFI-007', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cartuchos-tinta/canon/imageprograf-pfi-007/pfi-007c-2144c001aa', name: 'Canon PFI-007C 2144C001AA cian 90ml', legacyCategory: 'printers_scanners' },
  { path: 'computo/componentes/enfriamiento/ventiladores-gabinete/120mm-argb/balam-rush-eolox-blaze-ex70-br-938044', name: 'Balam Rush Eolox Blaze EX70 BR-938044 120mm ARGB', legacyCategory: 'components' },
  { path: 'software/licencias/windows-server/cal-rds/device-cal-2025', name: 'Windows Server 2025 RDS Device CAL', legacyCategory: 'software' },
  { path: 'software/licencias/windows-server/cal-rds/device-cal-2025/hpe-p77119-b21', name: 'HPE P77119-B21 Windows Server 2025 RDS 1 Device CAL', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-adm', name: 'Licencias Aspel ADM', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-adm/premium-anual', name: 'Aspel ADM Premium anual electronico', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-adm/premium-anual/adm12mpv', name: 'Aspel ADM12MPV ADM Premium anual', legacyCategory: 'software' },
  { path: 'redes/switches/poe-no-administrables/cctv/8-puertos-120w', name: 'Switches PoE CCTV 8 puertos 120W', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables/cctv/8-puertos-120w/provision-isr-poes-08120c-2i', name: 'Provision-ISR PoES-08120C+2I 8 PoE 120W', legacyCategory: 'networking' },
  { path: 'computo/monitores/gaming/27-fhd/180hz', name: 'Monitores gaming FHD de 27 pulgadas 180Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/27-fhd/180hz/aoc-27g4', name: 'AOC 27G4 monitor gaming 27 FHD 180Hz', legacyCategory: 'monitors' },
  { path: 'computo/almacenamiento/memorias-flash/usb/32gb/diseno-animado/brobotix-190432-24-pirata-rudo', name: 'BRobotix 190432-24 USB 32GB Pirata Rudo', legacyCategory: 'storage' },
  { path: 'computo/monitores/gaming/27-fhd/75hz-curvos-va', name: 'Monitores gaming curvos VA FHD de 27 pulgadas 75Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/27-fhd/75hz-curvos-va/acer-ed273-bbmiix', name: 'Acer ED273 Bbmiix monitor curvo 27 FHD 75Hz', legacyCategory: 'monitors' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop/16-pulgadas/lenovo-thinkpad-essential-eco-4x41c12468', name: 'Lenovo ThinkPad Essential Eco 4X41C12468 mochila 16 pulgadas', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/cartuchos-tinta/epson', name: 'Cartuchos de tinta Epson', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cartuchos-tinta/epson/ultrachrome-xd2', name: 'Cartuchos Epson UltraChrome XD2', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cartuchos-tinta/epson/ultrachrome-xd2/350ml', name: 'Cartuchos Epson UltraChrome XD2 350ml', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cartuchos-tinta/epson/ultrachrome-xd2/350ml/t41p220-cian', name: 'Epson T41P220 UltraChrome XD2 cian 350ml', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/control-acceso/asistencia/biometricos/huella-rfid/zkteco-tf1700', name: 'ZKTeco TF1700 huella RFID y PIN', legacyCategory: 'security' },
  { path: 'impresion/consumibles/toner-laser/lexmark', name: 'Toner laser Lexmark', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/toner-laser/lexmark/t65x', name: 'Toner Lexmark serie T65x', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/toner-laser/lexmark/t65x/t650a11l', name: 'Lexmark T650A11L toner negro 7000 paginas', legacyCategory: 'printers_scanners' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/electronicos', name: 'Reguladores electronicos de voltaje', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/electronicos/bifasicos-220v', name: 'Reguladores electronicos bifasicos 220V', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/electronicos/bifasicos-220v/8000va', name: 'Reguladores electronicos bifasicos 8000VA', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/reguladores-voltaje/electronicos/bifasicos-220v/8000va/sola-basic-xellence-xl32-22-280-220-s', name: 'Sola Basic Xellence XL32-22-280-220 S 8000VA', legacyCategory: 'power' },
  { path: 'computo/monitores/gaming/27-fhd/180hz/samsung-odyssey-g3-ls27dg300elxzx', name: 'Samsung Odyssey G3 LS27DG300ELXZX 27 FHD 180Hz', legacyCategory: 'monitors' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/17-pulgadas', name: 'Maletines para laptop 17 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/17-pulgadas/brobotix-oslo-6006757-gris', name: 'BRobotix Oslo 6006757 maletin 17 pulgadas gris', legacyCategory: 'accessories' },
  { path: 'computo/componentes/fuentes-poder/atx-500w/acteck-blazar-basic-ft500b', name: 'Acteck Blazar Basic FT500B ATX 500W', legacyCategory: 'components' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc/panel-firma', name: 'Tarjetas PVC con panel de firma', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/credenciales-identificacion/consumibles/tarjetas-pvc/panel-firma/zebra-104523-118', name: 'Zebra 104523-118 tarjetas PVC panel de firma', legacyCategory: 'accessories' },
  { path: 'energia/supresores-reguladores/supresores-picos/multicontactos/6-contactos', name: 'Multicontactos con supresor de 6 contactos', legacyCategory: 'power' },
  { path: 'energia/supresores-reguladores/supresores-picos/multicontactos/6-contactos/nextep-ne-240', name: 'Nextep NE-240 multicontacto 6 contactos 490J', legacyCategory: 'power' },
  { path: 'computo/componentes/enfriamiento/disipadores-cpu/torre-120mm-argb/tdp-220w', name: 'Disipadores CPU torre 120 mm ARGB TDP 220W', legacyCategory: 'components' },
  { path: 'computo/componentes/enfriamiento/disipadores-cpu/torre-120mm-argb/tdp-220w/balam-rush-heliux-pro-hex55-br-941983', name: 'Balam Rush Heliux Pro HEX55 BR-941983 220W', legacyCategory: 'components' },
  { path: 'redes/radioenlaces-antenas/antenas-parabolicas/5ghz-34dbi', name: 'Antenas parabolicas 5GHz 34dBi', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/antenas-parabolicas/5ghz-34dbi/ubiquiti-rocketdish-rd-5g34', name: 'Ubiquiti RocketDish RD-5G34 34dBi', legacyCategory: 'networking' },
  { path: 'redes/tarjetas-red/pcie/10gbe-dual-rj45', name: 'Tarjetas PCIe dual 10GbE RJ45', legacyCategory: 'networking' },
  { path: 'redes/tarjetas-red/pcie/10gbe-dual-rj45/synology-e10g30-t2', name: 'Synology E10G30-T2 dual 10GbE RJ45', legacyCategory: 'networking' },
  { path: 'computo/servidores/torre/dell-poweredge-t160', name: 'Dell PowerEdge T160 servidores torre', legacyCategory: 'laptops' },
  { path: 'computo/servidores/torre/dell-poweredge-t160/t160-fy26q1e-mx', name: 'Dell PowerEdge T160-FY26Q1E-MX Xeon E-2434', legacyCategory: 'laptops' },
  { path: 'video/proyectores/portatiles/1080p-smart/yaber-t2-plus', name: 'Yaber T2 Plus proyector portatil 1080p smart', legacyCategory: 'tvs' },
  { path: 'video/senalizacion-digital/pantallas-interactivas', name: 'Pantallas interactivas para senalizacion digital', legacyCategory: 'monitors' },
  { path: 'video/senalizacion-digital/pantallas-interactivas/75-uhd-touch', name: 'Pantallas interactivas 75 pulgadas UHD touch', legacyCategory: 'monitors' },
  { path: 'video/senalizacion-digital/pantallas-interactivas/75-uhd-touch/samsung-wa75f-lh75wafwlgcxzx', name: 'Samsung WA75F LH75WAFWLGCXZX 75 UHD touch', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/ultrawide-curvos/34-uwqhd-200hz', name: 'Monitores gaming ultrawide curvos 34 pulgadas UWQHD 200Hz', legacyCategory: 'monitors' },
  { path: 'computo/monitores/gaming/ultrawide-curvos/34-uwqhd-200hz/dahua-dhi-lm34-e330ca', name: 'Dahua DHI-LM34-E330CA monitor curvo 34 UWQHD 200Hz', legacyCategory: 'monitors' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo/8mp-dual-light-microsd-mic', name: 'Camaras IP PoE domo 8MP Dual Light microSD y microfono', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo/8mp-dual-light-microsd-mic/hikvision-ds-2cd1183g2-liuf', name: 'Hikvision DS-2CD1183G2-LIUF domo 8MP Dual Light', legacyCategory: 'cameras' },
  { path: 'computo/almacenamiento/memorias-flash/microsd/64gb-clase-10/uhs-i-u1', name: 'Tarjetas microSD 64GB Clase 10 UHS-I U1', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/microsd/64gb-clase-10/uhs-i-u1/nextep-ne-474s', name: 'Nextep NE-474S microSD 64GB Clase 10 UHS-I U1', legacyCategory: 'storage' },
  { path: 'servicios-ti/soporte-garantias/hpe-tech-care', name: 'HPE Tech Care', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/hpe-tech-care/servidores', name: 'HPE Tech Care para servidores', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/hpe-tech-care/servidores/proliant-dl385-gen10', name: 'HPE Tech Care ProLiant DL385 Gen10', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/hpe-tech-care/servidores/proliant-dl385-gen10/hv6c6e-3y-essential', name: 'HPE HV6C6E Tech Care Essential 3 anos DL385 Gen10', legacyCategory: 'software' },
  { path: 'redes/switches/poe-administrables/gigabit/8-puertos/layer-3-2-sfp-plus', name: 'Switches PoE administrables Layer 3 8 Gigabit y 2 SFP+', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables/gigabit/8-puertos/layer-3-2-sfp-plus/grandstream-gwn7811p', name: 'Grandstream GWN7811P Layer 3 PoE 8 Gigabit 2 SFP+', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables/gigabit/24-puertos-2-sfp-370w', name: 'Switches PoE no administrables 24 Gigabit 2 SFP 370W', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables/gigabit/24-puertos-2-sfp-370w/intellinet-561907', name: 'Intellinet 561907 PoE 24 Gigabit 2 SFP 370W', legacyCategory: 'networking' },
  { path: 'computo/tabletas/accesorios/fundas-con-teclado/universales-10-pulgadas', name: 'Fundas con teclado universales para tablet 10 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/tabletas/accesorios/fundas-con-teclado/universales-10-pulgadas/brobotix-102760g', name: 'BRobotix 102760G funda universal 10 pulgadas con teclado', legacyCategory: 'accessories' },
  { path: 'computo/almacenamiento/memorias-flash/usb/64gb/usb-3-2-gen-1-giratorias', name: 'Memorias USB 64GB USB 3.2 Gen 1 giratorias', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb/64gb/usb-3-2-gen-1-giratorias/kingston-datatraveler-exodia-s-dtxs-64gb', name: 'Kingston DataTraveler Exodia S DTXS/64GB', legacyCategory: 'storage' },
  { path: 'redes/transceptores-convertidores/cables-dac', name: 'Cables DAC direct attach copper', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/cables-dac/sfp56', name: 'Cables DAC SFP56', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/cables-dac/sfp56/50g-3m', name: 'Cables DAC SFP56 50G 3m', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores/cables-dac/sfp56/50g-3m/hpe-aruba-r0m47a', name: 'HPE Aruba R0M47A DAC SFP56 50G 3m', legacyCategory: 'networking' },
  { path: 'impresion/consumibles/toner-laser/lexmark/708hy', name: 'Toner Lexmark 708HY', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/toner-laser/lexmark/708hy/70c8hy0-amarillo', name: 'Lexmark 70C8HY0 708HY amarillo 3000 paginas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/multifuncionales-laser/monocromaticas/a4-wifi', name: 'Multifuncionales laser monocromaticas A4 Wi-Fi', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/multifuncionales-laser/monocromaticas/a4-wifi/xerox-b105-bi', name: 'Xerox B105_BI multifuncional laser monocromatica Wi-Fi', legacyCategory: 'printers_scanners' },
  { path: 'gaming/consolas/accesorios', name: 'Accesorios para consolas', legacyCategory: 'accessories' },
  { path: 'gaming/consolas/accesorios/cargadores-controles', name: 'Cargadores para controles de consola', legacyCategory: 'accessories' },
  { path: 'gaming/consolas/accesorios/cargadores-controles/xbox-one', name: 'Cargadores para controles Xbox One', legacyCategory: 'accessories' },
  { path: 'gaming/consolas/accesorios/cargadores-controles/xbox-one/immortal-imgxbc3', name: 'Immortal IMGXBC3 cargador dual Xbox One', legacyCategory: 'accessories' },
  { path: 'energia/no-breaks-ups/doble-conversion/trifasicos/40000va', name: 'UPS online trifasicos doble conversion 40000VA', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/doble-conversion/trifasicos/40000va/complet-ups-mar-40', name: 'Complet UPS-MAR-40 UPS online trifasico 40kVA', legacyCategory: 'power' },
  { path: 'accesorios/cables-adaptadores/usb/usb-c-c/1m/100w', name: 'Cables USB-C a USB-C 1m 100W', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/usb/usb-c-c/1m/100w/adata-cacc-100pn-bk', name: 'ADATA CACC-100PN-BK cable USB-C 100W 1m', legacyCategory: 'accessories' },
  { path: 'redes/poe', name: 'Power over Ethernet', legacyCategory: 'networking' },
  { path: 'redes/poe/extensores', name: 'Extensores PoE', legacyCategory: 'networking' },
  { path: 'redes/poe/extensores/gigabit', name: 'Extensores PoE Gigabit', legacyCategory: 'networking' },
  { path: 'redes/poe/extensores/gigabit/exterior-ip65', name: 'Extensores PoE Gigabit exterior IP65', legacyCategory: 'networking' },
  { path: 'redes/poe/extensores/gigabit/exterior-ip65/intellinet-561211', name: 'Intellinet 561211 extensor PoE Gigabit IP65', legacyCategory: 'networking' },
  { path: 'computo/accesorios/baterias-laptop', name: 'Baterias para laptop', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/baterias-laptop/apple', name: 'Baterias para laptops Apple', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/baterias-laptop/apple/macbook-pro-15-a1707', name: 'Baterias para MacBook Pro 15 A1707', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/baterias-laptop/apple/macbook-pro-15-a1707/ovaltech-ota1820', name: 'OvalTech OTA1820 bateria para MacBook Pro 15 A1707', legacyCategory: 'accessories' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1700/h610', name: 'Tarjetas madre Intel LGA1700 H610', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1700/h610/ddr4-micro-atx', name: 'Tarjetas madre H610 DDR4 micro ATX', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1700/h610/ddr4-micro-atx/asus-prime-h610m-k-d4-csm', name: 'ASUS PRIME H610M-K D4-CSM tarjeta madre H610 DDR4', legacyCategory: 'components' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/192v', name: 'Bancos de baterias rack torre 192V', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/bancos-baterias/rack-torre/192v/apc-srt192bp', name: 'APC SRT192BP banco de baterias externo 192V', legacyCategory: 'power' },
  { path: 'accesorios/cables-adaptadores/video-vga/hd15-1-8m/tripp-lite-p512-006', name: 'Tripp Lite P512-006 cable VGA HD15 1.83m', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/inalambricos', name: 'Lectores de codigo de barras inalambricos', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/inalambricos/2d', name: 'Lectores inalambricos de codigo de barras 2D', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/inalambricos/2d/honeywell-xenon-xp-1952g-bf', name: 'Honeywell Xenon XP 1952G-BF lector 2D sin bateria', legacyCategory: 'accessories' },
  { path: 'computo/monitores/profesionales/27-qhd-usb-c-65w', name: 'Monitores profesionales 27 QHD USB-C 65W', legacyCategory: 'monitors' },
  { path: 'computo/monitores/profesionales/27-qhd-usb-c-65w/dahua-dhi-lm27-p301a', name: 'Dahua DHI-LM27-P301A monitor 27 QHD USB-C 65W', legacyCategory: 'monitors' },
  { path: 'oficina/equipo-oficina/perforadoras/1-orificio-6mm', name: 'Perforadoras de oficina 1 orificio 6mm', legacyCategory: 'accessories' },
  { path: 'oficina/equipo-oficina/perforadoras/1-orificio-6mm/nextep-ne-128', name: 'Nextep NE-128 perforadora 1 orificio 6mm', legacyCategory: 'accessories' },
  { path: 'telefonia/smartphones/apple', name: 'Smartphones Apple', legacyCategory: 'smartphones' },
  { path: 'telefonia/smartphones/apple/iphone', name: 'Apple iPhone', legacyCategory: 'smartphones' },
  { path: 'telefonia/smartphones/apple/iphone/iphone-14-pro-max', name: 'iPhone 14 Pro Max', legacyCategory: 'smartphones' },
  { path: 'telefonia/smartphones/apple/iphone/iphone-14-pro-max/128gb-esim-plata-rfb', name: 'iPhone 14 Pro Max 128GB eSIM plata RFB', legacyCategory: 'smartphones' },
  { path: 'telefonia/smartphones/apple/iphone/iphone-14-pro-max/128gb-esim-plata-rfb/iph14pm128-pl', name: 'Apple IPH14PM128/PL iPhone 14 Pro Max 128GB plata RFB', legacyCategory: 'smartphones' },
  { path: 'computo/tabletas/android/8-pulgadas/2gb-32gb', name: 'Tabletas Android 8 pulgadas 2GB 32GB', legacyCategory: 'tablets' },
  { path: 'computo/tabletas/android/8-pulgadas/2gb-32gb/stylos-stta81a', name: 'Stylos STTA81A Taris V2 8 pulgadas azul', legacyCategory: 'tablets' },
  { path: 'oficina/papeleria/sobres/acolchados-burbuja', name: 'Sobres acolchados con burbuja', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/acolchados-burbuja/no-5-10-5x16-paquete-25', name: 'Sobres burbuja No. 5 10.5 x 16 paquete 25', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/acolchados-burbuja/no-5-10-5x16-paquete-25/nextep-ne-017n', name: 'Nextep NE-017N sobre burbuja No. 5 paquete 25', legacyCategory: 'accessories' },
  { path: 'computo/componentes/gabinetes/gaming/atx-mid-tower/cubo-cristal-argb/ocelot-a-cube-1', name: 'Ocelot Gaming A-CUBE 1 gabinete cubo cristal ARGB', legacyCategory: 'components' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/full-size-rgb/switch-rojo', name: 'Teclados mecanicos gaming full-size RGB switch rojo', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/full-size-rgb/switch-rojo/yeyian-asward-ytm-28207r', name: 'Yeyian Asward YTM-28207R switch rojo RGB', legacyCategory: 'gaming' },
  { path: 'telefonia/smartphones/apple/iphone/iphone-13-pro-max', name: 'iPhone 13 Pro Max', legacyCategory: 'smartphones' },
  { path: 'telefonia/smartphones/apple/iphone/iphone-13-pro-max/256gb-verde-rfb', name: 'iPhone 13 Pro Max 256GB verde RFB', legacyCategory: 'smartphones' },
  { path: 'telefonia/smartphones/apple/iphone/iphone-13-pro-max/256gb-verde-rfb/iph13pm256-vd', name: 'Apple IPH13PM256/VD iPhone 13 Pro Max 256GB verde RFB', legacyCategory: 'smartphones' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/inalambricos-full-size-rgb', name: 'Teclados mecanicos gaming inalambricos full-size RGB', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/inalambricos-full-size-rgb/balam-rush-dominate-gk979i-br-940382', name: 'Balam Rush Dominate Expert GK979I BR-940382', legacyCategory: 'gaming' },
  { path: 'redes/access-points/wifi-6/wall-plate', name: 'Access points Wi-Fi 6 wall plate', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-6/wall-plate/cambium-xv2-22h0a00-rw', name: 'Cambium cnPilot XV2-22H0A00-RW wall plate', legacyCategory: 'networking' },
  { path: 'audio/audifonos/bluetooth/tws/in-ear/acteck-boost-plus-ep425', name: 'Acteck Boost Plus EP425 audifonos TWS in-ear', legacyCategory: 'headphones' },
  { path: 'gaming/mobiliario/sillas-gamer/pvc', name: 'Sillas gamer de PVC', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/pvc/reclinables-110kg', name: 'Sillas gamer PVC reclinables hasta 110 kg', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/pvc/reclinables-110kg/xzeal-xz05r-roja', name: 'Xzeal XZ05R silla gamer roja 110 kg', legacyCategory: 'gaming' },
];
