export const MANUAL_CATEGORY_TREE_CYCLE003_PART003 = [
  { path: 'computo/accesorios/soportes-monitor/vesa/adaptadores-apple/mr3c2zma', name: 'Apple MR3C2ZM/A adaptador VESA iMac Pro', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/stylus-tablets/apple-pencil/pro', name: 'Apple Pencil Pro', legacyCategory: 'accessories' },
  { path: 'servicios-ti/soporte-garantias/apple', name: 'Soporte y garantias Apple', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus', name: 'AppleCare+', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad', name: 'AppleCare+ para iPad', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-air-11-m4', name: 'AppleCare+ iPad Air 11 M4', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-11-a16', name: 'AppleCare+ iPad 11 A16', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-air-11-m3', name: 'AppleCare+ iPad Air 11 M3', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/ipad/ipad-pro-11-m5', name: 'AppleCare+ iPad Pro 11 M5', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/mac', name: 'AppleCare+ para Mac', legacyCategory: 'software' },
  { path: 'servicios-ti/soporte-garantias/apple/applecare-plus/mac/imac-24-m4', name: 'AppleCare+ iMac 24 M4', legacyCategory: 'software' },
  { path: 'gaming/accesorios/controles-gamepad/bluetooth-usb-c/asus-rog-raikiri-pro', name: 'ASUS ROG Raikiri Pro', legacyCategory: 'gaming' },
  { path: 'computo/accesorios/mousepads/gaming-xl/speed-control/asus-rog-sheath', name: 'ASUS ROG Sheath XL', legacyCategory: 'accessories' },
  { path: 'software/cad-diseno/autodesk-autocad-lt', name: 'Autodesk AutoCAD LT', legacyCategory: 'software' },
  { path: 'software/cad-diseno/autodesk-autocad-lt/3y-1usuario-eld', name: 'AutoCAD LT 3 anos 1 usuario ELD', legacyCategory: 'software' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp', name: 'Tarjetas SNMP para UPS', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/accesorios/tarjetas-comunicacion/snmp/cdp-uposnmp-db9', name: 'CDP UPOSNMP-DB9 tarjeta externa SNMP', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos', name: 'Conectores electricos', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos/nema', name: 'Conectores electricos NEMA', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos/nema/l5-30r', name: 'Conectores NEMA L5-30R', legacyCategory: 'power' },
  { path: 'energia/conectores-electricos/nema/l5-30r/datashield-mi-4100', name: 'DataShield MI-4100 NEMA L5-30R', legacyCategory: 'power' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc', name: 'Kits de mantenimiento para PC', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc/manhattan-400077-13p', name: 'Manhattan 400077 13 piezas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc/manhattan-530071-17p', name: 'Manhattan 530071 17 piezas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-mantenimiento-pc/manhattan-530217-145p', name: 'Manhattan 530217 145 piezas', legacyCategory: 'accessories' },
  { path: 'video/accesorios-av/splitters-vga', name: 'Splitters y divisores VGA', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/splitters-vga/1x4', name: 'Splitters VGA 1 entrada 4 salidas', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/splitters-vga/1x4/manhattan-207348', name: 'Manhattan 207348 splitter VGA 1x4', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/extensores-vga', name: 'Extensores VGA', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/extensores-vga/audio-cat5e-cat6', name: 'Extensores VGA con audio por Cat5e/Cat6', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/extensores-vga/audio-cat5e-cat6/manhattan-177344', name: 'Manhattan 177344 extensor VGA audio', legacyCategory: 'tvs' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/15-4', name: 'Maletines para laptop 15.4 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/15-4/manhattan-times-square-421430', name: 'Manhattan Times Square 421430', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/papel-plotter/mate', name: 'Papel mate para plotter', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/mate/doubleweight', name: 'Epson Doubleweight Matte Paper', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/mate/doubleweight/rollos-24in-82ft', name: 'Rollos Doubleweight Matte 24 x 82 pies', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-plotter/mate/doubleweight/rollos-24in-82ft/epson-s041385', name: 'Epson S041385 Doubleweight Matte 24 x 82', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico', name: 'Papel fotografico', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico/luster', name: 'Papel fotografico luster', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico/luster/carta-50-hojas', name: 'Papel luster carta 50 hojas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/papel-fotografico/luster/carta-50-hojas/epson-s041405', name: 'Epson S041405 Ultra Premium Luster carta', legacyCategory: 'printers_scanners' },
];
