export const MANUAL_CATEGORY_TREE_CYCLE003_PART004 = [
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos', name: 'Marcadores Azor Signal punto fino surtidos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos/5-piezas', name: 'Azor Signal punto fino surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos/5-piezas/azor-signal-30653', name: 'Azor Signal 30653 surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro', name: 'Azor Pin Point cuerpo transparente negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro/12-piezas', name: 'Azor Pin Point 6830NE negro 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro/12-piezas/azor-pinpoint-6830ne', name: 'Azor Pin Point 6830NE negro 1.0 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe', name: 'Marcadores Azor Signal punto fino cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe/12-piezas', name: 'Azor Signal 30007 cafe 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe/12-piezas/azor-signal-30007', name: 'Azor Signal Fino 30007 cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta', name: 'Marcadores base agua doble punta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta/12-colores', name: 'Marcadores base agua doble punta 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta/12-colores/azor-aquarelo-duo-29412', name: 'Azor Aquarelo Duo 29412 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul', name: 'Marcadores Azor Signal Xtra azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul/12-piezas', name: 'Azor Signal Xtra azul 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul/12-piezas/azor-signal-xtra-40003', name: 'Azor Signal Xtra 40003 azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo', name: 'Marcadores Azor Signal Xtra rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo/12-piezas', name: 'Azor Signal Xtra rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo/12-piezas/azor-signal-xtra-40002', name: 'Azor Signal Xtra 40002 rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo', name: 'Marcadores Azor Signal punto fino amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo/12-piezas', name: 'Azor Signal 30005 amarillo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo/12-piezas/azor-signal-30005', name: 'Azor Signal Fino 30005 amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta', name: 'Marcadores Azor Signal punto fino violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta/12-piezas', name: 'Azor Signal 30008 violeta 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta/12-piezas/azor-signal-30008', name: 'Azor Signal Fino 30008 violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul', name: 'Uni-ball Deluxe roller azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul/blister-1-pieza', name: 'Uni-ball Deluxe azul blister 1 pieza', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul/blister-1-pieza/azor-ub155az1', name: 'Uni-ball Deluxe UB155AZ1 azul 0.5 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/broches-archivo/7cm', name: 'Broches para archivo 7 cm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/broches-archivo/7cm/baco-b072-50-piezas', name: 'Baco B-072 broche archivo 7 cm 50 piezas', legacyCategory: 'accessories' },
];
