export const MANUAL_CATEGORY_TREE_RECENT = [
  { path: 'computo/desktops/mini-pc/dell-pro-micro', name: 'Dell Pro Micro compactas', legacyCategory: 'laptops' },
  { path: 'telefonia/telefonos-ip/escritorio/1-cuenta-sip', name: 'Telefonos IP de escritorio 1 cuenta SIP', legacyCategory: 'networking' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior/1080p', name: 'Camaras IP WiFi interiores 1080p', legacyCategory: 'cameras' },
  { path: 'computo/monitores/oficina/32-qhd-usb-c', name: 'Monitores de oficina 32 pulgadas QHD USB-C', legacyCategory: 'monitors' },
  { path: 'seguridad/cctv/camaras-analogicas/turret', name: 'Camaras analogicas turret', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-analogicas/turret/2mp-ir', name: 'Camaras analogicas turret 2MP IR', legacyCategory: 'cameras' },
  { path: 'computo/tabletas/accesorios/fundas-uso-rudo/lenovo-tab-k10-11', name: 'Fundas uso rudo Lenovo Tab K10 11 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/componentes/tarjetas-madre/amd-am4/b550m-wifi-ac', name: 'Tarjetas madre AMD AM4 B550M con WiFi AC', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1200', name: 'Tarjetas madre Intel LGA1200', legacyCategory: 'components' },
  { path: 'computo/componentes/tarjetas-madre/intel-lga1200/h510m', name: 'Tarjetas madre Intel LGA1200 H510M', legacyCategory: 'components' },
  { path: 'seguridad/cctv/camaras-ip-poe/ptz/4mp-16x-lighthunter', name: 'Camaras IP PoE PTZ 4MP 16x LightHunter', legacyCategory: 'cameras' },
  { path: 'computo/componentes/fuentes-poder/atx-80-plus-gold/1000w', name: 'Fuentes ATX 80 Plus Gold 1000W', legacyCategory: 'components' },
  { path: 'software/productividad-oficina/microsoft-365/business-standard', name: 'Microsoft 365 Business Standard', legacyCategory: 'software' },
  { path: 'computo/accesorios/mochilas-fundas/mochilas-laptop/17-pulgadas', name: 'Mochilas para laptop hasta 17 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/full-size-rgb', name: 'Teclados gaming mecanicos full-size RGB', legacyCategory: 'gaming' },
  { path: 'seguridad/cctv/dvr-nvr/xvr-pentahibrido/4-canales-1080p-lite', name: 'XVR pentahibridos 4 canales 1080P Lite', legacyCategory: 'cameras' },
  { path: 'computo/accesorios/filtros-privacidad', name: 'Filtros de privacidad para computo', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/filtros-privacidad/monitores', name: 'Filtros de privacidad para monitores', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/filtros-privacidad/monitores/23-8-16-9', name: 'Filtros de privacidad para monitor 23.8 pulgadas 16:9', legacyCategory: 'accessories' },
  { path: 'video/proyectores/dlp/wxga-3000-lumenes', name: 'Proyectores DLP WXGA 3000 lumenes', legacyCategory: 'tvs' },
  { path: 'energia/no-breaks-ups/line-interactive/rack-torre/1500va', name: 'UPS line-interactive rack torre 1500VA', legacyCategory: 'power' },
  { path: 'computo/almacenamiento/memorias-flash/microsd/32gb-clase-10', name: 'Tarjetas microSD 32GB Clase 10', legacyCategory: 'storage' },
  { path: 'computo/componentes/cables-internos/alimentacion-sata/molex-a-doble-sata', name: 'Cables Molex a doble SATA de alimentacion interna', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/coples', name: 'Coples y uniones HDMI', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/coples/hembra-hembra', name: 'Coples HDMI hembra a hembra', legacyCategory: 'accessories' },
  { path: 'software/seguridad/antivirus/bitdefender-internet-security', name: 'Bitdefender Internet Security', legacyCategory: 'software' },
  { path: 'software/seguridad/antivirus/bitdefender-internet-security/1-usuario-1-ano', name: 'Bitdefender Internet Security 1 usuario 1 ano', legacyCategory: 'software' },
  { path: 'computo/accesorios/mochilas-fundas/fundas-laptop/14-pulgadas', name: 'Fundas para laptop 14 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/fundas-laptop/14-pulgadas/neopreno', name: 'Fundas de neopreno para laptop 14 pulgadas', legacyCategory: 'accessories' },
  { path: 'redes/access-points/wifi-6/exterior', name: 'Access points Wi-Fi 6 de exterior', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-6/exterior/ax3600', name: 'Access points Wi-Fi 6 exterior AX3600', legacyCategory: 'networking' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-227', name: 'Toner Brother TN-227', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-227/negro', name: 'Toner Brother TN-227 negro', legacyCategory: 'printers_scanners' },
  { path: 'energia/no-breaks-ups/line-interactive/2000va', name: 'UPS line-interactive 2000VA', legacyCategory: 'power' },
  { path: 'redes/cableado-estructurado/patch-cords/cat6/5m', name: 'Patch cords Cat6 de 5 m', legacyCategory: 'networking' },
  { path: 'energia/cargadores-inalambricos/3-en-1', name: 'Cargadores inalambricos 3 en 1', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-810xlbk', name: 'Toner Brother TN-810XLBK negro', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/cctv/accesorios-cableado/cables-camaras-moviles', name: 'Cables para camaras moviles CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado/cables-camaras-moviles/streamax-m4pin', name: 'Cables Streamax M4PIN para camaras moviles', legacyCategory: 'cameras' },
  { path: 'computo/accesorios/herramientas-reparacion', name: 'Herramientas de reparacion para computo', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/herramientas-reparacion/kits-laptop-celular', name: 'Kits de herramientas para laptop y celular', legacyCategory: 'accessories' },
  { path: 'redes/cableado-estructurado/bobinas-utp/cat5e/cca-305m', name: 'Bobinas UTP Cat5e CCA de 305 m', legacyCategory: 'networking' },
  { path: 'computo/componentes/gabinetes/atx-mid-tower/fuente-500w', name: 'Gabinetes ATX mid tower con fuente 500W', legacyCategory: 'components' },
  { path: 'computo/perifericos/teclados/gaming/membrana-rainbow', name: 'Teclados gamer de membrana con iluminacion rainbow', legacyCategory: 'gaming' },
  { path: 'audio/bocinas/portatiles-karaoke/doble-8-pulgadas', name: 'Bafles karaoke portatiles doble 8 pulgadas', legacyCategory: 'headphones' },
  { path: 'computo/accesorios/limpieza/alcohol-isopropilico/250ml', name: 'Alcohol isopropilico para electronica 250 ml', legacyCategory: 'laptops' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/llave/nano', name: 'Candados de seguridad nano para laptop con llave', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/900va', name: 'UPS line-interactive 900VA', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/line-interactive/900va/lcd', name: 'UPS line-interactive 900VA con LCD', legacyCategory: 'power' },
  { path: 'computo/almacenamiento/ssd/2-5-sata/240gb', name: 'SSD 2.5 SATA de 240GB', legacyCategory: 'storage' },
  { path: 'computo/servidores/torre/hpe-proliant-ml30', name: 'Servidores torre HPE ProLiant ML30', legacyCategory: 'laptops' },
  { path: 'software/licencias/aspel-sae/actualizacion-base', name: 'Actualizaciones base Aspel SAE', legacyCategory: 'software' },
  { path: 'audio/bocinas/inteligentes', name: 'Bocinas inteligentes', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/inteligentes/alexa', name: 'Bocinas inteligentes con Alexa', legacyCategory: 'headphones' },
  { path: 'telefonia/telefonos-ip/accesorios', name: 'Accesorios para telefonos IP', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/accesorios/fuentes-poder', name: 'Fuentes de poder para telefonos IP', legacyCategory: 'networking' },
  { path: 'impresion/consumibles/cintas-tarjetas/evolis', name: 'Cintas Evolis para impresoras de tarjetas', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cintas-tarjetas/evolis/monocromas-negras', name: 'Cintas Evolis monocromaticas negras', legacyCategory: 'printers_scanners' },
  { path: 'computo/perifericos/bocinas-audio/gaming', name: 'Bocinas gamer para PC', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/bocinas-audio/gaming/2-0-rgb', name: 'Bocinas gamer 2.0 RGB', legacyCategory: 'headphones' },
  { path: 'gaming/accesorios/iluminacion', name: 'Iluminacion para setup gamer', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios/iluminacion/torres-rgb', name: 'Torres LED RGB para setup gamer', legacyCategory: 'gaming' },
  { path: 'computo/laptops/workstations', name: 'Workstations moviles', legacyCategory: 'laptops' },
  { path: 'computo/laptops/workstations/16-pulgadas', name: 'Workstations moviles de 16 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/laptops/workstations/16-pulgadas/lenovo-thinkpad-p16', name: 'Lenovo ThinkPad P16 workstations de 16 pulgadas', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-c-c/2m', name: 'Cables USB-C a USB-C de 2 m', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/toner-laser/xerox/006r04845', name: 'Toner Xerox 006R04845 negro', legacyCategory: 'printers_scanners' },
  { path: 'computo/accesorios/mousepads/basicos-antiderrapantes', name: 'Mousepads basicos antiderrapantes', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/webcams/usb-2k/bocina-dual', name: 'Webcams USB 2K con bocina dual', legacyCategory: 'cameras' },
  { path: 'telefonia/telefonos-ip/escritorio', name: 'Telefonos IP de escritorio', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/escritorio/2-lineas', name: 'Telefonos IP de escritorio 2 lineas', legacyCategory: 'networking' },
  { path: 'computo/almacenamiento/ssd/externos/usb-3', name: 'SSD externos USB 3.0', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/ssd/externos/usb-3/1tb', name: 'SSD externos USB 3.0 de 1TB', legacyCategory: 'storage' },
  { path: 'video/soportes-tv/pared/articulados-13-43-20kg', name: 'Soportes articulados de pared para TV 13 a 43 pulgadas 20 kg', legacyCategory: 'tvs' },
  { path: 'computo/accesorios/baterias-laptop/hp/oa04', name: 'Baterias para laptop HP OA04', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-433/cian', name: 'Toner Brother TN-433 cian', legacyCategory: 'printers_scanners' },
  { path: 'redes/adaptadores-wifi/usb/n300-alta-ganancia', name: 'Adaptadores Wi-Fi USB N300 de alta ganancia', legacyCategory: 'networking' },
  { path: 'computo/componentes/memoria-ram/udimm-ddr4/16gb-3200', name: 'Memoria RAM UDIMM DDR4 16GB 3200MHz', legacyCategory: 'components' },
  { path: 'computo/componentes/gabinetes/gaming/atx-mid-tower/frente-madera', name: 'Gabinetes gamer ATX mid tower con frente tipo madera', legacyCategory: 'components' },
  { path: 'computo/componentes/gabinetes/gaming/atx-mid-tower/panoramicos', name: 'Gabinetes gamer ATX mid tower panoramicos', legacyCategory: 'components' },
  { path: 'video/proyectores/dlp', name: 'Proyectores DLP', legacyCategory: 'tvs' },
  { path: 'video/proyectores/dlp/svga-4000-lumenes', name: 'Proyectores DLP SVGA 4000 lumenes', legacyCategory: 'tvs' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-830xl', name: 'Toner Brother TN-830XL negro', legacyCategory: 'printers_scanners' },
  { path: 'energia/baterias-ups/selladas-12v/5ah', name: 'Baterias selladas 12V 5Ah para UPS', legacyCategory: 'power' },
  { path: 'impresion/consumibles/etiquetas-papel/brother-dk', name: 'Etiquetas Brother DK para impresoras QL', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/etiquetas-papel/brother-dk/29x90mm', name: 'Etiquetas Brother DK 29 x 90 mm', legacyCategory: 'printers_scanners' },
  { path: 'redes/radioenlaces-antenas/accesorios-montaje', name: 'Accesorios de montaje para radioenlaces y antenas', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas/accesorios-montaje/soportes-antena', name: 'Soportes de montaje para antenas', legacyCategory: 'networking' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo/4mp-smart-hybrid-light', name: 'Camaras IP PoE domo 4MP Smart Hybrid Light', legacyCategory: 'cameras' },
  { path: 'computo/monitores/oficina/27-fhd-120hz', name: 'Monitores FHD de 27 pulgadas 120Hz', legacyCategory: 'monitors' },
  { path: 'computo/componentes/gabinetes/gaming/micro-atx', name: 'Gabinetes gamer Micro-ATX', legacyCategory: 'components' },
  { path: 'punto-de-venta/impresoras-recibos/80mm-usb-serial', name: 'Impresoras POS termicas 80 mm USB serial', legacyCategory: 'printers_scanners' },
  { path: 'impresion/impresoras/multifuncionales-laser/monocromaticas/hp-laserjet-tank', name: 'Multifuncionales laser monocromaticas HP LaserJet Tank', legacyCategory: 'printers_scanners' },
  { path: 'video/televisores/led-tizen/43-4k', name: 'Televisores LED Tizen 43 pulgadas 4K', legacyCategory: 'tvs' },
  { path: 'punto-de-venta/impresoras-recibos/80mm-usb-serial-ethernet', name: 'Impresoras POS termicas 80 mm USB serial Ethernet', legacyCategory: 'printers_scanners' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/4-5m', name: 'Cables HDMI alta velocidad 4.5 m', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/video-hdmi-vga/audio', name: 'Adaptadores HDMI a VGA con audio', legacyCategory: 'accessories' },
  { path: 'impresion/consumibles/toner-laser/kyocera/tk-5197m-magenta', name: 'Toner Kyocera TK-5197M magenta', legacyCategory: 'printers_scanners' },
  { path: 'accesorios/cables-adaptadores/video-vga/hd15-1-5m', name: 'Cables VGA HD15 de 1.5 m', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/cargadores-laptop/compatibles-dell', name: 'Cargadores compatibles para laptops Dell', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/cargadores-laptop/compatibles-dell/45w-19-5v-4-5x3-0', name: 'Cargadores Dell 45W 19.5V punta 4.5 x 3.0 mm', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/standby', name: 'UPS standby', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/standby/650va', name: 'UPS standby de 650VA', legacyCategory: 'power' },
  { path: 'computo/componentes/gabinetes/gaming/atx-mid-tower', name: 'Gabinetes gamer ATX mid tower', legacyCategory: 'components' },
  { path: 'computo/monitores/oficina/24-fhd-100hz/usb-c-hub', name: 'Monitores FHD 24 pulgadas 100Hz con hub USB-C', legacyCategory: 'monitors' },
  { path: 'seguridad/cctv/dvr-nvr/xvr-pentahibrido/8-canales-1080p-lite', name: 'XVR pentahibridos 8 canales 1080P Lite', legacyCategory: 'cameras' },
  { path: 'energia/supresores-reguladores/supresores-picos/multicontactos/usb-c-10-contactos', name: 'Multicontactos con supresor USB-C de 10 contactos', legacyCategory: 'power' },
  { path: 'punto-de-venta/terminales-accesorios/soportes-tablet/antirrobo-pared', name: 'Soportes de pared antirrobo para tablet POS', legacyCategory: 'accessories' },
  { path: 'computo/almacenamiento/ssd/externos', name: 'SSD externos', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/ssd/externos/usb-c', name: 'SSD externos USB-C', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/ssd/externos/usb-c/1tb', name: 'SSD externos USB-C de 1TB', legacyCategory: 'storage' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/6mp-dual-light', name: 'Camaras IP PoE turret 6MP dual light', legacyCategory: 'cameras' },
  { path: 'redes/switches/poe-no-administrables/fast-ethernet/10-puertos', name: 'Switches PoE Fast Ethernet no administrables de 10 puertos', legacyCategory: 'networking' },
  { path: 'redes/extensores-wifi/dual-band/ac1200', name: 'Extensores Wi-Fi dual band AC1200', legacyCategory: 'networking' },
  { path: 'seguridad/cctv/accesorios-montaje', name: 'Accesorios de montaje CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-montaje/soportes-pared', name: 'Soportes de pared para camaras CCTV', legacyCategory: 'cameras' },
  { path: 'computo/servidores/rack/1u', name: 'Servidores rack 1U', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/multifuncionales-laser/monocromaticas', name: 'Multifuncionales laser monocromaticas', legacyCategory: 'printers_scanners' },
  { path: 'audio/audifonos/bluetooth/diadema-on-ear', name: 'Audifonos Bluetooth de diadema on-ear', legacyCategory: 'headphones' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-inalambricos', name: 'Lectores inalambricos 2D QR de codigo de barras', legacyCategory: 'laptops' },
  { path: 'redes/switches/poe-administrables/gigabit/16-puertos', name: 'Switches PoE Gigabit administrables de 16 puertos', legacyCategory: 'networking' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/anclas-k-slot', name: 'Anclas adhesivas K-Slot para candados de laptop', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/line-interactive/rack-torre', name: 'UPS line-interactive rack torre', legacyCategory: 'power' },
  { path: 'energia/no-breaks-ups/line-interactive/rack-torre/750va-senoidal', name: 'UPS line-interactive rack torre 750VA senoidal', legacyCategory: 'power' },
  { path: 'impresion/consumibles/toner-laser/kyocera/tk-5372m-magenta', name: 'Toner Kyocera TK-5372M magenta', legacyCategory: 'printers_scanners' },
  { path: 'accesorios/cables-adaptadores/usb', name: 'Cables y adaptadores USB', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-c', name: 'Cables USB-A a USB-C', legacyCategory: 'accessories' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-c/1m', name: 'Cables USB-A a USB-C de 1 m', legacyCategory: 'accessories' },
  { path: 'computo/laptops/consumo/14-pulgadas', name: 'Laptops de consumo de 14 pulgadas', legacyCategory: 'laptops' },
  { path: 'computo/laptops/consumo/14-pulgadas/hyundai-hybook', name: 'Laptops Hyundai HYbook de 14 pulgadas', legacyCategory: 'laptops' },
  { path: 'video/soportes-tv/piso-tripode', name: 'Soportes de piso tipo tripode para TV', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/piso-tripode/45-65-32kg', name: 'Soportes tripode para TV 45 a 65 pulgadas hasta 32 kg', legacyCategory: 'tvs' },
  { path: 'seguridad/alarmas', name: 'Alarmas y sensores de seguridad', legacyCategory: 'security' },
  { path: 'seguridad/alarmas/accesorios', name: 'Accesorios para alarmas', legacyCategory: 'security' },
  { path: 'seguridad/alarmas/accesorios/repetidores-inalambricos', name: 'Repetidores inalambricos para alarmas', legacyCategory: 'security' },
  { path: 'seguridad/cctv/accesorios-cableado/baluns-video/hdcvi-4k', name: 'Baluns HDCVI 4K', legacyCategory: 'cameras' },
  { path: 'computo/almacenamiento/discos-duros/3-5-sata', name: 'Discos duros 3.5 SATA', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/discos-duros/3-5-sata/vigilancia', name: 'Discos duros 3.5 SATA para videovigilancia', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/discos-duros/3-5-sata/vigilancia/8tb', name: 'Discos duros de vigilancia 8TB 3.5 SATA', legacyCategory: 'storage' },
  { path: 'video/televisores/qled-google-tv/43-fhd', name: 'Televisores QLED Google TV 43 pulgadas Full HD', legacyCategory: 'tvs' },
  { path: 'gaming/mobiliario/sillas-gamer/malla', name: 'Sillas gamer con respaldo de malla', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/malla/140kg', name: 'Sillas gamer de malla hasta 140 kg', legacyCategory: 'gaming' },
  { path: 'impresion/consumibles/cintas-etiquetas/brother-tze', name: 'Cintas Brother TZe para rotuladores P-touch', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cintas-etiquetas/brother-tze/flexible-id', name: 'Cintas Brother TZe Flexible ID', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/cintas-etiquetas/brother-tze/flexible-id/12mm', name: 'Cintas Brother TZe Flexible ID de 12 mm', legacyCategory: 'printers_scanners' },
  { path: 'seguridad/cctv/dvr-nvr/xvr-hdcvi/16-canales-wizsense', name: 'XVR HDCVI WizSense de 16 canales', legacyCategory: 'cameras' },
  { path: 'computo/tabletas/accesorios/fundas/ipad-a16-11', name: 'Fundas para iPad A16 11 pulgadas', legacyCategory: 'accessories' },
  { path: 'computo/tabletas/accesorios/fundas-con-teclado/ipad-10-2', name: 'Fundas con teclado para iPad 10.2 pulgadas', legacyCategory: 'accessories' },
  { path: 'seguridad/cctv/camaras-moviles/ahd-box', name: 'Camaras moviles AHD tipo box', legacyCategory: 'security' },
  { path: 'seguridad/cctv/camaras-moviles/ahd-box/2mp-ir', name: 'Camaras moviles AHD box 2MP con IR', legacyCategory: 'security' },
  { path: 'redes/access-points/wifi-6/techo', name: 'Access points WiFi 6 de techo', legacyCategory: 'networking' },
  { path: 'redes/access-points/wifi-6/techo/ax1800', name: 'Access points WiFi 6 de techo AX1800', legacyCategory: 'networking' },
  { path: 'video/proyectores/portatiles', name: 'Proyectores portatiles', legacyCategory: 'monitors' },
  { path: 'video/proyectores/portatiles/1080p-smart', name: 'Proyectores portatiles 1080p smart', legacyCategory: 'monitors' },
  { path: 'computo/componentes/tarjetas-video/nvidia-geforce/rtx-50/rtx-5060', name: 'Tarjetas de video NVIDIA GeForce RTX 5060', legacyCategory: 'components' },
  { path: 'video/accesorios-proyeccion/soportes-proyector/techo', name: 'Soportes de techo para proyector', legacyCategory: 'accessories' },
  { path: 'video/accesorios-proyeccion/soportes-proyector/techo/13-5kg', name: 'Soportes de techo para proyector hasta 13.5 kg', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/mouse/inalambricos/ergonomicos/silenciosos-dual-receptor-1000-dpi', name: 'Mouse ergonomicos inalambricos silenciosos USB-A USB-C 1000 DPI', legacyCategory: 'accessories' },
  { path: 'telefonia/pbx-ip/grandstream-ucm6300/audio-2fxo-2fxs', name: 'PBX IP Grandstream UCM6300 Audio 2 FXS 2 FXO', legacyCategory: 'networking' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas', name: 'Pantallas electricas de proyeccion', legacyCategory: 'monitors' },
  { path: 'video/accesorios-proyeccion/pantallas-electricas/203-pulgadas', name: 'Pantallas electricas de proyeccion 203 pulgadas', legacyCategory: 'monitors' },
  { path: 'impresion/consumibles/tambores/brother', name: 'Tambores Brother para impresoras laser', legacyCategory: 'printers_scanners' },
  { path: 'impresion/consumibles/tambores/brother/dr890', name: 'Tambores Brother DR890', legacyCategory: 'printers_scanners' },
  { path: 'computo/monitores/profesionales', name: 'Monitores profesionales', legacyCategory: 'monitors' },
  { path: 'computo/monitores/profesionales/27-qhd-120hz', name: 'Monitores profesionales QHD de 27 pulgadas 120Hz', legacyCategory: 'monitors' },
  { path: 'energia/cargadores-usb/estaciones-carga', name: 'Estaciones de carga USB multipuerto', legacyCategory: 'accessories' },
  { path: 'energia/cargadores-usb/estaciones-carga/usb-9-en-1-140w', name: 'Estaciones de carga USB 9 en 1 de 140W', legacyCategory: 'accessories' },
  { path: 'computo/perifericos/teclados/gaming', name: 'Teclados gaming', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos', name: 'Teclados gaming mecanicos', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/teclados/gaming/mecanicos/tkl-rgb', name: 'Teclados mecanicos gaming TKL RGB', legacyCategory: 'gaming' },
];
