export const MANUAL_CATEGORY_TREE_CYCLE003_PART004 = [
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos', name: 'Marcadores Azor Signal punto fino surtidos', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos/5-piezas', name: 'Azor Signal punto fino surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/surtidos/5-piezas/azor-signal-30653', name: 'Azor Signal 30653 surtido 5 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro', name: 'Azor Pin Point cuerpo transparente negro', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro/12-piezas', name: 'Azor Pin Point 6830NE negro 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/azor-pinpoint-cuerpo-transparente/negro/12-piezas/azor-pinpoint-6830ne', name: 'Azor Pin Point 6830NE negro 1.0 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe', name: 'Marcadores Azor Signal punto fino cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe/12-piezas', name: 'Azor Signal 30007 cafe 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/cafe/12-piezas/azor-signal-30007', name: 'Azor Signal Fino 30007 cafe', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta', name: 'Marcadores base agua doble punta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta/12-colores', name: 'Marcadores base agua doble punta 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/base-agua-lavables/doble-punta/12-colores/azor-aquarelo-duo-29412', name: 'Azor Aquarelo Duo 29412 12 colores', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul', name: 'Marcadores Azor Signal Xtra azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul/12-piezas', name: 'Azor Signal Xtra azul 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/azul/12-piezas/azor-signal-xtra-40003', name: 'Azor Signal Xtra 40003 azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo', name: 'Marcadores Azor Signal Xtra rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo/12-piezas', name: 'Azor Signal Xtra rojo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-xtra/rojo/12-piezas/azor-signal-xtra-40002', name: 'Azor Signal Xtra 40002 rojo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo', name: 'Marcadores Azor Signal punto fino amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo/12-piezas', name: 'Azor Signal 30005 amarillo 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/amarillo/12-piezas/azor-signal-30005', name: 'Azor Signal Fino 30005 amarillo', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta', name: 'Marcadores Azor Signal punto fino violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta/12-piezas', name: 'Azor Signal 30008 violeta 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/permanentes/signal-fino/violeta/12-piezas/azor-signal-30008', name: 'Azor Signal Fino 30008 violeta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul', name: 'Uni-ball Deluxe roller azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul/blister-1-pieza', name: 'Uni-ball Deluxe azul blister 1 pieza', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/roller/uni-ball-deluxe/azul/blister-1-pieza/azor-ub155az1', name: 'Uni-ball Deluxe UB155AZ1 azul 0.5 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/broches-archivo/7cm', name: 'Broches para archivo 7 cm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/broches-archivo/7cm/baco-b072-50-piezas', name: 'Baco B-072 broche archivo 7 cm 50 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/lapices-bicolor', name: 'Lapices bicolor escolares', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/escritura/lapices-bicolor/baco-55408-12p', name: 'BACO 55408 lapiz bicolor 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/ergonomia/cojines-asiento/espuma-viscoelastica/kensington-p4936', name: 'Kensington P4936 cojin de asiento', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95/azul-valvula', name: 'Cubrebocas KN95 azul con valvula', legacyCategory: 'accessories' },
  { path: 'salud/higiene/cubrebocas/kn95/azul-valvula/ksa-ph007', name: 'KSA PH007 KN95 azul con valvula', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/crema', name: 'Folders carta color crema', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/crema/100-piezas', name: 'Folders carta crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/carta/crema/100-piezas/diem-mf01c100', name: 'DIEM MF01C100 folder carta crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/crema', name: 'Folders oficio color crema', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/crema/100-piezas', name: 'Folders oficio crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/archivo/folders/oficio/crema/100-piezas/diem-mf01oc100', name: 'DIEM MF01OC100 folder oficio crema 100 piezas', legacyCategory: 'accessories' },
  { path: 'redes/controladoras/omada', name: 'Controladoras TP-Link Omada', legacyCategory: 'networking' },
  { path: 'redes/controladoras/omada/hardware-controller', name: 'Controladoras hardware Omada SDN', legacyCategory: 'networking' },
  { path: 'redes/controladoras/omada/hardware-controller/tp-link-oc300', name: 'TP-Link Omada OC300 controladora hardware', legacyCategory: 'networking' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/combinacion', name: 'Candados laptop de combinacion', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/combinacion/n17-slim', name: 'Candados Kensington N17 Slim de combinacion', legacyCategory: 'accessories' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/combinacion/n17-slim/kensington-k68009ww', name: 'Kensington K68009WW Slim N17 combinacion', legacyCategory: 'accessories' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra/gk420d-gx420d-203dpi', name: 'Cabezales Zebra GK420d/GX420d 203 dpi', legacyCategory: 'printers_scanners' },
  { path: 'impresion/refacciones/cabezales/termicos/zebra/gk420d-gx420d-203dpi/105934-037', name: 'Zebra 105934-037 cabezal GK420d/GX420d', legacyCategory: 'printers_scanners' },
  { path: 'gaming/mobiliario/sillas-gamer/accesorios', name: 'Accesorios para sillas gamer', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/accesorios/cojines', name: 'Cojines y almohadas para sillas gamer', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/sillas-gamer/accesorios/cojines/yeyian-yka-20705', name: 'Yeyian YKA-20705 kit de almohadas', legacyCategory: 'gaming' },
  { path: 'video/accesorios-proyeccion/filtros-aire', name: 'Filtros de aire para proyectores', legacyCategory: 'accessories' },
  { path: 'video/accesorios-proyeccion/filtros-aire/epson-elpaf32-v13h134a32', name: 'Epson ELPAF32 V13H134A32 filtro de aire', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina', name: 'Papel y cartulina de oficina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-opalina', name: 'Papel opalina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-opalina/carta', name: 'Papel opalina tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/papel-opalina/carta/diem-pobtcc100-100h', name: 'DIEM POBTCC100 papel opalina carta 100 hojas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-opalina', name: 'Cartulina opalina', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-opalina/carta', name: 'Cartulina opalina tamano carta', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/papel-cartulina/cartulina-opalina/carta/diem-cobtcc100-100p', name: 'DIEM COBTCC100 cartulina opalina carta 100 piezas', legacyCategory: 'accessories' },
  { path: 'telefonia/telefonos-ip/escritorio/1-linea', name: 'Telefonos IP de escritorio una linea', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/escritorio/1-linea/poe', name: 'Telefonos IP una linea con PoE', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/escritorio/1-linea/poe/cisco-7811-3pcc', name: 'Cisco 7811 3PCC telefono IP una linea PoE', legacyCategory: 'networking' },
  { path: 'oficina/papeleria/sobres/coin', name: 'Sobres coin', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/coin/ante', name: 'Sobres coin color ante', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/coin/ante/8-8x16-4', name: 'Sobres coin ante 8.8 x 16.4 cm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sobres/coin/ante/8-8x16-4/mae-nassa-im0130-500p', name: 'NASSA MAE IM0130 sobre coin ante 500 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera', name: 'Marcadores de cera', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera/pelikan', name: 'Marcadores de cera Pelikan', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera/pelikan/rojo-10-piezas', name: 'Marcadores de cera Pelikan rojos 10 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/marcadores/cera/pelikan/rojo-10-piezas/50800103', name: 'Pelikan 50800103 marcador de cera rojo 10 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus', name: 'BIC Cristal Dura+ punto mediano', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus/azul', name: 'BIC Cristal Dura+ azul', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus/azul/12-piezas', name: 'BIC Cristal Dura+ azul 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/boligrafos/boligrafo-punto-mediano/bic-cristal-dura-plus/azul/12-piezas/923996', name: 'BIC 923996 Cristal Dura+ azul 1.0 mm 12 piezas', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz', name: 'Digitalizadores y accesorios Topaz', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz/accesorios', name: 'Accesorios Topaz para firma digital', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz/accesorios/protectores-pantalla', name: 'Protectores de pantalla Topaz', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/digitalizadores-firma/topaz/accesorios/protectores-pantalla/a-olsl-3', name: 'Topaz A-OLSL-3 protector SigLite 1x5 3 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/blocks', name: 'Blocks de notas adhesivas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/blocks/3x3', name: 'Blocks de notas adhesivas 3 x 3 pulgadas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/notas-adhesivas/blocks/3x3/janel-memotip-1173', name: 'Janel Memo Tip 1173 notas adhesivas 3 x 3', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves', name: 'Lapices de color Blanca Nieves', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/cortos-12p', name: 'Blanca Nieves lapices de color cortos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/cortos-12p/45075', name: 'Blanca Nieves 45075 colores cortos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/largos-12p', name: 'Blanca Nieves lapices de color largos 12 piezas', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/material-escolar/dibujo-arte/lapices-color/blanca-nieves/largos-12p/45074', name: 'Blanca Nieves 45074 colores largos 12 piezas', legacyCategory: 'accessories' },
];
