export const MANUAL_CATEGORY_TREE_CYCLE003_PART006 = [
  { path: 'seguridad/cctv/camaras-ip-poe/box', name: 'Camaras IP PoE box', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/box/4mp-lighthunter-wdr', name: 'Camaras IP box 4MP LightHunter WDR', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/box/4mp-lighthunter-wdr/uniview-ipc544se-dk-i0', name: 'Uniview IPC544SE-DK-I0 4MP box', legacyCategory: 'cameras' },
  { path: 'computo/tabletas/android/7-pulgadas/3gb-64gb', name: 'Tabletas Android 7 pulgadas 3GB 64GB', legacyCategory: 'tablets' },
  { path: 'computo/tabletas/android/7-pulgadas/3gb-64gb/ghia-a7-a333-ga7333r26-roja', name: 'GHIA A7 A333 GA7333R26 roja', legacyCategory: 'tablets' },
  { path: 'computo/almacenamiento/memorias-flash/usb-c', name: 'Memorias flash USB-C', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb-c/128gb', name: 'Memorias flash USB-C 128GB', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb-c/128gb/diseno-crayola', name: 'Memorias USB-C 128GB diseno Crayola', legacyCategory: 'storage' },
  { path: 'computo/almacenamiento/memorias-flash/usb-c/128gb/diseno-crayola/sandisk-sdczic-128g-g46o-mango', name: 'SanDisk Crayola SDCZIC-128G-G46O Mango Tango', legacyCategory: 'storage' },
  { path: 'punto-de-venta/lectores-codigo-barras/accesorios/bases-flexibles', name: 'Bases flexibles para lectores de codigo de barras', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/accesorios/bases-flexibles/honeywell-stnd-15f03-101-4', name: 'Honeywell STND-15F03-101-4 base flexible 6 pulgadas', legacyCategory: 'accessories' },
  { path: 'software/licencias/microsoft/enterprise-mobility-security', name: 'Microsoft Enterprise Mobility + Security', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/enterprise-mobility-security/e5', name: 'Microsoft Enterprise Mobility + Security E5', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/enterprise-mobility-security/e5/csp-anual', name: 'Microsoft EMS E5 CSP anual', legacyCategory: 'software' },
  { path: 'software/licencias/microsoft/enterprise-mobility-security/e5/csp-anual/cfq7ttc0lfj1-0001-p1y', name: 'Microsoft CFQ7TTC0LFJ1 EMS E5 anual', legacyCategory: 'software' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-usb/omnidireccionales', name: 'Lectores 2D USB omnidireccionales', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-usb/omnidireccionales/3nstar-sc504', name: '3nStar SC504 lector omnidireccional 1D 2D', legacyCategory: 'accessories' },
  { path: 'software/licencias/aspel-noi', name: 'Licencias Aspel NOI', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-noi/usuarios-adicionales', name: 'Usuarios adicionales Aspel NOI', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-noi/usuarios-adicionales/noi-11-2-usuarios', name: 'Aspel NOI 11 2 usuarios adicionales', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-noi/usuarios-adicionales/noi-11-2-usuarios/actualizacion-perpetua/noil2an', name: 'Aspel NOIL2AN actualizacion perpetua 2 usuarios', legacyCategory: 'software' },
  { path: 'computo/componentes/procesadores/amd-ryzen', name: 'Procesadores AMD Ryzen', legacyCategory: 'components' },
  { path: 'computo/componentes/procesadores/amd-ryzen/ryzen-9', name: 'Procesadores AMD Ryzen 9', legacyCategory: 'components' },
  { path: 'computo/componentes/procesadores/amd-ryzen/ryzen-9/9000-series', name: 'AMD Ryzen 9 serie 9000', legacyCategory: 'components' },
  { path: 'computo/componentes/procesadores/amd-ryzen/ryzen-9/9000-series/x3d2/ryzen-9-9950x3d2', name: 'AMD Ryzen 9 9950X3D2 Dual Edition', legacyCategory: 'components' },
  { path: 'computo/accesorios/baterias-laptop/hp/business-notebook-6530b', name: 'Baterias laptop HP Business Notebook 6530b', legacyCategory: 'accessories' },
  { path: 'computo/accesorios/baterias-laptop/hp/business-notebook-6530b/ovaltech-oth6930-batovl660', name: 'Ovaltech OTH6930 BATOVL660 bateria HP 6530b', legacyCategory: 'accessories' },
  { path: 'computo/componentes/procesadores/amd-ryzen/ryzen-7', name: 'Procesadores AMD Ryzen 7', legacyCategory: 'components' },
  { path: 'computo/componentes/procesadores/amd-ryzen/ryzen-7/7000-series', name: 'AMD Ryzen 7 serie 7000', legacyCategory: 'components' },
  { path: 'computo/componentes/procesadores/amd-ryzen/ryzen-7/7000-series/ryzen-7-7700x', name: 'AMD Ryzen 7 7700X', legacyCategory: 'components' },
  { path: 'software/analitica-datos', name: 'Software de analitica de datos', legacyCategory: 'software' },
  { path: 'software/analitica-datos/business-intelligence', name: 'Business Intelligence', legacyCategory: 'software' },
  { path: 'software/analitica-datos/business-intelligence/microsoft-power-bi', name: 'Microsoft Power BI', legacyCategory: 'software' },
  { path: 'software/analitica-datos/business-intelligence/microsoft-power-bi/pro-saas', name: 'Power BI Pro SaaS por usuario', legacyCategory: 'software' },
  { path: 'software/analitica-datos/business-intelligence/microsoft-power-bi/pro-saas/cfq7ttc0lhsfp1ym', name: 'Microsoft CFQ7TTC0LHSFP1YM Power BI Pro', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/kaspersky-next', name: 'Kaspersky Next Endpoint Security', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/kaspersky-next/edr-optimum-plus', name: 'Kaspersky Next EDR Optimum Plus', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/kaspersky-next/edr-optimum-plus/500-999-licencias-2-anos', name: 'Kaspersky Next EDR Optimum Plus 500-999 licencias 2 anos', legacyCategory: 'software' },
  { path: 'software/seguridad/endpoint/kaspersky-next/edr-optimum-plus/500-999-licencias-2-anos/kl4066zaud8', name: 'Kaspersky KL4066ZAUD8 500-999 2 anos', legacyCategory: 'software' },
  { path: 'telefonia/telefonos-ip/accesorios/modulos-expansion', name: 'Modulos de expansion para telefonos IP', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos-ip/accesorios/modulos-expansion/grandstream-gxp2200ext', name: 'Grandstream GXP2200EXT modulo BLF', legacyCategory: 'networking' },
  { path: 'computo/desktops/all-in-one/apple-imac', name: 'Apple iMac all-in-one', legacyCategory: 'desktops' },
  { path: 'computo/desktops/all-in-one/apple-imac/24-retina-4-5k', name: 'iMac 24 pulgadas Retina 4.5K', legacyCategory: 'desktops' },
  { path: 'computo/desktops/all-in-one/apple-imac/24-retina-4-5k/m4-10c-24gb-1tb-plata', name: 'Apple iMac 24 M4 10C 24GB 1TB plata', legacyCategory: 'desktops' },
  { path: 'redes/cableado-estructurado/patch-cords/cat5e/5m', name: 'Patch cords Cat5e de 5 m', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords/cat5e/5m/utp-negro/intellinet-320771', name: 'Intellinet 320771 Cat5e UTP negro 5m', legacyCategory: 'networking' },
  { path: 'redes/switches/administrables/gigabit/24-puertos-4-sfp/hpe-aruba-cx-6000-r8n88a', name: 'HPE Aruba CX 6000 R8N88A 24G 4SFP', legacyCategory: 'networking' },
  { path: 'audio/bocinas/bluetooth/portatiles/ip64-3w', name: 'Bocinas Bluetooth portatiles IP64 3W', legacyCategory: 'audio' },
  { path: 'audio/bocinas/bluetooth/portatiles/ip64-3w/evorok-cargo-ev-927529-verde', name: 'Evorok Cargo EV-927529 verde', legacyCategory: 'audio' },
  { path: 'oficina/papeleria/sujetadores/binder-clips', name: 'Sujetadores binder clip', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/binder-clips/41mm', name: 'Binder clips 41 mm', legacyCategory: 'accessories' },
  { path: 'oficina/papeleria/sujetadores/binder-clips/41mm/nextep-ne-157-12p', name: 'Nextep NE-157 sujetadocumentos 41mm 12 piezas', legacyCategory: 'accessories' },
  { path: 'punto-de-venta/terminales-pos/all-in-one/15-pulgadas/ec-line-ec-vp-1100i3-256-win', name: 'EC Line EC-VP-1100i3-256-WIN POS 15 pulgadas', legacyCategory: 'accessories' },
  { path: 'video/soportes-tv/pared/fijos', name: 'Soportes fijos de pared para TV', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/pared/fijos/39-75-79kg', name: 'Soportes fijos TV 39 a 75 pulgadas 79 kg', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/pared/fijos/39-75-79kg/peerless-av-sf650', name: 'Peerless-AV SF650 SmartMount fijo', legacyCategory: 'tvs' },
];
