export const MANUAL_CATEGORY_TREE_EXPANSION = [
  { path: 'redes/poe/inyectores', name: 'Inyectores PoE', legacyCategory: 'networking' },
  { path: 'redes/poe/inyectores/24v', name: 'Inyectores PoE pasivos 24V', legacyCategory: 'networking' },
  { path: 'redes/poe/inyectores/802-3af', name: 'Inyectores PoE IEEE 802.3af', legacyCategory: 'networking' },
  { path: 'redes/poe/splitters', name: 'Splitters PoE', legacyCategory: 'networking' },
  { path: 'redes/poe/extensores', name: 'Extensores PoE', legacyCategory: 'networking' },
  { path: 'redes/poe/extensores/fast-ethernet', name: 'Extensores PoE Fast Ethernet', legacyCategory: 'networking' },
  { path: 'redes/switches', name: 'Switches', legacyCategory: 'networking' },
  { path: 'redes/switches/administrables', name: 'Switches administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/administrables/gigabit', name: 'Switches Gigabit administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables', name: 'Switches PoE administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables/gigabit', name: 'Switches PoE administrables Gigabit', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables/gigabit/8-puertos', name: 'Switches PoE Gigabit administrables de 8 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables/gigabit/24-puertos', name: 'Switches PoE Gigabit administrables de 24 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-administrables/gigabit/48-puertos', name: 'Switches PoE Gigabit administrables de 48 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables', name: 'Switches PoE no administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables/cctv', name: 'Switches PoE no administrables para CCTV', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables/cctv/16-puertos', name: 'Switches PoE CCTV de 16 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/poe-no-administrables/cctv/24-puertos', name: 'Switches PoE CCTV de 24 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/no-administrables', name: 'Switches no administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/no-administrables/fast-ethernet', name: 'Switches Fast Ethernet no administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/no-administrables/fast-ethernet/16-puertos', name: 'Switches Fast Ethernet no administrables de 16 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/no-administrables/gigabit', name: 'Switches Gigabit no administrables', legacyCategory: 'networking' },
  { path: 'redes/switches/no-administrables/gigabit/5-puertos', name: 'Switches Gigabit no administrables de 5 puertos', legacyCategory: 'networking' },
  { path: 'redes/switches/no-administrables/gigabit/8-puertos', name: 'Switches Gigabit no administrables de 8 puertos', legacyCategory: 'networking' },
  { path: 'redes/seguridad', name: 'Seguridad de red', legacyCategory: 'networking' },
  { path: 'redes/seguridad/firewalls', name: 'Firewalls y gateways seguros', legacyCategory: 'networking' },
  { path: 'redes/routers', name: 'Routers', legacyCategory: 'networking' },
  { path: 'redes/routers/vpn', name: 'Routers VPN', legacyCategory: 'networking' },
  { path: 'redes/routers/vpn/omada', name: 'Routers VPN Omada', legacyCategory: 'networking' },
  { path: 'redes/routers/wisp', name: 'Routers WISP', legacyCategory: 'networking' },
  { path: 'redes/routers/wifi-n', name: 'Routers Wi-Fi N', legacyCategory: 'networking' },
  { path: 'redes/routers/wifi-7', name: 'Routers Wi-Fi 7', legacyCategory: 'networking' },
  { path: 'redes/routers/wifi-7/be6500', name: 'Routers Wi-Fi 7 BE6500', legacyCategory: 'networking' },
  { path: 'redes/routers/wifi-7/gaming-be19000', name: 'Routers gaming Wi-Fi 7 BE19000', legacyCategory: 'networking' },
  { path: 'redes/routers/mesh-wifi', name: 'Routers mesh Wi-Fi', legacyCategory: 'networking' },
  { path: 'redes/routers/mesh-wifi/wifi-5-ac1200', name: 'Routers mesh Wi-Fi 5 AC1200', legacyCategory: 'networking' },
  { path: 'redes/routers/mesh-wifi/wifi-5-ac1900', name: 'Routers mesh Wi-Fi 5 AC1900', legacyCategory: 'networking' },
  { path: 'telefonia/pbx-ip', name: 'PBX y conmutadores IP', legacyCategory: 'networking' },
  { path: 'telefonia/pbx-ip/grandstream-ucm6300', name: 'PBX IP Grandstream UCM6300', legacyCategory: 'networking' },
  { path: 'telefonia/telefonos', name: 'Telefonos', legacyCategory: 'laptops' },
  { path: 'telefonia/telefonos/inalambricos', name: 'Telefonos inalambricos', legacyCategory: 'laptops' },
  { path: 'telefonia/telefonos-ip', name: 'Telefonos IP', legacyCategory: 'networking' },
  { path: 'telefonia/accesorios', name: 'Accesorios para telefonia movil', legacyCategory: 'laptops' },
  { path: 'telefonia/accesorios/soportes-celular', name: 'Soportes para celular', legacyCategory: 'laptops' },
  { path: 'telefonia/accesorios/soportes-celular/magneticos', name: 'Soportes magneticos para celular', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras', name: 'Impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/etiquetas', name: 'Impresoras de etiquetas', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/etiquetas/rotuladores-p-touch', name: 'Rotuladores P-touch y etiquetadoras portatiles', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/etiquetas/termicas-moviles', name: 'Impresoras termicas moviles de etiquetas', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/multifuncionales-laser', name: 'Multifuncionales laser', legacyCategory: 'laptops' },
  { path: 'impresion/impresoras/multifuncionales-ecotank', name: 'Multifuncionales EcoTank', legacyCategory: 'laptops' },
  { path: 'impresion/escaneres', name: 'Escaneres documentales', legacyCategory: 'cameras' },
  { path: 'impresion/escaneres/documentales-duplex', name: 'Escaneres documentales duplex', legacyCategory: 'cameras' },
  { path: 'impresion/escaneres/documentales-compactos', name: 'Escaneres documentales compactos', legacyCategory: 'cameras' },
  { path: 'impresion/accesorios/bandejas-alimentadores', name: 'Bandejas y alimentadores de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/accesorios/unidades-duplex', name: 'Unidades duplex para impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cabezales', name: 'Cabezales de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cabezales/hp-smart-tank', name: 'Cabezales HP Smart Tank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tinta-toner', name: 'Tinta, toner y cintas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser', name: 'Toner laser', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/hp', name: 'Toner laser HP', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/hp/laserjet-tank-154a', name: 'Recargas HP 154A LaserJet Tank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother', name: 'Toner laser Brother', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-229', name: 'Toner Brother TN-229', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-229/xl-amarillo', name: 'Toner Brother TN-229XL amarillo', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-229/xxl-amarillo', name: 'Toner Brother TN-229XXL amarillo', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-436bk', name: 'Toner Brother TN-436BK', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-920', name: 'Toner Brother TN-920', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/brother/tn-920/xxl-negro', name: 'Toner Brother TN-920XXL negro', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/kyocera', name: 'Toner laser Kyocera', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/kyocera/tk-1122', name: 'Toner Kyocera TK-1122', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/kyocera/tk-3102', name: 'Toner Kyocera TK-3102', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/kyocera/tk-3432', name: 'Toner Kyocera TK-3432', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/kyocera/tk-5417', name: 'Toner Kyocera TK-5417', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/canon', name: 'Toner laser Canon', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/canon/gpr-52', name: 'Toner Canon GPR-52', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/xerox', name: 'Toner laser Xerox', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/toner-laser/xerox/b305-b315', name: 'Toner Xerox B305/B310/B315', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cintas-tarjetas', name: 'Cintas para impresoras de tarjetas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cintas-etiquetas', name: 'Cintas para rotuladores y etiquetadoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cintas-etiquetas/transferencia-termica', name: 'Cintas ribbon de transferencia termica', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cintas-etiquetas/transferencia-termica/ribbon-cera', name: 'Ribbons de cera para transferencia termica', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cintas-etiquetas/brother-m', name: 'Cintas Brother M no laminadas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cartuchos-tinta', name: 'Cartuchos de tinta', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cartuchos-tinta/brother-lc402xl', name: 'Cartuchos Brother LC402XL', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta', name: 'Botellas de tinta', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta/brother-bt5001', name: 'Botellas Brother BT5001', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta/brother-bt6001', name: 'Botellas Brother BT6001', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-ecotank', name: 'Botellas de tinta EcoTank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-ecotank/epson-t504', name: 'Botellas Epson T504', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-ecotank/epson-t574', name: 'Botellas Epson T574', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-megatank', name: 'Botellas de tinta MegaTank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/botellas-tinta-megatank/canon-gi10', name: 'Botellas Canon GI-10 MegaTank', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/contenedores-desperdicio', name: 'Contenedores de toner residual', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tambores', name: 'Tambores y unidades de imagen', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tambores/xerox', name: 'Tambores Xerox', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/etiquetas-papel', name: 'Etiquetas y papel', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/etiquetas-papel/transferencia-termica', name: 'Etiquetas de transferencia termica', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-fotografico-sublimacion', name: 'Papel fotografico y sublimacion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-plotter', name: 'Papel para plotter', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/mantenimiento', name: 'Mantenimiento de impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/unidades-transferencia', name: 'Unidades de transferencia', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/pulseras-termicas', name: 'Pulseras termicas de identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras', name: 'Lectores de codigo de barras', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras/1d-usb', name: 'Lectores codigo de barras 1D USB', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-usb', name: 'Lectores codigo de barras 2D USB', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras/2d-omnidireccionales', name: 'Lectores 2D omnidireccionales', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/cajones-dinero', name: 'Cajones de dinero POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/cajones-dinero/metalicos', name: 'Cajones de dinero metalicos', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/detectores-billetes', name: 'Detectores de billetes falsos', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/impresoras-recibos', name: 'Impresoras termicas de recibos POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/impresoras-recibos/portatiles-58mm', name: 'Impresoras POS portatiles de 58 mm', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/impresoras-recibos/moviles-3-pulgadas', name: 'Impresoras POS moviles de 3 pulgadas', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/digitalizadores-firma', name: 'Digitalizadores de firma', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/verificadores-precio', name: 'Verificadores de precio POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/verificadores-precio/android-8-pulgadas', name: 'Verificadores de precio Android de 8 pulgadas', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/terminales-accesorios', name: 'Terminales y accesorios POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/terminales-accesorios/soportes-tablet', name: 'Soportes POS para tablet', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/software-pos', name: 'Software punto de venta', legacyCategory: 'software' },
  { path: 'punto-de-venta/credenciales-identificacion', name: 'Credenciales e identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-bond', name: 'Rollos bond POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-autocopia', name: 'Rollos autocopia POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/etiquetas-termicas', name: 'Etiquetas termicas POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-termicos', name: 'Rollos termicos POS', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/biometricos', name: 'Biometricos de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/biometricos/checadores-asistencia', name: 'Checadores biometricos de asistencia', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/tarjetas-rfid', name: 'Tarjetas RFID de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/cerraduras-inteligentes', name: 'Cerraduras inteligentes', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/videoporteros-ip', name: 'Videoporteros IP', legacyCategory: 'cameras' },
  { path: 'seguridad/control-acceso/videoporteros-ip/kits', name: 'Kits de videoportero IP', legacyCategory: 'cameras' },
  { path: 'seguridad/control-acceso/videoporteros-analogicos', name: 'Videoporteros analogicos', legacyCategory: 'cameras' },
  { path: 'seguridad/control-acceso/videoporteros-analogicos/kits', name: 'Kits de videoportero analogico', legacyCategory: 'cameras' },
  { path: 'seguridad/control-acceso/videoporteros-hibridos/kits', name: 'Kits de videoportero hibrido', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras', name: 'Camaras CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-analogicas', name: 'Camaras analogicas HD', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-analogicas/bullet-hd', name: 'Camaras analogicas bullet HD', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-analogicas/bullet-hd/2mp-ahd', name: 'Camaras analogicas bullet AHD 2MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-analogicas/bullet-hd/2mp-ir', name: 'Camaras analogicas bullet 2MP IR', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi', name: 'Camaras HDCVI analogicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi/domo-eyeball', name: 'Camaras HDCVI domo eyeball', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi/domo-eyeball/2mp-full-color', name: 'Camaras HDCVI domo eyeball 2MP full-color', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-hdcvi/bullet', name: 'Camaras HDCVI bullet', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi', name: 'Camaras IP WiFi', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/interior', name: 'Camaras IP WiFi de interior', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-interior', name: 'Camaras IP WiFi PT de interior', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-interior/3mp', name: 'Camaras IP WiFi PT de interior 3MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-interior/4mp-2k', name: 'Camaras IP WiFi PT de interior 4MP 2K', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-interior/5mp', name: 'Camaras IP WiFi PT de interior 5MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/bullet-exterior', name: 'Camaras IP WiFi bullet de exterior', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/bateria-exterior', name: 'Camaras IP WiFi de exterior con bateria', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-exterior', name: 'Camaras IP WiFi PT de exterior', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi/pt-doble-lente', name: 'Camaras IP WiFi PT doble lente', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe', name: 'Camaras IP PoE', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet', name: 'Camaras IP PoE bullet', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/2mp', name: 'Camaras IP PoE bullet 2MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/2mp/iluminacion-dual', name: 'Camaras IP PoE bullet 2MP con iluminacion dual', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/2mp-owlview', name: 'Camaras IP PoE bullet 2MP OwlView', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/4mp-mic', name: 'Camaras IP PoE bullet 4MP con microfono', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/4mp-full-color', name: 'Camaras IP PoE bullet 4MP full-color', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/bullet/8mp', name: 'Camaras IP PoE bullet 8MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo', name: 'Camaras IP PoE domo', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo/2mp', name: 'Camaras IP PoE domo 2MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo/4mp', name: 'Camaras IP PoE domo 4MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret', name: 'Camaras IP PoE turret', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/2mp', name: 'Camaras IP PoE turret 2MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/4mp', name: 'Camaras IP PoE turret 4MP', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/4mp-dual-light', name: 'Camaras IP PoE turret 4MP dual light', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/4mp-owlview', name: 'Camaras IP PoE turret 4MP OwlView', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/turret/full-color', name: 'Camaras IP PoE turret Full Color', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo-varifocal', name: 'Camaras IP PoE domo varifocal', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/domo-varifocal/motorizadas', name: 'Camaras IP PoE domo varifocal motorizadas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/panoramicas', name: 'Camaras IP PoE panoramicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe/ptz', name: 'Camaras IP PoE PTZ', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd', name: 'Camaras TurboHD analogicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd/bullet', name: 'Camaras TurboHD bullet', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd/turret', name: 'Camaras TurboHD turret', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd/turret/8mp-colorvu', name: 'Camaras TurboHD turret 8MP ColorVu', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles', name: 'Camaras moviles vehiculares', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles/ahd-placa', name: 'Camaras AHD para placa vehicular', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles/adas-dsm', name: 'Kits vehiculares ADAS y DSM', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles/dashcam', name: 'Dashcams vehiculares', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-moviles/turbo-hd', name: 'Camaras moviles TurboHD vehiculares', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/kits-vigilancia', name: 'Kits de videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado', name: 'Accesorios y cableado CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado/baluns-video', name: 'Baluns y transceptores de video CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado/conectores-bnc', name: 'Conectores BNC para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado/conectores-corriente', name: 'Conectores de corriente para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-montaje', name: 'Accesorios de montaje CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-montaje/cajas-conexion', name: 'Cajas de conexion CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/cable-coaxial-siames', name: 'Cable coaxial siames CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/cable-coaxial-siames/15m', name: 'Cable coaxial siames CCTV 15 m', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/fuentes-poder', name: 'Fuentes de poder para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr', name: 'DVR y NVR', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/dvr-4-canales', name: 'DVR analogicos de 4 canales', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/nvr-ip', name: 'NVR IP para videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/nvr-ip/16-canales', name: 'NVR IP de 16 canales', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/nvr-poe', name: 'NVR PoE para videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/xvr-hdcvi', name: 'XVR y DVR HDCVI', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr/xvr-pentahibrido', name: 'XVR pentahibridos', legacyCategory: 'cameras' },
  { path: 'seguridad/epp/proteccion-facial', name: 'Proteccion facial EPP', legacyCategory: 'laptops' },
  { path: 'seguridad/epp/proteccion-ocular', name: 'Proteccion ocular EPP', legacyCategory: 'laptops' },
  { path: 'salud/equipo-medico/monitoreo', name: 'Monitoreo medico domestico', legacyCategory: 'laptops' },
  { path: 'telefonia/smartphones', name: 'Smartphones', legacyCategory: 'smartphones' },
  { path: 'wearables/smartwatches', name: 'Smartwatches y bandas inteligentes', legacyCategory: 'smartphones' },
  { path: 'audio/audifonos', name: 'Audifonos', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/alambricos-3-5mm', name: 'Audifonos alambricos 3.5 mm', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/alambricos-3-5mm/diadema-con-microfono', name: 'Audifonos de diadema 3.5 mm con microfono', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/in-ear', name: 'Audifonos in-ear', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/in-ear/usb-c', name: 'Audifonos in-ear USB-C', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/usb', name: 'Audifonos USB con microfono', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/usb/diadema-microfono', name: 'Diademas USB con microfono', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth', name: 'Audifonos Bluetooth', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth/tws', name: 'Audifonos Bluetooth TWS', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/bluetooth/tws/deportivos', name: 'Audifonos Bluetooth TWS deportivos', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/gaming-alambricos', name: 'Audifonos gaming alambricos', legacyCategory: 'headphones' },
  { path: 'audio/audifonos/gaming-inalambricos', name: 'Audifonos gaming inalambricos', legacyCategory: 'headphones' },
  { path: 'audio/microfonos', name: 'Microfonos', legacyCategory: 'headphones' },
  { path: 'audio/microfonos/escritorio-3-5mm', name: 'Microfonos de escritorio 3.5 mm', legacyCategory: 'headphones' },
  { path: 'audio/microfonos/soportes-brazos', name: 'Soportes y brazos para microfono', legacyCategory: 'headphones' },
  { path: 'audio/conferencia-speakerphones', name: 'Bocinas de conferencia', legacyCategory: 'headphones' },
  { path: 'audio/adaptadores-bluetooth', name: 'Adaptadores Bluetooth de audio', legacyCategory: 'headphones' },
  { path: 'audio/adaptadores-bluetooth/auto', name: 'Adaptadores Bluetooth de audio para auto', legacyCategory: 'headphones' },
  { path: 'audio/bocinas', name: 'Bocinas', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/bluetooth', name: 'Bocinas Bluetooth portatiles', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/bluetooth/portatiles', name: 'Bocinas Bluetooth portatiles compactas', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/bluetooth/portatiles/fm-usb', name: 'Bocinas Bluetooth portatiles con FM y USB', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/portatiles', name: 'Bocinas portatiles', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/portatiles/karaoke-party', name: 'Bocinas portatiles karaoke party', legacyCategory: 'headphones' },
  { path: 'audio/bocinas/portatiles-karaoke', name: 'Bafles portatiles para karaoke', legacyCategory: 'headphones' },
  { path: 'audio/barras-sonido', name: 'Barras de sonido', legacyCategory: 'headphones' },
  { path: 'audio/barras-sonido/pc', name: 'Barras de sonido para PC', legacyCategory: 'headphones' },
  { path: 'colaboracion/video-conferencia/controladores', name: 'Controladores de videoconferencia', legacyCategory: 'laptops' },
  { path: 'colaboracion/presentacion-inalambrica', name: 'Presentacion inalambrica', legacyCategory: 'laptops' },
  { path: 'video/televisores', name: 'Televisores', legacyCategory: 'tvs' },
  { path: 'video/televisores/led-webos', name: 'Televisores LED webOS', legacyCategory: 'tvs' },
  { path: 'video/televisores/led-webos/32-hd', name: 'Televisores LED webOS 32 pulgadas HD', legacyCategory: 'tvs' },
  { path: 'video/televisores/qled-google-tv', name: 'Televisores QLED Google TV', legacyCategory: 'tvs' },
  { path: 'video/televisores/qled-vidaa-tv', name: 'Televisores QLED VIDAA TV', legacyCategory: 'tvs' },
  { path: 'video/proyectores', name: 'Proyectores', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion', name: 'Accesorios de proyeccion', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion/pantallas-tripie', name: 'Pantallas de proyeccion con tripie', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion/soportes-proyector', name: 'Soportes para proyector', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av', name: 'Accesorios de audio y video', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/switches-hdmi', name: 'Switches HDMI', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/switches-hdmi/3x1-4k60', name: 'Switches HDMI 3x1 4K60', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/splitters-hdmi', name: 'Splitters y divisores HDMI', legacyCategory: 'tvs' },
  { path: 'video/accesorios-av/splitters-hdmi/1x2-4k', name: 'Splitters HDMI 1x2 4K', legacyCategory: 'tvs' },
  { path: 'video/streaming', name: 'Streaming y reproductores multimedia', legacyCategory: 'tvs' },
  { path: 'video/streaming/reproductores', name: 'Reproductores de streaming', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv', name: 'Soportes para television', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/piso-carrito', name: 'Soportes moviles de piso para TV', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/piso-carrito/32-55', name: 'Soportes moviles de piso para TV 32 a 55 pulgadas', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/pared', name: 'Soportes de pared para television', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/pared/inclinables', name: 'Soportes de pared inclinables para TV', legacyCategory: 'tvs' },
  { path: 'video/soportes-tv/pared/fijos-60-100', name: 'Soportes fijos de pared para TV 60 a 100 pulgadas', legacyCategory: 'tvs' },
  { path: 'gaming/consolas', name: 'Consolas', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios', name: 'Accesorios gaming', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios/estaciones-carga', name: 'Estaciones de carga y soportes gaming', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario', name: 'Mobiliario gaming', legacyCategory: 'gaming' },
  { path: 'gaming/mobiliario/escritorios', name: 'Escritorios gaming', legacyCategory: 'gaming' },
  { path: 'oficina/mobiliario-accesorios', name: 'Mobiliario y accesorios de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/mobiliario-accesorios/sillas-oficina', name: 'Sillas de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/mobiliario-accesorios/sillas-oficina/operativas-sin-brazos', name: 'Sillas operativas sin brazos', legacyCategory: 'laptops' },
  { path: 'oficina/mobiliario-accesorios/sillas-gaming', name: 'Sillas gaming', legacyCategory: 'laptops' },
  { path: 'oficina/mochilas-bolsas', name: 'Mochilas y bolsas de uso diario', legacyCategory: 'laptops' },
  { path: 'oficina/papel-consumibles', name: 'Papel y consumibles de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/pizarrones-interactivos', name: 'Pizarrones interactivos', legacyCategory: 'laptops' },
  { path: 'oficina/limpieza-higiene/dispensadores', name: 'Dispensadores de higiene', legacyCategory: 'laptops' },
  { path: 'oficina/ergonomia/soportes-lumbares', name: 'Soportes lumbares ergonomicos', legacyCategory: 'laptops' },
  { path: 'herramientas/herramientas-mano', name: 'Herramientas de mano', legacyCategory: 'laptops' },
  { path: 'herramientas/herramientas-mano/pinzas-corte', name: 'Pinzas de corte', legacyCategory: 'laptops' },
  { path: 'software/licencias', name: 'Licencias de software', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-coi', name: 'Licencias Aspel COI', legacyCategory: 'software' },
  { path: 'software/licencias/aspel-sae', name: 'Licencias Aspel SAE', legacyCategory: 'software' },
  { path: 'software/licencias/windows-server', name: 'Licencias Microsoft Windows Server', legacyCategory: 'software' },
  { path: 'software/licencias/windows-server/cal-rds', name: 'CAL de Remote Desktop Services para Windows Server', legacyCategory: 'software' },
  { path: 'software/sistemas-operativos', name: 'Sistemas operativos', legacyCategory: 'software' },
  { path: 'software/seguridad', name: 'Software de seguridad', legacyCategory: 'software' },
  { path: 'software/seguridad/antivirus', name: 'Antivirus y proteccion endpoint', legacyCategory: 'software' },
  { path: 'software/seguridad/antivirus/small-office', name: 'Antivirus para oficina pequena', legacyCategory: 'software' },
  { path: 'software/seguridad/antivirus/multidispositivo', name: 'Antivirus multidispositivo', legacyCategory: 'software' },
  { path: 'software/seguridad/antivirus/multidispositivo/5-dispositivos', name: 'Antivirus multidispositivo 5 dispositivos', legacyCategory: 'software' },
  { path: 'software/cad-diseno', name: 'Software CAD y diseno', legacyCategory: 'software' },
  { path: 'software/productividad-oficina', name: 'Software de productividad y oficina', legacyCategory: 'software' },
  { path: 'software/productividad-oficina/microsoft-365', name: 'Microsoft 365', legacyCategory: 'software' },
  { path: 'servicios/garantias-extendidas', name: 'Garantias extendidas y servicios', legacyCategory: 'software' },
  { path: 'accesorios/seguridad-fisica', name: 'Seguridad fisica para equipos', legacyCategory: 'laptops' },
  { path: 'accesorios/seguridad-fisica/candados-laptop', name: 'Candados de seguridad para laptop', legacyCategory: 'laptops' },
  { path: 'accesorios/seguridad-fisica/candados-laptop/llave', name: 'Candados de seguridad para laptop con llave', legacyCategory: 'laptops' },
  { path: 'accesorios/limpieza', name: 'Limpieza y cuidado de equipos', legacyCategory: 'laptops' },
  { path: 'accesorios/limpieza/pantallas', name: 'Limpieza de pantallas', legacyCategory: 'laptops' },
  { path: 'accesorios/limpieza/pantallas/kits-lcd', name: 'Kits de limpieza LCD', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mousepads', name: 'Mousepads y tapetes para mouse', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mousepads/gel', name: 'Mousepads con gel', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mousepads/ergonomicos-con-gel', name: 'Mousepads ergonomicos con gel', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mousepads/gaming-carga-inalambrica', name: 'Mousepads gaming con carga inalambrica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/herramientas-esd', name: 'Herramientas antiestaticas ESD', legacyCategory: 'laptops' },
  { path: 'energia/power-banks', name: 'Baterias externas y power banks', legacyCategory: 'laptops' },
  { path: 'energia/power-banks/magneticos', name: 'Power banks magneticos', legacyCategory: 'laptops' },
  { path: 'energia/power-banks/magneticos/5000mah', name: 'Power banks magneticos 5000mAh', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas/maletines-laptop/15-6', name: 'Maletines para laptop 15.6 pulgadas', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores', name: 'Cables y adaptadores', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/energia', name: 'Cables de energia', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/energia/corriente-cpu', name: 'Cables de corriente CPU', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb', name: 'Cables USB', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-c-c', name: 'Cables USB-C a USB-C', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-c-c/1m', name: 'Cables USB-C a USB-C de 1 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-a', name: 'Cables USB A-A', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-b', name: 'Cables USB A-B', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-b/1-8m', name: 'Cables USB A-B de 1.8 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-b/3m', name: 'Cables USB A-B de 3 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-b/4-5m', name: 'Cables USB A-B de 4.5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/usb-a-b/5m', name: 'Cables USB A-B de 5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones', name: 'Extensiones USB', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones/1-8m', name: 'Extensiones USB de 1.8 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones/4-5m', name: 'Extensiones USB de 4.5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones/activas', name: 'Extensiones USB activas', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones/activas/5m', name: 'Extensiones USB activas de 5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones/activas/10m', name: 'Extensiones USB activas de 10 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/extensiones/activas/rj45', name: 'Extensores USB activos por RJ45', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/mini-usb', name: 'Cables USB A a Mini-B', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/micro-usb', name: 'Cables USB a Micro USB', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb/otg-usb-c', name: 'Adaptadores OTG USB-C a USB-A', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb-serial', name: 'Adaptadores USB a serial', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-dvi-vga', name: 'Adaptadores DVI VGA', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi-vga', name: 'Adaptadores HDMI a VGA', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi', name: 'Cables HDMI', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad', name: 'Cables HDMI de alta velocidad', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/1-8m', name: 'Cables HDMI alta velocidad 1.8 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/2m-ethernet', name: 'Cables HDMI alta velocidad 2 m con Ethernet', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/3m', name: 'Cables HDMI alta velocidad 3 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/5m', name: 'Cables HDMI alta velocidad 5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/5m-ethernet', name: 'Cables HDMI alta velocidad 5 m con Ethernet', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/7-5m', name: 'Cables HDMI alta velocidad 7.5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/10m', name: 'Cables HDMI alta velocidad 10 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/alta-velocidad/22-5m', name: 'Cables HDMI alta velocidad 22.5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/fibra-optica', name: 'Cables HDMI activos de fibra optica', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/mini-hdmi', name: 'Cables HDMI a Mini HDMI', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi/mini-hdmi/1-8m', name: 'Cables HDMI a Mini HDMI de 1.8 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi-dvi', name: 'Cables HDMI a DVI', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-vga', name: 'Cables VGA HD15', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-vga/hd15-1-8m', name: 'Cables VGA HD15 de 1.8 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-vga/hd15-3m', name: 'Cables VGA HD15 de 3 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-vga/hd15-4-5m', name: 'Cables VGA HD15 de 4.5 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-vga/hd15-15m', name: 'Cables VGA HD15 de 15 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-usb-c-hdmi', name: 'Adaptadores USB-C a HDMI', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-displayport', name: 'Cables DisplayPort', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-displayport/2m', name: 'Cables DisplayPort de 2 m', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-displayport-hdmi', name: 'Cables DisplayPort a HDMI', legacyCategory: 'laptops' },
  { path: 'accesorios/montaje-soportes', name: 'Montaje y soportes', legacyCategory: 'laptops' },
  { path: 'movilidad/scooters-electricos', name: 'Scooters electricos', legacyCategory: 'gaming' },
  { path: 'mascotas', name: 'Mascotas', legacyCategory: 'laptops' },
  { path: 'mascotas/alimentacion', name: 'Alimentacion para mascotas', legacyCategory: 'laptops' },
  { path: 'mascotas/alimentacion/comederos-inteligentes', name: 'Comederos inteligentes para mascotas', legacyCategory: 'laptops' },
  { path: 'mascotas/alimentacion/comederos-inteligentes/con-camara-6l', name: 'Comederos inteligentes con camara de 6L', legacyCategory: 'laptops' },
  { path: 'mascotas/bebederos-fuentes', name: 'Bebederos y fuentes para mascotas', legacyCategory: 'laptops' },
  { path: 'mascotas/higiene', name: 'Higiene para mascotas', legacyCategory: 'laptops' },
  { path: 'mascotas/higiene/limadores-unas-electricos', name: 'Limadores electricos de unas para mascotas', legacyCategory: 'laptops' },
];
