import { normalizeCatalogText } from './catalogIndex.mjs';

export const MANUAL_TAXONOMY_VERSION = 'manual-taxonomy-mx-2026-05-28';

export const MANUAL_CATEGORY_TREE = [
  { path: 'computo/laptops', name: 'Laptops', legacyCategory: 'laptops' },
  { path: 'computo/desktops', name: 'Computadoras de escritorio', legacyCategory: 'laptops' },
  { path: 'computo/servidores/componentes', name: 'Servidores y componentes', legacyCategory: 'laptops' },
  { path: 'computo/servidores/rack', name: 'Servidores rack', legacyCategory: 'laptops' },
  { path: 'computo/servidores/almacenamiento-cintas', name: 'Almacenamiento LTO y cintas', legacyCategory: 'laptops' },
  { path: 'computo/monitores', name: 'Monitores', legacyCategory: 'monitors' },
  { path: 'computo/componentes/procesadores', name: 'Procesadores', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-madre', name: 'Tarjetas madre', legacyCategory: 'laptops' },
  { path: 'computo/componentes/memoria-ram', name: 'Memoria RAM', legacyCategory: 'laptops' },
  { path: 'computo/componentes/fuentes-poder', name: 'Fuentes de poder', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-video', name: 'Tarjetas de video', legacyCategory: 'gaming' },
  { path: 'computo/componentes/enfriamiento-gabinetes', name: 'Enfriamiento y gabinetes', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/ssd', name: 'SSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/discos-duros', name: 'Discos duros', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/memorias-flash', name: 'Memorias flash y microSD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos', name: 'Medios opticos CD/DVD', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/medios-opticos/accesorios', name: 'Accesorios para medios opticos', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/accesorios-montaje', name: 'Accesorios de montaje para almacenamiento', legacyCategory: 'laptops' },
  { path: 'computo/almacenamiento/adaptadores-usb', name: 'Adaptadores USB para discos SATA IDE', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados', name: 'Teclados', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/teclados/keycaps', name: 'Keycaps y accesorios de teclado', legacyCategory: 'gaming' },
  { path: 'computo/perifericos/mouse', name: 'Mouse', legacyCategory: 'laptops' },
  { path: 'computo/perifericos/webcams', name: 'Webcams', legacyCategory: 'cameras' },
  { path: 'computo/perifericos/bocinas-audio', name: 'Bocinas y audio PC', legacyCategory: 'headphones' },
  { path: 'computo/perifericos/presentadores', name: 'Presentadores inalambricos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza', name: 'Limpieza de computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/limpiadores-pantalla', name: 'Limpiadores para pantalla', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/toallas-limpiadoras', name: 'Toallas limpiadoras para computo', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/liquidos-antiestaticos', name: 'Liquidos antiestaticos de limpieza', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/limpieza/espumas-limpiadoras', name: 'Espumas limpiadoras para electronica', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/docks-hubs', name: 'Docks y hubs', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/hubs-usb', name: 'Hubs USB', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mochilas-fundas', name: 'Mochilas y fundas para laptop', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/stylus-tablets', name: 'Stylus para tablets', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/seguridad-biometrica', name: 'Seguridad biometrica para computo', legacyCategory: 'laptops' },
  { path: 'computo/componentes/tarjetas-audio', name: 'Tarjetas de sonido', legacyCategory: 'headphones' },
  { path: 'computo/componentes/tarjetas-audio/usb', name: 'Tarjetas de sonido USB', legacyCategory: 'headphones' },
  { path: 'computo/componentes/pasta-termica', name: 'Pasta termica y compuestos', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups', name: 'No-breaks y UPS', legacyCategory: 'laptops' },
  { path: 'energia/no-breaks-ups/doble-conversion', name: 'UPS doble conversion online', legacyCategory: 'laptops' },
  { path: 'energia/accesorios-ups/tarjetas-snmp', name: 'Tarjetas SNMP para UPS', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups/cartuchos-reemplazo', name: 'Cartuchos de reemplazo para UPS', legacyCategory: 'laptops' },
  { path: 'energia/pilas-baterias/boton-cmos', name: 'Pilas de boton y CMOS', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-usb', name: 'Cargadores USB y USB-C', legacyCategory: 'laptops' },
  { path: 'energia/cargadores-inalambricos', name: 'Cargadores inalambricos Qi', legacyCategory: 'laptops' },
  { path: 'energia/baterias-ups', name: 'Baterias para UPS', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores/supresores-picos', name: 'Supresores de picos', legacyCategory: 'laptops' },
  { path: 'energia/supresores-reguladores', name: 'Supresores y reguladores', legacyCategory: 'laptops' },
  { path: 'energia/inversores-solares', name: 'Inversores y cargadores solares', legacyCategory: 'laptops' },
  { path: 'domotica/sensores', name: 'Sensores inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/movimiento', name: 'Sensores de movimiento inteligentes', legacyCategory: 'laptops' },
  { path: 'domotica/sensores/fugas-agua', name: 'Sensores de fuga de agua', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos', name: 'Electrodomesticos', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/microondas', name: 'Hornos de microondas', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/lavadoras', name: 'Lavadoras', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aspiradoras-robot', name: 'Aspiradoras robot', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/exprimidores', name: 'Exprimidores y extractores de jugo', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/aires-acondicionados', name: 'Aires acondicionados y minisplits', legacyCategory: 'laptops' },
  { path: 'hogar/electrodomesticos/purificadores-aire', name: 'Purificadores de aire', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-enfriamiento', name: 'Racks y enfriamiento', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios', name: 'Accesorios para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/herrajes', name: 'Herrajes y tornilleria para racks', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/soportes-pared', name: 'Soportes de pared para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas', name: 'Charolas y bandejas para rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas-monitor', name: 'Charolas para monitor en rack', legacyCategory: 'monitors' },
  { path: 'infraestructura/racks-accesorios/charolas-teclado', name: 'Charolas para teclado en rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/charolas-servidor', name: 'Charolas para servidor en rack', legacyCategory: 'laptops' },
  { path: 'infraestructura/racks-accesorios/organizadores-cable', name: 'Organizadores de cable para rack', legacyCategory: 'networking' },
  { path: 'infraestructura/racks-enfriamiento/racks-piso', name: 'Racks de piso', legacyCategory: 'laptops' },
  { path: 'infraestructura/cajas-registro', name: 'Cajas de registro y montaje', legacyCategory: 'laptops' },
  { path: 'redes/access-points', name: 'Access points', legacyCategory: 'networking' },
  { path: 'redes/radioenlaces-antenas', name: 'Radioenlaces y antenas', legacyCategory: 'networking' },
  { path: 'redes/transceptores-convertidores', name: 'Transceptores y convertidores', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado', name: 'Cableado estructurado', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/bobinas-utp', name: 'Bobinas de cable UTP', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/patch-cords', name: 'Patch cords de red', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/divisores-adaptadores', name: 'Divisores y adaptadores RJ45', legacyCategory: 'networking' },
  { path: 'redes/cableado-estructurado/acopladores-rj45', name: 'Acopladores y coples RJ45', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado', name: 'Herramientas para cableado', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/crimpadoras', name: 'Crimpadoras para conectores modulares', legacyCategory: 'networking' },
  { path: 'redes/herramientas-cableado/ponchadoras-impacto', name: 'Ponchadoras de impacto para jacks', legacyCategory: 'networking' },
  { path: 'redes/controladores-cloud', name: 'Controladores cloud de red', legacyCategory: 'networking' },
  { path: 'redes/fibra-optica/olt-gpon', name: 'OLT GPON de fibra optica', legacyCategory: 'networking' },
  { path: 'redes/tarjetas-red/pcie', name: 'Tarjetas de red PCI Express', legacyCategory: 'networking' },
  { path: 'redes/switches', name: 'Switches', legacyCategory: 'networking' },
  { path: 'redes/routers', name: 'Routers', legacyCategory: 'networking' },
  { path: 'impresion/impresoras', name: 'Impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/escaneres', name: 'Escaneres documentales', legacyCategory: 'cameras' },
  { path: 'impresion/accesorios/bandejas-alimentadores', name: 'Bandejas y alimentadores de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/cabezales', name: 'Cabezales de impresion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/tinta-toner', name: 'Tinta, toner y cintas', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/etiquetas-papel', name: 'Etiquetas y papel', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-fotografico-sublimacion', name: 'Papel fotografico y sublimacion', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/papel-plotter', name: 'Papel para plotter', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/mantenimiento', name: 'Mantenimiento de impresoras', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/unidades-transferencia', name: 'Unidades de transferencia', legacyCategory: 'laptops' },
  { path: 'impresion/consumibles/pulseras-termicas', name: 'Pulseras termicas de identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/lectores-codigo-barras', name: 'Lectores de codigo de barras', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/cajones-dinero', name: 'Cajones de dinero POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/digitalizadores-firma', name: 'Digitalizadores de firma', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/verificadores-precio', name: 'Verificadores de precio POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/terminales-accesorios', name: 'Terminales y accesorios POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/software-pos', name: 'Software punto de venta', legacyCategory: 'software' },
  { path: 'punto-de-venta/credenciales-identificacion', name: 'Credenciales e identificacion', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/etiquetas-termicas', name: 'Etiquetas termicas POS', legacyCategory: 'laptops' },
  { path: 'punto-de-venta/consumibles/rollos-termicos', name: 'Rollos termicos POS', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/biometricos', name: 'Biometricos de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/tarjetas-rfid', name: 'Tarjetas RFID de control de acceso', legacyCategory: 'laptops' },
  { path: 'seguridad/control-acceso/cerraduras-inteligentes', name: 'Cerraduras inteligentes', legacyCategory: 'laptops' },
  { path: 'seguridad/cctv/camaras', name: 'Camaras CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-wifi', name: 'Camaras IP WiFi', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-ip-poe', name: 'Camaras IP PoE', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/camaras-turbohd', name: 'Camaras TurboHD analogicas', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/kits-vigilancia', name: 'Kits de videovigilancia', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/accesorios-cableado', name: 'Accesorios y cableado CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/cable-coaxial-siames', name: 'Cable coaxial siames CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/fuentes-poder', name: 'Fuentes de poder para CCTV', legacyCategory: 'cameras' },
  { path: 'seguridad/cctv/dvr-nvr', name: 'DVR y NVR', legacyCategory: 'cameras' },
  { path: 'seguridad/epp/proteccion-facial', name: 'Proteccion facial EPP', legacyCategory: 'laptops' },
  { path: 'seguridad/epp/proteccion-ocular', name: 'Proteccion ocular EPP', legacyCategory: 'laptops' },
  { path: 'salud/equipo-medico/monitoreo', name: 'Monitoreo medico domestico', legacyCategory: 'laptops' },
  { path: 'telefonia/smartphones', name: 'Smartphones', legacyCategory: 'smartphones' },
  { path: 'wearables/smartwatches', name: 'Smartwatches y bandas inteligentes', legacyCategory: 'smartphones' },
  { path: 'audio/audifonos', name: 'Audifonos', legacyCategory: 'headphones' },
  { path: 'audio/microfonos', name: 'Microfonos', legacyCategory: 'headphones' },
  { path: 'audio/conferencia-speakerphones', name: 'Bocinas de conferencia', legacyCategory: 'headphones' },
  { path: 'audio/adaptadores-bluetooth', name: 'Adaptadores Bluetooth de audio', legacyCategory: 'headphones' },
  { path: 'audio/bocinas', name: 'Bocinas', legacyCategory: 'headphones' },
  { path: 'audio/barras-sonido', name: 'Barras de sonido', legacyCategory: 'headphones' },
  { path: 'colaboracion/video-conferencia/controladores', name: 'Controladores de videoconferencia', legacyCategory: 'laptops' },
  { path: 'colaboracion/presentacion-inalambrica', name: 'Presentacion inalambrica', legacyCategory: 'laptops' },
  { path: 'video/televisores', name: 'Televisores', legacyCategory: 'tvs' },
  { path: 'video/proyectores', name: 'Proyectores', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion', name: 'Accesorios de proyeccion', legacyCategory: 'tvs' },
  { path: 'video/accesorios-proyeccion/soportes-proyector', name: 'Soportes para proyector', legacyCategory: 'tvs' },
  { path: 'gaming/consolas', name: 'Consolas', legacyCategory: 'gaming' },
  { path: 'gaming/accesorios', name: 'Accesorios gaming', legacyCategory: 'gaming' },
  { path: 'oficina/mobiliario-accesorios', name: 'Mobiliario y accesorios de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/mochilas-bolsas', name: 'Mochilas y bolsas de uso diario', legacyCategory: 'laptops' },
  { path: 'oficina/papel-consumibles', name: 'Papel y consumibles de oficina', legacyCategory: 'laptops' },
  { path: 'oficina/pizarrones-interactivos', name: 'Pizarrones interactivos', legacyCategory: 'laptops' },
  { path: 'oficina/limpieza-higiene/dispensadores', name: 'Dispensadores de higiene', legacyCategory: 'laptops' },
  { path: 'oficina/ergonomia/soportes-lumbares', name: 'Soportes lumbares ergonomicos', legacyCategory: 'laptops' },
  { path: 'software/licencias', name: 'Licencias de software', legacyCategory: 'software' },
  { path: 'software/sistemas-operativos', name: 'Sistemas operativos', legacyCategory: 'software' },
  { path: 'software/seguridad', name: 'Software de seguridad', legacyCategory: 'software' },
  { path: 'software/cad-diseno', name: 'Software CAD y diseno', legacyCategory: 'software' },
  { path: 'software/productividad-oficina', name: 'Software de productividad y oficina', legacyCategory: 'software' },
  { path: 'servicios/garantias-extendidas', name: 'Garantias extendidas y servicios', legacyCategory: 'software' },
  { path: 'accesorios/seguridad-fisica', name: 'Seguridad fisica para equipos', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/mousepads', name: 'Mousepads y tapetes para mouse', legacyCategory: 'laptops' },
  { path: 'computo/accesorios/herramientas-esd', name: 'Herramientas antiestaticas ESD', legacyCategory: 'laptops' },
  { path: 'energia/power-banks', name: 'Baterias externas y power banks', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores', name: 'Cables y adaptadores', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/usb-serial', name: 'Adaptadores USB a serial', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-dvi-vga', name: 'Adaptadores DVI VGA', legacyCategory: 'laptops' },
  { path: 'accesorios/cables-adaptadores/video-hdmi-dvi', name: 'Cables HDMI a DVI', legacyCategory: 'laptops' },
  { path: 'accesorios/montaje-soportes', name: 'Montaje y soportes', legacyCategory: 'laptops' },
  { path: 'redes/cableado-estructurado/placas-keystone', name: 'Placas keystone y faceplates', legacyCategory: 'networking' },
  { path: 'movilidad/scooters-electricos', name: 'Scooters electricos', legacyCategory: 'gaming' },
  { path: 'mascotas/bebederos-fuentes', name: 'Bebederos y fuentes para mascotas', legacyCategory: 'laptops' },
];

const rules = [
  ['seguridad/control-acceso/cerraduras-inteligentes', /\b(dl05|cerradura inteligente|smart fingerprint lock|smart lock|fechadura inteligente)\b/],
  ['seguridad/control-acceso/biometricos', /\b(an c2slim bt|an-c2slim-bt|c2 slim|c2slim|sofavz570|control de acceso anviz|lector de huella digital)\b/],
  ['seguridad/control-acceso/tarjetas-rfid', /\b(an emicard|an-emicard|sofavz070|tarjeta rfid anviz|rfid 125 khz|125khz|tarjeta de proximidad)\b/],
  ['seguridad/cctv/kits-vigilancia', /\b(sua kit xvr1e04|sua-kit\/xvr1e04|kit de videovigilancia|kit cctv|4 b10p)\b/],
  ['seguridad/cctv/dvr-nvr', /\b(dvr|nvr|grabador|xvr)\b/],
  ['seguridad/cctv/camaras-ip-poe', /\b(mob 203d|mob-203d|mtd 203d|mtd-203d|camara ip bullet|camara ip domo|camara ip turret|poe)\b/],
  ['seguridad/cctv/camaras-ip-wifi', /\b(uho s2e m3|uho-s2e-m3|uniarch uho|camara ip mini pt wifi|3mp wifi smart pt|ezviz|tapo c210|tapoc210|cs h9c|csh9c10mp|230379|cs bc1c|cs eb3|cs h80f|scam3db|duosmart e21|e21 wifi|e21 duosmart|camara inteligente wifi e21|camara ip|camera ip|camara wifi|camera wifi)\b/],
  ['seguridad/cctv/camaras-turbohd', /\b(tddl200a|tddl 200a|tbdl200a|tbdl 200a|tddl500a|tddl 500a|tbdl500a|tbdl 500a|mdl 3202a|mdl-3202a|mdl 2202a|mdl-2202a|uac t112|uac-t112|uniarch uac|turbohd|turbo hd|ds2ce|ds 2ce|b8turbo|b8 turbo|topvision|thc b|thcb|colorvu|tvi ahd cvi cvbs)\b/],
  ['domotica/sensores/movimiento', /\b(orvibo sn11|sn11|accorb110|sensor de movimiento|motion sensor|pir inteligente|zigbee pir)\b/],
  ['domotica/sensores', /\b(orvibo sm11|sm11|sm10zw|sm10zw-1vo|accorb120|imou ard311|ard311-sw|accdah1160|contacto magnetico|sensor de puerta|sensor ventana|door window sensor|zigbee door)\b/],
  ['seguridad/cctv/camaras', /\b(camara|camera|ipc|hac|dahua|hikvision|uniview|bullet|domo|turret)\b/],
  ['computo/perifericos/teclados', /\b(pro x60|pro x 60|920 011921|920 010478|920-010478|teclog1330|teclog1020|mx keys mini)\b/],
  ['computo/perifericos/teclados/keycaps', /\b(sacarab|scarab|a130w|a130w-sp|tecrdg180|keycaps|kit de teclas|pudding)\b/],
  ['redes/controladores-cloud', /\b(omada oc200|oc200|acctpl560|cloud controller|controlador cloud omada|controladora cloud omada)\b/],
  ['redes/access-points', /\b(access point|ap\b|eap|uap|wifi|wi fi|wireless)\b/],
  ['redes/radioenlaces-antenas', /\b(nb50|acpnet030|6972012672565|088591201754|netis cpe|outdoor digital bridge|cpe exterior|airfiber|airmax|litebeam|nanobeam|powerbeam|rocketm|rocket|pbe|lbe|af\s?5|am\s?[25]g|amo\s?[25]g|rd\s?5g|horn\s?5|lap\s?120|lap\s?gps|antena|radioenlace)\b/],
  ['accesorios/cables-adaptadores/usb-serial', /\b(205146|205153|accitl080|accitl1165|cb-170|ad-113|usb a serial|usb to serial|usb-a to serial|rs232|rs 232|db9)\b/],
  ['computo/componentes/tarjetas-audio/usb', /\b(150859|accitl525|ad-152|usb.*tarjeta sonido|usb.*sound card|tarjeta sonido 5\.1|sound card 5\.1)\b/],
  ['redes/transceptores-convertidores', /\b(sfp|transceiver|transceptor|gbic|media converter|convertidor|mc200cm\w*|mc110cs\w*|sm311\w*|uf mm|uf gp|uf loco|uf nano|fibra optica)\b/],
  ['redes/herramientas-cableado/crimpadoras', /\b(210836|211048|accitl1455|accitl1990|ac-1419|ac-1910|pinza.*crimp|crimpe?ar|crimping tool|crimpadora)\b/],
  ['redes/herramientas-cableado/ponchadoras-impacto', /\b(211055|accitl2060|ac-1421|pinza.*ponchar|p[ao]nchadora|terminal blocks?|bloques terminales|jacks.*terminal)\b/],
  ['redes/herramientas-cableado', /\b(aw250nxt11|accnxx170|aw251nxt05|ptkckkbsdkt01|accnxx200|kit basico de herramientas|network tool kit|punchdown|punzadora|herramienta de impacto|terminacion 110|bloques 110|blade 110)\b/],
  ['redes/cableado-estructurado/patch-cords', /\b(8699862cpc|acccdt360|cordon de parcheo|patch cord|patchcord|cable patch.*cat6)\b/],
  ['redes/cableado-estructurado/bobinas-utp', /\b(664464|acccdm1010|66446815|acccdm1030|66446835|acccdm1040|66445632|acccdm970|bobina.*utp|cable utp condumex|utp cat5e|utp cat6|ultracat|bravotwist)\b/],
  ['redes/cableado-estructurado/divisores-adaptadores', /\b(504195|accitl1635|ac-2145|distribuidor modular|modular distributor|1x2 rj45|1 x 2 rj45|splitter rj45)\b/],
  ['redes/cableado-estructurado/acopladores-rj45', /\b(504225|accitl320|ac-1759|cople.*cat ?5e|cat ?5e modular beige|rj45 coupler|acoplador rj45|cople rj45)\b/],
  ['redes/tarjetas-red/pcie', /\b(522533|52253|accitl1480|nic-747|tarjeta red.*pci|gigabit pci express|network card.*pci|pci express network card)\b/],
  ['redes/cableado-estructurado', /\b(panduit|belden|jack modular|patch panel|faceplate|tapa ciega|rj45|cat6|cat 6|nk6|cj688|cfpe|wmph|wmp|ld10|sp688|intellinet \d+)\b/],
  ['redes/fibra-optica/olt-gpon', /\b(ds p7001 16|ds-p7001-16|acctpl1240|840030703621|g pon|gpon olt|olt gpon|olt de fibra)\b/],
  ['redes/switches', /\b(switch|poe|gigabit|jetstream)\b/],
  ['redes/routers', /\b(router|gateway|firewall|mikrotik|fortigate)\b/],
  ['computo/servidores/rack', /\b(r760xs|poweredge r760xs|r470271|r470|poweredge r470|serddl070|serddl180|servidor rack)\b/],
  ['infraestructura/racks-accesorios/herrajes', /\b(la100te1224x50|tuerca enjaulada|cage nut|12 24|12-24|acclcs230)\b/],
  ['infraestructura/racks-accesorios/soportes-pared', /\b(la100ksp|kitlcs020|soportes de pared laces|soportes ajustables 12|wall mount supports)\b/],
  ['infraestructura/racks-accesorios/charolas-monitor', /\b(north051-bkl|north051|accnsy020|charola para monitor|monitor shelf)\b/],
  ['infraestructura/racks-accesorios/charolas-teclado', /\b(north054-bkl|north054|accnsy090|ac-6402|charola.*teclado|keyboard shelf)\b/],
  ['infraestructura/racks-accesorios/charolas-servidor', /\b(north080-bkl|north080|accnsy110|charola para servidor|server shelf)\b/],
  ['infraestructura/racks-accesorios/charolas', /\b(aw222nxt67|nps v11u3b|nps-v11u3b|aw222nxt66|nps s11u3b|nps-s11u3b|accnxx110|bandeja sencilla|charola para rack|vented shelf|rack mount shelf)\b/],
  ['infraestructura/racks-accesorios/organizadores-cable', /\b(aw222nxt62|npm dh2ub|npm-dh2ub|north109|north109-bkl|north115|north115-bkl|accnsy085|organizador vertical north system|organizador vertical|organizador horizontal north system|organizador horizontal|organizador de cable|horizontal duct|vertical duct|duct cable management)\b/],
  ['infraestructura/racks-enfriamiento/racks-piso', /\b(north001-bkl|north001|accnsy010|rack de piso|floor rack|rack 45u)\b/],
  ['infraestructura/racks-enfriamiento', /\b(rack|gabinete mural|charola|shelf|panel|srcool|fanroof|cagenuts|srshelf|srwf|sr1upanel|cooling|enfriamiento)\b/],
  ['infraestructura/cajas-registro', /\b(enson ens pcb|ens pcb|pcb1010|caja de plastico|caja estanca|caja registro|ip66)\b/],
  ['energia/accesorios-ups/tarjetas-snmp', /\b(ap9643|accapc1550|network management card 3|nmc3|rmcard205|cyberpower rmcard205|remote management card|tarjeta snmp cyberpower|smartbitt snmp|snmp administrador|tarbit010|tarjeta de administracion de red|viewpower|snmpv3)\b/],
  ['energia/baterias-ups/cartuchos-reemplazo', /\b(rbc35|apcrbc35|accapc060|fr-209|battery cartridge 35|replacement battery cartridge 35|bateria de reemplazo apc)\b/],
  ['energia/baterias-ups', /\b(cei 1 006|cei-1-006|12v 7ah|12 v 7 ah|rbc|replacement battery|bateria ups|battery cartridge|apcrbc)\b/],
  ['energia/pilas-baterias/boton-cmos', /\b(432528|accitl1430|ac-1865|cr2032|cmos 3v|pila cmos|bateria pila)\b/],
  ['energia/supresores-reguladores/supresores-picos', /\b(brc 1 002|brc-1-002|acccom010|ac-9644|7501693402193|504 joule|504j|supresor de picos complet)\b/],
  ['energia/supresores-reguladores', /\b(supresor|regulador|tlp\d|isotel|contactos|multicontacto|pv375usb|vp132|supvic010)\b/],
  ['energia/cargadores-usb', /\b(ci710|accact4850|ac-937160|cp20w|accact4360|energon prime cp20w|db pd64|db-pd64|accdbu020|cargador de pared|usb c pd|usb-c pd|gan|power delivery|67w|64w|20w)\b/],
  ['energia/cargadores-inalambricos', /\b(ac 937146|ac-937146|ac-11797|ci730|accact3530|mobifree base de carga|base de carga inalambrica|cargador inalambrico|inalambrico qi|wireless charger)\b/],
  ['energia/no-breaks-ups/doble-conversion', /\b(upo22 10|upo22-10|nbkcdp1750|fr-2354|ups online|doble conversion|double conversion)\b/],
  ['energia/no-breaks-ups', /\b(ups|no break|nobreak|bateria|battery backup|regulador)\b/],
  ['domotica/sensores/fugas-agua', /\b(tapo t300|t300|sensor de fuga|water leak sensor|fugas de agua)\b/],
  ['hogar/electrodomesticos/aspiradoras-robot', /\b(tapo rv20 max|rv20 max|tapo rv30 max|rv30 max|acctpl1210|acctpl1230|robot vacuum|robot aspirador|aspiradora robot)\b/],
  ['hogar/electrodomesticos/microondas', /\b(hmms3411dsv|hmms2509sp|microondas|horno de microondas)\b/],
  ['hogar/electrodomesticos/lavadoras', /\b(wsa1102pcn|lavhse030|6901101814562|lavadora|washing machine)\b/],
  ['hogar/electrodomesticos/exprimidores', /\b(mbj01n|ele-15|mirati home|exprimidor de citricos|extractor de jugos)\b/],
  ['hogar/electrodomesticos/aires-acondicionados', /\b(ac121cf|ac122cf|acr242kg|airhse260|airhse270|airhse550|6926597788319|minisplit|aire acondicionado|1 tonelada|2 toneladas|24000 btu|solo frio)\b/],
  ['hogar/electrodomesticos/purificadores-aire', /\b(lanix 14996|14996|airlnx180|xair 1|purificador de aire)\b/],
  ['audio/barras-sonido', /\b(bs600|ac 940801|ac-940801|bocact660|dynamic thin|bs465|bocact310|ac-935234|dynamic trim|creative stage 360|stage 360|dell sb521a|sb521a|creative stage v2|stage v2|hisense hs2100|hs2100|hisense hs1000|hs1000|audhse060|888143023564|bsp 320|bsp-320|bocvgo2000|sound blaster gs5|blaster gs5|pc 114024|pc-114024|bocmst4180|emphoria|boccrl040|barra de sonido|barra de audio|soundbar)\b/],
  ['colaboracion/video-conferencia/controladores', /\b(polycom tc10|poly tc10|tc10|875k5aa|accpol1240|197497663662|controlador de videoconferencia|touch controller)\b/],
  ['colaboracion/presentacion-inalambrica', /\b(twy31|5a\.f7v28\.bp2|accbnq810|instashare button|transmisor inalambrico|wireless presentation)\b/],
  ['video/accesorios-proyeccion/soportes-proyector', /\b(multimedia screens 4365|4365|accmtd010|soporte para proyector|projector mount|montaje techo.*proyector)\b/],
  ['video/accesorios-proyeccion', /\b(msc 305|msc-305|msc 265|msc-265|msc 332|msc-332|mse 332|mse-332|panscr050|panscr480|panscr490|panscr500|pantalla de proyeccion|pantalla para proyector|lampara proyector|lamp module|ls1st|ls1lt|botones adicionales|wdc10|v13h010|elplp)\b/],
  ['computo/accesorios/limpieza/limpiadores-pantalla', /\b(421010|421027|60cc|200cc|accitl2250|accitl2360|cn-1664|limpiador pantallas?|limpiador lcd|screen cleaner|lcd cleaner)\b/],
  ['computo/monitores', /\b(monitor|display|odyssey|lcd|led\s?\d{2})\b/],
  ['video/proyectores', /\b(proyector|projector|benq\s(mh|ms|mx|mw|th|tk|w)\d|acer\s(x|p)\d{4})\b/],
  ['computo/desktops', /\b(desktop|workstation|mini pc|all in one|aio)\b/],
  ['computo/servidores/almacenamiento-cintas', /\b(lto|ultrium|data cartridge|rDX|cinta de respaldo)\b/],
  ['computo/servidores/componentes', /\b(hewlett packard enterprise|hpe\b|proliant|smart array|dl\d{3}|ml\d{3}|p\d{5}\s?b21|j9150|dell 412|dell 470|poweredge|4xh7a83845|acclen4540|riser pcie|pcie riser|sr630 v3|thinksystem v3)\b/],
  ['oficina/mochilas-bolsas', /\b(pc 085058|pc-085058|malgen4650|holdi|pc 085249|pc-085249|malgen4890|bookery|pc 084433|pc-084433|malgen4320|delfin astro|pc 085027|pc-085027|malgen4660|ac-12376|holdy|avellana|pc 085294|pc-085294|malgen4910|kiddo corazon|pc 084730|pc-084730|malgen4580|sportiva|pc 085164|pc-085164|malgen5150|arcade|pc 085089|pc-085089|malgen4750|kiddo monstruos|pc 085225|pc-085225|malgen4900|loopy color rojo|pc 085300|pc-085300|malgen4920|brooklyn dinosaurios|pc 085317|pc-085317|malgen4930|pc 084396|pc-084396|malgen4280|bolso deportivo|mochila escolar|bolsa de hombro|bolso cruzado)\b/],
  ['computo/accesorios/mochilas-fundas', /\b(tzlbp29|maltch440|tzlbp02|acctch9440|pc 085201|pc-085201|malgen4870|loopy|cp5724s|ecoloop pro slim backpack|cb 300|cb-300|malvgo110|el 994312|el-994312|malgen3180|manhattan 438889|manhattan 439893|438889|439893|ac-1572|ac-8286|malitl360|malitl730|london laptop briefcase|es1520p|maldll660|1032248174627|dell essential backpack|maletin london|maletin laptop|mochila laptop|backpack laptop|funda laptop)\b/],
  ['accesorios/seguridad-fisica', /\b(pa410s|asp71glx-s|asp71glx|acctrg2950|defcon compact serialized|defcon scl|serialized cable lock|nanosaver|nano saver|kensington k60604|k60604ww|k64430s|acckns1230|microsaver 2\.0 keyed chassis|chassis lock|bloqueo de chasis|kensington k64444|k64444ww|k64448ww|dual head laptop lock|candado seguridad|candado laptop|laptop lock|cable lock)\b/],
  ['computo/laptops', /\b(laptop|notebook|thinkpad|macbook|vivobook|latitude|elitebook|xps)\b/],
  ['computo/almacenamiento/memorias-flash', /\b(ud512gex3l1|premier extreme|sd7 1 express|high endurance|microsd|micro sd|ausdx64|ausdh32|memdat7020|memdat7310|tarjeta microsd|memoria flash)\b/],
  ['computo/almacenamiento/medios-opticos/accesorios', /\b(verbatim 49976|49976|cdrwcb1780|sobre de papel cd|paper sleeves|cd dvd sleeves|sleeves with clear window)\b/],
  ['computo/almacenamiento/medios-opticos', /\b(verbatim 94776|verbatim 95310|verbatim 95179|verbatim 95093|95310|95179|95093|cdrwcb125|cdrwcb860|cdrwcb1760|cdrwcb130|dvd-rw|dvd rw|dvd-r|dvd r|dvd\+r|dvd r dl|dvd\+r dl|cd-r|cd r|52x cd|700 mb|4\.7gb|4 7gb|8\.5gb|8 5gb|240 min|120 min|80 min)\b/],
  ['computo/componentes/pasta-termica', /\b(140065|701662|accitl2450|accitl420|cn-1731|cn-1152|br 937412|br-937412|na 0649|na-0649|ice shield|pasta termica|thermal paste|eolox|jeringa.*cpu)\b/],
  ['computo/componentes/procesadores', /\b(core i[3579]|ryzen|procesador|cpu\b)\b/],
  ['computo/componentes/tarjetas-madre', /\b(motherboard|tarjeta madre|mainboard|b\d{3}|z\d{3}|x\d{3})\b/],
  ['computo/componentes/memoria-ram', /\b(ram|ddr[345]|memoria)\b/],
  ['computo/componentes/fuentes-poder', /\b(fuente de poder|power supply|psu|cx\d{3}|cv\d{3}|rm\d{3}|cp 902|80 plus|80 bronze)\b/],
  ['computo/componentes/enfriamiento-gabinetes', /\b(cooler|fan|ventilador|gabinete|case|h100|hydro|pwm|cc 901|cw 906|be quiet)\b/],
  ['computo/almacenamiento/accesorios-montaje', /\b(sna br2 35|sna-br2\/35|sna-br2|acckgt150|2\.5 to 3\.5|2\.5\" to 3\.5\"|ssd bracket|mounting bracket|rieles de montaje|riel de montaje|bracket ssd)\b/],
  ['computo/almacenamiento/adaptadores-usb', /\b(179195|accitl1545|ad-120|usb.*hdd|usb.*sata\/ide|usb.*sata ide|sata\/ide adapter|ide40|otb)\b/],
  ['computo/almacenamiento/ssd', /\b(ssd|nvme|m\.2|solid state)\b/],
  ['computo/almacenamiento/discos-duros', /\b(hdd|disco duro|hard drive|sata)\b/],
  ['computo/perifericos/teclados', /\b(pro x60|pro x 60|920 011921|920 010478|920-010478|teclog1330|teclog1020|mx keys mini|teclado|keyboard)\b/],
  ['computo/accesorios/mousepads', /\b(423526|423533|422871|434362|accitl045|accitl300|accitl1840|accitl200|ac-1571|ac-1570|ac-2375|ac-1569|mousepad|mouse pad|tapete para mouse|tapete p raton)\b/],
  ['computo/perifericos/mouse', /\b(mouse|raton|logitech 910|trackball)\b/],
  ['computo/perifericos/webcams', /\b(webcam|camara web)\b/],
  ['audio/conferencia-speakerphones', /\b(jabra speak 510|speak 510|jabra speak 710|speak 710|accjab080|accjab230|7510-209|7510-109|speakerphone|bocina de conferencia|altavoz de conferencia)\b/],
  ['audio/adaptadores-bluetooth', /\b(shift plus ab424|ab424|accact4990|ac-939775|receptor bluetooth|transmisor bluetooth|adaptador de audio bluetooth|3\.5 mm a bluetooth)\b/],
  ['audio/bocinas', /\b(ac 934961|ac-934961|bocgen3620|glee max|ap460|bs685|bocact190|ac-935210|dynamic exact|r bs700|r-bs700|bocact680|7506215940818|pc 112716|pc-112716|miniglow|bocmst3900|ksp 180|ksp-180|spk-2689|bocvgo1900|ksp 205|ksp-205|spk-2690|bocvgo1910|ksp 350|ksp-350|bocvgo1930|bsp 400|bsp-400|spk-2791|bocvgo1400|pool bluetooth|karaoke speaker|bafle dual|mini bafle|vortred v 930280|v-930280|bocmst4110|bocinas gamer|bocina bluetooth|altavoz|speaker)\b/],
  ['computo/perifericos/bocinas-audio', /\b(bocina|as215|ac 935272|ac-935272|as430|ac 935265|ac-935265|bsp \d|ksp \d|audio pc|logitech h390|vorago au|hpb 401|hs 502)\b/],
  ['computo/perifericos/presentadores', /\b(tzapl03|acctch9960|apuntador laser|indicador 50 m|logitech spotlight|spotlight presenter|presentador|presentation remote|moulog1800)\b/],
  ['computo/componentes/tarjetas-video', /\b(rtx 5060|geforce rtx 5060|rtx5060|vc-1400|shadow 2x oc|tarjeta de video|graphics card|gddr7)\b/],
  ['computo/componentes/tarjetas-audio', /\b(sb1870|sb1570|sound blaster audigy|tarjeta de sonido|sound card)\b/],
  ['computo/accesorios/limpieza/toallas-limpiadoras', /\b(pc-?030324|accmst095|toallas limpiadoras|panos humedos|toallitas limpiadoras|cleaning wipes)\b/],
  ['computo/accesorios/limpieza/liquidos-antiestaticos', /\b(pc-?033066|accmst1350|cn-183|limpiador liquido antiestatico|liquido antiestatico|antistatic cleaner|250 ml)\b/],
  ['computo/accesorios/limpieza/espumas-limpiadoras', /\b(pc-?030089|accmst1680|cn-597|espuma limpiadora|e-foam|ultra clean|432 ml|400grs)\b/],
  ['computo/accesorios/limpieza', /\b(na 0801|na-0801|accncb770|naceb toallas|53 0083|53-0083|sablmp050|disperse electronico|desplazador de humedad|cln \d|limpiador|limpiadora|aire comprimido|toallitas|toallas humedas|kit limpieza|alcohol iso|alcohol isopropilico|silimex|prolicom|silitek|silimpo|compucare|aerosol)\b/],
  ['computo/accesorios/hubs-usb', /\b(160599|161572|accitl1500|accitl2900|ac-1616|ac-3076|hub usb|usb hub|4 ptos|10 ptos|4 puertos usb|10 puertos usb|4-port usb|10-port usb)\b/],
  ['computo/accesorios/docks-hubs', /\b(docking|dock\b|hub usb|dell wd19|wd19s|dwm2655m|vorago plug)\b/],
  ['software/sistemas-operativos', /\b(fqc 10572|fqc-10572|sws-4985|windows 11 pro|sistema operativo|descarga digital windows|esd windows)\b/],
  ['software/seguridad', /\b(norton 21414731|21414731|sws-4445|norton 360|total security|antivirus|3 dispositivos)\b/],
  ['software/cad-diseno', /\b(057q1 ww6525 l347|057q1-ww6525-l347|sofatd720|autocad|autodesk)\b/],
  ['software/productividad-oficina', /\b(ep2 06874|ep2-06874|sofmsc1880|196388412518|office 2024)\b/],
  ['computo/accesorios/herramientas-esd', /\b(410144|accitl1055|pulsera antiestatica|antiestatica|anti static|esd)\b/],
  ['computo/accesorios/seguridad-biometrica', /\b(k64704ww|k64704|acckns2040|verimark pro|verimark it|fingerprint key|lector de huellas|llave de huellas)\b/],
  ['energia/inversores-solares', /\b(is 1000|is-1000|in 5000|in-5000|in 6000|in-6000|invdts010|is 3000|is-3000|invdts020|invdts030|invdts040|datashield is|datashield in|inversor cargador solar|inversor solar|solar inverter)\b/],
  ['energia/power-banks', /\b(npw 10fc|npw-10fc|batnnn050|necnon npw|power bank|bateria externa|c100 digital|adata c100)\b/],
  ['redes/cableado-estructurado/placas-keystone', /\b(aw161nxt02|n206-fp02-ind|n206 fp02 ind|cabtrl4150|placa keystone|placa de pared|face plate|wall plate|bulkhead wall plate)\b/],
  ['punto-de-venta/consumibles/etiquetas-termicas', /\b(ev 3012c|ev-3012c|accevo020|etiquetas termicas 10\s?\*?\s?15|etiquetas termicas pos)\b/],
  ['punto-de-venta/credenciales-identificacion', /\b(vbdg204eu|kitbad130|badgy|ymcko|ribbon badgy|kit de credenciales|card printer ribbon)\b/],
  ['punto-de-venta/consumibles/rollos-termicos', /\b(10011042|acczbr640|z-perform 1000d|receipt paper|papel recibo|rollo termico|3\.1 x 80|3 x 80)\b/],
  ['impresion/consumibles/papel-fotografico-sublimacion', /\b(pasu85-63|pasu85 63|pappol030|papel de sublimacion|papel sublimacion|sublimation paper|polaroid pasu)\b/],
  ['impresion/consumibles/etiquetas-papel', /\b(tze|dk12|dk22|etiqueta|label|papel fotografico|rollo|zebra 10\d{3})\b/],
  ['impresion/consumibles/papel-plotter', /\b(10b4|10b13|10b11|10b5|accpcm595|accpcm705|accpcm685|accpcm605|papel bond pcm|plotter|0 61 x 50|0 91 x 50|0 91 x 100|610 mm|914 mm)\b/],
  ['impresion/consumibles/unidades-transferencia', /\b(bu229cl|bu-229cl|belt unit|transfer belt|unidad de transferencia|cinturon de arrastre)\b/],
  ['impresion/consumibles/cabezales', /\b(bh 10|bh-10|ch 10|ch-10|0692c004aa|3yp86al|m0h50al|m0h51al|cabezal hp gt|cabezal de impresion|printhead)\b/],
  ['impresion/consumibles/tinta-toner', /\b(3yp17al|gt52|botella de tinta amarilla|yellow ink bottle|carhpp4330|tinta|toner|cartucho|drum|tambor|ribbon|cinta|tn\d|dr\d|pfi|gpr|pg \d|cl \d|erc|s015|s041|t\d{5,}|lexmark|xerox|kyocera|okidata|canon \d{3}\b|brother t[nz]|epson t)\b/],
  ['impresion/consumibles/mantenimiento', /\b(t04d100|t04d1|c33s021501|careps6570|cn-4492|sjmb6000|sjmb 6000|maintenance box|caja de mantenimiento|maintenance kit)\b/],
  ['impresion/consumibles/pulseras-termicas', /\b(z-band direct|z band direct|10006995k|acczbr1080|pulsera termica|wristband|wristbands)\b/],
  ['impresion/escaneres', /\b(scanjet pro n4600|n4600 fnw1|scanjet pro n4000|n4000 snw1|scanjet pro 3000|scanjet pro 2000|scanjet pro 2600|20g07a|6fw08a|6fw07a|6fw06a|20g05a|scahpi520|scahpi440|scahpi455|scahpi465|scahpi510|fi 70f|fi-70f|scafjt430|sv600|scansnap sv600|scafjt040|fujitsu fi|epson ds|workforce ds|document scanner|escaner documental)\b/],
  ['impresion/impresoras', /\b(impresora|printer|laserjet|deskjet|ecotank|multifuncional|zebra pc 200994)\b/],
  ['punto-de-venta/digitalizadores-firma', /\b(t-l460-hsb-r|tl460hsbr|accitr070|digitalizador de firma|signature pad|siglite|topaz t-l460|851718004107)\b/],
  ['punto-de-venta/lectores-codigo-barras', /\b(scanner|scaner|lector codigo|codigo de barras|barcode|ev 3006|ev-3006|ev 3007|ev-3007|honeywell|xenon|ms7820|3nstar sc|3nstar cd|zebra ds|zebra ls|topaz t)\b/],
  ['punto-de-venta/cajones-dinero', /\b(qoc 143sk|qoc-143sk|cjnqia030|cajon de dinero|caja para dinero|cash drawer)\b/],
  ['punto-de-venta/verificadores-precio', /\b(xb vp1106|xb-vp1106|kiosyb010|syble|verificador de precios|price checker)\b/],
  ['punto-de-venta/software-pos', /\b(psf030|kitpsf030|sf020|kitpsf020|psf040|kitpsf040|kitpsf050|kitpsf060|kitpsf070|pacific soft|software punto de venta|punto de venta para farmacias|punto de venta para autoservicios|punto de venta para restaurantes|comandera movil|software pos)\b/],
  ['punto-de-venta/consumibles/rollos-termicos', /\b(ev 3021c|ev-3021c|ev 3023c|ev-3023c|ev 3025c|ev-3025c|accevo030|accevo050|accevo070|rollos de papel termico|papel termico 57|papel termico 80)\b/],
  ['punto-de-venta/terminales-accesorios', /\b(cajon de dinero|cash drawer|pos\b|terminal punto de venta|3nstar ct|gaveta)\b/],
  ['punto-de-venta/credenciales-identificacion', /\b(evolis|vbdg204eu|kitbad130|badgy|ymcko|hid \d|credencial|tarjeta pvc|pvc card|104523|zk teco|zkteco|biometrico)\b/],
  ['seguridad/control-acceso/biometricos', /\b(an gc150|an-gc150|gc150|sofavz580|digitalpersona|lector huella|fingerprint|huella digital|50013 001 104)\b/],
  ['seguridad/cctv/accesorios-cableado', /\b(video balun|balun|transceptor pasivo|ptr 101v|ptr101v|vb 03|vb03)\b/],
  ['seguridad/cctv/cable-coaxial-siames', /\b(rg59ul 305b|rg59ul-305b|acccdm1080|cable siames|coaxial siames|siames rg 59|siames rg-59)\b/],
  ['seguridad/cctv/fuentes-poder', /\b(pr 12v5a|pr-12v5a|12v5a|fuente de poder cctv|fuente para camara)\b/],
  ['seguridad/epp/proteccion-facial', /\b(pco110|pco120|cubpco110|cubpco120|careta|proteccion facial|face shield|cpa nino)\b/],
  ['seguridad/epp/proteccion-ocular', /\b(gksa01|goggles|proteccion ocular|lentes de seguridad)\b/],
  ['salud/equipo-medico/monitoreo', /\b(gp 200|gp-200|teryob010|hg01|terhis010|bin zun r6|bing zun bz-r6|terbin020|sonolife lmt|lmt-01|accson020|oximetro|termometro infrarrojo|bp 201m|bp-201m|tensiometro|baumanometro|presion sanguinea)\b/],
  ['oficina/pizarrones-interactivos', /\b(pm 87ir|pm-87ir|piz-59|accmtd530|pizarron interactivo|pizarra interactiva|interactive whiteboard|touch infrarroja|20 toques)\b/],
  ['oficina/limpieza-higiene/dispensadores', /\b(csy090|discs y090|discsy090|clar systems csy090|dispensador de toalla|dispensador toalla)\b/],
  ['oficina/ergonomia/soportes-lumbares', /\b(k60412ww|acckns1810|smartfit conform back rest|respaldo lumbar|soporte lumbar|back rest)\b/],
  ['oficina/papel-consumibles', /\b(papel navigator|navigator 802839500207|papel carta|papel a4|5000 hojas|500 hojas|764025932868|paphpb010)\b/],
  ['impresion/accesorios/bandejas-alimentadores', /\b(t200\/t600|t200 t600|8aj60a|apl hpd610|aplhpd610|alimentador automatico|alimentadora hp|automatic sheet feeder|designjet t200|designjet t600)\b/],
  ['wearables/smartwatches', /\b(55020fad|acchuw1400|watch fit 4 pro|huawei fit 4 pro|staswm3ca|staswm3cb|staswm3cp|accsty450|accsty460|accsty480|stylos smartwatch|55020eku|55020ees|55020eel|55020ekx|55020ekw|acchuw1500|huawei band 10|nsw 101|nsw-101|necnon smartwatch|pc 270225|pc-270225|pc 270164|pc-270164|pc 270157|pc-270157|pc 270218|pc-270218|accmst4620|accmst4860|reloj-132|mercury|minoro|smartwatch amber|smartwatch|smart watch|banda inteligente)\b/],
  ['telefonia/smartphones', /\b(iphone|galaxy|pixel|moto|smartphone|telefono)\b/],
  ['audio/microfonos', /\b(pc 110583|pc-110583|microfono|microphone|cardioide|noise barrier)\b/],
  ['computo/accesorios/stylus-tablets', /\b(55037261|55037722|acchuw1450|acchuw1440|m-pencil|m pencil|m-pen|m pen|af63-r|af63 r|stylus|lapiz optico)\b/],
  ['audio/audifonos', /\b(audifonos|auriculares|diadema|headphones|headset|aeh101tt|boctrg020|spk-2258|wired mono headset|el 994787|el-994787|bocmst2340|g335|981 001018|boclog1750|hsg500|game factor hsg500|na 0308n|na-0308n|bocncb660|fornax|voyager 4310|accpts1960|197029504531|783q1aa|accpts2390|encorepro 510|encorepro hw510|quick disconnect|bocvgo1240|spk-2711|zone 300|h540|981 000510|hc560|ac 942935|ac-942935|na 0304r|na-0304r|hc580|ac 942386|ac-942386|tzdibt01|techzone monoaural|bose|sony wh|earbuds)\b/],
  ['video/televisores', /\b(tv|televisor|qled|oled|crystal uhd)\b/],
  ['gaming/consolas', /\b(playstation|xbox|nintendo|switch oled|ps5|consola)\b/],
  ['movilidad/scooters-electricos', /\b(stscm02b|stscm03o|stscm03a|accsty530|accsty540|accsty550|scooter electrico|stylos m2|stylos m3)\b/],
  ['mascotas/bebederos-fuentes', /\b(zwf01|ac-11643|zoomy|bebedero para mascotas|fuente para mascotas|pet fountain|triple sistema de filtracion)\b/],
  ['gaming/accesorios', /\b(balam rush|kg 200|gamepad|joystick|silla gamer|gaming chair)\b/],
  ['oficina/mobiliario-accesorios', /\b(nextep|silla|escritorio|archivero|organizador oficina)\b/],
  ['servicios/garantias-extendidas', /\b(5ps0a23193|extlen620|pol-3200|3yr adp|3 year adp|onsite intl|accidental damage protection|extension de garantia|garantia extendida|warranty extension)\b/],
  ['software/licencias', /\b(licencia|license|bitdefender|kaspersky|windows server|office 365|office home business|ep2 06687|ep2-06687|microsoft cfq\w*|microsoft software|aspel|contpaqi|sofcpc|nominas)\b/],
  ['accesorios/cables-adaptadores/video-dvi-vga', /\b(328883|accitl810|ad-122|dvi.*hd15|dvi.*vga|29m.*hd15h|dvi-i|adaptador dvi)\b/],
  ['accesorios/cables-adaptadores/video-hdmi-dvi', /\b(372503|accitl920|cb-273|hdmi.*dvi-d|dvi-d.*hdmi|dvi-d m-m|hdmi.*1\.8m)\b/],
  ['accesorios/cables-adaptadores', /\b(cable|adaptador|hdmi|usb|brobotix)\b/],
  ['accesorios/montaje-soportes', /\b(soporte|bracket|mount|rack|charola)\b/],
];

const categoryByPath = new Map(MANUAL_CATEGORY_TREE.map((category) => [category.path, category]));

export const getManualCategorySeeds = () => MANUAL_CATEGORY_TREE.map((category) => ({
  slug: category.path.split('/').at(-1),
  path: category.path,
  parent_slug: category.path.split('/').slice(0, -1).join('/'),
  name: category.name,
  legacy_category: category.legacyCategory,
  status: 'manual_verified',
  version: MANUAL_TAXONOMY_VERSION,
}));

export const classifyManualCategory = (product) => {
  const text = normalizeCatalogText([
    product.name,
    product.brand,
    product.category,
    product.model_number,
    product.description,
    JSON.stringify(product.specs || {}),
  ].filter(Boolean).join(' '));

  for (const [path, pattern] of rules) {
    if (!pattern.test(text)) continue;
    const category = categoryByPath.get(path);
    return {
      path,
      legacyCategory: category?.legacyCategory || product.category || 'laptops',
      reviewStatus: 'manual_rule_applied',
      confidence: 0.86,
      taxonomyVersion: MANUAL_TAXONOMY_VERSION,
    };
  }

  const fallback = MANUAL_CATEGORY_TREE.find((category) => category.legacyCategory === product.category);
  return {
    path: fallback?.path || 'computo/laptops',
    legacyCategory: fallback?.legacyCategory || product.category || 'laptops',
    reviewStatus: 'needs_manual_review',
    confidence: 0.45,
    taxonomyVersion: MANUAL_TAXONOMY_VERSION,
  };
};
